[quote.epigraph, , Ps. 126:6]
____
He that goeth forth and weepeth, bearing precious seed,
shall doubtless come again with rejoicing, bringing his sheaves with him.
____

== Introduction

The biography herewith presented to the reader is one of no common character.
It is the plain and unassuming, though in some portions self-defensive narrative,
of one who, after being for many years put in trust with the gospel,
and highly esteemed for the work`'s sake,
found the latter years of his pilgrimage and ministry
fraught with uncommon exercise and trial,
from the unexpected discovery of a spirit at work in the Society to which he belonged,
and especially in the land of our forefathers,
tending to undermine its original principles and character--a spirit which,
in its progress,
though exposed and opposed by him and by other faithful watchmen in Europe and America,
yet, spreading across the Atlantic,
had power and influence sufficient to accomplish a schism in the Society--of which schism,
this worthy man was an early victim.

A former heresy,
in which the precious doctrines of the sonship and
atonement of our Lord and Saviour Jesus Christ,
and the divine authority of Holy Scripture, were set at naught,
had found him at his post, in the meridian of life,
firmly standing by the ancient Christian faith of the Society.
That scourge, however,
had passed over without producing much devastation within New England Yearly Meeting,
or in Great Britain.
But great was his distress and conflict, several years later,
in finding that the same spirit which had lately
been leading astray into the wilderness of unbelief,
was again at work, under a very plausible guise,
drawing away multitudes in the opposite direction,
into a dependence on man`'s wisdom and learning, and producing a disrelish for,
and departure from, the pure, deep,
spiritual doctrines of those who had been instrumental, two hundred years ago,
in gathering the Society in a true experience and
united acknowledgment of "`Christ within,
the hope of glory.`"
He saw the inroads of this second schism,
and its tendency to bring in a religion of "`the letter,`" and of outside show,
in place of that of living experimental knowledge--one of ease to the fleshly mind,
instead of that which is and must be "`with burning and fuel of
fire`"--and being bold in the Lord to withstand it,
he brought down upon himself by his faithfulness the hostility
of those whose backsliding was by him constantly testified against.

The story of his persecution by false brethren, and of their ultimate departure,
in New England, into a separation from sound Friends,
will be recognized in the future history of the Society,
as unfolding an almost incredible page of outrage;
first upon the original principles of Quakerism,
and next upon private rights and the Christian discipline of the church.
We may well say "`almost incredible;`" for when we consider all its features,
of irregular and tyrannical proceedings to accomplish their determined object,
we are led to conclude that surely such a case is without a parallel
in Christian history outside of the dark walls of Romanism.
The spectacle of an aged minister of the gospel,
of long acknowledged worth and integrity,
being for years pursued by the constituted authorities of his own Society,
and ultimately cast out of their communion, on account of his faithful testimony,
in accordance with the requirements of their own discipline,
against palpable innovations upon their ancient faith,
might well excite a doubt of the correctness or impartiality of the delineator,
were not his statements borne out by collateral and concurrent
testimony beyond the reach of cavil or doubt.
The cumulative evidence in this case is overwhelming,
and even drawn in part from the publications of the very party concerned against him,
as has been shown in the "`Report of Philadelphia Yearly Meeting on the Division in
New England;`" and the only attempt to avoid the consequences of such developments,
so far as we yet know, has been by vague denial,
and a recourse to side issues and evasions.

Sad indeed is the consideration,
that such a picture should be presented within the
once peaceful enclosure of the Society of Friends;
and great is the stumbling-block thereby laid in
the way of the honest inquirer after truth,
until by a fair and candid investigation, the fact is clearly appreciated,
that these transactions were not the doings of men governed by
and walking in accordance with that unerring Spirit which true
Friends have always looked to as their safe and wisdom-giving guide;
but that they were the doings, partly,
of men who had departed from a practical unison with this ancient faith of the Society,
and were prepared unscrupulously to adopt any necessary measures
to put down all opposition to the favorite modernizer of its faith;
and partly, of those who, not abiding in the light,
but placing implicit reliance on the leaders of the people,
knew not what spirit such were of, and blindly followed their dictation.
So that the occurrence of these sorrowful events shows the liability
of unwatchful man to wander from this his sure Guide;
and should not be considered as militating against our great principle
of the infallibility of the pure dictates of the Holy Spirit in man,
as the primary rule of faith and practice;
but rather as confirmatory of that great and necessary Christian doctrine,
when we see the gross errors into which those are led, who, having once known it,
have departed therefrom, and become practically opposers of that great truth.

The attentive reader of his Journal may easily perceive,
that John Wilbur was slow to realize the fact of so great and complete a defection
as was forced upon his belief in the course of successive events.
The reality came upon him gradually, though unexpectedly,
and with awful and grievous weight, while travelling in the ministry in Great Britain;
and his sad forebodings were afterwards amply confirmed,
in witnessing the schism which occurred in the Society there a very few years later,
and subsequently in feeling and experiencing, in his own trials,
such conduct on the part of the prominent members,
as could only be accounted for on the ground of their
degeneracy in principle from the faith of their forefathers.

During his protracted trials on account of his faithful testimony against error,
the minds of many friends of kindred views and feelings in various parts of the Society,
were turned towards him in true sympathy; and many valuable letters,
expressive of their close unity with him in his sufferings,
from some of the most eminently gifted and spiritually minded servants of the Lord,
both in Europe and America, were from time to time received,
to the encouragement of his deeply afflicted mind.
The attention of the reader is particularly invited to that portion of these letters,
selected for the present publication.
A large number of similar letters have been omitted at present for the sake of brevity.
It will be perceived that the writers of these letters saw eye
to eye with him in regard to the state of things in the Society,
and regarded themselves as fellow-sufferers with him for the testimony of Jesus;
according to the declaration of the apostle, "`if one member suffer, all the +++[+++living]
members suffer with it.`"
These letters came to him as "`a brook by the way;`"
often reaching him at times of deep dejection,
when the enemy was permitted to come in as a flood,
and his faith was almost ready to fail; and were eminently serviceable,
through the divine blessing, in keeping his head above the billows,
by which he felt himself in danger at such times of being overwhelmed.
Comparatively few of his own letters to his friends
have been accessible for the present volume;
they being very much scattered,
and many of the recipients of his correspondence having been in distant lands,
or since removed by death, and their papers fallen into the hands of those who,
leavened into the new views, or influenced by others who are so,
have been reluctant to give them up for publication.

John Wilbur was a man of a clear and energetic intellect,
and known and esteemed throughout his native State of Rhode Island,
for remarkable uprightness and integrity.
In his example he adorned the doctrine which he professed,
maintaining in an eminent degree, consistency in life and conduct,
walking in humility and in the fear of the Lord;
and was ever ready to advise and assist any whom he saw to be in difficulty and distress.
And his sound and discriminating mind being divinely strengthened and enlightened,
and his spiritual "`senses exercised by reason of use`" and long experience,
he was often called upon, and in many such cases was greatly serviceable,
both within his own Society and without.

As a minister of the Gospel, he was earnest in persuasion,
and sound in doctrine beyond the power of his enemies to gainsay.
The importance of a living experimental acquaintance with the truths of Christianity--the
spirituality and heart-cleansing excellency of the gospel dispensation,
and its superiority over that of the law--the opening
of the Holy Scriptures in and by Christ Jesus,
the true Light--and the necessity, in order to a true understanding of them,
to believe in and give heed unto Him who "`hath the key
of David,`" and who still teacheth as never man taught,
and is alone able to preserve his obedient children from
the wiles of the enemy--were truths much dwelt upon by him,
and constituted the distinguishing features of his public testimonies in gospel ministry.

In his family, he held forth an example worthy to be followed as he followed Christ.
His words were few and savory, and his conversation, though, lively,
yet weighty and instructive,
calculated to lead the minds of his children to the only true source of happiness,
and away from the snares and temptations of the world.
He was frequently concerned to call them together
for religious opportunities in waiting on the Lord;
wherein he was often led to minister to their conditions, in gospel authority.

He was indeed no formalist;
yet was he truly sensible of the great value of the
Christian discipline established by our worthy forefathers,
and was deeply concerned that it should be maintained in its integrity,
entrusted to clean hands,
and administered in the true life which alone can give it efficacy.
And as he was no formalist, so also was he no innovator or latitudinarian.
The ancient paths, "`the straight gate and the narrow way,`" were broad enough for him;
in them he was concerned to live, and in them he was found faithful unto death.
When brought under suffering and distress for his allegiance to his Lord and Master,
he was enabled to endure it without murmuring or complaining, and without reviling again;
often saying that he regretted he was not more worthy to suffer in such a cause.

Depending, in humble trust and confidence, on the Divine guidance,
and regarding less than many of his contemporaries the favor and applause of men,
he was endued with a clear view of the real state of things in the professing church,
and of the "`mystery of iniquity`" which still worketh;
and continuing through heights and depths to live
near to the blessed Fountain of all good,
he was mercifully preserved through all his trials,
and enabled to bring honor to the name of Israel`'s God,
by his faithful dedication to the end of his days.

After the separation of the Gurney party from Friends in New England,
he continued livingly engaged in the service of the Gospel,
earnestly concerned for the building up of the remnant that had escaped,
and for their establishment upon "`the Rock of Ages.`"
He was diligent in his calling,
going in and out among them with watchful zeal and humble dedication,
though far beyond the boundary of threescore years and ten;
and several times was concerned to travel beyond the limits of his own Yearly Meeting,
and once more across the Atlantic, as will appear in his Journal;
and very sweet and acceptable were these his visits in the love of the Gospel,
to such as were truly and without dissimulation, of like precious faith.
Thus was he enabled "`to bring forth fruit in old age,`" to the honor of the Great Husbandman;
and maintaining with unflinching firmness and integrity
the position assigned him in the church militant,
he was qualified to say with the apostle, "`I am now ready to be offered,
and the time of my departure is at hand; I have fought a good fight;
I have kept the faith.`"
His own expressions to an intimate friend who visited
him about two weeks before his last illness,
were, with much sweetness, meekness, and calmness:
"`I do not see that much further service will be called for at my hands;
and I feel like one quietly waiting for the dismissal.`"
This he often appeared fully aware was nigh at hand,
and spoke of it as a change which he not only looked for, but desired.

In the conclusion, he was favored with a short illness;
and though advanced to the age of nearly eighty-two years,
his mental faculties and outward vision were scarcely impaired;
so that it might almost be said of him as it was of an eminent servant of the Lord formerly,
"`his eye was not dim, nor his natural force abated.`"
He was blessed with a clear sense to the last,
and with a calm view of the good land before him; and thus in great peace,
and at a good old age, he departed, and rests from his labors,
and his works do follow him.

And now,
in view of his dedicated life and tribulated path--of his marvellous preservation therein,
and of his truly peaceful close,
the hearts of many are made to overflow with gratitude
to the God and Father of all our sure mercies,
in that He deigned to be with him in the furnace of affliction,
carried him safely through all his conflicts, and in the end gave him the victory,
causing his sun to go down with a brightness animating
and encouraging to succeeding generations.
