[short="Chapter I"]
== Chapter I. Account of his Engagements in the Ministry From 1819 to 1822.

In 1819, I left home on fourth day, the 20th of 10th mo.,
in order to attend the meetings generally in this +++[+++Rhode Island]
and Smithfield Quarterly Meetings.
I got to Paul Coffin`'s in Coventry, and next day I met Abel Collins and wife at Foster,
where we attended Friends`' Meeting to a good degree of satisfaction.
After dining with John Ailsworth, we rode six miles to Benjamin Arnold`'s, and lodged.
The next day we rode to Friends`' Meeting at Coventry, which ended pretty well;
dined at Perez Peck`'s,
and then rode to a meeting appointed for us at a Methodist meetinghouse in Cranston,
which was a painful meeting, and we left without much relief.
Stayed that night with Amos Collins; and the next day, with him and children in company,
went ten miles to a meeting appointed for us at Scituate; which was dull at first,
and pretty long silent,
but through deep wading we were at length favored
to experience the stone rolled from the well`'s mouth,
and water sprang up, I believe to the refreshing of many minds.
We dined at Elihu Bowen`'s,
and after a family sitting rode six miles to William Green`'s and lodged.
First day the 24th, we went to Providence, and attended two meetings there;
dined at David Anthony`'s, and lodged at Jabez Anthony`'s, out of town.
On second day morning we went to see the children
of our worthy deceased friend Job Scott,
and had a little solid opportunity with them;
after which we went to Attleborough in order to attend a meeting tomorrow at Cumberland.
On third day we attended Friends`' Meeting at Cumberland,
and in the afternoon attended a meeting appointed
for us at a place called Cumberland Hill,
in which the doctrines of final perseverance, unconditional election,
and universal salvation, were treated on,
and ability was mercifully afforded to relieve our minds.
We were afterwards informed that there were some present who were
endeavoring to satisfy themselves under each of these opinions.
Fourth day attended Providence Monthly Meeting, held at lower Smithfield,
about seven miles from the last-named meeting--quite satisfactory.

28th. Fifth day.
We went to Smithfield Monthly Meeting, which we attended to good satisfaction;
sixth day attended Uxbridge Monthly Meeting, where the business was well conducted;
we lodged at Richard Mowry`'s;
and on seventh day attended the select meeting in the morning,
and a meeting appointed for us at Douglass in the afternoon,
and came to Josiah Shove`'s at night.
31st. First day.
We went seven miles in the morning to attend the upper meeting at Mendon,
where many other people were gathered,
to whom divers of our doctrines were largely opened.
Then rode four miles to Samuel Smith`'s,
near whose house is the lower meetinghouse in Mendon,
where we had a savory good meeting this afternoon.
On second day we travelled to Mansfield, eighteen miles,
where we had an open meeting in the afternoon, in which the doctrines of baptism,
unconditional election, the ministry, etc., were treated on.
We lodged at the Widow Skinner`'s, a convinced woman, and very kind.
On third day we went to Taunton and attended their meeting,
in which we had some pretty close searching service,
mostly I believe for the members of our Society.
In the afternoon rode towards Swansey, and lodged at Benjamin Buffinton`'s, in Dighton.

Fourth day, 3rd. We went to Somerset, and attended the select meeting,
and on fifth day attended the Quarterly Meeting.
Sixth day, 5th. This afternoon went to Fall River,
and attended a meeting there at three o`'clock.
Seventh day attended a small meeting at Tiverton,
and after meeting went to Benjamin Freeborn`'s on Rhode Island;
on our way visited Sarah Tucker.
First day, attended Portsmouth Meeting,
after which we attended one meeting on the Island to good satisfaction.
On the 9th we went to Freetown, twenty-three miles,
and had a meeting in the evening at a village called Assonet,
in which we were favored with strength to relieve our minds among the people.
10th. Attended their meeting at Freetown,
and after meeting rode eleven miles to William Earle`'s and lodged.
11th. Attended their meeting at Somerset; notice being given,
and there being a funeral also, the meeting was large,
in which some of the doctrines of the Gospel were clearly opened,
best help being mercifully afforded;
had a meeting in the evening at a little village called Swansey Factory,
which was an open time.
On the 12th we went to Providence, visited Friends`' Boarding School,
and had a religious opportunity with the superintendents, instructors,
and children collectively, to good satisfaction.

+++[+++By the remaining memoranda of this visit,
it appears that they went homeward from Providence, taking several meetings on their way,
and appointing some among those not Friends; which were to good satisfaction,
although the latter were among people little acquainted with spiritual worship.
They reached home on the 17th of 11th mo., 1819.]

10th mo., 29th, 1820.
Having obtained a certificate from my Monthly Meeting for the purpose,
I this day left home to make a visit to Friends and others
in the northern and eastern part of our Yearly Meeting;
and attended a meeting at Noose-Neck, in West Greenwich.
The people, though civil, appeared to be unacquainted with silent spiritual worship;
they were directed to the substance of spiritual religion,
and I was favored to labor with them to a good degree of satisfaction.
Afternoon, attended a meeting at a school-house, about four miles from the former place,
in which the parable of the prodigal son was alluded to, and much dwelt upon,
and a state of unfaithfulness spoken to.
30th. Attended Greenwich Monthly Meeting held at Cranston,
in which I had a short testimony,
recommending attention to the angelic descending as at the Pool of Bethesda,
in order for a right experience of that which has the healing virtue;
but these remarks seemed to be counteracted by another
testimony which was afterwards offered,
and I left the meeting with a heavy heart.

After stopping one night with William Almy,
(accompanied by Amos Collins as companion for the journey,) we went to Swansey,
in order to attend the Quarterly Meeting, which was held on fourth and fifth days;
during the latter day I felt much depression of spirits in regard
to my insufficiency for the work and service before me,
yet through all my conflicts I durst not look back,
and all at length centered in a degree of resignation to my lot;
and having the sympathy and encouragement of several dear friends,
I set out this morning, the 3rd of 11th mo., with some degree of cheerfulness, for Lynn;
travelled about thirty miles, and lodged at Sharon.
11th mo., Fourth.
Had a meeting by appointment at Sewal Hodge`'s,
and another the next day in the same town; both of which, I think,
were owned by the Helper of Israel.
We lodged one night at the house of T. P.,
he and his wife being solid hopeful young Friends,
to whom some encouragement was offered on our parting with them.
The 6th we went to Lynn, a distance of twenty-eight miles; on the 7th, set out for Weare,
N+++.+++ H.; made a stop at Goffstown, and arrived at Daniel Gove`'s this evening,
seventy-five miles from Lynn.

9th. Fifth day.
Attended Weare Monthly Meeting at the north house,
and returned to D. Gove`'s. 10th. Attended the south meeting;
I felt a good degree of peace to follow these two days labor.
We went this afternoon to Henniker and lodged, and on the 11th, attended meeting here,
wherein I had to speak closely and pressingly to some,
who had slidden from the right ground,
and squandered the good things which had been given them,
with a feeling invitation to return to the father`'s house and say, "`Father,
I have sinned against heaven and in thy sight,
and am no more worthy to be called thy son.`"
After meeting I was told that there were two persons
present who had been favored with a gift in the ministry,
but by going too fast had been bewildered; getting into an exalted state,
they had left their standing and been disowned from the Society.
How needful it is to watch and keep on the ground of true humility!
This was largely opened in this meeting,
and strength was mercifully given to sound an alarm to such as had departed from it.
We went this afternoon to Bow, and attended a meeting there in a school-house,
with people mostly not of our Society;
in which I had strength given me to declare the efficacy of the Gospel,
acting as an inward teacher,
showing the insufficiency of outward forms in effecting the work of true renovation;
and in conclusion I was favored in fervent supplication.

At Gilmanton he wrote to his wife and children as follows:--

"`We arrived here about 8 o`'clock last evening,
and put up at the house of our kind friend Ezekiel Hoyt,
with whom I had before been acquainted.
Two days after leaving Lynn, we arrived at Weare,
and have attended meeting every day since;
and although I have passed through some pretty deep wading,
and my faith has been nearly tried at times with discouragements inwardly and outwardly,
among which are the menaces of approaching winter,
yet through all I have been mercifully supported with a little confidence
that He who has called will enable me to go as far as He requires,
and when the measure is filled up I shall be rejoiced, if permitted, to see you again,
and all my dear friends at home; but the prospect as yet continues open before me,
and however I may have trials and difficulties to encounter,
yet as I have experienced help, so far as I have gone,
to be mercifully afforded in the needful time,
I dare not cherish a disposition to despair of its continuation; so I commit myself,
with all that is near and dear, to his holy care and keeping,
desiring that He may preserve us all in the way which will lead to an immortal crown.`"

First day, 12th. Attended Friends`' Meeting at Concord, which, though small,
was in a good degree favored.
Here we parted with Johnson Page and wife,
and several other Friends from Henniker and Weare,
who had attended these last two meetings.
We travelled this afternoon in company with Josiah Rogers, to Pittsfield.
13th. Attended meeting here, and had a religious opportunity with a number of Friends,
where it seemed to be my place to treat a little on the necessity of a close
attention to the openings of truth in the exercise of the Gospel ministry.
We had some reason to believe that things were out
of order among them in regard to the ministry.
We went this afternoon and evening to Gilmanton (thirty
miles from Concord) by way of Pittsfield,
where we had a meeting next day,
in which Truth gained the ascendency and was raised into dominion,
and the universality of Divine love was fully set forth.
15th. This evening had a meeting at a school-house near Center Harbor.
On going to this meeting I felt unusually cast down with weakness and poverty of spirit,
as much so, perhaps, as I ever experienced; but after sitting down,
and a short time of silence, way opened for some communication,
and strength began to be added,
and a clearer opening of the doctrines of the Gospel has seldom, if ever,
been by me experienced,
or a more immediate change from great weakness to
that of a degree of fulness in the Lord`'s strength;
and it was marvellous in mine eyes, for his arm was made bare for our help,
and my heart was made joyful and thankful for his merciful favors.

16th. We went to Sandwich and attended their Monthly Meeting,
in which I had to call the attention of Friends to the necessity
of our hearkening to the Lord in preference to Moses,
citing, "`This is my beloved Son, hear him:`" with some further enlargement.
After I sat down, and after it appeared to be about time to close the sitting,
there were several appearances in the meeting, which to my mind had not a right savor;
after which I was constrained to stand upon my feet and offer a caution
to those who step forward to lend a helping hand to the little ones,
lest overdoing in this respect may unhappily cause
them to place too much dependence on such,
and deter them from a true dependence upon Him on whom "`help is laid.`"
These observations were offered in great simplicity and much good will,
and several solid Friends mentioned to me after meeting that the
remarks were appropriate to the state of things among them,
and satisfactory to their feelings.
17th. Attended their north meeting, and went to Cyrus Varney`'s,
where we had an evening meeting with Friends and others;
this meeting was long silent and laborious, but ended to a good degree of satisfaction.

18th. We parted with our friends Cyrus Beede and wife,
who had been with us for two days past.
We now set out in company with Benjamin Fry, for Parsonsfield, a distance of thirty miles.
19th. We had a meeting there with Friends and many others,
and in the evening another at Limington, Maine, ten miles farther on;
this was a large meeting, many, not Friends, attending;
and although I was so much unwell that I felt doubtful
about being able to sit this meeting through,
yet I was favored to hold out,
and had strength given to declare the doctrines of the Gospel beyond my expectation.

20th. We travelled seventeen miles to Gorham, and lodged at William Cobb`'s,
where we had a meeting on the 21st, and another in the evening at Windham.
In these two meetings I had some pretty close searching labor,
and several states were opened and spoken to.
22nd. Went seventeen miles to Poland.
23rd. Had a little meeting there with a few simple-hearted Friends and friendly people,
to whom the language of encouragement flowed freely.
In the afternoon we travelled thirteen miles to Lewistown, and on the 24th,
near this place, we crossed the Androscoggin River by boat, below the Falls,
about forty miles above its mouth;
the waters of this large river rudely tumble down a precipice of rugged rocks,
and fall (as the boatman told us) fifty feet in a short distance.
Here we had a highly favored meeting, wherein the fall of man,
and his restoration and redemption through our Lord Jesus Christ,
were pretty fully set forth.

The following is an extract from a letter to his wife written at this place:--

"`Since I last wrote thee at Gilmanton we have attended a number of meetings,
the distance between some of which was a day`'s ride.
The travelling has been bad, occasioned by the snow,
the melting of which now makes the ways rather heavy;
yet we have persevered with all diligence, and on the whole have been much favored,
having enjoyed, most of the time, good health.
We have not been hindered at all on that account, and no accident has befallen us.
Notwithstanding I have felt sometimes like a stranger in a strange land,
yet as the way has been opened before me, and ability given to pursue,
I have not the least reason to doubt but my being here is in the ordering of Truth,
and indeed best help has been mercifully extended;
and as I have endeavored to keep low and humble, I have, to my own admiration,
received a gracious supply of help, in which I have been favored with mouth and wisdom,
tongue and utterance; for which all the praise is everlastingly due to the great Giver.`"

In the afternoon we went to Leeds, a distance of twelve miles, and lodged.
25th. Had a painful meeting here,
under a strong apprehension that things were not right among
them by reason of a worldly and lukewarm spirit.
I had some pretty close labor, but it seemed very difficult to reach the witness in them,
for the seed appeared to be under great oppression in some of their hearts.
We left them with heaviness, and travelled this afternoon fourteen miles to Winthrop.

First day, 26th. We attended meeting there,
which consisted mostly of those not in membership with us.
The doctrine of Gospel light, its universality,
and the insufficiency of outward ordinances, were pretty fully opened,
and help was mercifully afforded, so that the truth in a good degree rose into dominion.

27th. In company with several Friends we went to a place called the Forks,
and held a little meeting, and thence, in the afternoon, to George Ramsdell`'s,
on the Kennebec River, where we had a meeting with his family and some Methodist people,
which was very satisfactory.

28th. We passed through Hallowell, crossed the Kennebec at Augusta,
and went to Vassalborough, lodging at our kind friend Moses Sleeper`'s,
who with his wife are valuable Friends.
29th, had a meeting here, which was satisfactory; and here we left our horse and chaise,
and were furnished with saddle horses to ride,
while we were visiting the meetings on the east side of the river.
On the 30th, in company with Moses Sleeper and wife, we attended the Pond meeting,
which we thought a quiet and favored one; and in the afternoon,
with John Nichols for pilot, we went ten miles to China.

12th mo.
1st. We had a meeting at Friends`' meetinghouse, to pretty good satisfaction;
and afterwards an evening meeting at a place called the Branch.
2nd. Rode twenty miles to a place called Unity;
here we had an evening meeting at a school-house, with some Friends and Baptist people;
in which the doctrines of truth were pretty fully opened,
but the usefulness of the meeting was in some degree hurt
near the close by an offering of a Baptist preacher,
although he did not gainsay anything which had been said.

First day,
3rd. We rode eight miles to Fairfield and had a meeting with Friends and Baptists,
in which I was led to speak pretty fully on Baptism, much to my own,
and I believe to my friends`' satisfaction.
We dined with our dear friend John Warren at his house,
and rode this evening fifteen miles, to Moses Sleeper`'s.

From Vassalborough he wrote to his wife and children as follows:--

"`I have yet had no information from home since I left,
which has occasioned some uneasiness; I wrote home from Lewistown,
and have since had many meetings in this section,
and having readied the extreme point of our prospect, have set our faces homeward.
We were yesterday at Fairfax and dined with our beloved friend John Warren.

"`We are in tolerable health, but have been often heavy-hearted since I last wrote,
partly occasioned by an account brought from Providence by a Friend at Leeds of an accident
which he heard happened at the former place the seventh day after our Quarterly Meeting;
from which and some other circumstances,
we were not without fears that it was our mother
and one or more of our children who were injured.
This has been a sore trial to us; yet as the Friend knew nothing of who it was,
and as it was but a flying report,
we saw no way but to pursue our journey as the way opened before us;
and although my mind has been deeply weighed down under
the most trying conflict that I ever experienced,
yet as I have endeavored to submit all to the Divine disposal,
and give up to make whatever sacrifice my Master may require,
I have found his gracious hand to be my support,
and his help to be near at those seasons when I was brought
to the work of turning the battle to the gate.`"

12th mo.
4th. We took leave of our friends at Vassalborough, and resumed our travels by chaise;
and after a little visit in several Friends`' families,
we called to see Joseph Douglass of Durham,
who was confined with sickness at Joshua Fry`'s in this place.
Then proceeding on our journey, we crossed the Kennebec on the ice,
Joseph Howland bearing us company; came to David Purinton`'s at Sidney,
and put up for the night.
5th. We attended their meeting there, wherein I had close searching labor,
to the great relief of my mind: and after meeting went nine miles to Augusta,
a large village on the Kennebec, where a meeting was appointed for us in the courthouse.
A highly-favored meeting it was,
in which strength was given to declare the gospel of life and salvation,
to my own admiration, though claiming nothing to myself.
After meeting we went to Hallowell with Harvey Chace,
and had a meeting there in the evening of the next day;
in which there appeared to be such a resistance in
the minds of the people to us and our doctrines,
that it seemed difficult to make much impression upon them.
I had a pretty long combat with them,
and it would sometimes seem that we might get a victory over their strong wills;
again they would reinforce in such a manner as almost
to suppress everything that was good;
then, again, a new point of doctrine would come before me with some degree of clearness,
and a little help afforded,
and this also as it crossed their strong opinions excited a new effort in their minds,
and they would again resist with their warlike weapons; and finally,
I was ready to conclude, we could do no more than come off on even ground;
for although the ground was taken and retaken,
yet I had not much hope that we left them better off than we found them.
A great weight of exercise attended my mind on going to this meeting;
and this exercise was no less my lot after meeting than before.
Yet I was a little borne up on reflecting that Paul was unsuccessful at Ephesus,
when the people unitedly cried, "`Great is Diana of the Ephesians!`"
We were almost in like manner straitened in our minds with
their united determination to stand by their religious tenets;
for although they spake not with their tongues in the meeting,
still it was plainly to be felt that they clave to
their own stronghold and resisted our doctrine.
Yet, after all,
we were not without a little hope that there might be a
few minds present in some degree benefited by the meeting.

7th. We went to Litchfield (eighteen miles from Augusta)
and had a meeting with Friends there,
and in the evening one at a school-house near by.
Here a preacher of the Baptists attended,
and after we had been sitting some time in silence, while the meeting was gathering,
he claimed an appointment which he said he had previously
made at this place and at this time;
and continued, that if Friends had nothing to offer, he would now proceed.
I informed him that we had no knowledge of his appointment,
or we should not have made an attempt to hold a meeting here at this time;
but if he had no objections, as we were strangers,
we would like to have the conducting of the meeting.
He said no more,
and I soon stood upon my feet with the subjects of the ministry and divine worship,
which had sprung in my mind and were opening before the conversation took place;
and although he and the people did not understand the necessity
of silent waiting in order for a right qualification for either,
yet as the subjects were treated on, a solemnity began to cover the meeting, and,
in course, divers other subjects opened in the life, and were enlarged upon,
and a heavenly time it was, and concluded in solemn supplication.
After we felt clear, I mentioned that the service of the meeting was over on our part;
and the meeting broke up without anything further
being said by this preacher about his appointment.

8th. Today we travelled twenty-five miles, crossed the Androscoggin on the ice,
and went to Durham to lodge.
9th. We had a meeting by appointment at Pownal with Friends, to satisfaction.
We had the company, at this meeting, of Thomas Jones,
and returned with him to Durham and lodged at his house.
Our valued friend Joseph Howland travelled with us from his own home to Litchfield,
where we parted with him at Noah Farr`'s, who bore us company to Durham,
carrying one of us in his sleigh.
First day, 10th. We attended their meeting at Durham,
which is considered the largest meeting of Friends below Lynn.
I had good service in this meeting.
11th. Went back over the Androscoggin, and had an evening meeting at Lisbon,
near its banks.
In this meeting, although there was a kind of resistance felt, yet the testimony,
after a long struggle in silence, arose,
and the Truth was brought into dominion over gainsayers.
12th. Went up the river about five miles, in company with several Friends,
and had a meeting at a place called the Bend;--this meeting was also pretty long silent;
but as we were engaged to dwell low, and keep to the Fountain of wisdom,
way opened for labor; and the subjects of baptism, Christ`'s spiritual coming,
the ministry, and divine worship were treated on,
in the retrospect of which we had peace.
After meeting we returned to John Collins`'s, and dined;
then went home with our friend Stephen Jones and lodged; and on the 13th,
in company with S. Jones and wife, went to John Winslow`'s, near Falmouth.

14th. In company with the aforesaid Friends and J. W. and wife, we went to Portland,
and attended their mid-week meeting, which was very small,
and appointed another in the evening,
which was interrupted by a Baptist preacher for a time,
but after getting a little settled, I had good service therein.
15th. Went to Cape Elizabeth, and appointed a meeting there,
which we attended to good satisfaction, and in this and the day following,
visited some relatives in that vicinity.

Here he wrote to his wife as follows:--

"`We arrived the day before yesterday at Portland,
where I found a letter from thee for the first time, dated 15th, of 11th mo.
I had prepared my mind as well as possible to hear the worst,
and how was I rejoiced to find that you were then all in usual health;
insomuch that if I had not been in company,
the emotions which I felt would have brought a flood of tears from my eyes.
I rejoiced, and gave thanks to the God and father of all my mercies,
and thy tender expressions caused my cup to overflow.
We are making progress on our sea-board route homeward-bound, which truly looks pleasant,
and we have great cause to acknowledge the favors of Divine Providence;
He hath in wisdom given me some bitter draughts for my humiliation, and then again,
as at the present, has caused my cup to overflow with his precious love.
We are now in good health, for us, for which I desire to be truly thankful;
and may that Hand which hath hitherto helped us, be thy support,
bear up thy mind through every conflict and keep
thee and the children under his gracious protection.`"

First day, 17th. Attended Friends`' Meeting at Falmouth,
and many other people being notified, attended also;
in which the Law state and Gospel state were compared and much enlarged upon,
and the subject of baptism explained.
Afternoon we went to Gray, and had an evening meeting there to good satisfaction,
and lodged with our dear uncle George Dake, who was greatly rejoiced to see us.
18th. Proceeding, we went to Scarborough,
where we had a little meeting with the few Friends in the place, and some others,
in which the insufficiency of mere human reasoning
in order to a right understanding of Divine things,
was pointed out, and it was shown that faith in the spiritual manifestation,
as well as that in the outward coming of Christ, is of the highest importance to us,
in order to receive the benefit thereof,
and to experience a real change of heart by his power,
and that there is none other name or power under heaven whereby we can be saved.
We were afterwards informed that there was a man
present who had imbibed principles of infidelity,
or a disbelief of the Christian religion.
We travelled twenty-eight miles this afternoon and evening to Berwick.

Fourth day, 20th. Went to Oak Woods, and attended an evening meeting there,
which was rather a painful one.
21st. Attended their preparative meeting at Berwick, which was long silent,
but way was at length made for a little lively labor among them;
after which there was something offered by a young man present who belongs to no Society;
his appearance was plain, and his doctrine sound, and I think did not hurt the meeting;
I left it with much satisfaction and peace.
After calling a little to see the children of our late friend Paul Rogers,
we went this afternoon, in company with Joshua Jenkins and wife, to Dover.

22nd. Proceeded to Rochester, where we had a small meeting, and returned to Dover.
Had an evening meeting there at Friends`' meetinghouse,
which was attended by many other people;
in which the original and present state of man were compared,
showing that the same Divine intelligence which made a distinction
between right and wrong to our first parents,
is evidently communicated to the human mind in the present day.

23rd. In company with William Brown and daughter, went to Seabrook, twenty-two miles,
and on first day, the 24th, we attended their meeting, which was small and silent.
The 25th, travelled thirty miles to Salem, and on the 26th,
had a meeting there in the afternoon, and next day went to Lynn,
and attended their week-day meeting.
In these two meetings the necessity of watchfulness against the
subtle temptations of the enemy was pressingly spoken of.
This afternoon, and next day, the 28th,
visited several of our relatives and dear friends in a social way, and on the 29th,
took leave of them and proceeded on our way towards Providence,
arriving at the School next day, the 30th;
and after making a little visit to the superintendents and instructors,
came to Amos Collins`'s home, where I lodged.
First day, the 31st, I went with Beriah Collins to Old Warwick,
and attended their meeting, (which is held monthly,) to good satisfaction,
and the ensuing day, 1st mo., 1st, 1821, I went to Greenwich Monthly Meeting,
held at Cranston; in which I had some service in the Gospel, and after meeting,
returned to Amos Collins`'s. 2nd. I arrived at home
and found my dear wife and children all well;
for whose preservation, as well as my own,
I felt truly thankful to Him whose hand had been mercifully round about us for our support.
I travelled in this journey by computation eight hundred and sixty-seven miles;
was absent two months and five days, and attended fifty-nine meetings.
I passed through many close and trying exercises, but through Divine favor,
was enabled to endure them in a good degree of patience and resignation;
and can do no less than acknowledge that help was afforded in the needful time,
as I was disposed to wait for it;
and also that the peace and satisfaction which I felt from time to time,
as well as at the present time, is more than an ample reward for all my labors.

Having had a concern upon my mind, for a considerable length of time,
to visit the people in Gospel love, in some parts of Connecticut,
the Western part of Massachusetts, and the Eastern part of the State of New York,
I obtained a certificate from my Monthly and Quarterly Meetings for that purpose,
and left home 12th mo., 13th, 1821, accompanied by our friend Othniel Foster;
Ethan Foster also going with us to Hartford, where we arrived on the 15th, at evening.
First day, 16th. We attended Friends`' Meeting at West Hartford,
in which it appeared that vital religion was in rather a low state with some present;
with these I was led into a pretty close inquiry,
exhorting them to a strict examination of their own state and condition,
for I had to believe that some of them had known better days than the present;
and however painful the sensation, I felt my mind in a good degree relieved.
We dined at Simeon Arnold`'s, and had a religious opportunity with him and wife,
and returned this evening to the city.
18th. Had an evening meeting at Wethersfield, among Presbyterians, Baptists,
and Methodists; most of whom appeared very unsettled,
and to have but little sense of vital religion,
talking and whispering during the short time of silence, if silence it might be called;
and it appeared that some looked upon us with ridicule; one got up and went out, saying,
as he passed us, "`he did not believe the spirit would move tonight,
and he would stay no longer.`"
I labored among them,
endeavoring to bring their minds to a little solemnity
and a feeling after the Divine presence;
a few appeared in some degree to realize what was offered,
but most of them I feared were lamentably ignorant of a
right preparation and exercise of mind for Divine worship.
I left them rather heavily, having to mourn over their superficial condition.

19th. We left Hartford, and went by the way of West Windsor to West Suffield,
where we found it our place to propose a meeting.
The proposition was cordially embraced by the people, and notice being given,
the school-house was crowded with people mostly of the Presbyterian denomination;
and considering there had never been a Friends`' meeting here before,
they gave great attention and sat very quietly,
and a favored baptizing season we had together; the doctrines of the Gospel,
substantially as they are believed by us, were pretty largely set forth,
and the meeting ended to satisfaction, with acknowledgments to Him who had helped us.
Here a young woman, a Presbyterian,
came to us after meeting and bid us "`God speed;`" she appeared to be an exercised woman,
and of some experience.
She made some inquiries respecting our principles, with which she seemed to be satisfied.

20th. We continued our travel northward until we came opposite to Springfield,
on the east side of the Connecticut River,
when we thought we felt a secret inclination to turn that way; which we accordingly did,
and stopping to feed our horse,
we fell into some conversation with a man on religious subjects,
who was of the Congregational Society,
but acknowledged to a directing principle in the heart, to which, he said, if we adhere,
we shall be sure to do right.
We distributed to him and several other young men present a number of our books,
which they seemed eager to receive, and some of them would fain have paid us for them.
There were also a number of young women in another room,
who got knowledge of our being there,
and sent us an invitation to come into their apartment and bring our books; which we did,
and let them select such as they chose; they also offered to pay us,
and gave us many thanks.
We had by this time got rid of two thirds of all we had;
but as several of the receivers lived in different parts at considerable distances,
we did not regret parting with them, they also promising to spread them.
Seeing this apparent desire and openness to receive and examine Friends`' books,
we regretted not having more in charge for distribution.
As no way opened for a meeting here at this time, we felt inclined to go eastward,
but seemed to go almost as if we knew not whither,
and feeling ourselves as strangers in a strange land;
but after a time we found ourselves at a village in the town of Wilbraham,
and seeing a man in the street,
we asked him if he thought the people would be willing
to come together to see some strangers.
He put the blush upon me by asking if I was a preacher, and however indirect my answer,
he gathered my meaning, and said he would consult his neighbors; and further said,
that if agreed to he would spread the information by the scholars,
and inform us at the tavern (to which we were going) of his success;
but said he would not promise us much of a meeting.
According to promise,
he came and informed that a meeting was appointed for us at the school-house;
where we met with near two hundred people,
and one of the ministers of the place with them.
It proved to be a highly favored season,
in which the doctrines of the Gospel flowed freely,
and our hearts were comforted and confirmed in the
almost unseen direction of our Holy Leader,
in bringing us hither.

21st. In conformity with an invitation last evening,
we breakfasted this morning with the Methodist minister of the place.
From here we returned to Springfield, crossed the river,
and travelled nine miles to Westfield;
where we felt desirous of a meeting in the evening, but by inquiring of our host,
were informed that their Conference Meeting came in course this evening at the town-house,
and that there was no other place to be had which would accommodate the people.
However, he went out to consult the deacons, whether they would waive their conference;
who, as he told us, were willing to give way on their own part,
but did not like to take the responsibility; by further consultation, however,
they agreed to get through with their services in about an hour,
when we might have our meeting.
We were accordingly invited by our landlord to go with him to the Conference.
They prayed and sung,
and then the Principal of the Academy was called upon to deliver a short sermon.
He came forward, opened a book, and read over a crooked kind of Calvinistic discourse,
yet couched in correct terms as to words; after this, a deacon again prayed,
and then said,
"`there was opportunity for the Friends present to speak
to the people,`" but excused himself from staying,
on account of special business.
During the time that these things were passing,
I endeavored to keep my mind as much retired as possible; but at best was in a stripped,
if not, in an almost confounded situation in myself,
having no prospect or view of any subject whatever on my mind;
but when the meeting fell into silence, a subject was soon presented to my view,
and I ventured (however foolish I felt) to step forward;
and the opening gradually increased until it became a baptizing season,
and the testimony of truth prevailed over all.
The people (some of whom, as our host told us, before meeting,
were afraid of us,) appeared now to be well satisfied,
and I felt the incomes of sweet peace in this evening`'s sacrifice.
Thus I find a full reduction of self is preparatory to my best seasons of labor,
as well as to a greater enlargement and opening in the Gospel.

23rd. Went to Northampton village, and put up at an inn.
As we felt desirous of a meeting here,
we inquired of our host if he thought the people would be
willing to come together and have a meeting with some strangers;
he replied that he thought they would, but alluding to the leading characters, he said,
"`our people are pretty superstitious here,`" yet added,
that he would go out and consult the deacons,
and try to get the liberty of the school-house.
After being gone a considerable time,
he returned with the information that they were not willing to encourage a meeting;
but that he and two or three more had hired a large hall near by,
for the accommodation of the meeting, and had notified it accordingly; which we attended,
and it was a satisfactory time.
First day, 24th. We had a meeting at a school-house, in the west part of Northampton,
to satisfaction.
25th. We set out for New Lebanon, in the State of New York,
a distance of about forty-five miles; the travelling was bad,
on account of the depth of the snow, and the path too narrow for our wheels;
and what made it still more laborious was,
that the first twenty miles were very hilly and mountainous,
so that our horse had enough to do, much of the way, to carry the empty chaise,
and we to clamber up the steep ascents on our feet; the path being very slippery,
we felt the want of corks, but we were favored to reach Hazard Mory`'s at night.
Next day we rested and I wrote to my family.

27th. In company with brother H. M., wife, and daughter, we went to Adams,
twenty-five miles,
and lodged at Samuel Browning`'s. 28th. Had a meeting here at Friends`' meetinghouse,
and in the evening at Joshua Mory`'s, Williamstown,
in which I had some clear openings in regard to the coming of Christ`'s kingdom,
and the doing of His will on earth as it is done in heaven;
a brief recapitulation of the progress of religion in the world,
and that in proportion as man comes to the purity of the Gospel,
his affection for outward things will diminish.
29th. Went to the Widow Gorton`'s, in Hancock, and had an evening meeting at her house,
in which the manner of obtaining the saving knowledge
of God was opened and fully treated on.
A Baptist minister attended, and was quiet.

30th. We had an appointed meeting in the village,
in which our doctrines in regard to Divine worship, the ministry, baptism,
and the supper were largely treated on.
The minister aforesaid was again present,
he and his hearers having given up their own meeting and attended ours;
they manifested no dissatisfaction, but sat quietly, and separated peaceably.
This meeting was on the first day of the week;
and in the evening we had a meeting at Lebanon Pool,
which was small on account of the severity of the weather; it was, however, satisfactory.
31st. Had another meeting at the same place this evening, to good satisfaction;
several Baptist people after meeting were inclined
to have some conversation on the subject of baptism,
in which we indulged them, and parted friendly.

1st mo., 1st, 1822.
We set out from Hazard Mory`'s and went to John Collins`'s, at Chatham,
where we were very affectionately received by him and wife.
Here I was much out of health for several days,
but was treated with the greatest kindness and tenderness.
I was, however, able to attend their meeting on fifth day,
which was pretty large and satisfactory.
On the same evening, we made a little visit to Sylvanus Gardner, an aged friend,
who is entirely blind; his company and conversation were savory.
He and his daughter live together, to whom the language of encouragement flowed freely.

While resting here at the house of his brother-in-law John Collins,
he wrote a letter to his wife, from which the following is an extract:--

"`I have in the course of this visit experienced some seasons of great depression,
and trial of faith;
wherein I have had sometimes to marvel that I should be out on such a service as this;
and again I have been renewed, and have appeared a little to myself,
like one who had risen from the dead.
I find that these descendings and ascendings prove as a check upon each other,
and a regulating balance upon the mind.
It is now three weeks since I left,
and getting round so far has taken rather less time than I expected;
but how much time may be required to perform the service before me, is yet uncertain.
I affectionately greet you all, with breathing desires for your preservation every way.`"

Seventh day, 4th. Went in company with brother J. C. and wife to Ghent,
and lodged at Nathan Collins`'s; here we had a favored meeting next day.

6th. In company with several Friends, we went to Hudson, where, in the evening,
we had a large meeting with Friends and the towns-people,
in which the state of mankind in different ages of the world was alluded to;
showing that the legal dispensation,
although adapted to the outward condition of mankind at that time, was not to continue;
but as men advanced fully to the purity of the Gospel,
outward and figurative observances are seen not to
be essential;--the meeting ended to good satisfaction.
7th. This evening, had a meeting at Claverack,
where we had a favorable opportunity with the people, mostly Dutch,
and not of our Society.
Substantial religion was closely recommended,
and the ill consequences of intemperance opened in a solemn manner.
8th. In company with Benjamin Jenkins and wife, of Hudson, went to Little Nine Partners,
and lodged at Samuel Gritman`'s, where next day we had a favored meeting, and went,
after it, to Jeremiah Browning`'s, and lodged; here we stayed till first day morning,
the 12th, when we went to Crum Elbow, and attended their meeting,
which was silent till near the close,
when I called their attention to the need of listening
to the intimations of truth on the mind,
rather than to be looking outward to hear the instructions of men.
13th. Had a meeting at the Creek, to good satisfaction,
and attended another in the evening, at Stanford,
which was attended by many of the Baptists,
whose opposition to the doctrine which was delivered,
seemed to run like a strong current against us,
and made it hard work to get rightly forward amongst them;
but Friends appeared to be satisfied with the meeting.
14th. Went to Oswego and attended their monthly meeting, to a good degree of satisfaction.
15th. Attended the monthly meeting at Nine Partners, which I sat through in silence,
having, at the same time, a fear attending my mind,
that they had more preaching here than was profitable; for I am confirmed in the belief,
that more than is meet will have a tendency to draw away the attention
of the people from the true place of waiting for instruction,
even in their own hearts.

17th. Accompanied by Eleazer Haviland, went to New Fairfield,
in the State of Connecticut, and lodged at the house of his father, Isaac Haviland,
near which we had a meeting next day, with Friends at the Valley; and in the afternoon,
went to Danbury, and had an evening meeting at the Courthouse,
which was large and satisfactory; the sheriff and one of the judges attended,
who were very attentive in keeping order in the meeting.
19th. Had a precious little meeting at Benjamin Knapp`'s, at the same place;
he and his wife are aged people, and were greatly tendered in this little opportunity;
at parting,
he expressed with tears that he could truly say it
was good for him that we had been there;
his children appeared to be people of religious sensibility,
and expressed much satisfaction in our visit.
In the afternoon, we went to Reading, and had an evening meeting there,
in which we had to acknowledge the great condescension
of Divine goodness in overshadowing us,
and qualifying for precious silent worship,
as well as vocal testimony and solemn supplication.

20th. Went to Trumbull, in company with E. H. aforesaid, and John Haviland,
who had kindly accompanied us hitherto from New Fairfield.
Here, as we passed the street, seeing no sign for a tavern,
we called on a man by the name of David Booth,
who had become dissatisfied with the Presbyterian religion,
and had read some of the writings of Friends.
He seemed glad to see us,
but our stay there appeared to bring a great strait over his mind,
on account of his family, which consisted of two daughters, his only children;
they were greatly troubled about their father,
on account of the course he was taking,--for we found before we left the place,
that the neighbors began to call him a Quaker, which, without doubt,
was very alarming to his daughters; and we having proposed a meeting,
one of them found means to get her father into another room,
where they had a pretty long conversation; on returning,
he told us he was very sorry it was so, but his daughters were going away that afternoon,
otherwise he should have been glad to entertain us at his house through the night;
therefore, we concluded, (which I had before proposed to my companion,
as being best,) to try to get entertainment elsewhere;
he told us where he thought we could be accommodated,
at the same time offering to do what he could to notify a meeting in their school-house.

Accordingly, he and J. H. went to inviting the people;
the rest of us went to the house proposed, kept by a widow woman,
to whom we applied for entertainment; but she appeared to be rather shy of us,
especially when E. H. told her that we had a meeting
appointed at the school-house that evening.
She inquired if we had seen "`Mr. Taylor,`" their minister, who, she said,
lived not far off, and told us where; saying she had no license,
and her stable was out of order.
But it so happened, that she saw the priest passing by, and called him in,
telling him in our presence,
that "`these gentlemen propose a meeting in the school-house this evening.`"
He put on a very affable countenance, and said,
he had made an appointment that evening for himself, and, therefore,
thought it would be rather difficult or improper
for us to have a meeting at the same time.

We told him that our meeting was already appointed, and many of the people notified,
and if he pleased, we should like to have his company also.
He replied,
that he would like to attend if he knew how to dispense with his own appointment.
The woman, on seeing this complacency between us, began to shake off her fears a little,
and said to him, "`Mr. Taylor, your appointment is on the other street,
and near three miles from this, and the people there can attend your meeting,
and the people on this street can attend the meeting which these gentlemen
have appointed;`" to which proposition he made no further objection,
and went on towards his own meeting; and when the time came, we attended ours,
which was a favored season, and best help, to my admiration,
was afforded while on my feet; and, as J. H. observed,
when I had nearly half done speaking, he saw the priest come into the entry, and stand,
among others, by the door, thus being a witness to the latter part of the testimony,
relative to outward ordinances, and the true Gospel ministry.

When we returned to our lodgings, we found him there.
I inquired of him whether he had been at our meeting?
He said he had, but it was so near the close, that he had no opportunity to hear,
and avoided conversation on the subjects treated on in the meeting, which he had heard,
but introduced the subject of receiving divine grace,
pleading that men must be elected and changed before they can receive it;
which proposition we reversed,
by showing that the change and election is effected
by receiving and conforming to its operation.
After divers objections, which he brought against the universality of light and grace,
were obviated and answered, and he had obligingly invited us to his house,
he took leave of us in a friendly manner.

There was a man present during this conversation, who told us, after the priest had gone,
that he had several times of late, heard him publicly declare,
that every man`'s election or reprobation was decreed from the foundation of the world.
But the woman seemed hardly willing to admit that her minister
had ever made so decided a statement in favor of decrees;
and said to the man, "`Whatever you may have understood Mr. Taylor to say on the subject,
he now appears to agree with these gentlemen in regard to free grace.`"
In the morning, before leaving the town, we called again to see David Booth,
who expressed much thankfulness for our visit to the place,
and great satisfaction in the meeting, and we left him very tender.

We went from this place to Bridgeport, where we thought it right to propose a meeting.
Accordingly, our host sent his young man with J. H. to consult the minister,
who kept the school in the academy,--the most suitable place to meet in.
He told them that he had been applied to by a man of the Methodist society
for the use of the room for a minister of theirs from New York,
who was expected there that evening,
and that it would be well for them to inquire of
the man whether they were likely to want it,
and if they were not, to let him know it,
and he would give out notice of the meeting for us by the scholars.
They applied to the Methodists,
and were told if their minister came they would have their meeting in their own meetinghouse,
near the academy, which accordingly took place; and being so near ours,
had rather an unfavorable tendency in the forepart of our meeting,
the people appearing to be in suspense which meeting to attend;
some would come in and sit awhile, and then go out, and those who stayed,
who were pretty many, appeared to be very unsettled in their minds, or most of them;
but however unfit the meeting seemed to be for receiving Gospel instruction,
I found it my place to stand up and labor among them,
in order that they might be gathered to the ground and place of true devotion.

The work was laborious indeed,
and I found that great care was necessary in order to step rightly along.
After thus striving with that floating, scattering disposition for a considerable time,
a solemnity began to cover some of their minds,
and finally spread over the whole audience.
While I was speaking the other meeting broke up, (which, it seemed,
was short,) and their whole company came to ours,
making some interruption for a few minutes; our house was now much crowded,
but soon became settled and quiet.
While this addition was making to our meeting, I sat down,
but as soon as the meeting became a little settled,
I resumed the subject where I left it,
and the opening was enlarged to divers doctrines of the Gospel, and, I believe,
it was a baptizing season to some.

22nd. We travelled to New Haven,
and attended a meeting appointed for us there in the courthouse, which,
although not large, on account of the great severity of the weather, was a solid meeting,
and there appeared great openness in those present to receive our testimony.
Here we found one member of our Society, and several friendly people,
who freely acknowledged the excellency of our principles.

23rd. We parted with our dear Friends E. H. and J. H.,
who had thus far given up to accompany us, and had been agreeable companions,
and truly helpful to us.

We proceeded from New Haven towards home, not much expecting to have any more meetings,
passing easily through several villages till we came to Killingsworth, where,
as we were passing along the street,
my mind was secretly and very unexpectedly arrested with
an inclination to make a little stop somewhere here;
and seeing some men with a team, I inquired of them the name of the place, which,
when I had heard, I inquired after one A. S., a man of considerable note,
of whom I had heard, that he lived at Killingsworth; they showed us his house near by,
where we called,
and after some conversation I opened to him my desire for a meeting with the town`'s-people.
He acquiesced, and his son and clerk went immediately out to notify the people.

This man would not consent for us to go to a tavern, but had our horses put up,
and kindly entertained us at his own house.
It was after sunset when this meeting was agreed on,
and in about one hour the room in the academy was much crowded with people,
besides a number who came that could not get in.
This meeting--how different from some which I have
attended! here they gathered as in the solemnity,
prepared to receive our testimony; and my heart was filled with matter,
like a vessel that wanted vent; mouth and wisdom, tongue and utterance,
were given to my admiration, and the meeting ended with solemn supplication,
wherein we were made joyful,
as in the house of prayer;--at which season we not only
felt breathing intercessions for the people present,
but for many with whom we had met in this visit,
and who were now brought near to our best feelings.
Here we were enabled, as a finishing season to the visit,
to present these as at the footstool of God`'s mercy and the throne of his grace,
acknowledging the favor of the past,
and desiring the continuance of their and our future preservation.
Next day, travelled about forty miles to Joshua Gardner`'s, in Stonington;
and the day following, the 27th of 1st month, 1822, arrived home,
and I was rejoiced to meet with my family again, and find them in usual health.
