[short="Chapter II"]
== Chapter II. His Travels and Exercises Between 1824 and 1827, Including Some Allusion to his Early Life and Experience.

7th mo., 17th, 1824.
Fifty years have now elapsed, since the day of my birth.
The events which have transpired--the exercises, experience, and errors of my past life,
are known to me; but those which yet remain in the bosom of futurity are unknown to me;
and although it is far from me to cherish a vain
desire of foreboding that which may fall to my lot,
yet one thing I do desire, namely,
that I may be favored with meekness and patience to endure the requisite
tribulations that may hereafter be my portion in Divine appointment;
and that a living experience in that which is good may be increased within me,
that so I may be more and more enabled to foresee and shun the evil.

Not having recorded any account of my life heretofore,
save of a few visits abroad on a religious account, I think proper now,
however out of season it may appear, to commence, by way of diary,
some account of my religious exercises and experience,
for the benefit of my family after time to me here shall be no more;--as
well as to note some circumstances considered more common in life.

But, regarding what is past, I may say that the guarded care of my parents,
a constant attendance of religious meetings,
and an attention to the reading of the Scriptures of truth,
were a great help to my mind in preparing the way for,
and directing my attention to the saving principle of Divine grace within,--the
restraining power of which I became acquainted with in very early life;
and I feel constrained to bear testimony to its efficacy and sufficiency in effecting
the work of regeneration and salvation of all who yield to its reforming power;
and this converting principle of light and grace,
I fully believe was procured and conferred on mankind by Jesus Christ our Lord;
that his coming, life, death, and sufferings,
are the very groundwork of the application of this principle; which is,
emphatically speaking, the spirit of Christ the Saviour of men.
That He is the only mediator,
and offered himself a propitiatory sacrifice for sins that are past, repented of,
and forsaken, is beyond all doubt; and on this hangs my hope.
It has, I trust, been the expiation of my past errors,
and in Him is my hope of preservation in the future.
It is this inward operating principle that has so far preserved me through life;
and it is to this blessed spirit of Christ alone that I trust for
direction and preservation during the remainder of my pilgrimage.

[.offset]
+++[+++A blank in the Manuscript follows the foregoing,
which gives the impression that he did not finish what he intended.
The following extract from a letter to a friend, written many years afterwards,
will in some measure supply this defect.]

[.embedded-content-document.letter]
--

I have often recurred, with a degree of satisfaction, to my early impressions,
as well as to the instructions which were given me by my parents.
They early made me acquainted with the doctrines of Christianity,
so far as the reading of the Scriptures of truth would give me that knowledge;
and I was carefully instructed to reverence these sacred writings.
The precepts of the New Testament, in a particular manner,
did seem fully to correspond with those secret sensations,
which I was early led to believe were the openings and leadings of truth upon my mind;
I was enabled also, without an expositor, to receive and satisfactorily to understand,
some of the more prominent and simple doctrines of the Gospel,
as to the character and the several offices of Jesus Christ the Saviour of the world.
And now also, in due time,
the history of the Society of Friends was introduced to my reading and observation;
and my youthful mind was thereby strengthened and confirmed to make a more perfect
discrimination between the works of the law and those of faith,
and to perceive what faith in God,
and in the Lord Jesus Christ would do,--even that faith which worketh by love,
to the purifying of the heart.
I saw that it was sufficient; that it enabled those sons of the morning of our day,
notwithstanding the mighty opposition which lay in their way,
to work the works of God,--even those spiritual works which were wrought in them,
and by them, through the sanctifying power of the Holy Spirit,
in the covenant of God`'s promise unto them,--even
in like manner as the primitive Christians did;
they joined and worked with the workings of grace in themselves, to the glory of God,
and to the praise of the Lord Jesus Christ.

And now I found myself to be one of this Society, not by birth and education only,
but I embraced and received, and fully believed in the doctrines of Christianity,
as professed by it; and I have ever since loved the Society and its testimonies,
wherever they have been planted; not only in my native land of America,
but also in this nation, +++[+++England,]
where this the Lord`'s right hand planting was, as regards our Society, first begun.

--

7th mo., 18th. First day.
Had no opening at meeting this day for communication to others,
but considerable enlargement in my own mind,
more especially on the attributes of divine greatness,--not only present in every place,
but extending through all extent, far beyond the limited reach of our widest conceptions.
The terms boundless and infinite exceed the utmost
stretch of practical reflection with us,
though they are frequently used by men in attempting to describe God`'s existence;--perhaps,
in a strict sense, even rather presumptuously so,
because they extend so far beyond anything we know;
and yet that He is incomprehensible by men, is no presumption at all,
because we know it and can truly say that He is good and great.
And, in the conclusion of these reflections, and a consideration of human foolishness,
finitude, and littleness, I had also to reflect,
how trivial are our trials and sufferings in this world,
and how supportable and easily endured,
by a mind truly enlarged in the enjoyment of love divine here,
and a prospect of a fruition of it hereafter.

2lst.
Micajah Collins, Paul Newhall, and Matthew and Betsy Purinton,
came to our house and lodged.
Micajah has now set out on a religious visit to Ohio and Indiana.
They all attended our preparative meeting the next day; Micajah had a lively testimony,
comforting and encouraging to the few exercised minds among us;
but close and pertinent to a worldly spirit,
and such as are halting between two opinions,
or such as are not fully decided whether to place their affections upon the Truth,
or upon the things of this world; for such there truly are,
whose minds are divided between God and Mammon;
and how feeble and unavailing must their efforts be on the side of religion,
while they are captivated by the god of this world!
The consideration of it is truly mournful,
and especially so when we are assembled for religious worship; for when there,
they are dull and heavy, and cannot participate in the exercise of it;
such a state prevalent in a meeting very much obstructs the current of lively devotion,
and brings a burden upon the living.
This afternoon our Friends left us, Micajah and his companion pursuing their journey,
and the others returning.

26th. At the Monthly Meeting held at South Kingston,
I had a fresh opening of the divine goodness in sowing the
seed of the kingdom in the hearts of the children of men,
its nature and sufficiency, the capacity of the mind to profit by it,
and that if fruit is not brought forth, we must "`blame the culture, not the soil.`"
The parable of the sower, and Isaiah`'s allegory of the vineyard,
opened in a consideration of the subject,
and our accountability for the interposition and favor of Divine Providence
toward us was brought pretty closely home to the minds of those present,
and that the denunciation against the Lord`'s vineyard must eventually be applied to us,
if there be not a faithful cultivation of the choice vine.

First day, 8th mo.,
1st. I left home in order to attend the Quarterly Meeting at Portsmouth--attended
in course the meeting at Coventry--silent--went to Providence,
and lodged at Moses Brown`'s. In this dear aged Friend we see,
not only what the power of truth and a devotion to it will do for the human mind,
but an uncommon continuation of the mental faculties in old age; he being, I think,
in his eighty-seventh year.

Second day.
Proceeding on my way toward Portsmouth, I stopped at Swansey to see my son,
who has commenced the practice of medicine there;
he appears to have obtained the confidence of the people so as to promise success;
but I feel cautious of flattering myself therewith,
knowing that the greatest prospects in this life
may be suddenly blasted by some unforeseen occurrence;
and my greatest desire for my dear children now centres in this,
that they may be preserved in the Truth by that providential
hand which can give success in outward things,
or otherwise, as He may see meet for our spiritual good.
Isaiah, chap.
v.

4th. Went to Portsmouth, and attended the Select Quarterly Meeting,
in which some remarks were made on the subject of
true faith in our Lord and Saviour Jesus Christ,
and on an improper extension of offerings in the ministry.

Fifth day.
In the morning attended a meeting of the Select Yearly Meetings`' committee
on a distressing case of difficulty and unsoundness about New Bedford;
the deliberation resulted in the conclusion for some part
of the committee to attend the Select Meeting there.
I attended the Quarterly Meeting this day, which was conducted satisfactorily,
after which I returned to Swansey; and on sixth day,
attended the meeting of the general School Committee at Providence,
in which a concern and care was manifest for a right regulation of that important institution.

Jonathan Chace, of Swansey, Mass., died very suddenly on first day,
the 24th of last month.
He was a minister in good esteem in our Society,
a zealous supporter of our principles and doctrines, both by example and precept;
a pattern of primitive simplicity and humility;
honest and plain to all in the discharge of what he apprehended to be his duty;
affable and agreeable in his conversation, and in his manners without affectation.

8th mo., 15th. I had some pretty clear openings this day, at meeting,
respecting the way to obtain living waters,
several passages of Scripture opening clearly on the subject;
but I had not as I apprehend the word of command to communicate anything of it to others.
23rd. Attended Monthly Meeting at South Kingston; where, after a long laborious time,
I had a close searching testimony near the close of the meeting for worship,
and an alarm to sound to some who (as appeared to the view of my mind) were buried
so deep in the earth as scarcely to be able to hear the word of the Lord,
though it might be thrice repeated, as by the Prophet, "`O Earth!
Earth!
Earth!`"
A current of consolation was nevertheless extended to the mourners in Zion,
for the lifting up of the weak hands, and the confirming of the feeble knees.

9th mo., 25th. Our Monthly Meeting--Matthew Purinton and his wife, Betsy, attended it;
in which she had good service, as also the next day in our Select Meeting.
30th. I attended the funeral of Martha Dye; had a very open time with the people,
and best help was mercifully afforded.
31st. I attended Greenwich Monthly Meeting, held at Cranston, silent throughout;
after which I went to D. and T. Howlands`', thence to Moses Brown`'s and lodged;
his company and conversation continue to be truly interesting.

11th mo., 2nd. The Select Meeting this day was overshadowed with the quieting,
cementing influence of Divine love and goodness, which united us together;
and although I found it not to be my place to speak of that,
yet I did in my measure feel thankful that we who constitute this meeting,
have hitherto been preserved from the jar and commotion with which our
Society is at this time shaken in several sections of the country,
on account of unsoundness in doctrine in divers individuals;
and in this meeting I feelingly commemorated our
favors and craved preservation in the future.

12th mo., 1st. Attended the Select Quarterly Meeting at New Bedford,
and in the afternoon the meeting for sufferings,
and the next day the Quarterly Meeting at large.
The meeting for worship was truly a painful time,
being much disturbed by some not in membership, and others not in unity,
they having imbibed unsound doctrines;
it appeared that these disturbers tried their utmost
to provoke us to make some reply to what they offered;
but wisdom, I believe, dictated silence on our part,
and I had to remember the trial before Pilate,
and the sufferings of our Saviour when his enemies
pressed him with keen invective and rude provocation,
to draw something from him, but to no effect; for it was said of him,
that he was as a sheep dumb before her shearers, in that he opened not his mouth.
I was glad that Friends exercised Christian patience and forbearance on this occasion;
for I have great reason to believe that their opposers are much in the same spirit now,
that His personal enemies were in that day.
They had him crucified because (as they said) he "`being a man, made himself God.`"
They crucified Him because he professed a Divine character;
and these very opposers of ours are also opposers of his Divine character,
which is evident from what was held forth in this meeting,
as well as what they have said at other times.

They say he was no more than a man, and, as a man,
"`was made perfect through suffering,`" and thus wrest the
apostles`' expressions from their proper meaning;
for the Saviour was doubtless holy and pure from his birth
of the virgin Mary to the day of his ascension into heaven;
but as the means which God had ordained for the redemption of mankind was not
completed or perfected until Christ had partaken of his cup of sufferings,
so the apostle might well say that he was made a
perfect and complete Redeemer through suffering.
The same apostle also says that "`in Him dwelt the fulness of the Godhead bodily,`"
which includes and is the unity of all the attributes of Deity--the power,
wisdom, goodness, justice,
and mercy--which no created being or thing ever possessed in the fulness,
either in heaven above or the earth beneath, save the man Jesus Christ.

I thought it my place to commend Friends (near the
close of the meeting for business) for their patience,
at the same time reminding them of the necessity
of being on their guard against the unsound principles,
which these people are striving to promulgate.

6th. Attended the meeting at Cranston in the morning, which, though small,
was a comfortable opportunity.
In the evening I had a meeting at the Arkwright village;
in which my labor at first was difficult and trying, on account, as I apprehended,
of the minds of the people being too much outward,
and not rightfully turned to the alone true object of worship;
and it seemed for a time that I should soon sit down
without obtaining any satisfaction from the opportunity;
and it would doubtless have proved so,
had I not honestly told them their fault in getting
above the just witness of God in their own minds,
and a want of humbly bowing in prostration before Him.
I then perceived they began to deepen a little,
and the truth appeared to have more place in their minds,
and way was finally made for much close and arduous service among them.
After I sat down R. G. made some remarks, and the meeting ended well.

3rd mo.
3, 1825.
According to invitation I attended the funeral of Susan Palmer, wife of Fones Palmer,
not a member of our Society, but educated in the way of the Seventh Day Baptists.
I had visited her several times in the course of her sickness,
which was a chronic consumption, and found her in a sweet sensible frame of mind,
and having a pretty good understanding of the transforming power of religion;--she
appeared fully to acquiesce in the Divine disposal of herself.
Her life had been regular and exemplary.
At her funeral, M. S.--a Baptist preacher--being also invited, attended,
with many of his hearers; many Friends also attended.
M+++.+++ S. came in and sat down by me,
and very soon asked me if I had been invited to attend the funeral.
He was answered in the affirmative;
soon after which he proposed that I should "`go forward
with the exercises of the day,`" as he expressed it,
and said that he should not only be satisfied for it to be so,
but should consider it a privilege; to which I replied, that,
as he had also been invited, I felt no disposition to be in his way,
or in the way of any service which he might feel it to be right for him to be
exercised in;--he replied that he would also wish me to act in my freedom.

He soon after arose,
and said that "`as it appeared that Friend Wilbur had nothing on his mind to say as yet,
and as he was not very fond of silent meetings,
he would attempt to go forward;`" and so made an
introduction in their usual way by prayer,
after which he took the Bible and opened to the passage,
"`Many are the afflictions of the righteous,
but the Lord delivereth him out of them all.`"
He was pretty lengthy in his exposition of it,
and by the tenor of his discourse it would appear
that this deliverance is either of a temporal nature,
or protracted to the end of life;
for he gave us no account of what the righteous experience of the
power of a Deliverer in their spiritual conflicts and temptations,
and he did not appear to believe in the righteous
being delivered from the power of temptation,
without sinning, until the end of life.

In the course of his preaching, he took up the subject of faith,
and spoke well upon it until he had nearly closed on that subject,
when he implied that true faith would lead to water baptism,
and brought forward the passage of Philip and the eunuch; soon after which he closed.
It appeared to have been his intention to make light of silent meetings,
or rather to give them a brush, and to maintain the propriety of water baptism;
but in a way that would not be very likely to produce much excitement on our minds,
yet at the same time to make some headway in the confirmation of his people,
and in derogation of our principles.

Here, then, the necessity of care and discretion on our part was very obvious,
and of our being "`wise as serpents and harmless as doves.`"
The champion of the Baptist connection hereaway being present and at their head,
their expectation doubtless was, through him, to take the lead;
and it appeared to me to be of importance so to conduct ourselves as not to give offence,
and yet not to abandon our principles, but to stand resigned, if required,
to maintain them in the ability afforded,
and at the same time to do nothing that would lead
to contention or disturbance on such an occasion.
After a short pause, the following passage of Scripture opened to my mind,
which I mentioned, namely, "`Lord, we saw one casting out devils in thy name,
and we forbade him, because he followed not us,`" and that the reply of our Lord was,
"`forbid him not, for he that is not against us is for us;
for there is no man doing a miracle in my name that will lightly speak evil of me.`"

A testimony of some length ensued, the outlines of which were to the following purport,
as nearly as can be remembered:
"`That although all the professors of Christianity
are not agreed to follow alike in all things,
yet any who are qualified to be instrumental in exterminating evil,
either from their own hearts or from others, ought not to be forbidden;
that no unkind feelings ought to be cherished in our hearts against our brethren,
the followers of Christ our master;--that as God is our Father, and one is our Master,
even Christ, so the whole Christian family is, or ought to be, one family;
that God looks at our sincerity; and that,
although my friend who sat by me did not see in all things as I did,
inasmuch as he was not fond of silent meetings,
yet I entertained no unfriendly feelings towards him,
however well assured I was of the propriety of silent,
solemn prostration before God when we come together to worship Him,
and of the necessity to wait on Him, our holy High Priest, standing at the altar,
and waiting for our sacrifice to be prepared before we offer it;
that impressions from Him should be attended to,
in preference to the expectation of the people; that as in heaven, so on earth,
his will should be done.

I reminded them that silence was observed for a certain space in heaven +++[+++Rev.
ch. viii.
1]; that our Saviour, in his last charge to his disciples before his ascension,
gave them this command, "`Wait for the promise of the Father,
which ye have heard of me;`" that although they had previously been sent forth to preach,
they were nevertheless to continue to wait for the renewing of the Holy Ghost.
Then the commission was more fully alluded to and repeated,
"`Go ye therefore and teach all nations, baptizing them in the name of the Father,
of the Son, and of the Holy Ghost; he that believeth and is baptized shall be saved,
and he that believeth not shall be condemned;`"--"`wait for the promise of the Father,
which ye have heard of me,`"--"`for John truly baptized with water,
but ye shall be baptized with the Holy Ghost,`" etc.--that is,
John baptized his disciples with water,
but my disciples shall be baptized with the Holy Ghost;
that Jesus referred them to the promise of the Father,
which they had heard of him,--alluding to the baptism of John,
and promising his own "`with the Holy Ghost.`"

In addition I directed all, hearers as well as speakers, to this promise of the Father;
for if we believed in it, we might all, by waiting for it,
become the happy receivers of this gift of God`'s Holy Spirit,
and the revelation of his will in our hearts by Jesus Christ,
which would do away all vanity, and unite us together into one body;
that enmity ought not in the least to have place in any of our minds,
for if indulged and cherished, it would lead to the very worst of evils.
In conclusion,
I spoke a few words in reference to the virtuous life and dying experience of the deceased;
and after a considerable pause, the meeting ended in solemn supplication,
in which near access was opened to the fountain of Goodness.

I think I may say that I was deeply humbled in thankfulness
to Him whose direction only can guide us aright,
and who alone is able to strengthen in the day of battle,
and keep peace under his own banner.--Amen.

6th mo., 16th. At our Yearly Meeting, this year, we had a favored quiet season;
and the concerns of it were transacted in much harmony and Christian condescension.
It felt truly comfortable to be again permitted to sit in this capacity,
under our own vine and fig-tree, and none from without to disturb or make us afraid;
and this favor was the more sensibly realized,
for the reason that this meeting had for several years past been
interrupted and disturbed by some unsound and troublesome persons,
who were opposed to good order and church government.

22nd. Brother Woodman Wilbur died, in the eighty-second year of his age;
he was the oldest child of my father by his first wife,
and I was the youngest by his last wife,
there being something more than thirty years`' difference in our ages.

25th. I attended a Monthly Meeting,
in which our friend George Hatton was livingly exercised in the ministry,
and the state of things among us was clearly and
feelingly spoken to--his testimony being very impressive.

26th. Attended the funeral of our deceased Brother,
and notwithstanding the near connection, my mouth was opened in public testimony,
and I thought it was a time of considerable favor.

8th mo.,
13th. Having had a concern for some time to visit
Friends in our eastern country in Gospel love,
I spread it, on the 26th ultimo, before our Monthly Meeting,
and obtained their certificate of concurrence, and expect, tomorrow,
to leave my home and my dear wife and children, to proceed on the journey.
I have had much close exercise to undergo of late, on account of leaving my family,
who seem to need my pretty constant care and help;
but I have had to consider that I must one day be called to leave them,
and all things else in time, no more to return; and that parting thus for a time may,
if rightly improved, be the means of preparing my mind, as well as theirs,
for our last separation from one another, as well as our final one from time.
And my desire and prayer to God is,
that He would be a Caretaker and Preserver of them in my absence; and if they remember,
love, and fear Him in all their ways,
I have faith to believe that they will find Him to be near,
and a present helper in every needful time.
And may I be favored so to follow his guidance in humility and faithfulness,
that he may deign to preserve me in the hour of temptation,
as well as at all other times.

Being furnished with a certificate from my Monthly Meeting,
I took solemn leave of my family on the 14th of 8th mo., 1825,
in order to visit Friends and others in the Quarterly Meetings of Salem, Dover, Falmouth,
and Vassalborough, with Ethan Foster for my companion.
Attended the Quarterly Meeting at Lynn, on the 17th and 18th,
as also the Meeting for Sufferings.
The Quarterly Meeting at large, was a time of favor,
wherein divers lively testimonies were borne to the truth,--George Hatton, from Indiana,
Huldah Hoag, from Vermont, and James Hazard, from Cornwall, (N. Y.,) being present;
but it was my lot through this meeting to be silent, with which I was well satisfied,
believing it to be in the ordering of best wisdom.

However clear the opening and prospect of this visit had been,
I have as yet felt very poor and destitute as it
regards a qualification for public labor.
My faith has been very nearly tried, and I have been almost ready sometimes to look back,
on account of this season of close trial and deep baptism,
in which I have been ready to say, surely I am not fit for such a mission,
for I have not bread to sustain my own drooping spirit, much less to hand to others.
But still a grain of secret faith was left me,
that as the prospect had been once clear to my mind, He who called,
and whose promise has never failed the humble obedient traveller,
would loose my bonds and make way for me, if it was his will that I should advance;
and I thought I could say it was not in my own will that I left my dear wife and children,
and under divers discouraging considerations and trials was made
willing to endeavor to do his will and follow his guidance.
And I said in my heart, "`Lord,
I have left all to follow thee,--wilt thou now be with me,
and enable me to follow thee whither soever thou leadest!`"

19th. I attended meeting at Salem, in company with H. H.,
in which I had to sound an alarm among them.
Afternoon, went to Newbury to R. Brown`'s,
and next day attended meeting there to good satisfaction.
Had a precious opportunity in this family, encouraging them to faithfulness.
Afternoon, went to Amesbury, in order to attend a meeting there,
but by reason of some neglect, the information was not spread, and but three or four,
besides our company, attended.

First day, 21st. Still in company with H. H., attended meeting at Seabrook,
where it was my lot to speak against pride and high-mindedness.
22nd. Had a pretty satisfactory meeting with the few Friends at Epping,
and some of their neighbors; and the same afternoon, one at Lee,
in which the Gospel state was testified of,
and brought home to them pressingly and feelingly, as being exalted above the law.
23rd. Went to Dover, and had a meeting there, in which Huldah was favored in testimony;
and though way did not open for much service on my part,
some things were brought pretty close home to the
backsliders and careless walkers in our Zion.
Dined at Isaac Wendell`'s, and then went to the Great Falls,
where we had a large evening meeting to pretty good satisfaction;
but H. H. stayed this afternoon at Dover, and attended a funeral.

24th. Went to Berwick, and attended their Select Quarterly Meeting,
where it was my concern to call Friends to a deep indwelling, humility,
and abiding in baptisms until we are qualified to do the Lord`'s work.
In the afternoon, in company with H. H., attended the meeting at Oak Woods, which,
though long silent and laborious, became a time of distinguished favor,
and the power of truth was made by Israel`'s helper to prevail
over all;--we returned to Berwick with refreshed hearts.
25th. Attended the Quarterly Meeting,
in which we endeavored to labor a little in the ability
which our Heavenly Father gave us.
There appeared to be much want, in some of the branches of this Quarterly Meeting,
of primitive zeal as it regards the attendance of religious meetings,
and also great want of love and unity;
which defects caused sorrowful feelings in my mind,
and led to much labor in the meeting for discipline for a recovery.

26th. Travelled to Scarborough,
and had an evening meeting with one family of Friends and their neighbors,
to a good degree of satisfaction, and lodged with this family.
"`We left H. H. at Berwick.

27th. Went to Cape Elizabeth, and on first day, the 28th, attended the meeting there,
and a painful one it was.
The leading member of this meeting had become unsound in the faith,
and had been disowned from the Society, but still at meeting kept his usual seat,
which to me appears very improper.
In the afternoon, I attended Friends`' meeting at Portland,
and had one appointed in the evening for the townspeople; in which,
though I felt utterly insufficient in the beginning,
I was favored with strength to explain some leading points,
and to bear testimony to the power of the Gospel,
recommending these great truths to the practical observance of those present;
this was a very crowded meeting, and was attended by three of the clergy.
29th. E. Foster being unwell, we rested, and I wrote to my family.

[.offset]
+++[+++From this letter, the following extract is taken:]

[.embedded-content-document.letter]
--

We expect to attend a meeting at Falmouth tomorrow,
appointed for the solemnization of two marriages, and then the Quarterly Meeting.

Things are much out of order in the Society within the compass of this Quarter,
which makes our prospect of labor very discouraging; from this and other causes,
I have had to endure much trial and conflict of late, and, indeed,
it has been very much my lot for most of the time since I have been out; yet, at times,
and more especially when at meeting,
I feel bound to acknowledge that the helper of Israel has been near;
and although discouragements sometimes intervene,
I am not without an assurance that we are in our places.

--

30th. Went to Falmouth, and attended the meeting appointed for two marriages, in silence.^
footnote:[In regard to this meeting, his companion related the following incident:
"`At the close of the meeting,
I asked him how it happened that he was silent among so large a company of young people?
To which he said he would reply in the language of an eminent minister,
on a similar occasion:
'`If I had had my Master`'s fowling-piece I could have wounded some of them`'`"]

31st. Attended the Select Quarterly Meeting there,
in which I had some very close labor among them; for, indeed,
I have had much exercise on account of the state of things among Friends here,
and have been brought very low in consideration of it;
but in delivering what lay on my mind, in the Select Meeting, I felt considerable relief.

9th mo., 1st. Attended the Quarterly Meeting at large,
in which I was not commissioned to open my mouth either
in the public meeting or in that for discipline.
At this meeting, we met again with Jas.
Hazard and H. H., and next day joined them, and went to Pownal and had a meeting there.
Seventh day, 3rd. We had a meeting at the Bend, (so called,) and Little River;
in the former of which it was my lot to be silent;
but in the latter my bow was strong for the battle,
and He who was pleased to go before gave us the victory.

The departure of the younger members of our Society in this land,
from our ancient testimony of simplicity and plainness, is cause of sorrow;
because it not only evinces that their minds are not sufficiently
subject to the restraint of the Cross of Christ,
but also leads directly to mingling with the people of the world,
and consequently into the spirit of it.

First day, 4th. Attended their meeting at Durham, which was very large and favored;
after which we went with Huldah to a meeting appointed for her at Bath,
which was held in a Baptist meetinghouse, and was large and very unsettled,
in which it was my place to be silent.

5th. Went to Litchfield, and next day had a meeting there, J. H. and H. H. being with us;
this meeting was rather laborious; after which we went to Vassalborough,
and on the 7th attended the Select Quarterly Meeting, and next day,
the Quarterly Meeting at large, which was a highly favored time.
I went into the Women`'s Meeting, and had good service among them.

9th. Went to Fairfield in company with J. H.;
Joseph Howland and wife concluded to accompany us for several days.
We had a meeting there, in which I was engaged in close searching testimony.
The young people here are mostly gone out from the Society,
but I believe this was an awakening time to some of those present.
In the afternoon, went to Belgrade, and lodged at Samuel Taylor`'s,
and next day had a highly favored meeting in his house, with a few Friends,
and many of their neighbors; and in the afternoon, one at Sidney.
Here we had a very trying meeting, which was silent on my part till near the close,
when I had to make some close remarks to some states present.

First day, 11th. Went to Eunice Ramsdell`'s, and attended their family meeting,
and divers of the neighbors being invited, came in, and we had, as I thought,
a pretty favorable opportunity with them.
Towards evening we had a large meeting at Gardner, in the Episcopalian meetinghouse,
wherein the different dispensations of the Law and
the Gospel were distinguished and illustrated;
showing that salvation is only attainable by the great mediatorial offering
of Christ in whom the remission of sins repented of and forsaken is obtained,
and grace and truth shed abroad upon the world; it was a solid meeting,
and we had some cause to hope that our labor would not be lost.
12th. Went to Bristol, where the day following we had a meeting,
which was a favored season, after a morning of deep wading and lamentation,
in consideration of the great departure of the children of Friends here;
for we found that nearly all of them had gone out of our Society.

Afternoon, went to Hope, where we found things but little better,
in regard to the children, and what increased our painful feelings,
was to find that the parents (most of the few who lived here) were too careless,
both as regards their children, and the testimony of Truth.
Our meeting here was very small, and most of those in attendance, not of our Society,
to whom, however, I had a testimony to bear for the life and power of Truth.
From here we went to Albion and lodged at John Warren`'s,
we being mutually glad to see each other.
15th. Went to Unity, and had an evening meeting there,
in which I had a close searching testimony,
and had to sound the trumpet of alarm to some present; it was a solemn time,
and the meeting ended in fervent supplication.

16th. Went back to Albion to attend a meeting appointed for us there;
met with George Hatton,
and found that he also had sent forward notice of
an appointment at the same time and place;
we also were made glad in meeting again.
The public service of this meeting fell on him;
he was now going eastward and we westward; we had, therefore, soon to part after meeting,
and in a little opportunity at that time the stream of Gospel fellowship,
and a desire for each others`' preservation, flowed freely,
not knowing that we should soon meet again, if ever.
After parting with him, and before we left here,
I felt a concern to give notice that we would be here again on first day,
the 18th. On the 17th we had a meeting at the Branch, and one at China,
the latter of which was a time of special favor.

18th. Went back to Albion, where we had a full meeting of Friends and many others,
in which help was abundantly afforded in demonstrating the ground
of man`'s coming to the presence of his Maker with acceptance.
After this meeting we spent a short time again with dear John Warren very pleasantly,
and then went to the Pond at Vassalborough,
and attended an appointed meeting in the evening; it was a very crowded assembly,
and divers doctrines were opened and states spoken to.
After meeting, we went home with Joseph Howland and wife,
who had travelled with us about one hundred and fifty miles.

19th. Had an appointed meeting at the River;
in which help was afforded in giving some encouragement and counsel to those present.
20th. Went to Windsor, and had an evening meeting there, which H. H. also attended,
in which I had pretty fully to treat on the subject of baptism--that
the saving baptism is inward and spiritual.
Huldah, also, had much to communicate.
21st. Went back to Vassalborough, and attended their mid-week meeting,
where also was a marriage; and after meeting, went to Augusta,
where we appointed a meeting for the next evening, meanwhile sending forward a notice,
that we would be at Winthrop the evening after.
Our evening meeting here was large, in which Gospel light,
and the possibility of falling from grace, were largely treated on,
and we thought it a time of favor.

23rd. At Winthrop, we met again with George Hatton, and attended the meeting together,
in which we both had testimonies to bear to the truth, and it was a good meeting.
Parting with G. H., we went to Leeds, and had a meeting there next day;
where I had to speak closely to a lukewarm state,
and also at the close offered encouragement to some exercised minds.
25th. Went to Lewistown, and had a meeting with the few Friends there, and many others;
here the substance of things was enlarged upon--that of free salvation for all--the
necessity of having faith to believe that we may overcome sin through the help
of Him on whom help is laid--and that He will make us able,
if there is faith in Him.
In the afternoon, went to Windham, where next day, the 26th of 9th month,
we had an appointed meeting;
in which I had to speak of the shortness and uncertainty of time,
and to spread a caution against an earthly spirit.
This afternoon we went to Gorham, and had an evening meeting--a baptizing melting time,
in which the invitation of Gospel love was extended to some present;
and I believe there were none in this meeting,
but felt something of the gracious overshadowing which prevailed at this season.

27th. Went to Limington, William Cobb going with us--where we had an evening meeting,
which was small, on account of the rain.
28th. Went to Parsonsfield, and attended their week-day meeting,
which was small on account of no notice having reached them of our being there;
yet it was a pretty comfortable meeting.
29th. With Enoch Parsons for our guide, went to Sandwich,
and had a good meeting in the evening at Cyrus Varney`'s;
and next day another at the north meetinghouse, which was also satisfactory.

10th mo., 1st. We had a meeting at the south house, which was long silent,
but was open towards the close for some labor; I left this place in much heaviness,
not feeling that sweet peace which has generally been my lot, through infinite mercy,
after thus laboring in a meeting.
The cause I may not undertake to determine;
yet the desertion and poverty which I felt this afternoon and next morning,
till meeting time,
greatly humbled my mind and taught me the continued
necessity of placing my whole dependence on God.
Went this afternoon to Wolfsborough and lodged at Joseph Varney`'s.

2nd. Our meeting here was held in the Academy;
it was large and solid--there was great openness in the minds of the people,
and also I believe a fitness in some to hear the
reconciling power of the Gospel declared among them;
it was, as I thought, a heavenly baptizing time.
After meeting we went to New Durham, and put up at Joseph Canney`'s.

10th mo., 3rd. We had a meeting here with Friends and many others,
which we thought was a good time, and concluded in the savor and power of truth.
After meeting we went to Gilmanton, where next day (4th) we had a small lively meeting,
and then proceeded to Pittsfield.
5th. Had an evening meeting in the Congregational meetinghouse,
which James Hazard also attended, and which proved a solid time.
6th. Attended their Monthly Meeting at Pittsfield, which was very painful throughout,
in part occasioned by an unsanctified appearance in the ministry,
and partly from a sense of a careless lukewarm spirit prevalent with too many here.
It was my lot to be silent, except a few words towards the close, in regard to discipline.
It appeared to me that this Monthly Meeting was in a very low weak state.
We found that there were divisions among them,
and some of a self-seeking disposition were striving to be greatest;
and I thought I had rarely, if ever,
sat in a Monthly Meeting where there was so much want of truly baptized minds,
qualified to steady the Ark; yet I believe there are some here,
especially among the younger class, who are well disposed,
but the prospect is truly lamentable on account of the want
of fathers and mothers to manage rightly the flock of God,
and I could but leave them in a mournful state of mind.

10th mo.,
7th. Went to Concord and had a small meeting with the few Friends and some others there;
and however discouraging the prospect was,
a renewing of God`'s visitation was in a lively exhortation extended to them.
After meeting we visited a friend who was out of health, and went to Henniker;
where next day, the 8th, we had a meeting,
in which the good hand of the Lord was reached forth
to our help both in testimony and supplication.

First day, 9th. Attended the North meeting at Weare in the forenoon,
and although long silent,
I was at length favored to see and administer to several states present;
and in much feeling of Gospel love,
was enabled to apply the balm to the mourners in Zion,
both to my own and their great consolation.
In the afternoon was at the South meeting,
where strength was given to sound forth the testimony of Truth to a large assembly present;
in which, among other things, the preparation of the heart was enlarged upon;
and the right ground of devotion; as it has been in all ages witnessed, only,
in faith and true humility of heart.

This being the last meeting which we expected to attend,
we had to look over our field of labor, and crave of Him who had been our helper,
that He would bless the work of our hands to those where our lot had been cast,
and strengthen the mourners in Zion,
and the hands of those whom we were about to leave still laboring in the same vineyard.
This was to me a very interesting season,
and the overshadowing of Divine goodness was such,
that it seemed like a crown upon our labors; and I could say in my heart, it is enough,
thy approbation, O Lord, is all in all!

After this meeting I felt entirely released from the service,
having accomplished what I had in prospect; and now gladly returned home,
which I reached 10th mo., 13th, 1825, and was rejoiced to find my wife and family well;
for which, and my preservation as well as theirs, while absent,
I feel bound to acknowledge our obligation to Him whose
goodness and mercy have been thus far extended to us.

First day, 23rd. Having a clear opening in our meeting,
and speaking to some states therein;
a woman of the Baptist Society present was greatly tendered.
She went home with me afterwards, and we had much conversation on religious subjects,
with which she appeared well satisfied.
I found her to be a woman of sincere mind,
and of considerable experience in vital religion.

11th mo., 2nd. My beloved and only brother, Isaac Wilbur,
departed this life at his house in Hopkinton; his sickness was a malignant fever,
continuing about ten days.
He was a man of good abilities, not forward in his manners,
but interesting in conversation, useful in his neighborhood,
and obtaining general respect;
he occupied several stations in the Society to general satisfaction,
so that his removal was sensibly felt by his relations, friends, and neighbors.
Fevers have been very prevalent in this and the adjacent towns of late,
of which many have died, mostly young and middle aged;
by which the evidence of our mortality, and the uncertainty of time,
have been again and again confirmed to us.

1826+++.+++ On the 1st and 2nd of 2nd month I attended, at Providence,
our Select Quarterly Meeting, Meeting for Sufferings, and Quarterly Meeting at large,
which were held to general satisfaction.
We had the company of James Hazard and Jabez Green from Cornwall, New York,
Mary Battey and Alice Rathbun from Smithfield Quarter;
the former and two latter held forth lively and edifying testimonies in the public meeting.

Fifth day, 9th of 2nd month, my cousin S. P., died at his home in Charleston,
aged forty-three years, a man of more than ordinary natural capacity;
but his life such as seemed to afford an illustration
of this sentiment of the poet Young:

[verse]
____
With the talents of an angel, a man may be a fool.
____

He suffered himself to be so far captivated with a thirst for ardent spirits,
that he became a slave to the excessive use of them;
which so completely destroyed the vital functions,
that in a few years he fell a victim to the ravages of this mighty foe.--Yet,
to do his character justice,
it should be added that he escaped measurably the train
of immoralities which almost invariably attend such a practice;
and although he had been flattering himself with the belief
that all men would be finally saved without reserve,
yet he freely and fully recanted from it before he died.
I attended his funeral on the 11th. On the 12th,
I had an appointed meeting at Charlestown, to a degree of satisfaction;
after which I visited two sick persons;
S+++.+++ S.`'s wife and J. C. I found her in a sweet frame of mind; but him,
under great apprehension and alarm, on account of his past life,
the failings whereof he seemed now disposed to paint in their true colors,
and was very penitent,
but almost impatient in the fervor of his soul to find forgiveness
and acceptance with an offended God.
I advised him patiently to wait and quietly to hope for God`'s salvation,
and to give himself up entirely into his hands, and wait the Lord`'s own time,
wherein he would give relief.

3rd mo., 22nd. I attended the funeral of Joshua Champlin, which, as I thought,
was a time of favor.
The public labor was opened with our Saviour`'s words, "`This is the condemnation,
that light is come into the world, and men loved darkness rather than light,`" etc.;
the deceased having acknowledged in his sickness that he
had been followed all his life long by the Light,
reproving and condemning him for sin and transgression,
opened the way for illustrating its intent and effect upon the mind of man,
showing that the condemnation of the disobedient is predicated upon this very thing,
their having had the means of God`'s salvation, but rejected it.

26th. Thomas Perry quietly departed this life at his own house at Westerly,
much beloved by his relatives and friends;
being highly esteemed for integrity and uprightness in all his temporal concerns;
for his benevolence and philanthropy, and his cheerful and obliging disposition.
He was truly a peacemaker.
"`Blessed are the peacemakers, for they shall be called the children of God.`"
His mind was remarkably covered during some of his last days with pleasantness and sweetness,
and his disposition, as we trust, was tempered with the temper of heaven;
and I have a hope that he was introduced to the fountain of better enjoyment,
on the commencement of endless life.
His funeral was on the 28th, at the same place,
attended by a large concourse of his respectable neighbors and friends.

5th mo., 11th. I left home, with the concurrence of my friends,
in order to visit the meetings and families of Friends
within the limits of Rhode Island Monthly Meeting.
I have had this concern on my mind for some months, and way opening now to proceed,
I went to Newport and spread my prospect before the ministers and elders there;
and they uniting with the concern,
and Andrew Nichols having kindly given up to bear me company, feeling, as I believe,
some engagement to join me therein, we began on seventh day, the 13th,
to visit families in Middletown,--Jonathan Dennis and wife being also with us:
this day we visited ten families.

First day, 14th. Visited three families in the morning,
and attended their forenoon meeting at Newport, to a good degree of satisfaction,
and in the afternoon went to Portsmouth, and attended a meeting appointed for us there,
which was large, but dull in the forepart.
It appeared to me that the greater part present were
not attending to their own gifts in solid waiting;
but after long waiting on my part, and I trust travail by many others,
way opened to remind them of the loss which they had already sustained for want
of coming down in their own minds to the alone right object of devotion;
and a solemnity gradually prevailing,
way at length opened for pretty extensive labor;--the living were encouraged,
the lukewarm called upon, the youth invited,
and the prodigal was ardently labored with for his return to the Father`'s house;
the meeting ended in solemn supplication and thankfulness.

Second day, 15th. Having Benjamin Freeborn in company, we went to Tiverton,
and visited the few families there,
(or the most of them,) and found things pretty low
among them--discouragingly so--yet we were enabled,
through deep baptism, to sound a word of alarm to some,
and administer encouragement to others in younger life;
and testimony was borne to some of them of the power of religion,
and the necessity of bearing the cross of Christ.
Towards evening, sat with several families on the Island,
and was led (unusually for me) to some very close dealing with a few young
people who were disposed to take too much liberty.

On the three following days, we visited nearly thirty families in Portsmouth,
and through deep dwelling (which I find indispensable for such service),
way opened for pretty extensive labor in divers places;
and it did indeed appear to be a time of renewed visitation of divine goodness to many,
in which their condition, as well as the things which belonged to their peace, were,
through holy help, opened to them.
We also attended their Preparative Meeting, which, though laborious, proved satisfactory.
Now, feeling clear of other parts of the Island, we went, on sixth day morning, the 19th,
to Newport, and visited two families.
Seventh day, we visited eighteen families in town, and first day, the 21st,
we visited six families, and attended their morning and afternoon meetings;
and a joyful evening it was to me,
feeling abundantly the incomes of heavenly love and sweet peace,
in which my cup was made to overflow with gospel love towards those
whom I had visited and travailed with for the birth immortal;
and unspeakable thankfulness was felt to Him who thus deigned to be near and
fill the heart of one so unworthy with his goodness and lovingkindness.
I lodged this night, at David Buffum`'s; and next day,
after visiting two or three families, felt clear of Newport,
having been kindly assisted by Stephen Gould and
accompanied by Clark Rodman in this service in town.

Second day, 22nd. Went to Jamestown, and attended an appointed meeting there,
which was very dull and heavy in the forepart;
and it seemed that I had to sit where the people sat.
I thought the weight of oppression which covered my mind was almost insupportable,
and must have been entirely so, had there not been a Hand of help extended,
by which I was enabled at length to break through, a little,
the shades of darkness which for a considerable time appeared to cover the meeting:
and this truly suffering opportunity I hope was not entirely lost.
23rd. We visited the few families of Friends here,
and one family not members of our Society;
to some of these the invitation of Gospel love flowed freely.
Thus, having accomplished the visit in prospect, I felt a good degree of peace,
and next day returned home.

Seventh day, the 8th of 6th month, leaving home with my daughter Lydia,
to attend our Yearly Meeting, I was met at Kingston Hill by O. Foster,
with information of the death of Jabez Tucker,
and a request for me to attend his funeral next day.
Many Friends being gone to the Yearly Meeting, I gave up to the request of his widow.
She and her husband had left the Baptist denomination,
and had been attending Friends`' meetings for some time;
and she being very desirous of Friends`' company, it appeared best for me to attend.
Many people were gathered on the occasion, and it was an open, solemn time;
after which I set out for Newport, and arrived there on second day morning.
Our Yearly Meeting, this year, was a quiet, favored season;
and Friends were much united in doing the business.
Elizabeth Robson and Anna Braithwaite from England, and Elisha Bates from Ohio,
were in attendance with us.

1827, 1st mo., 31st. I attended, this day, the Select Quarterly Meeting at Providence,
in the afternoon the Meeting for Sufferings, and next day the Quarterly Meeting at large.
We had a favored season in the meeting for worship, and also in that for discipline.
The day following, I attended the School Committee, and returned homeward,
but found a concern on the way to attend Friends`' meeting at Coventry; accordingly,
notice was given, and we met with them at the usual hour on first day,
which was a solemn, favored time,
in which we had cause to believe that Truth gained the victory.
We returned peacefully home the same evening, my wife being with me.

2nd mo., 27th. With many other Friends,
I attended the funeral of Henry Knowles of South Kingston;
it was a pretty large gathering, in which I had to labor extensively,
and felt great peace and thankfulness to Israel`'s Helper.

3rd mo., 11th;--first of the week.
I had not felt the necessity of opening my mouth in our meeting at home,
(except once or twice in a few words,) for several months;
but this day was considerably enlarged, both in testimony and supplication,
and felt the reward of peace to follow,
in which I feel thankful for the tender mercies and kind dealings of the Good Hand,
in that He withholds not his direction, and has preserved me hitherto.
I feel breathing desires for preservation during the little
time which may be allotted me in this world,
so that I may be favored to bring no reproach upon his holy name and testimony;
but am sensible that my preservation will altogether depend upon deep dwelling
and humble watchfulness;--for those only who continue and hold out in these,
have the assurance of his protection and salvation.

25th. I had a pretty open time at meeting, today, some of other societies being present.

4th mo., 9th. Acors Rathbun, of North Stonington, died suddenly,
and was interred on the 11th. The meeting, held at our meetinghouse, on the occasion,
was, I thought, a pretty good opportunity--in which the passage of Holy Writ,
that "`Secret things belong to the Almighty, but things that are revealed,
to us and to our children,`" was revived and opened among us;
and allusion was also made to another position equally true,
that power and wisdom belong to God, but weakness and ignorance,
to us and the whole race of mankind, as men and creatures.
In this great contrast we were, in a degree, favored by the help afforded,
to exalt the Creator and humble the creature,
which appears to me to be one great object of the Christian religion--for without such
a disposition of mind I believe we shall never be approved in the Divine sight.

In the 7th mo., 1827,
I laid before our Monthly Meeting a concern which had rested with me for some time,
to visit Friends in the western part of the State of New York,
and obtained its certificate;
which concern was also laid before our Quarterly Meeting in the 8th mo.,
and was united with, and indorsed by said meeting.
The observations of Friends, on the perils and dangers attending such an undertaking,
amid the existing commotions in that part of the country,
brought my mind into some deep exercise,
in addition to the trials preparatory to my opening the prospect to our Monthly Meeting;
but I saw no better way than to attend simply to the prospect,
and humbly to trust in the protection of my Good Master who called thereto.

My brother-in-law Abel Collins, who had a like concern, accompanied me on this visit.

We left home on the 12th of 9th month, 1827,
expecting to visit Friends and others within the limits of Duanesburg, Scipio,
and Farmington Quarterly Meetings.
We were four days in travelling to New Lebanon;
tarried two nights with our brother-in-law H. Mory,
and attended Friends`' meeting at Chatham.

[.offset]
+++[+++The following is extracted from a letter which he wrote from New Lebanon to his wife:]

[.embedded-content-document.letter]
--

We arrived here on seventh day afternoon, and yesterday went,
in company with our brother and sister, (H. Mory and wife,) to Chatham,
and attended meeting there, returning in the afternoon.
My health has improved on travelling;
and although the journey and service before us looks great and arduous,
yet I have a little faith that we shall be enabled to persevere,
and accomplish that which is assigned us; but it is rather a low time with me,
in which I feel the need of best Help,
and am pretty fully sensible that without it we cannot be preserved either
temporally or spiritually--more especially do I feel this to be the case
while engaged in this arduous service in a distant land;
and I humbly crave divine preservation and protection for thee and me,
and our dear children; that we and they may so live in the Lord`'s fear,
and may so love him, that he will deign to be round about us, as a safe enclosure,
and guide us in a way well pleasing to himself.
If this is our experience, we have the promise that hard things shall be made easy,
and bitter things sweet;
so that our present temporary separation will be the more easily endured;
and I much desire that it may be made easy to thee and the dear children,
by the rich descendings of the dew of Hermon.

--

Third day, 19th. Went to Duanesburg, and stopped two nights at Isaac Gages,
the weather being very stormy.
21st. Attended their mid-week meeting,
(notice being given,) in which faith in Christ was spoken of, and somewhat enlarged upon,
as consisting in what has been done for us without
us as well as in what is doing within us;
in which labors, although I felt at first some opposition, I was favored to get above it,
and the meeting ended better than I expected,
and some who I thought were tinctured with infidelity,
appeared to be measurably wrought upon.
From this place we travelled to Burlington, where we arrived on the 23rd,
and had an appointed meeting with Friends and others;
and an open heavenly meeting it was, in which we were favored with mouth and wisdom,
tongue and utterance;
for which favor I was humbly thankful and I trust in a good
degree sensible that nothing belongs to the creature,
but that all good cometh from the Lord.
This afternoon we went to Brookfield, and next day, the 1st of the week,
we had a meeting there, which was heavy and painful;
but towards the close I was enabled to sound an alarm among them,
and obtained some relief.
In the afternoon we proceeded to Smyrna, in company with Thomas Kenyon and wife; where,
next day, we had a meeting with Friends, which was long silent;
but way at length opened for communication, and we had a favored time.

From Smyrna Village we went to De Ruyter, and on the 26th,
we travelled forty miles to a place called Salmon Creek,
and in the morning reached Scipio, and attended the Select Quarterly meeting;
in which it was my lot to act the part of a sentinel,
and sound the watchword that an enemy was round about the camp.
The next day we attended the Quarterly Meeting at large,
in which I was concerned to encourage the faithful
to stand their ground and hold fast to the faith.
In the meeting for business we were greatly disappointed and exercised in finding a
disorganizing and rending spirit spreading its baleful influence in this Quarterly Meeting;
and it fell to my lot to hold up the necessity of order and discipline in the church.

The day following (as their manner is) they held a meeting for worship,
in which I was greatly exercised concerning the state of things there,
apprehending much unsoundness in the Christian faith.
I was long shut up in silence,
but way was made at length to step forward in advocating the true Christian doctrine,
as it regards our faith in what has been done for us without us,
as well as what is doing for us within us; in which it was opened, that the latter,
so far from rendering useless the former (by which it has been obtained
for us) corroborates and illustrates its effect and usefulness.
After this meeting was over (the labors in which brought
great peace and consolation to my mind) we crossed the Cayuga
Lake (three miles wide) and went to our brother John Collins`'s,
at Hector, and lodged there.

10th mo., 1st. We set out for Farmington, and arriving there the next morning,
attended the Select Quarterly Meeting;
in which my mouth was opened in an incitement to Friends to mind their calling,
to deepen down, and feel for the foundation;
and a few words of encouragement were spoken to the faithful among them.
Next day we attended their Quarterly Meeting at large, where it was my lot to be silent;
but I had painfully to behold a spirit of unsoundness and innovation,
leading to much disorder and disturbance.
The day following they held a large public meeting,
in which I was deeply exercised on account of unsoundness of doctrine,
which is sorrowfully making its way among Friends in this land;
and it fell to my lot publicly to defend, as help was afforded,
the doctrines of Christianity, in which I felt peace.
We stayed one night with Caleb Macomber, and after Quarterly Meeting,
went to Joseph Eddy`'s, at Henrietta, and on the 5th attended a meeting there;
and next day went to Wheatland and had a satisfactory meeting there.

First day, 7th. We went to Rochester, and attended a meeting there, in which,
though laborious in the forepart, I was favored pretty fully to discharge my mind,
to my own relief; called to see Mead Atwater and wife,
and proceeded to Riga the same night.
8th. We rode twenty miles to Elba, and had a meeting there at three o`'clock,
in which strength was given to preach the Gospel, I trust,
in "`demonstration of the Spirit and of power;`" and next day we went to Shelby,
and attended a meeting there, which was truly a heavenly time,
in which we had to rejoice in Him from whom the favor was received.
After meeting, we went to Hartland, and on the 10th, after having a meeting there,
we rode to Royalstown, where we had a sweet precious meeting,
and afterwards an opportunity in a family,
where my mind was particularly drawn to an exercised young woman,
whom I apprehended to be under deep concern and tenderly reached
by the power of Truth--encouragement flowed freely to her.
From here we went to Lockport, where we had a meeting the next day,
and though I was considerably opened in testimony,
yet I left them not feeling quite as clear as usual.
After meeting, travelled nineteen miles,
and stayed at a public house in a village called Tonawanda; and the next day,
through Buffalo to Hamburg.
First day, the 14th, we attended their meeting here, which proved a favored time;
and in the afternoon, one at Boston, and next day going to Clear Creek,
we had a meeting there at the fourth hour.
16th. We had a meeting at Collins,
and Friends of Evans meeting (four miles distant) being also invited, attended;
though I was long silent, yet at length I was largely opened in doctrine,
relative to the ministry and Christian redemption;
and after fervent supplication the meeting ended well.
We then went back to Hamburg, and next day set our faces eastward,
travelling as far as Orangeville,
where we had an evening meeting with Friends and others, open and satisfactory;
in which Christ`'s outward coming and inward manifestation were fully spoken of,
and near access to the throne of Grace was experienced.

The day following we travelled through the villages of Warsaw, Leroy, and Scottsville,
forty miles, and lodged with our valuable friend Robert Comfort.
20th. We went to Mendon, and lodged again at Caleb Macomber`'s. The day following,
in company with Caleb and his wife, we had meetings at Mendon and Palmyra.
These meetings were rather dull, especially the latter,
and the little labor bestowed did not afford much relief.
First day, 21st. We travelled about twenty miles and attended Friends`' meeting at Galen,
where there appeared to be much unsoundness,
or a want of faith in the outward coming of Christ, the Saviour of the world;
I was largely opened on this doctrine, and had great peace in my labors.
In the afternoon we had a meeting at Junius,
where it is to be feared that things were no better,
yet I felt no liberty here to open my mouth on points of doctrine,
but thought I felt free to drop some advice to the young people present;
though attended with much weakness.

It appears evident to me that very little can be
done for those who are unsound in the Christian faith,
unless there is some room yet left in their minds,
or way is made by the power of Truth to enforce the
doctrine most surely believed by us as a people;
namely, the necessity of the coming of our Lord and Saviour Jesus Christ,
and of his offering up his precious life that we might be reconciled to God;
for if this faith is wanting in these days of favor,
it appears to me that all is wanting, whatever they may possess besides, there being,
then, no foundation to build Christianity upon.

Second day, the 22nd. We went to Hector, and lodged at brother John Collins`'s,
where we rested one day, and wrote to our families,
and the day following attended their midweek meeting, which was a precious season.
In the afternoon, we had a meeting by appointment at a school-house,
mostly of other people; where, notwithstanding some were at first light and airy,
yet way was made for considerable labor, which I hope will not be altogether lost.
We stayed here at my brother-in-law, John Collins`'s, till next afternoon,
and then set out for Scipio, but were detained all night at the ferry.
Next morning, getting over, we had a meeting with Friends and some others,
at Spring Mill, in which strength was given to preach Christ the Redeemer;
and if I am not mistaken, his kingdom was exalted over some who had denied his name,
and my heart was filled with joy.

28th. We were at Scipio, and attended North-street meeting in the morning,
and South-street in the afternoon.
The former was rather trying and painful,--not much labor--some opposition felt.
The latter was open,
and notwithstanding I had reason to believe that some present were opposed to the doctrine,
yet strength being mercifully given to get above all opposition, Truth had the victory,
and my mind was filled with sweet peace.

First day, 29th. We had a meeting at Salmon Creek,
in which the doctrine of Christ was preached, and made victorious over infidelity.
From this place we travelled to De Ruyter, and had an appointed meeting on third day,
where also mere human reason, which is ready to triumph over the meekness of a Saviour,
was confounded, like the Babel builders of old,
and intercessions were offered for their guidance in the path of wisdom.
From here we travelled in two days to Butternuts, and on sixth day,
had a comfortable meeting there, and another in the evening at Lawrence, in which,
though I sat long silent, I have to acknowledge the helping hand of the Lord.
Next day, we proceeded towards Duanesburg, and lodged in Sharon,
where next morning we attended a meeting appointed
among the Methodists by our friend Joseph Bowne,
in which it was my lot to be silent.

11th mo., 6th. We attended the Select Quarterly Meeting at Duanesburg,
in which I endeavored to encourage its members to a faithful support of the discipline.
At the Quarterly Meeting next day, I was silent,
but we had two or three short lively testimonies in the public meeting,
and one very unsavory and burdensome.
Next day, at the public meeting,
I was concerned to labor in word and doctrine for the testimony of Jesus Christ;
but the meeting was interrupted by a young woman, in the same manner as yesterday;
she now attempted to counteract my doctrine,
and one other woman (not a member of this Quarterly Meeting) made a similar
attempt in a few words;--but I trust neither of them to much effect,
and I felt easy not to subjoin.
This was the last meeting we attended while on this visit;
after which we returned directly home,
believing that the service assigned us was now accomplished.
We arrived at home the 14th of 11th month; finding my family in usual health,
for which I was truly thankful, and have to acknowledge, with deep gratitude,
the kindness of Providence in preserving us, and in restoring us safely to our friends.

[.offset]
+++[+++This record, commenced in 1824, here concludes,
and does not appear to have been afterwards resumed;
probably owing to a prospect of further and more weighty service,
requiring long absence from home; across the Atlantic, which had long rested on his mind,
now approaching maturity, which occasioned increased exercise,
and engagement both of mind and body; and after his return from Great Britain,
his mind was much occupied, and his labors constant and assiduous,
in guarding the Society against the unsoundness in doctrine,
which had for some time been apparent to his mind, as being introduced among us,
though in a disguised and insidious manner.
These engagements, and the manner in which they were opposed,
brought upon him a weight of exercise and labor in defence of the cause of truth,
and necessarily in his own defence,
which left comparatively little time for other occupations.]
