[short="Chapter V"]
== Chapter V. Account of his Sufferings, From the Year 1840 to 1844, for his Testimony Against Unsound Doctrines.

[.offset]
+++[+++The following narrative of events,
forming a most important portion of the travails and exercises,
and deep sufferings of John Wilbur for the cause and testimony of Truth,
is abstracted from his published Narrative and Exposition,
and is introduced here in the absence of any regular diary of these events,
in the belief that his biography would be imperfect if omitting
to elucidate this eventful period of his life.]

Among those seeking and awakened souls,
who became dissatisfied with the lifeless formalities which yet remained
in the professing Christian church after the reformation from Popery,
was George Fox.
He, through deep meditation, waiting upon and dwelling with God in spirit,
was made a chosen instrument in unfolding the religion of Jesus Christ,
more perfectly agreeable to the New Testament;
and was endued with a remarkable gift of discernment of the condition of men:
and in the mystery of true godliness, that it stood not in form but in power.
And with great meekness and Christian courage,
he was enabled to combat the sins of the age in which he lived,
and more clearly to instruct and to direct those seeking souls to the
teaching of Christ in the inner man by his light and good Spirit;
and to bring them off from trusting in man, and from those, who like the Papists,
were still making a trade of the gospel,
a thing unknown in the primitive days of the Church.

To this faith and ministry, and to the covenant of the pure gospel of peace,
many were gathered.
These separated themselves from the spirit and friendship of the world,
(so prevalent among the protestors of that day) for the purpose
of restoring primitive Christianity in the lite and power of it,
to the purging of the consciences of men,
through the inward operations and purgations of the Holy Ghost, to the doing away of war,
retaliation, and oppression, as well as a hireling ministry;
all of which had been introduced into the church during its degenerate condition.
This doctrine, which inculcates the belief in Christ`'s teaching his people himself,
and the faith that every true believer has access to God through him,
as also the testimony against war and a hireling ministry,
spread alarm among the clergy of that day.

Hence, as the number of the Quakers increased,
the clergy began to have fearful apprehensions as to the safety of their callings,
or the continued enjoyment of their salaries; and consequently,
resorted to the exercise of their influence,
(which was then great in England,) for the purpose
of disaffecting the minds of the people against this,
to them, new doctrine, of free grace, and a free ministry;
and soon succeeded in raising a storm of persecution against these unresisting Christians.
And they, the priests, successfully invoked the civil powers to their assistance;
so that the spoiling of goods, imprisonment,
and even death itself was often inflicted upon this unoffending people;
when nothing could be laid to their charge, but obedience to the law of their God,
in honestly promulgating the doctrines of Christ
and his apostles as exemplified in the New Testament,
and thereby carrying out the reformation which the first reformers had begun.
Here then were seen, Protestants inflicting persecution upon their fellow Protestants,
(similar to that which those of the Roman Church inflicted upon one another,) and only
for the reason that the latter were consummating the good work that the former,
or their predecessors, had begun.

But God`'s permission of the deep sufferings of the many
messengers whom he had sent to bear witness for him,
is no evidence against the validity of their mission or calling.
Their sufferings were as seed sown,
and the fruit to be gathered in God`'s providence in after generations,
by those who are accounted worthy also to suffer for the name of Him who died for them;
whilst those who have lifted up their cruel hands against the Lord`'s humble messengers,
are equally reprehensible, whether those messengers were prophets or apostles,
or early Christians, or modern reformers,
however unsuccessful any of them may appear to have been,
in obviously reforming the church from a lapsed condition,
or of having effected a reformation.

One thing is very observable, that the peaceable, unresisting,
and patient endurance of persecution, by our early Friends,
as dictated by the precepts and spirit of Christ,
has been apparently instrumental in terminating to a great extent,
persecution among Protestants;
an influence which we have reason to believe has also reached the Roman Catholics.

Persecution is a thing so heinous, and so irreconcilable with the law of Christ,
that we may well say it was never inflicted by one true Christian upon another,
or upon any other person.
Discipline,
the church of Christ has always had--not for wounding but for curing--not
for the annoyance or restraining of him who reprobates the evil,
but for reproof to him who doeth evil.

But the liability of men and Christians to a declension
and departure from the immediate government of Truth,
as individuals and as a body,
induced George Fox and his fellow-helpers to institute and establish a written discipline,
both for the church and for the members, as a guide to the ordering of church government,
and for the deciding of all questions that might after arise in the Society.
They were aware that the same liability existed in the primitive church,
and that a sad departure from the meekness and true Christian spirit of right government,
did by degrees actually take place with their successors,
and saw the great benefit that a just and wholesome system of discipline
set up and established during the purer condition of the church,
under the authority of Truth, would have been to those who followed after,
if adhered to by all.

Under these considerations, it undoubtedly was,
that the discerning minds of our first Friends saw
the importance of a written system of Christian discipline,
set up and established under the dictates of Truth,
and by the consent and authority of the whole church collectively,
for the future government of the Yearly Meeting, and its subordinate branches,
and for the reproof and reclaiming of disorderly walkers,
as well as for the praise of them that do well.

Coincident with a written discipline,
a written confession of faith was also adopted in the Society,
as exemplified in the writings of the first Friends, and agreed to by the whole Society.
And these doctrines were fully recognized by the discipline,
and summarily incorporated in it.
Whosoever, therefore, deviated either in faith or practice,
became subjects of dealing by the true intent of that discipline,
be their outward standing or condition in the church what it might.
Hopeful, and in a good degree successful had the administration of this discipline been,
when in the hands of faithful men and women,
acting under the authority and benign influence of the spirit by which it was dictated,
in guarding against innovation, and honestly laboring for the safety of the Society.

But notwithstanding the many advantages with which the Society is favored,
if unhappily the "`leaders of the people`" should become apostate in principle and practice,
as did the successors of the primitive church,
that excellent system of doctrine and discipline handed down by George Fox and his contemporaries,
would not govern their proceedings;
but would be disregarded or shaped into a mere automaton,
and turned in an unhallowed manner to almost any direction,
or made to serve almost any purpose that such men might choose,
and finally be changed into an instrument of persecution!

Notwithstanding the great and helping hand of such a system of discipline,
is not the deepest concernment to the church under our name,
involved in the rectitude of the rulers,
and in the inquiry whether this people are more secure and
less liable to an apostasy than was the primitive church?
Is it not obvious that when the heads of the tribes begin to cry peace, peace,
and to preach up the safety and infallibility of the church and of themselves,
that the greater danger awaits it, as in the middle ages?
Yes;
and then it is that the watchful and faithful sentinel sees
the greater cause of alarm and the most imminent danger.

And how many deeply exercised and afflicted laborers could be named,
from the days of George Fox down to the present time,
who have watched over this people as they have watched over their own souls!
And how often have they trembled with fear for the church`'s safety,
when they were made to see, in the visions of light, that an enemy had entered the camp!
And how faithful to give the watchword of alarm,
and to cry aloud for the awakening of the armor bearers, lest,
while men slept in security, the city should be broken up!

The following narrative has been taken from records
made at the time when the events took place.
In the early part of John Wilbur`'s visit to England, in the year 1832,
his mind was brought into deep exercise by the unexpected discovery of a spirit
at work in the minds of some of the influential members of our Society,
which appeared to him to be at variance with the established
and well-known doctrines and testimonies of Friends.
As he advanced in his religious engagements,
more and more of this spirit was brought to view,
in a manner which led him to suspect that the Society was, at least in some danger,
either of a retrograde lapse, as a body,
into a similar state of things from whence it came out,
or otherwise of a rent or division,
if its members generally could not be awakened to the perils which awaited them,
or induced more decidedly to rally to the standard which George Fox and
his fellow-helpers set up against the spirit and friendship of the world,
as well as against the ceremonials and false doctrines which
then remained among the Protestant professors of Christianity.

Finding this departure so formidable,
on account of the talent and station of many of those concerned in it,
his mind was brought into great distress, and mourning over the flock of God,
once so loyal to the precepts of Christ, the Mediator of the New Covenant.
But now alas! in this very land where this standard was first set up,
(after the apostasy,) a departure from first principles
was seen among some of the leading members;
the consideration of which was very afflicting at times during his sojourn in that land.

He saw the great subtlety of the enemy, (in taking advantage of the Hicksite heresy,
which led off on the one side from the true doctrine,) working on the minds of
those who were the most prepared to forsake the original ground of vitality;
so that whilst they were guarding against a fatal lapse on the one hand,
he might the more easily and unsuspectedly plunge them into another as
destructive on the other hand,--both insidious and defective in relation
to the true faith in the offices and attributes of the Saviour of men.

Under these circumstances and apprehensions,
the author wrote a series of letters whilst in that country,
to his friend George Crosfield, which were by him published,
for the purpose of apprising, at least, some of his friends, of his exercises,
and concern,
and with a desire that both of these extremes and departures might be avoided.

These letters drew upon their author, as well as their publisher,
the great displeasure of those in England,
who were disposed to confound Hicksism with primitive Quakerism.
They came out on the eve of the publication of their avowed sentiments to that effect;
which they soon after published in a work called the _Beacon,_
and which also contained many other sentiments,
which stand directly at variance with the fundamental doctrines of Friends.
Many of the abettors of these opinions soon after separated themselves from the Society,
and set up meetings of their own; and much better would it have been for the Society,
if all at that time, who held opinions discordant with its ancient doctrines,
had withdrawn from Friends,
and openly avowed their real sentiments on the Christian religion;
if indeed they were beyond the reach of being reclaimed.

Subsequently, when the author returned to America,
a number were not wanting in New England,
who instead of strengthening his hands in that important
concern as they ought to have done,
hesitated not to condemn his letters and the publication of them,
and thereby much too nearly committed themselves to the
views which those letters were intended to counteract,
affirming,
"`that the state of things in England was not such
as called for the writing of those letters.`"
They professed to know more of the state of things in that country,
than one who had mingled largely with the Society there,
and had held conversation with most or all of their principal members.

But the coming out of the _Beacon_ soon after,
and the author of it being strongly supported, as he was,
by divers leading and influential characters,
put the question out of all dispute with sound Friends,
that those letters were needful on the occasion and published at
the right time,--that it was highly important that something of
the kind should have been laid before the Society at that time.
When that pernicious book called the _Beacon,_ so subversive of Quakerism,
as well as of vital Christianity, reached this country, the writer of this,
under the same concern,
used his best endeavors to prevail on the Meeting for Sufferings
for New England to testify against its sentiments,
but his labors in this respect were unsuccessful.

The doctrines of J. J. Gurney contained in his [.book-title]#Brief Remarks
on Impartiality in the Interpretation of Scripture,#
are of the same cast with those of the _Beacon,_ by Isaac Crewdson,
and so nearly agreeing in substance,
that a wise man could scarcely distinguish the purport of the one from the other.
Each of these writers has published doctrines essentially
at variance with those of the religious Society of Friends,
which being carried out and adopted, must unavoidably undermine Quakerism;
and it is self-evident, that whosoever openly defends or advocates either of these men,
commits himself to and identifies himself with the doctrines
of the man whom he thus defends against the Society,
and the more especially so,
if that defence be made upon the occasion of others opposing such doctrines.
This course has been unhappily pursued, and to a fearful extent,
by prominent members of New England Yearly Meeting,
to whom allusion will be hereafter made.

It is apprehended that a loss, in a greater or less degree, of the virtue, life,
and power of pure Christianity,
had prepared the minds of too many in the Society of Friends,
to imbibe sentiments at variance with true self-denial,
and full conformity to the cross of our Lord Jesus Christ, and, consequently,
with his doctrines, as held and laid down by the early writers in our Society.
That a great tendency outward, and to outward views and outward things, has, of late,
been apparent in this once greatly favored Society, is very obvious.
Consequently the sentiments of some writers,
who have not known the living savor of the Divine life to predominate in their own hearts,
(or otherwise have lost its unction,) have sorrowfully
spread and taken root in many minds.

Moreover,
the great schism and fearful departure from the Christian covenant on the one hand,
in the Society farther west, has furnished the enemy with vast and powerful machinery,
to delude, deceive, and draw off, from the same covenant on the other hand;
insomuch that many of those who were not caught in the snare of that apostasy,
called Hicksism, have been of late in great jeopardy,
by the influence and insidious sentiments of persons of genius, high standing,
and great learning in the schools of men,
tending to draw away from the same gospel covenant in an opposite direction.

These having lost, or never found that hidden treasure of this covenant,
as revealed by the Divine power in the inner man of the heart,
have taken offence at the law and restraints of a meek and lowly Saviour,
and so far imbibed the spirit of this world and of the age,
as to despise the foolishness of the cross,
which is the power of God and the wisdom of God, and not of man, nor of the flesh,
but of God.

Instead of submitting, therefore, to die with Christ,
and to abide the painful struggle of yielding up the will and wisdom of the flesh,
these have moulded and fashioned to themselves a substitute,
by professedly extolling and claiming the faith of Christ`'s incarnate sufferings
and propitiatory sacrifice upon the cross without the gates of Jerusalem,
as the whole covenant of salvation, and by him thus accomplished without them; and,
consequently,
it is feared are carnally believing and trusting in this alone for justification,
without its essential concomitant, the true obedience of faith,
and the work of sanctification wrought in the heart.

These views, and many others of the like tendency,
having been avowed and published by Joseph John Gurney, (who,
unlike Isaac Crewdson and his followers, continued his connection with the Society,
and maintained great influence therein,) were spread far and wide,
and have been the cause of great uneasiness and much
dissatisfaction in the minds of faithful Friends;
and the more,
because many are found among us who are disposed
to advocate and defend the author of them,
without, and in the refusal of an examination of his published sentiments,
or a comparison of them with our acknowledged and well-known doctrines.

Some concerned Friends, who have remained at their posts,
have watched over the "`landmarks`" of Israel`'s inheritance,
as they have watched over their own souls,
and can but tremble for the safety of the Ark of his testimonies, when, with their eyes,
they behold the demolishing of those stakes,
of which the good Shepherd of the fold ordained that "`not one of them should be removed.`"

And, notwithstanding what they have fearfully beheld,
of that which they apprehended was an attempt to obliterate and cancel
those distinguishing signals of our profession and its defence,
they have marvelled to hear so many of the watchmen cry peace!
peace! when the citadel itself is beset by a troop of strong men.
They believe that so great a loss cannot otherwise be sustained,
either by us or by the world at large,
as would be sustained by the breaking down of our distinguishing doctrines and testimonies.
Consequently, they see the great necessity of keeping a single eye to their safety,
and a scrupulous watchfulness against "`every appearance of evil,`"
that may in the least forebode an apostasy of principle,
inasmuch as such did happen, to a sorrowful extent,
to the primitive church--the best of bodies--and that too by small beginnings.

Furthermore,
these concerned Friends have felt not a little responsibility resting upon themselves,
and upon the church at large,
by reason of the committal to its charge and keeping of the most exalted, efficient,
and dignified principles vouchsafed to the hand of man in these modern times,
or in any age of the world,
because they are the same as committed to the primitive church,
in that all relates to Christian redemption and salvation.
And they have also felt something of the weight of
that appeal which was made of God to his servant,
the Prophet Ezekiel, chap.
iii. 28; also xxxiii.
8, 9. "`If thou do not warn my people from their ways, they shall die in their iniquity,
but their blood will I require at thy hands,`" etc.

Moreover, the late attempts at innovation, by those above alluded to,
speak loudly as a warning to us of the jeopardy which awaits us as a people;
for our unfaithfulness and disloyalty to the blessed Truth is such,
that Satan appears to have availed himself of the advantage of our relaxation,
and seems resolved to divide and scatter us from the true faith;
still we hear the cry of peace! still we hear the language of safety reiterated
among us! still we see a prevalent disposition to trust in man,
and to make flesh our arm!

J+++.+++ J. Gurney, on his visit to America, came to New England, in the 6th month, 1838,
and found the ground already prepared in many minds to receive and defend him,
notwithstanding the defection of his doctrines.

The persons whose minds had been thus prepared,
had evidently been for some years seeking control over New England Yearly Meeting,
and its concerns, in which they had been successful; and being men of influence,
and disposed to avail themselves of all means within their reach,
(which were not in any wise very limited,) whereby
to clothe themselves with rule and with power,
have drawn many to them, or after them, by their proffered friendship,
by promotion in appointments, by the honor of man, and by temporal favors,
bestowed in many ways.
By these means they have encompassed (however unsuspected their
object by many) a great proportion of those who were active members,
as well as others, and have promoted and made active, many who were not so before.

And those who have not fallen into these new views,
have not been desirous of office or control in the church,
and consequently have not put themselves or one another forward much for appointments;
and, more especially of late,
perceiving a disposition in those of the new ground to exclude them,
have mostly refrained from action.
And latterly in the Yearly Meeting,
these were entirely excluded from taking a part in its concerns,
by the supporters of unsound men and their doctrines deciding to reject from any service
the names of all such as had expressed themselves opposed to their previous proceedings,
thus declaring such out of unity;
a measure which had already been adopted and acted upon by Rhode Island Quarterly Meeting.

Those who had thus assumed the control in the Yearly Meeting, formed,
from their own number, standing committees therein,
as also committees of Rhode Island Quarterly Meeting,
and clothed themselves with authority to visit and control subordinate meetings,
and consequently to control the religious rights of all their members;
and these committees have not been backward in exercising this authority.
And further, the Yearly Meeting, through their influence,
of late made its committee`'s advice and decisions conclusive and final;
so that appeals from their advice, either by individuals or subordinate meetings,
to the Yearly Meeting, have been unavailing,
however contrary to discipline their advice or decisions may have been.

In the 11th month of 1839, John Wilbur felt himself bound under a religious concern,
to visit most of the Quarterly Meetings in the Yearly Meeting;
and was cordially liberated by his own Monthly Meeting for that service.
After having visited one Quarter and some of its subordinate meetings,
he was cited by one of these committees, to appear before a deputation from their body.
But their letter not arriving seasonably for him
to meet them at the time and place assigned,
he called on the writer of that letter as he passed on in pursuance of his journey.
His having made a stand against the new doctrines by writing to some ministers and elders,
as well as by conversation,
was alleged by the writer of the letter as a disqualification
for travelling in the ministry;
but J. W. was enabled to convince him that he ought to be
left at liberty to pursue his journey--and he did so.

When J. J. Gurney first arrived in New England,
there was a report in circulation that he had made satisfaction
to his friends at home on account of his exceptionable writings;
but J. W. being aware, through direct communications from England,
that the report was unfounded,
(a matter of great importance for the Society to know,) took an opportunity with him,^
footnote:[The first interview of J.W. with J.G. on account of uneasiness with his sentiments,
was in London during their Yearly Meeting in 1832, in presence of Jonathan Hutchinson,
and George and Ann Jones, in which no satisfaction was obtained.
This latter interview was at Newport in the 6th mo.
1838, in presence of Henry Hinsdale of New York.]
and informed him of the apprehensions of many Friends in regard to his sentiments,
as set forth in his books, and so extensively abroad in the Society;
and suggested to him the desirableness of his satisfying Friends in relation to such
of his doctrines as were not in conformity with our acknowledged principles,
and thereby open his own way among us.
But instead of giving any encouragement of doing so,
he entered into a prompt defence and justification of all his writings,
without exception.

In consequence, therefore, of the result of J. W.`'s visit to the author,
he believed it to be his religious duty to caution Friends, on suitable occasions,
against receiving or imbibing the unsound doctrines alluded to;
and at the same time making direct reference to some
of the most exceptionable among them.
On John Wilbur`'s return from his eastern visit,
he produced certificates from all the Quarterly and Monthly Meetings which he attended,
expressive of their satisfaction with his services among them.
And soon after his return from this journey,
he obtained the concurrence of his Monthly Meeting
and attended the Yearly Meeting in Philadelphia.

But his travelling as a minister, on account of his objection to those doctrines,
was displeasing to those who were supporting and defending the author of them.
It being apparently too much of a circumstance frequently to call
together the committee of the Yearly Meeting of Ministers and Elders;
and further,
as the committee of the Yearly Meeting at large was
not authorized to recognize ministerial service,
a way was devised to get a committee appointed in the Select Quarterly Meeting;
and if practicable, to be vested with authority to take hold of him,
and to stop his speaking against the doctrines of J. J. Gurney,
or travelling as a minister.

To effect this, deficient accounts were brought up in relation to unity,
from two subordinate meetings, where themselves predominated,
and under the pretension of bestowing labor in the cases referred to in those accounts,
a committee was appointed, ostensibly for the restoration of unity and harmony.^
footnote:[The accounts which went up at this time from South Kingston Monthly Meeting,
to which J.W. belonged, were unexceptionable as to unity.]
Howbeit, if their own confession is sufficient evidence, we are warranted in saying,
that they never attempted any labor of the kind, whatever,
within the limits of those two meetings from which the defective accounts came up.

John Wilbur was called upon to meet this committee the next morning after its appointment;
and they artfully attempted to make him a subject of dealing,
and to decoy him to place himself within the purview of their appointment,
by asking him the question,
"`whether he believed any of the members of our Select Meeting were unsound?`"
expecting, as was supposed, an affirmative answer; and if so, then here,
as they might think, would be a case of disunity fairly within their reach.

But their object was seen, and the question not answered, although all the committee,
save one, joined in pressing him to answer it.
Being defeated in this, they severely reprimanded him for having been to Philadelphia,
accusing him of having known that they were unwilling he should travel in the ministry.
But this charge, of knowing it, he was able to meet,
by adducing what some of them had said to him and others, during his eastern journey.
One of the committee had said, in a letter to his daughter,
that "`they had no desire to stop his travelling in the ministry,`" and another,
who met with him on the journey, said "`he was glad to meet with him there.`"

But they brought many other complaints and accusations against him,
of which the principal was, that "`he had written and spoken against J. J. Gurney,
and had spread long lists of extracts from his doctrines.`"

He now informed them that he had not spoken to the disadvantage of J. J. G.,
otherwise than by a recital and disavowal of some parts of his doctrines;
and in order to show them that those parts of his
writings to which he had made exceptions were unsound,
and consequently that the course which he had taken was correct and agreeable to discipline,
he proposed reading to them the extracts which they had charged him with spreading.

But they were unwilling to hear him read these extracts,
and conceded there might possibly be some things in the manner
of J. J. Gurney`'s expressions that would be deemed exceptionable.
But J. W. insisted on reading these extracts,
in order that the committee might know how unsound his doctrines were,
(believing that his defence rested upon their demerits,) but the committee
appeared exceedingly unwilling to allow the reading of them,
and the dilemma in which they were now placed, apparently drew from David Buffum,
one of their number, the expression,
"`I acknowledge that some of J. J. Gurney`'s writings are very unsound.`"
But for this imprudence, he was immediately jogged by John Meader,
one of his colleagues who sat near him, and who dissented from his concession, by saying,
"`I should not have said so.`"

Finally,
they utterly refused to hear his defence or the reading
of the extracts from Gurney`'s doctrines,
and gave him very little opportunity of any oral vindication
of himself in relation to the charges brought against him,
by reason of their own claims upon the time;
freely and in close succession bestowing upon him their censures,
and demanding from him immediate concessions,
accompanied with the advice "`to stay at home and be quiet.`"
And so this interview ended.

Thus being denied a full and fair personal hearing,
which truth and justice always allows, even to the greatest offenders,
John Wilbur addressed the following letter to Thomas Anthony,
the first-named of the committee,
with whom he had previously stood in the relation of great intimacy.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Hopkinton, 30th of 5th mo., 1840.

[.salutation]
To My Dear Friend, Thomas Anthony,

After thus allowing time for solid deliberation on
the subject of discussion with Friends at thy daughter`'s,
it seems right for me to address a few lines to thee in relation thereto,
inasmuch as I had not full opportunity in the end to speak for myself,
by reason of the claims of others on the time, as well as the want of time; thou wilt,
I apprehend, allow me the opportunity of reviewing it in this way,
and to remark further upon the charges brought against me; and, as I trust,
will hear me patiently,
seeing that vastly more is involved in the consideration of the
question than merely the exculpation or condemnation of an individual,
without allowing him the right, both civil and religious, of a defence,
not only of himself, but of the testimonies and usages of the Society,
such as truth and justice call for.

Thou art well aware that even in the civil department,
the laws of the land allow the accused a defence of himself,
in all the bearings of his case, and, not only so, they premise, if need be,
that he should be provided with counsel,
lest unhappily the innocent should be adjudged guilty.
And in the religious department,
thou wilt agree that a still higher and purer order
of justice and righteousness is contemplated,
for beyond all controversy, such is the true character of Christianity,
and its superiority over every other system of moral
or civil order instituted by the children of men.

But when we become acquainted with the history of
ecclesiastical transactions since the Christian era,
we are bound to acknowledge that the civil has never been more abused than the religious,
under the dominion of power.

But to come directly to the question, and the capacity in which Friends acted,
I deem it right for me to remark,
that I might suppose they acted as individuals under
an apprehension of the necessity of the case,
and not as a committee of the Select Quarterly Meeting:
for the appointment of the committee was grounded, and only grounded,
(if I understand it,) upon deficiencies represented in the
answers to the queries from the subordinate meetings,
and, consequently, Friends could not, as a committee of that meeting,
extend care to any meeting, or to a member of it,
which gave no account of deficiencies in relation to things queried after;
and no tangible inference can be drawn from that of South Kingston,
(however it may be in others,) that there does any
want of harmony or unity exist in that meeting;
and which I esteem as a favor, for which we are bound to be thankful.
But I am entirely prepared to say,
that I ever hope to be willing to receive advice either from committees or individuals,
acting conformably to the mind of Truth, and the order established in our Society.

But are Friends now prepared to evacuate the ground which has been taken, viz:
that a certificate for a man to travel as a minister is a full defence to him,
against all comers in relation to whatever may have
transpired previous to the issuing of that certificate?
Or will they say that the deputed right of one body shall be regarded,
and that of another may be disregarded and contemned?
And does it rest with committees or others,
not delegated for that special purpose by the Yearly Meeting itself,
to arrest the established right and order which that
body has conferred upon its subordinate branches?
Or shall these things yet rest upon their ancient foundation and usage,
that when a minister, though liberated by an authorized body,
is found defective either in faith or conduct,
and for which satisfaction has not been made,
that he shall be liable to be called to an account,
by those whose constituted duty it is,
under whatsoever circumstances he may have placed himself, or others may have placed him?

By this rule, my dear friend, I am entirely willing to be tried and judged,
but not upon mere hearsay,
or vague allegations and reports--not for the alleged faults or imprudence of others;
nor yet without a hearing upon the great point and premises of the case, to wit:
the stand which I have taken against the erroneous doctrines
which are spread abroad among us by their author,
both before and since his liberation for our land.
And whatever I have said or done in the case, relates unequivocally to those doctrines;
and, consequently,
the merits or demerits of that course rests upon
the soundness or unsoundness of those doctrines,
as will be shown further on; and I hesitate not to say,
that the present dissension in the Society at large,
is the legitimate fruits of the circulation,
and the author`'s continued adherence to the doctrines alluded to.
And my concern has been,
(as I told Friends when together,) that those sentiments
might be clearly developed and faithfully reprobated,
so that the fearful consequences of such dissension might be obviated.

But if these baneful doctrines, or their unrelenting author, which is the same thing,
are continued to be advocated and defended,
we have reason to fear that serious difficulties will ensue;
because there is no doubt there are some, and perhaps not a few in this Yearly Meeting,
who cannot be brought to the adoption of such sentiments, come what may come.
And inasmuch, as great wrong has been inflicted upon the Truth, and its principles, who,
thinkest thou, my dear friend, will find the most peace of mind in the result of things?
Will it be those, who, out of a good conscience, have withstood those innovations,
(though perhaps not always in the most perfect line of Divine wisdom,) or those
who have defended such views by strenuously advocating and warmly defending,
and thereby giving strength to their author,
and by endeavoring to put down those who have honestly withstood his sentiments?

How any can defend an unsound man, at the expense and rejection of those who are sound,
and yet be acting upon sound principles,
is a problem which I very much desire to see demonstrated, if demonstrated it can be.

I will now remark upon the charges brought against me,
and however trivial some of them are, and unreasonable others appear to me, yet,
as they have been deemed by ministers and elders to be worth naming,
they will be recognized, by way of a defence and apology, for the course I have taken.

[.numbered-group]
====

[.numbered]
_1st._ That I have frequently, in conversation and in writing,
reprobated some of the sentiments of J. J. Gurney,
and even on some occasions when abroad in the ministry.
To this charge, so worded, I confess guilty, if guilt is attached thereto; and,
in remarking upon it, I will first ask thee, Thomas,
whether thou will admit that a professed minister abroad could
be chargeable with doctrines so dangerous as to warrant such procedure?

[.numbered]
_2nd._ Whether the doctrines of Hannah Barnard and Elias Hicks were so exceptionable
as to warrant a watchword to the churches under similar circumstances?

[.numbered]
_3rd._ Whether Moses and the prophets were warranted,
in so full and so public a manner as they often did,
in testifying against the abuses of the doctrines and commandments of the former covenant?

[.numbered]
_4th._ Whether the apostle Paul and George Fox did right in
publicly withstanding and marking those who caused divisions
by introducing doctrines contrary to the doctrines of Christ?

====

The apostle, it seems, in his public epistle, entreated his brethren,
without distinction of age or standing, and without exception to any circumstance,
to mark those which cause divisions and offences,
contrary to the doctrines which they have learned, and to avoid them. Rom. 16:17.
And so we shall find, if we examine the Holy Scriptures,
that both prophets and apostles were prompt and vigilant, in detecting and exposing,
as well as in exterminating everything which stood
at variance with the Lord`'s doctrines and testimonies,
whether seen in kings, princes, or prophets,
(however reprehensible such detection was deemed by those in power,)
a procedure led to by the inspiration and commands of God.
For it was seen then, as it in some degree is seen now,
that human nature is so propense to ease,
and to overlook the needful restraints of true religion,
that a guard against the inlet of evil was continually needful.

But one of our Friends said,
that he acknowledged the doctrines in question were very unsound,
but afterwards said he thought we ought to give a pass to their author.
But truly he could not have meant to have been understood to say,
that the Yearly Meeting ought to give him a certificate of unity, for, in so saying,
he would exhibit an opinion different from that of the apostle,
when he was speaking of those who brought in doctrines
contrary to the doctrines of Christ;
for, said he, "`He that biddeth him God speed, is a partaker of his deeds.`"

[.numbered-group]
====

[.numbered]
_2nd charge._
That I knew the Yearly Meeting`'s committee were
unwilling that I should travel in the ministry;
therefore, I ought not to have gone to Philadelphia.
To which I need to say no more than to refer to thy expression to a Friend; to Thos.
Howland`'s own handwriting,
and to J. Meader`'s language to me at Dover Quarterly Meeting, all amounting to this,
that the committee had no desire to stop my going on the proposed visit; besides which,
I had never heard from them--how, then, can the committee make this charge?

[.numbered]
_3rd charge._
That they understood that I had favored the idea of a division of the Yearly Meeting;
which was so fully answered at thy daughter`'s, viz: That no one among us,
to my knowledge, had labored more to keep Friends in New England to the one faith,
even to that alone which would keep us together, and prevent our being scattered;
+++[+++showing]
that a disagreement in principle is the root of schism.

[.numbered]
_4th charge._
That I have companied with some young men,
who have made a stand against the unsound sentiments of J. J. Gurney;
to which I confess judgment; and that I have also companied with some who are not young,
but have the same opinions of the same man.
But I would say, that I believe these with whom I have companied,
and who have taken the same ground,
would not suffer in point of character in a comparison with others.

[.numbered]
_5th charge._
That I suffered Thomas B. Gould to go with me, as companion, to Philadelphia.
That he went in company with me, as did divers other Friends, I acknowledge;
but that he went with me as a companion,
in the way that this phrase is understood by Friends, is altogether unfounded;
nor did he pass for such at any place where we were; nor George F. Read either,
though he lodged with me every night at Philadelphia, and is also a sound Friend;
nor am I ashamed to be in company with either of them;
although neither may be without his faults--nor yet myself--did
not think of its being any disgrace to be seen with them.

[.numbered]
_6th charge._
"`That I suffered letters and extracts from John Barclay
and Ann Jones to pass through my hands to others.`"
In answer to this, I would ask,
whether it would be more harm to quote English authority against very unsound doctrines,
or to quote English authority in defence of very unsound doctrines?
And I would ask again,
whether there has not been a great deal done throughout our settlements in America,
in spreading English and other letters in commendation of this very unsound man?
I say unsound man, for he yet adheres to his unsound doctrines.
Again, whether thy colleagues are so much dissatisfied,
and do find as much fault with letters which go to give
currency to the author of these very unsound doctrines,
as they do with letters which go to expose and detect them?

[.numbered]
_7th charge._
"`That I said to N. Monroe, that J. J. Gurney would not dare to come to New England.`"
Now we know the difficulty of proving a negative;--but I will say,
that I was at Monroe`'s, and probably said something in relation to the man;
but in how many and what kind of words, I cannot now recollect; however,
as I know that I never had the least expectation of our escaping a visit from him,
it looks so altogether unlikely that I used that form of words,
that I feel safe in demurring to the charge;
however little or nothing could be made of it, if I had so spoken,
more than that I was mistaken.

====

Now, if we take all these accusations into view, my dear Thomas,
which of the things complained of would not be affected, in point of right or wrong,
either by the soundness or unsoundness of the doctrines of J. J. Gurney?
When you say that I have spoken against his doctrines--that I have
written against his doctrines--that I have suffered to pass through
my hands letters which go to discourage the imbibing of his doctrines,
and to warn of the consequences of doing so--that I have
companied with others who protest against his doctrines,
you say truly; and yet wonderful it is to hear you further say,
that his unsoundness of doctrine has nothing to do
with my defence for doing so!!! And as wonderful,
that pertinent evidence, offered in defence of the rectitude of the course taken,
sufficient to exculpate from blame thy correspondent,
should be refused!!! I say sufficient, because the refusal of hearing that evidence,
probo factum, gives to me the right of this assumption.

But you seem inclined to resort to the abstract doctrine,
that a certificate from a corresponding body or Yearly Meeting ought to defend
him against all charges for wrongs done previous to the date of that document.
For a full refutation of which position, I refer to my letter to John Meader.

But inasmuch as some continue to advance an abstract propensities,
you will admit an abstract solution.
In the civil department, we are an independent nation,
yet are on good corresponding and commercial terms with Great Britain;
and let us suppose that one of their trading vessels had heretofore, by means,
of an inclination thereto, and a strong armory,
made many captures and had committed many wrongs
upon the rights and property of the American people.

However, in process of time, the same vessel, having escaped retribution,
obtains regular papers for a general trading voyage to our land.
Now, I would inquire whether it would be any breach of good faith towards Great Britain,
civilly to ask the commander of this vessel to make
reparation for the wrongs which he had done us?
Or whether it would be reprehensible in any of our citizens, to speak of the wrong;
which that vessel had committed upon us,
when those wrongs were clearly provable by the register of the vessel,
and had been fearlessly published by the commander throughout
all the trading companies in the country?

Or whether it be a breach of faith for our government
to refuse to give her returning papers,
and a protection upon the high seas,
until she would make reparation for the wrongs which she had done us?
And inasmuch as worldly property and civil rights bear no
proportion to religious principles and Christian rights,
the civil department could not possibly sustain an equal
loss by means of the strongest ship upon the high seas,
as would be incurred by our Society in the striking out of even but two or three
of the fundamental and distinguishing articles from our confession of faith,
as apparently aimed at by the person alluded to.
But let us stop a moment,
and inquire whether there have not been some depredations
committed during the present visit.

[.numbered-group]
====

[.numbered]
_First,_ he justifies his former wrongs,
which revives and restores them to the present tense,
and refuses to make the least concession of them.

[.numbered]
_Second,_ he has himself been spreading defective books since his arrival in America.
I saw one which he presented to a Friend, with a note desiring his acceptance of it,
dated Philadelphia, 8th month, 1837,
and signed with his own hand--a book recommending a form of prayer,
and public discoursing upon Christianity, distinct from the ministry.
This is said not to be a solitary instance.
And besides his spreading unsound books since his arrival,
many defective ideas of doctrine have escaped him in the Gallery; the which,
if collected with the like industry as has been obvious in some other instances,
the catalogue would be very considerable.

====

Now, my dear friend, pause for a moment, and see; one man can write, and preach,
and spread very unsound doctrines, and still receive the warm support,
or defence of both ministers and elders among us; whilst another,
who is afflicted because of the jeopardy which awaits our Society,
by means of the spreading of these unsound sentiments,
and ventures to bear witness against them, is consigned to reproach!
However, this case is not entirely new; there have been honest Friends heretofore,
and undoubtedly better than thy correspondent,
greatly reproached and defamed for withstanding unsound doctrines, and even disowned;
and to what extremity this may come, the Lord only knows.

But there is one thing which I desire, and another which I lament.
The former is,
that I may be reconciled to whatever sufferings may be permitted to fall to my lot,
in the discharge of duty, and myself made to profit by it.
The latter is, that I am not more worthy to suffer for the Truth,
and for its doctrines and testimonies.
But I might well say, that a releasement from Labor,
if the enjoyment of peace and quietness were bestowed, must be esteemed a great favor.

To be released from the labors and dangers of the field,
and yet be permitted to divide the spoil, is a privilege of God`'s own conferring.
That precious peace and quietness, which is the reward of honest labor in the field,
is nevertheless the fruit of his abundant grace; how much more, then,
that which fills the heart with peace and joy in its private
exercise and retirement in the house of prayer,
and under its own vine and fig-tree, must be of unutterable love.

And, however he who serveth at the altar receives his portion of the gift, yet,
if God be pleased to release from the service for a time,
as he often did our first Friends, and though it were by means of the secular power,
yet it undoubtedly contributed to their furtherance,
and greater depth in the power of the cross of Christ--his name be praised!
And my confidence in thee is such,
that it will not be perilling the pearl to acknowledge
to the unbounded grace of a good and merciful God,
through Christ Jesus, in vouchsafing to his weak and unworthy messenger,
in his late journeys, a greater fulness of strength and understanding,
in speaking of the things of his own kingdom, and power, and glory,
than he ever saw meet to bestow before; and my enjoyment,
subsequent to many of these seasons, was inexpressible.

And the praise and the glory was and is, as I trust, wholly rendered unto him;
for I clearly saw that it was entirely of him; and to him it was rendered,
in language both utterable and unutterable.
And it has been, and remains to be, to me an evidence, not to be despised,
that my good God has owned and does own my sincerity in bearing a faithful
testimony against "`every appearance of evil,`" and innovation,
upon our inestimable testimonies, both in the times of our former,^
footnote:[Hicksite troubles.]
and our present troubles and dangers.
And that it is his will that I should do so, does not rest +++[+++wholly]
upon his unmerited favors abroad (as evidence),
but peace and quietness have succeeded to the fulfillment
of apprehended duty in that respect at home.

Nor was I ever more clearly instructed, than in these late journeys,
in relation to the opening and shutting of the fresh springs of the gospel ministry.
In one large public Quarterly Meeting, and in several other large meetings,
the ministry was to me "`as a spring shut up,
a fountain sealed,`" for which I could assign no other reason
than that the good Master would have it so.
But in the same Quarterly Meeting for business, which was held the next day,
a very unusual flow of the gospel life and power (for me)
was witnessed in both the men`'s and women`'s meeting.

The two or three exceptionable doctrines of J. J. Gurney, alluded to above,
might be selected from the many, under the following heads:--

[.numbered-group]
====

[.numbered]
_1st._ That the gospel of Christ, is not in itself the power of God unto salvation.

[.numbered]
_2nd._ That men are justified by faith, without regard to obedience.

[.numbered]
_3rd._ That was the true light which lighteth every man that cometh into the world,
he construes to mean no more than Christ incarnate, "`the enlightener.`"
Let all imbibe these three items of doctrine, and Quakerism would be no more.

====

Having a little room yet left upon this sheet,
I will occupy it with a few extracts from a piece in my possession on church order,
as followeth:--

"`It would appear to be at variance with the very nature of things,
as well as the right order of church government, and the spirit of Christian discipline,
to suppose that a person can place himself,
or that others can place him under such circumstances,
as that he cannot be reprehended for a breach of faith in the promulgation
of sentiments perversive of the established and fundamental doctrines
of a religious society to which he belongs.

"`If a way has been found in which a person can be securely sheltered and protected,
under an obvious and public violation of the doctrines of his own society,
(without concessions,) then, indeed,
it would seem that innovation upon its principles may be considered inevitable,
and without a remedy.

"`If a religious body has no alternative,
but to unite with and to give currency to the religious
and official standing of such person,
then would it be in vain to hope for the preservation of the purest system of Christianity,
or the best confessions of faith.

"`But the Truth itself, it is presumed, has never placed a man in such a condition,
that his errors, whether doctrinal or practical,
could not be rightly recognized and reprobated, so long as they remain unretracted.

"`Hence, it cannot be supposed that anybody, acting in conformity to the Truth,
should be understood intentionally to approve,
or give currency to doctrines which are at variance with the Truth;
nor that any rightly qualified person can be reprehensible for
detecting wrongs which have been inflicted upon the Truth,
and its principles, and doctrines, as exemplified in the Holy Scriptures,
from the beginning to the end; nor do we find, in those sacred records,
that the names of those who had committed depredations upon the Truth are spared.

"`By the exercise and dictates of Truth`'s principles,
it was that good order and wholesome regulations were originally
instituted and established in the Society of Friends,
for the protection and security of its doctrines,
as well as for the support of its moral economy; hence it is not to be believed,
that a wise and discreet exercise of that order can
ever lead to the strengthening or upholding of error,
or the justification of wrongs committed against the author of that order, to wit,
the principle of Christianity.

"`Therefore, any proceedings under a profession of sustaining that order,
if their tendency is to strengthen the wrongs done to that
principle which brought all good order into existence;
then such proceedings, so far from being the right support of good order,
are but the abuse of order,
and can be accounted of no better than an attempt
to support order at the expense of principle,
the parent of order.`"

[.signed-section-closing]
I am thy friend,

[.signed-section-signature]
J+++.+++ W.

--

To this letter, both himself and his colleagues declined altogether to make any reply,
or to attempt a refutation in writing;
yet they did not fail to resort to personal declamation and high-sounding words,
in an interview which they called for,
in the early part of the Yearly Meeting at Newport, 1840,
with an evident design to alarm him, and to induce him to condemn,
not only the course which he had taken, but also the letter which he had written to them;
and because he hesitated, conscientiously doing so, they cast upon him many reproaches,
and the epithet of stubbornness,
and a disposition to resist his friends and the good order of society.
They also now denied the intimation in the letter, that one of the:
number had said that some of J. J. Gurney`'s doctrines were very unsound.
And D. Buffum himself denied ever saying any such thing.
And they further declared, that no one would know, by reading the letter,
anything about what transpired at their meeting at Greenwich.

During these interviews, in which the committee evinced much excitement,
J+++.+++ W. was favored to endure their reproaches and revilings without reviling again,
and to make no concession or compromise of principle.
The fourth meeting of the committee, with some additions to their number,
was held at Portsmouth, R. I., and J. W. was cited again to meet with them, which he did.

The committee now attempted reading extracts from his letter to them,
against which they were intending to join issue;
but he objected to their reading extracts from his
letter without first reading the whole letter,
and the more,
because a number of the committee now present had never become acquainted with its contents,
except by hearsay; and because: also, T. Anthony, one of their number,
had told him that he had placed upon it, with pen and ink, the inscription of falsehood.
J+++.+++ Wilbur`'s arguments for either reading the whole letter
or else for not reading the extracts from it,
though strongly opposed by some, finally prevailed.

After the letter was read,
some attempts were made (though feeble) to read extracts from it,
in order for refutation, but in this course they proceeded not far,
as J. W. now called for their objections in writing,
both to the course which he had taken in the first place, and to the letter itself,
distinctly and severally giving their reasons for such objections.

This seemed to throw the committee into considerable disorder,
after which their proceedings were irregular and desultory.
At one time they would declaim against his making a defence against his friends,
and at another time they would accuse him of having taken false premises in his letter;
and again, D. Buffum came forward in a denial of saying at Greenwich,
"`that some of J. J. Gurney`'s writings were very
unsound,`" and attempted to change the ground,
by now adopting this version of it, to wit, "`For argument sake,
I will admit that some of J. J. Gurney`'s writings are very unsound.`"
And John Meader, who jogged him at Greenwich, and remarked,
"`I should not have said so,`" now responded to the truth of his present version of it,
and said, I remember these were David`'s expressions.
Why, then, asked J. W., didst thou jog David at Greenwich, and say,
"`I should not have said so?`"
But before this query, to which John Meader made no reply,
several of the committee had indorsed his present statement of it.

Finally, as Andrew Nichols had said nothing to this disputed point,
they called on him to testify in regard to it; and though a diffident man,
he did say to David, the words which thou hast now prefixed,
were not prefixed at Greenwich, thy words then were,
"`I acknowledge that some of the doctrines of J. J. Gurney are very unsound.`"
And so ended this part of the discussion.

After having been together near four hours,
they began to talk of what course should be taken,
inasmuch as the object of their meeting had not been attained.
Two of the committee proposed to burn the papers and drop the subject altogether;
but others hesitated.
J+++.+++ Wilbur had complained of the injustice and severity
of their charges thrown out against him,
of the aspersion of falsehood indorsed upon his letter, saying, that he had never,
in speaking of them, or of J. J. Gurney, made use of such language.
In answer to which T. A. said,
"`I don`'t think that John Wilbur meant to say anything in that letter which was untrue.`"
J+++.+++ W., after repeating his request to be furnished with their complaint in writing,
withdrew, in order to remove all embarrassment from their deliberations.

From this time J. W. heard nothing of the intentions of the committee
until the holding of the Select Quarterly Meeting at Somerset,
in the 11th month following,
wherein his sufferings were by no means inconsiderable in consequence
of their bringing the case to view before that meeting;
but silence was believed to be his lot and ground of safety.
After meeting, he was called upon to meet them that afternoon at three o`'clock;
but not feeling ready in his own mind therefor, and having other good reasons,
he declined an interview on that day,
but informed them that he would wait on them the next day, or at any future time,
as they would best like.

Accordingly he was notified the next day, after Quarterly Meeting,
to meet them on the following morning at the Boarding School at Providence,
to which he agreed, and met them there accordingly on 6th day morning,
the 6th of 11th month, to wit, six men and two women.
And after a short pause Rowland Greene rose and said,
that passing over J. W.`'s speaking of a Friend travelling in the ministry to his disadvantage,
they would proceed to read such passages from his
letter as were not satisfactory to the committee,
and so proceeded to read them.
To which objections J. W. now felt at liberty to
make some remarks and to reply somewhat in course;
but withal again claiming the right of being put
in possession of their objections on paper.

With a view of sustaining their charge of falsehood against
his letter they had taken the ground at a former interview,
that their censure of him was not for objecting to Jos.
J+++.+++ Gurney`'s doctrines, but for speaking against J. J. Gurney himself.
But, nevertheless, their first and prominent charge against him at the first interview,
was that he had "`spread long lists of extracts from Jos.
J+++.+++ Gurney`'s doctrines.`"
It is true, that when at that interview, J. W. attempted to justify his having done so,
by showing the unsoundness of those doctrines, they feigned,
in order to avoid the exposure of them even among themselves, to let go the complaint,
which they had thus emphatically preferred against him, and,
attempting to discriminate between the man and his doctrines,
to make their charge against him for objections to the man only.
Which latter charge they never could, nor can they ever substantiate,
and consequently by this wily contrivance to shift their hold,
their whole fabric falls to the ground.

Now, at this meeting at Providence,
J+++.+++ W. inquired of them whether they were now disposed to relinquish
their first charge against him of "`spreading long lists of extracts
from that Friend`'s doctrines,`" to which several of them responded,
No, oh no.
And although J. W., at Newport, did not feel himself at liberty,
even to clear himself from many of their accusations, yet now such restraint was removed,
and his mind was free, and opened in clearness,
and strength was given to speak in defence of the good cause,
and to exculpate himself from blame in so far as he had
been endeavoring to guard it against innovation.

It was not long the committee pursued reading extracts,
because of their objections being so fully answered;
choosing rather to object to the letter in a more summary way,
they alleged that J. W. had, by that letter,
"`implied that the committee were unsound as to their religious sentiments.`"
To this he replied, "`that no body of people, or individuals,
had any occasion to fear that a charge of unsoundness could be made to lie against them,
if they had not accused or identified themselves therein by things which
they had said or done--that if this committee would come forward and now
disavow and condemn the unsound doctrines of J. J. Gurney,
as himself had done, there was no one who would attempt to implicate them therewith;
and he earnestly and affectionately entreated them to do
so for the clearing of themselves from all imputation.

This proposition and entreaty brought much solemnity over the company,
and silence prevailed until he found it right to speak further, and to tell them,
that they had found much fault with him in relation to expressions in the letter;
that he as well as they, had susceptible feelings, and if they would give him leave,
he would remind them of a few expressions and movements
of their own which had been afflictive to him,
and then paused for liberty to proceed.
After standing for some time, he subjoined, if Friends are unwilling to be thus reminded,
I will take my seat; but soon rose again,
and revived the saying that silence gives consent,
and then proceeded to tell them that because he conscientiously
hesitated to condemn his letter at Newport,
they "`charged him with stubbornness`" and also, divers times,
said "`that no one could tell by his letter anything about what transpired
at the first interview,`" +++[+++making the whole document a fabrication,]
and further, at Portsmouth, had "`pronounced the premises therein taken to be false,
and the conclusions therefore to be false and unsound,`"
and had inscribed this upon the letter,
and in the Select Quarterly Meeting but a day or two previous,
had opened the subject in a manner altogether uncalled for and unnecessary,
unless it was needful to reproach him in that open manner.
Silence again reigned, until he again proceeded;
the committee also required of him to hear them read to him an anonymous letter,
reflecting unfairly upon his proceedings;
which letter or paper was withheld from his possession.
An act which he thought the most extraordinary he
had ever known to be practised by those called Friends.
Not the least reply was made to this exposure of their injustice.

It was now very observable that the committee (for
the present) were somewhat softened and moderated;
they consented that J. W. should be furnished with
their objections to his letter on paper,
or with a copy of his letter with then objections designated in the margin.
They agreed that T. A who was not present, should, if he was willing,
furnish him with them in the one form or the other.
But still before we parted, they so far recovered their former feelings, that they,
of individuals of them, were disposed to annoy him with questions, if not to entrap him,
in an unprovoked manner; a process, in such a case, as dishonorable as it is unchristian.
But the result was, that the answer to every question they asked,
as well as to every accusation they made, tended to their own disappointment.

On the 28th of 12th month following,
Rowland Greene and Thomas Anthony of the Select Quarterly
Meeting`'s committee came to South Kingston Monthly Meeting,
and at the close thereof, called together the ministers and elders.
When convened, R. G. stated to them,
that a misunderstanding existed between the Quarterly
Meeting`'s committee and John Wilbur,
a member of this meeting, on account of a letter which he wrote to them,
which letter was very dissatisfactory;
and they apprehended that the members of this select meeting had been misinformed,
and therefore had not a correct knowledge of the case;
that they of the committee had now called the members together
in order to give them a right understanding of it.
To this T. A. subjoined, that the letter alluded to, contained things that were untrue,
and again repeated it--contained things that were not true;
and then proposed reading extracts from the said letter,
for the information of the meeting.
But J. W. proposed the reading of the whole letter,
because divers of the members had never seen it,
and because there was a chain of connection throughout,
showing a relation of one part with another.

And, although the reading of the whole letter was strongly opposed by these two committee men,
yet the proposition for reading the whole prevailed,
and the letter was deliberately read.
Now the committee, instead of offering their extracts,
and instead of going about to prove their assertions of falsehood,
which they had said it contained, proposed, and, as they said,
in order to put an end to the controversy, to destroy the letter,
with the copy retained by the writer; and at the same time stoutly affirmed,
and repeated it again and again,
that the letter was altogether inapplicable to what they said to him at Greenwich;
that he, the writer, had made his own premises and drawn his own conclusions, etc.
Wherefore J. W. desired them to put a finger on one
of his seven references to their charges at Greenwich,
and to refute it.

This he pressed them earnestly several times to do.
But instead of doing it they boldly affirmed that
they never made any charge against him there,
that they only made some friendly inquiries of him,
and thus evaded an examination of the premises so
distinctly grounded upon their own charge.
They had, in this meeting,
made both a formal and formidable complaint of something which he had said or done,
and he now earnestly called upon them to show what it was,
that thereby it might be seen what it was not, alleging that, in the civil department,
a man was never so much as brought to trial for defaming others,
without propounding the words charged upon him, much less subjected,
without proving them.
But they now declined altogether an examination of those items
in the letter which referred to their charges against him,
which charges were the whole occasion and groundwork of the letter.

And again, inasmuch as they had inscribed upon the letter this condemnatory sentence,
viz: that "`the premises therein taken were false,
and consequently that the conclusions were false and unsound`"
which inscription had been read in this meeting,
and they had also declared at the same time, without reserve,
that "`the letter contained things which were not true,`"
he now called upon them to make good those high charges.
Being thus closely pressed to do the thing which
they at first professed to have come for,
they referred to the passage relating to their "`endeavors to put down
those who honestly withstand J. J. Gurney`'s sentiments,`" and said,
"`those expressions which they understood to have been applied to the committee,
were untrue.`"

J+++.+++ W. now reminded them of what one of them (R Greene) said to him whilst at Greenwich,
viz:
"`Thou knew that the Yearly Meeting`'s committee were not
willing that thou should travel in the ministry,
and therefore thou ought not to have gone to Philadelphia,`" and subjoined,
"`and my advice to thee is to stay at home and be quiet.`"
To which advice every one of the committee then present, except Andrew Nichols responded.
Knowing that these were their own words, they appeared to feel the weight of their defeat.

It was observed by one of the members of South Kingston Select Meeting,
and seen by every one present, that the truth of the passage referred to was sustained.
To this observation they of the committee made no reply.
And then again J. W. asked them for other objections, if any they had,
tending to prove their charge, but without effect;
they wholly declined challenging any other item in the whole letter,
though once and again called on to do so.

And inasmuch as the committee had pressingly proposed the burning of the letter,
and had given the assurance that such a measure would put an end to the whole controversy;
one or two members of the meeting, seeing the utter failure of the committee, and,
as it may be, feeling a little for them,
and greatly desiring the restoration of peace among us,
proposed to John Wilbur that he consent to the consuming
of the papers that related to this unhappy controversy;
being also unduly credulous as to the assurance given,
that this measure would end it,--not seeing the consequences
that would most likely follow;
for should this letter become extinct,
and therefore could no longer bear witness for itself,
false charges might be brought against it,
in which case the writer would be left in a very unpleasant predicament,
on account of the difficulty of proving a negative without a record.
Moreover, another good reason why the letter ought not to be burnt was,
because the charge of falsehood was written and remained upon it,
and because the writer of it was now charged in a meeting of ministers and elders,
with writing things therein that are untrue.

Consequently, for him to consent to the destruction of the papers,
until those slanderous charges were removed and retracted, it might,
and not very unfairly,
be construed as an acknowledgment on the part of the writer
that those accusations of falsehood were correct.
Hence he saw it much safer to preserve a correct copy of the letter,
and resolved to do so.

The great efforts and unhallowed means resorted to heretofore by the committee,
to calumniate J. W., and to prevent his having an opportunity to vindicate his cause,
induced him to suspect their integrity in a professed desire and
assurance of a settlement through the destruction of this letter.
And this suspicion has been since abundantly confirmed by the acknowledgment
of other members of the Select Yearly Meeting`'s committee.
Thomas Howland, the one who first cited J. W. before them,
having said in a letter to a friend, "`The burning of that letter would, I conceive,
have done little if anything at all, towards settling the difficulty.`"
At the close of this interview,
J+++.+++ W. asked T. A. for the extracts which they at first proposed to read in that meeting,
which he declined giving,
but handed him a copy of the letter with some pencil marks in the margin.

At our Select Quarterly Meeting at Providence, 2nd month, 3rd, 1841,
the committee presented a report setting forth, as near as can be remembered,
(for J. W. has been denied a copy) that "`a member of this meeting
having spread reports to the injury of the order of Society,
was labored with on that account by your committee,
whereupon the said member wrote a letter to them
containing things that were unjust`" etc.

This report produced considerable expression, mingled with censure and exhortation,
pointedly to the individual,
with professions of sympathy for and travail with the committee.
And it was concluded that the subject should remain with the same committee.
It was perceived by J. W., that the committee at large,
was resolved to disregard and overlook the proceedings
of the two who had been to South Kingston;
he rose, on behalf of the person alluded to in that report;
requesting that the meeting would either take up the subject itself and
allow that individual a fair opportunity of making his innocency appear;
or otherwise, instruct their committee to do so;
stating that some of their number had convened the select meeting,
of which he was a member,
and there openly in the meeting brought complaints against him
of a more aggravated nature than those stated in this report,
but which complaints they were not able to sustain,
and which failure he believed was obvious to every member of that meeting;
that he had been suing for six months past for distinct
objections to the course which he had taken;
and as he thought obtained a promise three months before to furnish him with those objections;
but that promise had not yet been redeemed.

He referred to the trial of W. Penn and W. Mead, in London,
to whom a full and fair hearing was promised, but which promise was not fulfilled;
and the court seemed disposed to condemn them upon
the reports abroad and the prejudice against them.
By which reference J. W. suggested whether the reports abroad tending
to produce unfavorable feelings towards the person alluded to in the report,
had not influenced the minds of some of his friends against him.

The committee now seemed to be brought to a stand what to say to this statement,
but one or two of them did say that much opportunity had been allowed him;
and referred to the time of one sitting,
which they said continued for five hours in discussion of the case.
But he reminded them, and informed the meeting,
that his solicitations through that meeting were the same as now,
to give him a plain statement, on paper, of their ground of uneasiness;
and thus the subject was left.
But before leaving Providence, J. W. asked T. Anthony,
(who furnished him with the copy of the letter,) whether those pencil
marks on the margin were intended to designate their objections?
To which he replied that "`he did not know.`"

John Wilbur received from one of the same committee a previous
notice to meet them at Greenwich on the 4th of 5th month,
1841, the day before the Select Quarterly Meeting there.
He went accordingly, and met with nine Friends of the before-mentioned committee,
and six of the standing committee of the Yearly Meeting.
And after a time of silence, one of the former said,
that inasmuch as J. W. had expressed a desire for an opportunity to make his defence,
the committee had now met to give him that opportunity.

He now waited some time for their complaint to be brought forward;
but not being presented,
he mentioned that he had been waiting in expectation that a complaint,
if any they had against him, would be presented;
and that nothing to that effect had been given him;
that although there were pencil marks on the copy of his letter; yet T. A.,
who handed it to him,
said he did not know whether those pencil marks covered
the committee`'s objections or not;
and that therefore he was not prepared to respond to their complaint,
having received no other designation in writing of their uneasiness.
But John Meader said that "`John Wilbur,
having received that marked copy from the hands of the committee,
he might have known that it contained their objections.`"
But as one of their own number had spoken doubtfully in relation to it,
J+++.+++ W. was not now prepared to meet those objections specifically.

But the committee decided on going into the consideration of the case at this time.
Whereupon he requested that they would allow him
the rightful privilege of one of two things,
viz: that they would either give him their objections in writing,
and time to canvass them,
or that they would constitute an individual of their
number as their organ to speak on their behalf,
intimating that for one individual to be laid under the necessity
of replying to the objections and allegations of so many,
might tend to an unreasonable embarrassment; these requests were both denied.
The Quarterly Meeting`'s committee plead that he had been furnished as above,
and that their objections were marked upon that copy,
and that he might have known that it defined their objections, etc.

It was now proposed, as he thinks, by the Yearly Meeting`'s committee,
that the letter should be read,
and that the Quarterly Meeting`'s committee should discuss
the objectionable passages as the reading went on.
To this proposal J. W. objected, for the reason that the Yearly Meeting`'s committee,
(who were presumed not to have seen it,) could not
in that way so well comprehend it as a whole.
And so the whole letter was read without any interruption.

And quite a solemnity prevailed throughout, and for some time after;
insomuch that it did almost seem doubtful whether the Quarterly
Meeting`'s committee would make any objections,
nor did they do so until the Yearly Meeting`'s committee
encouraged them to bring them forward,
saying that it contained the insinuation that the
Quarterly Meeting`'s committee were unsound, etc.
Finally they attempted, but in so feeble a manner, and so indefinite,
that the Yearly Meeting`'s committee proffered their help,
(though brought here professedly to judge in a case of uneasiness
between the Quarterly Meeting`'s committee and J. W.,) in pointing
out a paragraph or two which they said by a reasonable construction,
appeared to them to bear upon the doctrinal views of the Quarterly Meeting`'s committee.

But to this J. W. said, as he had heretofore said,
that it was not his intention to charge the committee with unsoundness;
and if it would give them any satisfaction he was still prepared to say so,
by way of explanation, and as they had asked the question, he would say,
that he was as willing to say it in writing as verbally,
as it could not then be misconstrued.

These committees held three meetings at this time at Greenwich;
at the first of which they gave occasion for J. W. to mention
the substance of the interview of two of the Quarterly Meeting`'s
committee with the ministers and elders at South Kingston,
and he was astonished to hear them disclaim having any remembrance of what he related;
and in the sequel they denied it! although provable by every member of that meeting.

David Buffum said (though uncalled for) "`that he
had never read anything in J. J. Gurney`'s writings,
which he considered unsound,`" (probably to redeem what he had
at first said against them.) And at the close of the sitting,
whilst many members were yet present, Abraham Sherman, jr.,
said he believed that J. J. Gurney`'s doctrines, when compared one with another,
would very nearly, if not entirely, comport with the doctrines of our early Friends.
To which William Jenkins and one or two more responded,
and no objection to either of these affirmations
was expressed by any one of the committees then present.^
footnote:[Here then,
we find those committees voluntarily identifying
themselves with the doctrines of J.J. Gurney.]

On 4th day morning, J. W. met again with the committee,
and in a recurrence to the great question of doctrines,
as treated of the preceding evening,
he told them that his fears had not diminished by reason of what passed yesterday;
that one of the Quarterly Meeting`'s committee had said that he had never
read anything in J. J. Gurney`'s writings which he thought unsound;
and that one of the Yearly Meeting`'s committee had also said, that he believed,
if we were to compare one thing with another,
that we should find J.J. Gurney`'s doctrines to be nearly,
if not entirely conformable to the doctrines of our early Friends;
and that one or two more responded to that sentiment.

But no reply to these remarks is recollected to have been made.
Subsequently, and after some conversation not recollected,
R+++.+++ Greene spoke at considerable length, in commendation of J. J. Gurney,
bestowing high encomiums and much praise upon him and his services in this country.
Soon after, they asked J. W. if he were willing to commit to writing his expressions,
that he had had no intention of charging the committee with unsoundness?
to which he answered in the affirmative,
inasmuch as he had quite a choice that such explanation, if made at all,
should be in writing; and proposed, if A. S. had a pencil, that he should sketch it out,
+++[+++meaning then while we were sitting.]
But, contrary to his expectation, the committee proposed to rise, and did so.
After the sitting of the Select Quarterly Meeting,
he was requested to meet the committee again next morning at nine o`'clock.

On fifth day morning, when assembled, A. S. read a paper,
not only embracing the explanation agreed to,
but a condemnation of expressions contained in his letter, and so shaped,
as J. W. thought, that they could apply it to any part of the letter they might choose,
and thereby, if they pleased, make him appear to retract the whole letter,
and the whole ground which he had taken against the doctrines of J. J. Gurney,
as well as his objection to the proceedings of the Quarterly Meeting`'s committee; hence,
of course, he refused to sign it,
but asked them to what expressions in the letter they alluded?
A+++.+++ S., the writer of the paper,
first referred to J. W.`'s saying that D. Buffum "`acknowledged that some of J. J. Gurney`'s
writings were very unsound,`" when David arose and denied making such expressions.
But J. W. now related the conversation that led to it,
and mentioned J. Meader`'s expression of dissatisfaction with it at the time, when he,
remarked, "`I should not have said so.`"
J+++.+++ W. then called on Andrew Nichols (who had not arrived until this morning)
to state his understanding of what D. B. said at the time alluded to.
And he, although backward about testifying, gave it verbatim as the letter stated;
and immediately that subject was dropped

A+++.+++ Sherman then referred to the passage in the letter which says,
"`When you say that I have spoken against the doctrines of J. J. G., etc.,`" and said,
"`that the committee alleged that J. W. had attributed
expressions to them which they had not made use of.`"

He now plainly stated to them,
that at the first interview (and previously to his proposing to read extracts,) they did,
and with some severity,
"`censure him for spreading extracts from the doctrines
of J. J. Gurney,`" but that on his producing those extracts,
and proposing to read them, for their information, as to the extent of their unsoundness,
thereby to evince the propriety of his showing those extracts,
then it was that they came round and said that the unsoundness of the
doctrines of J. J. G. had nothing to do with J. W.`'s defence.

But even now (continued he) suppose we were to waive this impassable ground,
and look to the restraints which the Select Quarterly Meeting`'s
committee essayed to lay upon him at that time,
and inquire for what cause?
Let the answer be in their own language--for his having spoken against J. J. Gurney.
This was effectually, and to every intent and purpose, making him,
so far as such could make him, an offender,
for speaking against the doctrines of J. J. Gurney, and not otherwise,
because it was his doctrinal characteristics only that were implied in these animadversions.
And if the committee can separate the doctrines from the man, so he, as well,
can separate the man from his doctrines.

In the next place,
A+++.+++ S. spoke at some length in denunciation of the course which J. W. had taken,
and much in the same strain as did the Quarterly Meeting`'s committee,
in the first place at Greenwich, affirming it to have been a breach of order, etc.
The speaker appeared to understand how to foreclose a reply,
by immediately proposing an adjournment on taking his seat, viz:
to meet again on first day evening, at the time of the Yearly Meeting at Newport,
which was agreed to.

At Newport, 1st day evening, the 13th of 6th month, 1841 the committee again met;
J+++.+++ W. being present, let them know that he had responded to,
or rather vindicated the passages marked on their copy of
his letter to the Quarterly Meeting`'s committee,
and now desired to be furnished with their objections, in writing,
in relation to the stand which he had made against the writings of J. J. Gurney.

They now denied having said, at their last meeting,
that the marked passages included the committee`'s objections, and J. Meader,
the very man who then said that "`J. W. might have known that the marked passages,
coming from the committee, did include their objections to the letter,`" now said,
that it was himself, unauthorized by the committee, who marked those passages;
and that they did not include all the committee`'s objections to that letter;
to the last assertion, to wit, that they did not include all their objections,
several others responded.

Then, after reminding them of the promise in the 11th month,
to furnish him with their objections, and of their assumption in the 5th month,
that they had done so, as related to the letter; he called upon the committee,
most seriously,
to furnish him with a plain account of their dissatisfaction with him on paper,
in a manner which could no more be changed,
averring that the allegations and complaints against him had been several times changed!
But they said he knew enough already of their dissatisfaction,
and utterly refused to give him a written recital of their uneasiness!

Howbeit, he told them, that such was not only his right, but altogether reasonable.
Wherefore he now told them that if they persisted in a refusal,
there would be no use in his meeting them any more.
Much, however, was said by this committee,^
footnote:[The Select Quarterly Meeting`'s committee had now, as they said,
resigned their authority to the Yearly Meeting`'s committee,
of which they were all members save two,
and by this maneuver Andrew Nichols was excluded.]
(which now amounted to about thirty persons together,
at this time,) and endeavors were not wanting to
place him in a fearful and alarming position.
They ultimately resorted in turn to persuasion, exhortation, and denunciation,
in order to obtain concessions from him; at one time, repeatedly said,
that it was but a little they would require of him to say;
at another time proclaimed him to be in a dangerous position; and again they told him,
that he was in a dark, hard state of mind!

After laboring in this way for some time,
they concluded that a smaller number would be better, to labor in a more private way;
and so appointed about half a dozen out of the number for the purpose,
and adjourned till 3rd day evening.
This sub-committee requested him to meet them next morning at 7 o`'clock, which he did.
But during the recess, and on much deliberation,
he became more and more confirmed in the belief, that he could not safely,
in any manner whatever, retract the course which he had taken.
In which conclusion he had the unity as well as the sympathy of his friends.

"`When this sub-committee met, he told them that he had but very little to say,
that his mind had been deliberately made up, that he could make no concessions,
and therefore was disposed to withdraw;
that the committee could take such course as they thought proper.
But they seemed very unwilling he should go out,
and proposed that he read his defence to such objections
as he had already received from the committee,
but he said there would be no use in answering to a part of an indictment,
before it was finished, or the whole brought in, which they could not gainsay,
but seemed inclined to administer more exhortation,
and to show him the danger of his condition;
and so he stayed until he supposed all had done.
They were quite importunate, however,
that he would meet the full committee the next evening,
but he gave them no encouragement of doing so, and did not meet them.

At the close of the Yearly Meeting he was invited into the committee room,
where he met with three or four of the committee, and where the question,
whether he would take the advice of his friends, was urged by one of them;
which was only answered by asking him whether he was prepared to give advice;
intimating that it would be time enough for them to ascertain that fact,
when their advice was given.

These few now importuned most earnestly that J. W. would make at least some little concession,
and asked him if he would not say this, viz: "`If I have done wrong, I am sorry for it.`"
To which he replied, this is by no means a proper way +++[+++for a transgressor]
to make satisfaction.
They finally asked him if he would not meet the whole committee next morning,
and pressed him to do so; but he did not promise,
telling them he should take the advice of his friends.

Sixth day morning, agreeably to the counsel of his friends,
he again met the Yearly Meeting`'s committee,
and was there again pressed to make them satisfaction by acknowledgment,
and R. G. undertook to give a history of the case,
but stated it in the most aggravated point of view,
omitting the circumstances militating against the committee,
and in favor of J. W. However,
as the latter had before concluded to make no defence before the committee,
until they had allowed him the just right of having a plain account, in writing,
of all their charges against him, he told them that,
however unjust and aggravated that statement was, he should make no formal defence.

Subsequently, his letter to the committee was read, and when accomplished,
reference was made by them to the denial therein contained,
of the right or authority of that committee to reprehend
him in the form and manner they had done.
He now called for a copy of the minute of the appointment
of the Select Quarterly Meeting`'s committee,
but it was not produced;
and then stated that he had applied to the clerk of the meeting which appointed them,
for a copy of that minute, but he had refused to give it.
And so they were pleading for assumed powers while they
refused to produce evidence of having such powers.
He then related the purport of the minute of their appointment, substantially as it was,
which they had no right to gainsay, as the only evidence was in their hands,
and that a matter of record.

He stated to them a supposed case where defective accounts
should be sent from one of the Quarters to the Yearly Meeting,
and a committee appointed on that account,
and asked whether such committee would have a right, under that appointment,
to go all over the Yearly Meeting in the exercise
of the authority thus conferred upon it.
To this they made no reply.

They now professed to have in their possession other complaints against him,
of which they had not yet told him!
He then desired that, if they had other charges against him,
they would be so good as to bring them forward,
as well as those of which they professed that he had sufficient knowledge,
so that he might have a plain list of the whole.
To which one of them replied,
that they had many others!! +++[+++He supposed that they
made this pretence of having more charges in store,
for the purpose of alarming him, and to induce him to yield to their demands.]
But no encouragement was given of letting him know what they were,
nor yet of making tangible on paper anything of the kind whatever.

In answer to their frequent demands for concessions, he replied, now near the close,
that there were many Friends, and probably in all parts of the Society,
who were nearly united in making a stand against
the unsound doctrines spread abroad among us,
and that with them, and in the same cause, he had taken a pretty prominent part;
therefore, if he should now condemn his having withstood those doctrines,
he would inflict a wound upon the good cause, and upon the feelings of his friends,
as well as upon his own conscience.
To this one replied, that those alluded to in other parts of the Society,
were as likely to be mistaken as was John Wilbur.
To which he saw fit to make no reply.

This committee, as it appears,
were desirous that he should say something that they could
call a condemnation of errors which he had committed,
and then to liberate him by their pardon, and in that way cast a stigma upon him,
and on the cause which he had supported;
and which would go to strengthen the doctrines which he had reprobated.
This he could no more agree to,
than George Fox and others could agree to be released from prison,
under the sentence of a premunire, by a pardon from the king,
the acceptance of which would have implied a confession of guilt.
George Fox therefore declared, that he would rather have lain in jail all his days,
than to act in any way dishonorable to the Truth,
or as implying transgression on his part.
Considerable more passed in the course of these discussions,
that was not essential to the merits of the controversy, and is therefore omitted.

At our Select Quarterly Meeting in the 11th month following, and in the forepart thereof,
divers pointed declarations were thrown out, evidently aimed at J. W.,
which passed without remark; but near the close of the business part of that meeting,
one of its committee fell to censuring South Kingston Select Meeting,
for sending up to that meeting, as representative,
one who was under the care of a committee of that meeting.

And now, although J. W. had let pass, without remark,
those pointed declarations which were aimed at him,
(he having a right to do so,) yet when the proceedings of
the meeting from which he was there as a representative,
were condemned, he felt it his duty to come forward in vindication of its rights;
and he informed the meeting that Friends of South
Kingston Meeting believed that this meeting`'s committee,
not being appointed for that purpose,
had interfered with and invaded the rights which the Yearly Meeting had confided to it,
and to all others within its limits, of that description;
and that in a manner unauthorized by discipline,
and that this interference was therefore gratuitous; and further said,
that superior meetings and their committees were bound to move
through the regular and defined channels of the same discipline,
which was to govern those of an inferior order, as well as individuals.
To which no one responded, for the meeting immediately rose.

In the 4th month, 1842,
fifteen in number of the Yearly Meeting`'s committee
attended South Kingston Monthly Meeting,
and brought a voluminous complaint against him, without any previous notice,
and literally made good their assertion eight or ten months before, viz:
that they had many things against him, of which they had not yet told him.
So they did indeed couch divers charges in this complaint
which they had never before brought against him as such.

This attempt by force of numbers, as it appeared,
to compel the Monthly Meeting to take immediate measures,
so contrary to the usual course of business, by overseers,
and through a preparative meeting,
caused a loss of confidence in the committee on the part of the Monthly Meeting,
and raised the question in many minds,
What can be the merits of a complaint which they dare not
venture with the overseers and preparative meeting,
nor even with the Monthly Meeting, without so great a number to enforce it?
Not that the Monthly Meeting was unwilling to recognize it,
through the usual channel prescribed by discipline and the order of society.
Nor was J. W. unwilling that this case should be submitted to South Kingston
Monthly Meeting for decision in a regular manner according to discipline.

The complaint thus irregularly brought into the Monthly Meeting is as follows:--

[.embedded-content-document.letter]
--

[.letter-heading]
To South Kingston Monthly Meeting of Friends:--

We, the committee appointed by the Yearly Meeting to extend a general care on its behalf,
for the maintenance of our Christian principles and testimonies,
and the preservation of love and unity among our members,
and in the ability that may be afforded us to assist and advise such meetings and members,
as circumstances may require, and way open for, under the direction of best wisdom,
having had our minds introduced into deep concern and exercise
on account of the course pursued for some time past by John Wilbur,
a member of South Kingston Monthly Meeting, in the station of a minister,
believe the time has now come, for us to state some of the particulars,
wherein he has departed from the good order of our religious Society,
in the disregard of our Christian discipline.

He has circulated an anonymous pamphlet, which impeaches the character of our Society,
and in which, some of its important doctrines,
as exemplified in the religious engagements of some of its faithful ministers,
are reproachfully held up to view;
and purports to contain the proceedings of London Yearly Meeting of Ministers and Elders,
with the sentiments of divers Friends therein named,
when the subject of liberating a minister to visit this country was before that meeting.
The object of which, together with sundry letters which he has circulated,
appears to be to induce the belief that the concern
did not receive the unity of the meeting,
and that the clerk did not act in conformity with the true
sense and judgment of the meeting in signing the certificate,
thus endeavoring to invalidate both the proceedings and conclusion of a meeting,
in unity with this Yearly Meeting,
and whose certificate on behalf of the same Friend was received and united with,
as entered on our records.

And while the Friend was in this country,
and engaged in the discharge of his apprehended religious duty,
with full certificates of unity from the Monthly
and Quarterly Meetings of which he is a member,
and the Yearly Meeting of Ministers and Elders of London, and which were duly presented,
received, and accredited, in all the Yearly Meetings in this country except one,
which he did not attend;
and thus was he at liberty for religious service within their limits
in the full and acknowledged character of an approved and authenticated
minister of the Society of Friends;--John Wilbur,
for the want, as we believe, of an humble abiding in the Truth,
has circulated divers letters,
one or more of which appear to have been written in England,
and others originating with himself, addressed to different Friends in this country,
which were intended to show that the minister thus liberated to
religious service was not in unity with his friends at home,
contrary to the long established order of our religious Society,
and designed to close his way in the minds of Friends.
And we also believe,
that for the want of maintaining his integrity in that dependence upon the Holy Spirit,
which would have preserved him in unity with Friends,
he has indulged in a spirit of detraction, in speaking and writing,
by which the religious character of divers Friends in our
own and other Yearly Meetings has been much misrepresented.

Many Friends were introduced into deep concern on his account,
and several of them treated with him in tenderness and love in relation to it,
but without producing any apparent change in his mind,
and there having been a committee appointed by Rhode
Island Quarterly Meeting of Ministers and Elders,
in the fifth month, 1840, of which body he was a member,
on account of existing deficiencies as manifest from the answers to the queries,
and under a concern for the cause of Truth;
and they having been made acquainted with John Wilbur`'s course, as last above stated,
and he having made divers assertions tending to induce dissatisfaction among Friends,
and with the proceedings of our Yearly Meeting in various particulars,
and calculated to produce division therein,
and also to disturb the unity of different Yearly Meetings,
and to alienate the feelings of their members from each other,
sought an opportunity with him,
in which they endeavored to show him the effects
of his proceedings both upon himself and others;
but he,
so far from receiving these labors of love in the spirit in which they were administered,
soon after wrote a letter to one of the committee, in which he made unjust insinuations,
and preferred charges against them which they deny in point of fact.

They, nevertheless, continued their care and labor,
but his mind appearing closed against their advice in the 5th month, 1841; we,
at their request, believed it to be our duty to extend care in his case;
and it is with deep regret and sorrow we have observed
the effect his course of conduct has produced,
in lessening that regard for the wholesome restraints of the discipline,
and for the labor of faithful Friends, for the preservation of that good order, love,
and unity, which are essential to the peace and welfare of the body.

We have had repeated opportunities with him,
in which we have labored to convince him of his errors,
but this desirable object not having been accomplished,
and after waiting several months to afford him opportunity
to make satisfaction for his deviation,
and two of the committee having unavailingly visited
him on this account at his own house,
and there not appearing that change in his mind which is
necessary to his being restored to the unity of Friends,
we now believe it incumbent upon us,
in discharge of the service confided to us by the Yearly Meeting,
to recommend his case to the immediate notice and
care of South King-ton Monthly Meeting.

[.signed-section-closing]
Providence, 4th Mo., 23,1842.

[.signed-section-closing]
(Signed,)

[.signed-section-signature]
Rowland Greene, Perez Peck, John Osborne, David Buffum, Caleb Nichols, John Meader,
Daniel Taker, William Jenkins, Edward Wing, Mary Wing, Thomas Anthony, Olive Wing,
Elizabeth Meader, Mary B. Allen, Allen Wing.

--

After the reading of the complaint,
the Yearly Meeting`'s committee proposed that the meeting should take action upon it,
by appointing a committee on the case at that time.

The Friend complained of, and others,
took the ground that the complaint should come to the Monthly Meeting
through the overseers and preparative meeting--agreeably to our uniform
practice,--but the committee said their authority from the Yearly Meeting
was such as to obviate the necessity of such preliminary proceedings;
and when it was proposed that the case should be referred for a month,
on the ground that the Monthly Meeting was hardly
in a situation to act in so important a matter,
on account of the small number present,^
footnote:[The meeting was at this time held at the
most remote place from the greater number of Friends,
and the day was wet, and consequently a smaller number than usual were present.]
the Yearly Meeting`'s committee insisted upon immediate proceedings,
saying an addition could be made at a future time to the committee now appointed,
if the meeting desired it; and threatened,
if the Monthly Meeting did not comply with their advice,
to carry a complaint against it to the Quarterly Meeting.

After an expression by the meeting,
in which the greater number objected to the proposed immediate action,
the clerk proposed to refer the decision of the question to the Yearly Meeting`'s committee,
who had been urging it upon the meeting.

The members of South Kingston Monthly Meeting generally knew very little of the
merits of this case before it was brought to them by the Yearly Meeting`'s committee.
At the Monthly Meeting in the 5th month,
the time for which the clerk was appointed having expired, a new clerk was chosen,
having the unity of more than three fourths of those who expressed themselves;
and those who opposed the appointment did it on the
ground of postponing the action of the meeting,
and not from any expressed objection to the person appointed.

The former clerk having left the table,
the one newly appointed was requested to take his seat, but before doing so,
he proposed for the former clerk to make a minute of the appointment,
but the former clerk said it was not customary.
The new clerk then went to the table, and the business of the meeting proceeded;
the former clerk,
and those who had advocated the postponement of the appointment of the clerk,
participated therein.
At this time one of the committee in the case of J. Wilbur
proposed that an addition be made to that committee,
the case being, as he said, a very important one, and the meeting,
when they were appointed, small.
An addition of five Friends was then made to the committee.

At the Monthly Meeting in the 6th month,
several of the Yearly Meeting`'s committee attended,
and proposed that the new clerk should resign,
and that the meeting should reappoint the former one;
giving it as their opinion that this course would
tend to restore unity and harmony in the meeting,
which they professed to be the object of their visit.
The committee said, their reason for this advice was,
that they had heard that the appointment of the clerk was made in a disorderly manner,
and that it was planned out of meeting;
but they were unable to sustain these charges when called upon to do so.
A large part of the meeting expressed their satisfaction
with the appointment of the new clerk,
making it evident that the change proposed would not tend to unite the meeting;
and the subject was passed from without making the change.

A committee being appointed at this time to transfer the books and papers
of the Monthly Meeting from the former to the present clerk,
the Yearly Meeting`'s committee stated that they
had advised the former clerk to retain them;
and gave as a reason,
that they had cause to apprehend that a separation
was contemplated by South Kingston Monthly Meeting.
This was disclaimed by the Monthly Meeting,
and no evidence of it was adduced by the committee.

In the 7th month the committee in the case of John
Wilbur met for the investigation of that case,
and six of the Yearly Meeting`'s committee attended.
Before the examination of the case was commenced,
J+++.+++ W. desired to have one or two of his friends to sit with him and assist him;
and after some discussion,
in which the Yearly Meeting`'s committee made objection to his having this privilege,
the respective parties withdrew,
submitting the matter to the Monthly Meeting`'s committee,
who unanimously decided to allow J. W. the assistance of two of his friends.
Upon their return, the Yearly Meeting`'s committee still objected,
and again retired a short time for consultation among themselves.
On again coming in,
they took decided ground that the decision of the Monthly Meeting`'s committee
must be reversed or they should not proceed with the opening of the case,
but should leave.
The Monthly Meeting`'s committee, on being again appealed to,
declined to take from J. W. the privilege they had granted,
without he should consent thereto.
J+++.+++ W. subsequently did consent to proceed without the help of his friends,
as from the determination of the Yearly Meeting`'s committee,
no other way appeared to go forward with the case, with said committee present,
which was to him desirable.

During the discussion of this question of allowing him assistance,
which occupied the whole of the first day,
the Yearly Meeting`'s committee claimed that it was their province,
after representing the case on their part,
to join the Monthly Meeting`'s committee in judging the same;
a position which the Monthly Meeting`'s committee were not ready to allow.
The Yearly Meeting`'s committee also, during the same discussion,
denied that they were complainants in this case; and when, the next morning,
they were asked by J. W. whether they still persisted in this denial,
notwithstanding their names were attached to the complaint, they made no reply.
In the early part of the trial,
the Yearly Meeting`'s committee introduced the pamphlet alluded to in the complaint,
and which J. W. was therein charged with circulating.

He requested the pamphlet might be read,
but this the Yearly Meeting`'s committee opposed,
proposing to read only certain extracts which they had selected from it;
and said if it was read at length they should leave; they opposed it strongly,
saying it would make them accessory to the further circulation of an improper book,
and responsible for it, if read before the Monthly Meeting`'s committee,
but subsequently said they were willing the committee should have the pamphlet for examination!
The Monthly Meeting`'s committee, however, decided to have it read,
and it was read accordingly.
The evidence of the Yearly Meeting`'s committee in support
of the charges in the complaint being gone through with,
J+++.+++ W. proposed in his defence to go into the examination
of certain fundamental doctrines of the Society,
as held by the early Friends, and also of certain other doctrines,
promulgated by Joseph John Gurney, as those of the Society,
because it was on account of his objection to the latter that he was complained of.
This was objected to by the Yearly Meeting`'s committee.

In support of his right to do so, J. W. referred to the discipline, p. 74,
which is as follows:--

[quote]
____
The importance of steadfastly maintaining our ancient principles,
respecting the doctrines of the gospel, coming renewedly under our consideration,
we earnestly recommend and enjoin upon Quarterly and Monthly Meetings,
and upon all faithful Friends, to be watchful over our members,
as it regards the profession of their faith in our Lord Jesus Christ,
both as to his outward coming in the flesh, wherein he tasted death for every man,
and was the propitiatory sacrifice for our sins, and not for ours only,
but also for the sins of the whole world, suffering the just for the unjust,
that we might be brought unto God through him;
and to his spiritual appearance in the heart, for, "`unto them that look for him,
shall he appear the second time, without sin, onto salvation.`"
And if in any instance there should be manifested any deviation
from our Christian principles in these respects,
that they proceed to labor with such in the spirit of meekness and wisdom,
endeavoring to bring them to a sense of their departure from our acknowledged principles,
that if possible they may be restored to soundness of faith.
And if there should be any who should persist in their errors,
notwithstanding such labor in brotherly love,
that our testimony may be maintained by testifying against such.
____

The Yearly Meeting`'s committee took the ground that the Monthly Meeting`'s
committee had no right to set themselves up as judges of doctrine;
and that only two bodies are in any case authorized to judge of doctrines, to wit:
the Yearly Meeting and the Meeting for Sufferings;
that if they entered into doctrines they would assume authority
to decide that the great body of the Yearly Meeting are unsound,
taking into view the great unanimity of it,
in granting Joseph John Gurney a returning certificate.

The Yearly Meeting`'s committee asked a decision of this question,
and after taking time for deliberation the committee of
the Monthly Meeting gave the following written decision:--

[.embedded-content-document]
--

Inasmuch as the complaint against John Wilbur charges
him with circulating an anonymous pamphlet,
in which some of the important doctrines of our religious
Society are reproachfully held up to view;
and inasmuch as the merits of that matter have been fully gone into,
on the part of the Yearly Meeting`'s committee, and further, as it appears to us,
that the merits of this case essentially depends upon the
doctrines which have been called in question by John Wilbur,
we have concluded to allow him to proceed with his defence,
introducing such evidence and documents on these subjects,
as shall appear essentially to relate to the same.

--

And, subsequently, the committee gave the following reasons for this decision, namely:--

[.embedded-content-document]
--

We come to this conclusion on the ground that John
Wilbur has been charged with circulating information,
both in writing and print, calculated and intended to close the way of a Friend,
from England, travelling among us as an approved and accredited minister,
as well as certain other offences against the discipline and order of the Society;
and he pleads in defence,
that what he has done has been in the faithful discharge
of his apprehended religious duty,
in guarding the Society against the introduction of unsound and pernicious doctrines,
subversive of Quakerism;
which doctrines he maintains were held and promulgated by the individual alluded to.
Now, since our Christian discipline enjoins upon all faithful
Friends to be watchful against such doctrines,
and to testify against them, it appears to us, that no less could be done,
than to allow the person so charged, to show, if he can,
that he has been acting in conformity with the discipline in such cases.

In answer to the assumption of the Yearly Meeting`'s committee,
that we have no right to judge of doctrines,
and that the only bodies authorized to do so, are the Yearly Meeting,
and the Meeting for Sufferings, we would observe,
that Monthly Meetings and committees appointed by them,
are required to judge of doctrines in many cases; as on receiving members,
whether they embrace our principles,
and sometimes in disowning members for an abandonment of them.
And it will be seen that the discipline above alluded to,
would involve an absurdity if this was not the case,
for therein all faithful Friends are enjoined to be watchful against
the manifestation of unsound doctrines among our members.

We acknowledge,
that the Yearly Meeting has very properly constituted its
Meeting for Sufferings the body to judge of the soundness
of doctrines proposed to be published as those of the Society,
and whose especial duty it is to guard against every inroad of error among us;
but this does not, and cannot debar subordinate meetings and their members,
from the right and duty of judging for themselves
in so vital a matter as the doctrines they embrace,
and bearing their testimony against manifest unsoundness, in whomsoever it may appear.
And, so far as our meetings and members are guided by the Spirit of Truth,
which leads into all Truth, so far there will be an unity of sentiment among them,
and all, as we believe,
in full accordance with those doctrines and principles so clearly and fully testified of,
in the early days of the Society by George Fox, and the primitive Friends.

--

The Yearly Meeting`'s committee being informed of the decision
of the committee of the Monthly Meeting on this question,
immediately withdrew,
taking with them all the papers and documents which
they had introduced to sustain their charges.
The Monthly Meeting`'s committee continued their sittings to the conclusion of the investigation.

At the Monthly Meeting in the seventh month a number
of the Yearly Meeting`'s committee attended.
The committee appointed to transfer the books and papers,
reported that they were unable to obtain them, the former clerk refusing to give them up,
alleging as a reason, that the Yearly Meeting`'s committee advised him to retain them.
It was proposed to take him under dealing for the offence,
and the meeting took the case into consideration,
denying the right of the committee to interfere with the records.
The Yearly Meeting`'s committee objected to his being taken under dealing,
but expressed their satisfaction with the continuance
of the committee for the transfer of the records,
and were willing, if Friends thought best, that one or two names be added!

The Yearly Meeting`'s committee again said, that from what they had seen and heard,
they were induced to believe that a separation was contemplated
on the part of South Kingston Monthly Meeting,
in which event they said it was very important that the Society should have its records,
and gave this as a reason for advising the former clerk to retain them.
Regret was expressed by the meeting that the committee should again allude to that subject,
and they were reminded of the great inconsistency and impropriety of such course;
professing to be laboring to restore unity and at the same time talking about a separation.

The committee in the case of John Wilbur,
stated that they were not prepared to report at present.
One of the Yearly Meeting`'s committee made inquiry
whether no part of the committee were ready;
upon which one of the committee stated, that two of them had a report in readiness.
The Yearly Meeting`'s committee advocated the reading
of this report of two out of a committee of nine,
but the meeting decided against it.
The seven members of the committee who did not sign
this report had never had an opportunity to see it,
this introduction of it to the meeting being their first knowledge of it.

Near the close of this meeting,
that member of the committee who said two of them had a report in readiness,
proposed that those in unity with the Yearly Meeting,
and the Yearly Meeting`'s committee and their doings,
be requested to stop in the house a short time, at the close of the meeting.
With this, the former clerk united, and wished the same request made of the women.
The Yearly Meeting`'s committee encouraged and approbated this proposal,
but the meeting generally objected to it,
on the ground that it appeared to be a scheme for a separation,
which it was hoped would not receive any encouragement,
and objected to this test of unity with them, as an improper one,
fully expressing unity with the doctrines of the Society, as held by the early Friends,
choosing rather to commit themselves to principles than to men.

The Yearly Meeting`'s committee made no charge of unsoundness against any;
but one of them said that a man might be entirely sound in doctrine,
and yet be very far from being in unity with the Yearly Meeting.
The judgment of the meeting was acquiesced in by him who made the proposition
upon a suggestion of a member of the Yearly Meeting`'s committee,
and the subject was passed from.

This was the condition of things relative to South Kingston Monthly
Meeting at the time of the Quarterly Meeting in the eighth month,
when the Yearly Meeting`'s committee reported it in a state of disunity,
disorder and insubordination;
and a Quarterly Meeting`'s committee was appointed
to unite with them in visiting that Monthly Meeting,
while the case of John Wilbur,
about which the Yearly Meeting`'s committee had manifested such extreme anxiety,
was still in the hands of the committee of the Monthly Meeting, who had not yet reported.

At the Monthly Meeting in the eighth month, several of the Yearly Meeting`'s committee,
and all the committee of the men`'s Quarterly Meeting attended,
and claimed that the Quarterly Meetings committee were incorporated with the meeting,
having a right to act as members, and to advise and assist the Monthly Meeting,
and that the meeting was bound to act according to their advice,
even to the abrogation of its recorded acts for months past.

The Monthly Meeting did not allow this claim;
it expressed its willingness to hear and consider
whatever advice the committee might offer,
and give it all proper weight, but claimed the right to exercise,
its own final judgment as to adopting it;
acknowledging itself responsible to the Quarterly and Yearly
Meetings in the manner and form prescribed by the discipline,
for any breach of the discipline and order of the Society.

Seven of the committee in the case of J. W. made the following report:--

[.embedded-content-document]
--

[.letter-heading]
To South Kingston Monthly Meeting of Friends, to be held at Hopkinton,
the 22nd of 8th mo., 1842.

The committee appointed by South Kingston Monthly Meeting to treat with John Wilbur,
on account of the complaint brought against him by the Yearly Meeting`'s committee,
have attended to that service;
having given notice to the parties of the time and place of our meeting,
John Wilbur and several of the Yearly Meeting`'s committee attended
and were heard upon the several matters contained in said complaint,

Upon a full and deliberate investigation of the case,
our judgment is that the charges against John Wilbur, have not been sustained,
but that his defence is sufficient to exonerate him from the same;
it appearing from the evidence brought before us,
that the complaint originated on account of John Wilbur`'s
labors under an apprehension of his religious duty,
and in conformity with our Christian discipline,
against the introduction into our Society of defective principles and doctrines,
and for the preservation of those ancient testimonies of Truth,
committed to us as a people.
We therefore recommend that the complaint against him be dismissed.

[.signed-section-context-close]
Hopkinton, 8th mo., 1842.

[.signed-section-signature]
Othniel Foster, William Nichols, John Foster, Isaac Collins, Joshua Gardner,
Jr. Samuel Sheffield, Charles Perry.

--

Two of the committee made a counter report.
The consideration of the first was then entered upon by the meeting;
and the Quarterly Meeting`'s committee advised against its adoption.

One of the Yearly Meeting`'s committee called for an explanation
of the causes which led that committee to leave,
before the investigation of the case of J. W. was concluded.
The clerk of the Monthly Meeting`'s committee then
read an extract from the committee`'s minutes,
giving their reasons for allowing him to go into
an investigation of doctrines in his defence.
These reasons were not attempted to be controverted or answered.
The meeting gave a very full expression in favor of receiving the report of the committee;
four fifths of the number of those who spoke in relation to it,
supporting it and at its final adoption only one member
of the Monthly Meeting spoke decidedly against it.

The meeting deliberated long upon the subject,
hearing all the committees had to say and when all discussions had ceased,
and the meeting had remained some time in silence,
the clerk made a minute accepting the report,
and it was sent to the women`'s meeting for their consideration.
The Quarterly Meeting`'s committee united with the Yearly Meeting`'s committee
in advising the former clerk to retain the records of the Monthly Meeting.
Before the report was returned by the women,
an attempt was made by two of the Yearly Meeting`'s committee,
sitting at the head of the meeting, to break it up, but it was not successful;
and the report was united with by the women`'s meeting.

At the Monthly Meeting in the ninth month a committee
was appointed to labor with Timothy C. Collins,
the former clerk, on account of his withholding from the Monthly Meeting its records,
and the committee had an opportunity with him on that account;
after the opportunity was ended,
he informed one of the committee that he had delivered
our records over to the Quarterly Meeting`'s committee,
who had given him a receipt for them,
and taken them away out of the limits of our Monthly Meeting!
Thus, by this bold depredation upon our property,
effectually depriving our members of the right secured to
them by the discipline of having access to our records.

At the Monthly Meeting in the 10th month,
four of the Quarterly Meeting`'s committee attended and
presented the following written advice to the Monthly Meeting.

[.embedded-content-document]
--

The committee appointed by the Quarterly Meeting to visit South Kingston Monthly Meeting,
and for other services,
as will appear by the minute of the Quarterly Meeting herewith presented,
now believe it right to state to South Kingston Monthly Meeting,
that having taken into our deliberate consideration,
the proceedings of that meeting in the 8th month last,
and other previous proceedings connected with it,
which have had the effect to produce the present
unhappy differences existing in that meeting,
and the state of insubordination in which it now is,--have come
to the conclusion that the placing of Samuel Sheffield at the table,
to act as clerk in the 5th month last,
in the irregular and disorderly manner in which it was effected,
and by which procedure the feelings and views of many of the members were wholly disregarded;
and being satisfied that he took his seat at the table,
and made the minute appointing himself out of the usual and long
established order of said meeting in appointing their clerk,
we did therefore unite with the advice previously given to Timothy C. Collins,
by the Yearly Meeting`'s committee,
that he should continue for the present to retain the records of that meeting.

And as this committee were also fully united in the advice
given in the 8th month last to South Kingston Monthly Meeting,
not to accept the report presented by that portion of the committee,
five of whom were added (contrary to the general usage of
our Society,) to the committee appointed in the 4th month,
to have charge of the case,
after Samuel Sheffield took his seat at the table in the 5th month,
and as we have cause to apprehend from the manner in which they were selected,
and from their relationship to the individual under care,
it was with a view to prevent an impartial exercise of our Christian discipline.

We, therefore, now on behalf of the Quarterly Meeting,
advise South Kingston Monthly Meeting at this time,
to remove Samuel Sheffield from acting as clerk,
and to reappoint Timothy C. Collins to the service,
to dismiss the case of Timothy C. Collins from their records,
and discharge the committee appointed last month to visit him as an offender
for retaining the records of said meeting as advised to do by this committee,
and likewise that the decision in the 8th month last,
as entered on their minutes in relation to John Wilbur,
against the judgment of concerned Friends of that
meeting and against the united advice of this committee,
be now set aside and be made void and of no effect.

Signed by the committee appointed by Rhode Island Quarterly Meeting
to visit South Kingston Monthly Meeting and advise it on its behalf.

[.signed-section-signature]
Asa Sherman, Beriah Collins, Joseph Metcalf, Arnold Congdon.

[.signed-section-context-close]
Members of the committee present.
Hopkinton, 10th mo., 24th, 1842.

--

The advice having been twice read, and embracing matters of great moment,
and wholly unprecedented, involving not only the rights of individuals, but of meetings,
it was proposed to refer it another month for consideration.
This document being dated at Hopkinton, the same day,
those present were asked if the whole of the committee were consulted in those advices;
they answered in the negative.
On inquiry of the committee,
whether they intended to ask the meeting to act upon it without time for deliberation,
one of them replied he thought it reasonable that
the meeting should have time to consider of it.
But afterwards the committee, and a few members of the Monthly Meeting,
advocated the immediate compliance of the meeting.
The subject was, however, referred for further consideration to the next month.

At the Quarterly Meeting held at Somerset, 3rd of 11th month, 1842,
the committee appointed at the last Quarterly Meeting,
to visit South Kingston and Swanzey Monthly Meetings,
reported that they had visited Swanzey Monthly Meeting,
and extended such advice as appeared necessary;
that they had also visited South Kingston Monthly Meeting in the eighth
month and given their advice in relation to the business of that meeting,
which was disregarded, they continuing to manifest a spirit of insubordination, etc.,
having appointed a committee to deal with their former clerk,
for complying with the advice of the Quarterly and Yearly
Meeting`'s committees in retaining the records of that meeting;
that they had also again visited them in the tenth month and given them advice in writing,
(here reciting their advice to the Monthly Meeting,)
which advice was not accepted by the meeting,
but they referred the consideration of it another month.

In conclusion, they gave it as their united judgment,
(as near as recollected) that South Kingston Monthly Meeting was not in a suitable state
to transact business as a Monthly Meeting in conformity with our Christian discipline,
and to the furtherance of the best interests of Society,
and therefore recommended that that Monthly Meeting be dissolved,
and the members of it joined to Greenwich Monthly Meeting.
The reading of the discipline under the head of Quarterly Meetings
was called for by a member of South Kingston Monthly Meeting,
and urged by many Friends, and for a considerable time refused,
during which time several united with the report.

At length after much importunity the discipline was read,
and it having been shown that the adoption of the
report would be a direct violation of it,
some of the Yearly Meeting`'s committee said a wrong construction was put upon the discipline,
but did not attempt to point out in what particulars.

Many Friends spoke against the adoption of the report,
insomuch that the meeting appeared nearly equally divided;
but a disposition being plainly manifested to adopt the report,
some of the members of South Kingston Monthly Meeting strongly remonstrated
against the summary dissolution of that meeting and joining it to another,
as a violation of the plain provisions of the discipline,
and asked for an opportunity to be heard before a committee, or in some other mode,
before the Quarterly Meeting should proceed to this extremity.
This was denied.
It was then stated on the part of South Kingston Monthly Meeting,
that if no other opportunity was to be afforded they should now
be obliged to make a statement of the proceedings of the Yearly
and Quarterly Meeting`'s committees in that Monthly Meeting,
for the information of the Quarterly Meeting before
it should act in so important a case.

Such opportunity being denied,
one of the representatives from South Kingston Monthly Meeting rose to read such statements;
when he was peremptorily directed by the clerk to "`take
his seat and put up his paper,`" but he continued to stand,
and amidst great interruption, to plead for the privilege and the right to be heard.
The clerk, however, who was himself an active member of the Yearly Meeting`'s committee,
read the minute dissolving the Monthly Meeting.

By the provisions of the minute, South Kingston Monthly Meeting is dissolved,
and the members thereof annexed to Greenwich Monthly Meeting.
It provides that the books be delivered to some person to
be appointed by Greenwich Monthly Meeting to receive them,
and that all unfinished business be closed by that Monthly Meeting.
It declares null and void the appointment of the addition to the committee,
in the fifth month, in the case of John Wilbur,
and the adoption of the report in his case;
also all that has been done in the case of Timothy C. Collins.
It continues the same committee,
with instructions to visit South Kingston Monthly Meeting, next to be held at Hopkinton,
and there to read to that meeting this minute of the Quarterly Meeting,
and advise those assembled quietly to separate,
and hereafter to consider themselves members of Greenwich Monthly Meeting,
and under its care;
and the committee is authorized and directed to extend
its care over all the Monthly Meetings in the Quarter.

At the Monthly Meeting held at Hopkinton on the 21st of 11th month, 1842,
several of the Quarterly Meeting`'s committee attended,
and read the minute of the Quarterly Meeting, dissolving South Kingston Monthly Meeting,
both in the men`'s and women`'s meetings,
and advised the members in the language of that minute, "`quietly to separate,
and consider themselves members of Greenwich Monthly Meeting,
and under its care;`" whereupon they withdrew,
and eleven members of each meeting with them.
Before they left,
application was made to them on behalf of South Kingston Monthly Meeting,
for a copy of the minute of the Quarterly Meeting, but they declined giving one.

The Monthly Meeting continued together,
and concluded to appeal to the next Yearly Meeting,
against the decision of the Quarterly Meeting; and then,
notwithstanding the injustice and irregularity of the requirement,
it was concluded to suspend the Monthly Meeting,
until the Yearly Meeting shall have acted on the appeal.

At Greenwich Monthly Meeting, held at East Greenwich, 2nd of 1st month, 1843,
two members of the Yearly Meeting`'s committee,
and one of the Quarterly Meeting`'s committee,
besides those belonging to Greenwich Monthly Meeting, attended.
One of the Yearly Meeting`'s committee requested that the minute
of the Quarterly Meeting dissolving the Monthly Meeting be read,
which was done.
He then said it would be seen by this minute that the appointment of a part of the committee,
and the report of the committee in the case of John Wilbur, were annulled,
and that it now became the duty of the committee originally appointed,
to report to this meeting.

One of the two of that committee who made the counter report in the eighth month,
inquired if it would not be proper for them to have another interview with John Wilbur,
and this was concluded on.
Objection was made to this proceeding,
on the ground that South Kingston Monthly Meeting
had appealed from the decision of the Quarterly Meeting;
that the action against that meeting was solely in
consequence of its decision in the case of John Wilbur;
that case was specified and fully brought to view,
in the Quarterly Meeting`'s committee`'s advice and the Quarterly Meeting`'s minute,
and the appeal ought to stay all proceedings in the case,
until the Yearly Meeting should decide it.

This just and reasonable ground was not allowed,
but a member of the Yearly Meeting`'s committee,
who had from the first been very active in the case,
said that the appeal and this case were distinct matters.
Another member of the same committee urged,
that if that Monthly Meeting intended to be subordinate to superior meetings, it must,
as the Quarterly Meeting had directed,
close the unfinished business of South Kingston Monthly Meeting,
and this case was particularly mentioned and brought
before them by the Quarterly Meeting`'s minute.
It had annulled the proceedings of South Kingston Monthly Meeting in the case.

It was replied, that South Kingston Monthly Meeting had appealed against all this,
and that it would only be proper for the Monthly Meeting
to carry out the direction of the Quarterly Meeting,
after the Yearly Meeting had decided that the Quarterly Meeting had done right.
A minute was made directing the committee in the
case of J. W. to report at a future meeting.

At Greenwich Monthly Meeting, held at Coventry, 30th of 1st month, 1843,
three members of the Yearly Meeting`'s committee attended,
besides those belonging to that meeting.
The case of John Wilbur was taken up,
and one of the committee appointed in the fourth month by South Kingston Monthly Meeting,
stated that two of them had met, having given notice of the meeting to the others,
and also to John Wilbur, that the latter might be present,^
footnote:[This was incorrect; he was not asked to be present, but merely notified,
by letter, of the time of their meeting,
and informed that he might send in an acknowledgment, if so disposed.]
if he saw fit, and make an acknowledgement; but he refused to attend.
These two members of the committee now made the following report, to wit:--

[.embedded-content-document]
--

We, of the committee appointed in the 4th month last, in the case of John Wilbur report:
that we have attended to the duties assigned us by
meeting John Wilbur and the Yearly Meeting`'s committee,
and hearing the evidence in the case,
and which was in our judgment sufficient to substantiate
all the charges preferred against him,
and which charges,
having relation altogether to his departure from discipline and good order,
it was evident to us his defence ought to be predicated on that ground alone.
And whereas the other part of the Monthly Meeting`'s committee,
were willing to allow him to make his defence, by leaving this only legitimate ground,
and go into a justification of his conduct by allusions to doctrines,
and which in our view was entirely foreign to the subject-matter under consideration; we,
therefore, felt ourselves bound to dissent from such a course.
And it is our united sense and judgment that he is not in a situation and state of mind,
to be continued a member of our religious Society,
which we submit to the Monthly Meeting.

[.signed-section-signature]
William S. Perry, Hezekiah Babcock.

[.signed-section-context-close]
South Kingston, 1th mo.
23rd, 1842.

--

This report was the same as that presented by the same persons,
to South Kingston Monthly Meeting in the eighth month.

The meeting being now about to act upon the report,
it was stated that the Complaint against J. W. had never been read in that Monthly
Meeting! and upon inquiry it was found that it was not now present in the meeting.
The clerk sent a messenger for it,
and the meeting suspended further proceedings in the case, until his return.
When the complaint was brought in, it was read,
and the report of the committee was then united with by most or all the
members of the Yearly and Quarterly Meeting`'s committees present,
and but two others.
Objection was made to the report by several Friends, but the clerk,
an active member of the Yearly Meeting`'s committee, made a minute adopting it,
and John Wilbur was in this irregular and disorderly manner disowned.

At Rhode Island Quarterly Meeting held at Providence, in the 2nd month, 1843,
one of the committee of South Kingston Monthly Meeting on their appeal,
laid a copy of the appeal on the clerk`'s table in the early part of the meeting,
and after a time the clerk stated that there was a paper on the table
purporting to be an appeal from South Kingston Monthly Meeting,
and asked for the direction of the meeting, as to what disposition should be made of it.
It was proposed to appoint some Friends to take it and examine it,
and report whether it should be read.

The reading of the discipline relating to such appeals was called for,
but the committee was first appointed,
and after they had taken the appeal out for examination,
considerable profession was made of willingness to have the discipline read,
and it was then done.
Shortly after, the committee returned the appeal, and recommended that it be read;
which being done, the clerk said Friends would observe,
that there was the name of a Friend on the committee of the Monthly Meeting on the appeal,
who had been placed under dealing by the action of the Quarterly Meeting.
He said the meeting would decide whether they would allow that name to stand there,
in case the appeal should go on their minutes.

After considerable discussion,
in which the injustice and incompatibility with the discipline,
of the act of the Quarterly Meeting was shown,
the clerk made a minute stating in substance,
that although the appeal contained the name of a Friend
placed under dealing by the action of the Quarterly Meeting,
we have concluded to enter it upon our minutes,
and send it up to our next Yearly Meeting.
One of the Yearly Meeting`'s committee corrected the clerk as to the latter clause,
saying that the conclusion of the meeting was,
to refer the consideration of it until next Quarter, whereupon he made that alteration.
The same member of that committee proposed that the word "`individual`"
should be substituted for "`Friend,`" and the clerk at once made the change.

While the appeal was in the hands of the committee,
a member of South Kingston Monthly Meeting,
(one of the committee on the appeal,) stated that
at the time that Monthly Meeting was dissolved,
a request was made of the Quarterly Meeting`'s committee, then present,
for a copy of the minute authorizing the dissolution, but it was refused;
that since then application has been made to the
clerk of the Quarterly Meeting for a copy,
who also refused it, on the ground that he was not authorized to give it,
without the authority of that meeting.
He now requested of the meeting, on behalf of the committee on the appeal,
a copy of that minute.

A member of the Yearly Meeting`'s committee said
that the meeting had not come to any conclusion,
as to the disposition of the appeal;
he thought it proper to wait until that was decided on,
and then the subject might be taken up.
The Friend who made the request, expressed his satisfaction with that course.
Afterwards, when the appeal had been referred to the next Quarter,
the clerk being about to proceed to other business,
application was renewed on behalf of South Kingston Monthly Meeting,
for a copy of the Quarterly Meeting`'s minute, but it was refused;
a member of the Yearly Meeting`'s committee saying;
that he thought it improper to give a copy! that it would be sufficient
for them to furnish the Yearly Meeting with a copy! and this being
sustained by other members of the same committee,
the meeting proceeded with other business;
thus denying South Kingston Monthly Meeting a copy
of the document by which it had been dissolved,
containing matters of the greatest importance relative to its case.

At the Quarterly Meeting held at Greenwich in the 5th month, 1843,
the account from Greenwich Monthly Meeting informed,
that John Wilbur having given them notice of his intention
to appeal from their judgment disowning him,
they had appointed a committee to represent the case
before a committee of the Quarterly Meeting.
It was stated on behalf of John Wilbur,
that he did not intend to prosecute his appeal at that time.
Representatives were appointed to attend the Yearly Meeting,
one of whom asked to be excused, which being done, another was named in his place,
but being obnoxious to those in authority, his name was rejected,
upon the pretence that there were already enough appointed.

The minute of the last meeting,
relating to the appeal of South Kingston Monthly Meeting was read.
A member of the Yearly Meeting`'s committee spoke of the great strait he was in,
on account of the name of an individual, standing as one of the committee on the appeal,
who had been placed under dealing by the action of the Quarterly Meeting;
and said he did not see how the appeal could be carried forward in its present shape.
Another member of the Yearly Meeting`'s committee expressed himself in a similar manner.

A Friend remarked if this was the case,
Greenwich Monthly Meeting might have disowned all the members of the appeal committee,
and thus have defeated it altogether.
Another Friend said he thought the minute of the Quarterly
Meeting carried its own condemnation on the face of it,
stating as it did that an individual was placed under dealing by the Quarterly Meeting;
he knew no discipline to warrant such a thing.

The clerk said he was ready to propose that this appeal should be again referred!
A Friend from South Kingston said the appeal was made to the next Yearly Meeting,
and to refer it again would defeat it.
It was now concluded to appoint a committee to represent the case at the Yearly Meeting,
premising that none should be appointed,
who did not unite with the proceedings in laying the Monthly Meeting down.
The committee on the appeal of South Kingston Monthly Meeting,
made application in writing for access to the record; of the Quarterly Meeting,
with a view to the timely preparation of the case; referring to the discipline,
"`that our records shall be open to any of our meetings, particular members,
and to such others as the respective Monthly Meetings may think necessary,
for the ascertaining of marriages, births, or other rights.`"
Page 43.

This request, after considerable discussion, was refused,
and much severity of expression was indulged in towards the applicants;
after which a member of South Kingston Monthly Meeting rose,
and very calmly commenced speaking,
when a large number of persons in the body of the
meeting rose and hurried out of the house,
those at the head of the meeting shook hands,
and it broke up in the greatest confusion and disorder.
The voice of the person speaking was entirely drowned by the noise,
and perceiving the meeting really breaking up, he desisted.

[.blurb]
=== At New England Yearly Meeting, held on Rhode Island. 6th month, 1843.

It appeared from the account of Rhode Island Quarterly Meeting,
that a portion of Greenwich Monthly Meeting,
late members of South Kingston Monthly Meeting,
had appealed from their judgment dissolving said
Monthly Meeting and annexing the same to Greenwich,
and that they had appointed Perez Peck and others to represent the Quarterly Meeting
before a committee of the Yearly Meeting to be appointed to hear the appeal.
When this case came up, the clerk read the discipline relating to such appeal,
and remarked that it had been customary in cases of appeal to appoint
a committee of two Friends from each Quarterly Meeting,
but proposed in this case the appointment of three from each Quarter,
which was united with.

On behalf of South Kingston Monthly Meeting a desire was
expressed to have the case tried in open Yearly Meeting,
for the full information of the members generally before acting thereon,
and referring to the practice of London Yearly Meeting,
in important cases--where doctrines are involved.
This was objected to on the ground that we must be governed by our own discipline;
and that the usual mode of trying appeal cases should be adhered to.

The clerk said that in cases of defamation,
the discipline gave the person complained of the
right to object to those named for a committee,
provided such objection does not extend to the major part thereof,
but there was no discipline which would apply to cases of this kind.
He said, however,
that the usage of Society had been to allow appellants this privilege in other cases,
so far as he knew.
He proposed to read from the discipline of another Yearly Meeting;
but objection being made on the ground that the Yearly Meeting
had already decided that we must be governed by our own discipline,
he did not read it.

A Friend said if he was correctly informed,
there was a large committee of the Yearly Meeting which had been active in this case,
having repeatedly attended South Kingston Monthly Meeting,
and advised in relation to the proceedings which had taken place in regard to that meeting;
and if so, he thought it improper to appoint members of that committee, on this appeal.
The clerk replied it might not be proper to appoint those of that committee who
had attended South Kingston Monthly Meeting and been active in the case.
Objection was made on behalf of South Kingston Monthly Meeting to the
appointment of any portion of the Yearly Meeting`'s committee,
and allowing them to nominate for this committee.

The clerk proceeded to take names, and having obtained the requisite number,
inquiry was made whether any of the Yearly Meeting`'s committee was included among them.
The clerk replied there was one; that one asked to be excused, which being done,
another Friend was appointed in his place.
It was also stated that several members of the committee
bad been named by members of the Yearly Meeting`'s committee,
and objection was made to these.
A member of the Yearly Meeting`'s committee said, if these Friends were objected to,
it would not probably stop there; that objection would be made on the other side, etc.
The committee was allowed to stand without further alteration.

A Friend from Sandwich Quarterly Meeting said,
it appeared evident to him from the discipline, as read by the clerk,
that the Quarterly Meeting had departed from it,
in annexing South Kingston Monthly Meeting to another,
while at the same time the Monthly Meeting has appealed against the dissolution.
If he understood it right,
the discipline only allows such annexation in case the Monthly Meeting refuses to appeal.
He requested the clerk again to read that paragraph giving this right of annexation.
The assistant clerk then read the succeeding paragraph.
The Friend said this was not the one, but the preceding one he wished read.

The whole passage was then read; when done,
the Friend said it was very clear that the discipline had not been kept to,
for the Monthly Meeting not only had not refused to appeal,
but the Quarterly Meeting had given us information that it had actually appealed.

[.embedded-content-document]
--

[.centered]
Discipline,

[.centered]
Authorizing the dissolution of Monthly Meetings, etc.

[.centered]
(From Book of Discipline, pages 118, 119.)

When a Quarterly Meeting hath come to a judgment respecting any difference,
relative to any Monthly Meeting belonging to them,
and notified the same in writing to such Monthly Meeting,
the said Monthly Meeting ought to submit to the judgment of the Quarterly Meeting;
but if such Monthly Meeting shall not be satisfied therewith,
then the Monthly Meeting may appeal to the Yearly Meeting,
against the judgment and determination of the Quarterly Meeting.

And if a Monthly Meeting shall refuse to take the advice
and submit to the judgment of the Quarterly Meeting,
and notwithstanding will not appeal against the determination
of the said meeting to the Yearly Meeting;
in such case the Quarterly Meeting shall be at liberty
either to dissolve such Monthly Meeting,
or bring the affair before the next or succeeding Yearly Meeting.

And in case a Quarterly Meeting shall dissolve a Monthly Meeting,
the dissolved Monthly Meeting or any part thereof, in the name of the said meeting,
shall be at liberty to appeal to the next or succeeding Yearly Meeting,
against such dissolution; but if the dissolved Monthly Meeting,
or a part thereof in its behalf, shall not appeal to the Yearly Meeting,
the Quarterly Meeting shall join the members of the said late Monthly Meeting,
to such other Monthly Meeting as they may think most convenient; and until such time,^
footnote:[This portion of Discipline was transcribed from that of London Yearly Meeting,
and adopted here.
In the original the words "`until such junction`"
were used instead of "`until such time`"]
shall take care that no inconvenience doth thereby
ensue to the members of such dissolved meeting,
respecting any branch of our discipline.

And if any of the Monthly Meeting,
to which the Quarterly Meeting shall join the whole or a part of the late Monthly Meeting,
do think themselves aggrieved,
they shall be at liberty to appeal against the Quarterly Meeting to the Yearly Meeting,
and until such appeal is heard and determined,
the Friends added by the Quarterly Meeting to them, shall be deemed their members.
1743.

--

The clerk was requested to read the "`appeal,`" a copy of which was in his hands,
and several Friends expressed a wish to have it read,
when one of the Yearly Meeting`'s committee said, that by our discipline,
no paper could be read in our meetings not coming from an immediate correspondent,
unless first examined by a committee.
To this is was replied,
that the discipline made these appellants immediate
correspondents by giving the right of appeal;
and that the Yearly Meeting ought to know the grounds on which the appeal is made.

After considerable discussion it was decided not to read it.
At the last sitting of the Yearly Meeting the committee
of the appeal presented two reports;
the first,
that the judgment of Rhode Island Quarterly Meeting ought
to be confirmed which was signed by thirteen members.
The other, that the judgment of the Quarterly Meeting ought to be reversed,
because some of its proceedings were in violation of the discipline.
This latter report was signed by six members.

Two members of the committee did not sign either report.
The report of the majority was adopted.

At Rhode Island Quarterly Meeting, in the 8th month, 1843,
a committee of nine was appointed in the case of John Wilbur`'s appeal,
and an attempt was made to appoint members of the Yearly Meeting`'s committee.
This was opposed, on the ground that they had already prejudged the case,
and some of them, several times over.
It was relinquished;
but a proposition that none should be appointed who were
not in unity with "`the body,`" was adopted and acted upon.
The name of a Friend who had taken no active part in the case, was refused,
merely because he was known to disapprove of some
of the proceedings of the Quarterly Meeting.

On asking for J. W. the privilege of objecting to a part of the committee,
if he should desire it, agreeably to discipline, in case of detraction,
and a usage in all cases; one of the Yearly Meeting`'s committee took the ground,
that the complaint against J. W. was not for detraction;
that if the word detraction was in the complaint, it was incidental, and as to usage,
it was of no consequence;
the meeting could do as it pleased!! It was decided that
J+++.+++ W. could not be allowed to object to any of the committee,
unless the committee of Greenwich Monthly Meeting
were allowed to object to an equal number,
for which no provision is made in the discipline.
In the discussion of this question, as many opposed this decision as favored it;
and of the latter the Yearly and Quarterly Meeting`'s
committees were the principal actors.

John Wilbur being called in, plead for his right of objection,
both on ground of discipline and usage, but without effect, and finally said,
if this was the conclusion of the meeting he should
not attempt to exercise the right of objection,
as it would be of no value.
The committee appointed at this time, proposed to meet at Somerset, in the 11th month,
at which time J. W. attended,
when the committee informed him they had ascertained that one of
their number was named by a member of Greenwich Monthly Meeting,
which was not proper, and they could not consent to proceed on that account.
J+++.+++ Wilbur told them he came there +++[+++near fifty miles]
prepared to proceed, and was anxious to do so,
and that he would waive all objections on account of the irregularity named;
but they pressed the objection, and adjourned to meet at Providence in the 2nd month,
1844.

At the Quarterly Meeting in the 11th month, 1843,
it was stated that a member of the committee on the appeal of J. W.
had been improperly named by a member of Greenwich Monthly Meeting,
and the clerk suggested that the same Friend should
be named by one of his own Monthly Meeting,
which was done, and the committee stood as it did before.
This committee met at Providence previous to the
Quarterly Meeting held there in the second month,
and gave J. W. a hearing.

At that Quarterly Meeting six of the committee reported in favor
of confirming the judgment of Greenwich Monthly Meeting,
two signed a contrary report, and one was not present.
Both reports were read.
One of the Yearly Meeting`'s committee was the first
to unite with the report of the majority;
he was followed by two others, who were not only of the same committee,
but also of Greenwich Monthly Meeting! both very active in that
meeting in favor of J. W.`'s disownment! being also of the number
of those who visited South Kingston Monthly Meeting so constantly,
and who were before the committee of that meeting as prosecutors in the same case!

On being reminded of the impropriety of this proceeding,
another of the Yearly Meeting`'s committee immediately united,
and these four were all signers of the complaint against J. Wilbur!!
Others of the Yearly and Quarterly Meeting`'s committee followed,
and not more than three or four are believed to have united
with the majority report who were not of these committees.
Some united with the other report, but the first was decided by the clerk to be adopted,
and he made a minute to that effect.
It was inquired whether John Wilbur would be allowed to come in and hear the conclusion;
this inquiry being answered in the affirmative,
he was called in and the clerk read the report and the minute adopting it.

J+++.+++ W. informed the meeting that he considered their decision not a rightful one,
and that he wished to appeal to the Yearly Meeting against the judgment of this meeting.
He then left the house.
The appointment of a committee to represent the Quarter was referred to the next meeting.

At New England Yearly Meeting, held on Rhode Island, 6th month, 1844,
the account from Rhode Island Quarterly Meeting brought to view the appeal of
John Wilbur against the conclusion of that meeting confirming the judgment of
Greenwich Monthly Meeting disowning him.
A committee of twenty-one was appointed, to which the case was referred.
In the appointment of this committee,
the meeting decided that members of the standing committee of the Yearly Meeting,
who had heretofore been engaged in the case of J. W.,
and those Friends who constituted the committee appointed last year,
on the appeal of South Kingston Monthly Meeting,
(the two cases being nearly similar,) should be excluded.
It was further proposed that those who had openly expressed themselves
opposed to the proceedings of the Yearly Meeting should also be excluded.

The meeting decided in favor of the proposition, and when a name was offered,
supposed to be of the class alluded to therein, it was rejected.
The right was asked for the appellant to be present and object to a portion of the committee,
should he desire it, in conformity with the discipline and usages of the Society.
This gave rise to considerable discussion,
and views of an opposite character were expressed.
The meeting finally decided that the appellant might state his objections if he desired,
and the meeting would take them into consideration, and decide on their validity.

This was objected to on the ground that it would render the right of no value,
and that there was neither discipline nor usage for it.
The appellant was called into the meeting,
and the privilege of objecting proffered him under this restriction.
It was declined.
He requested to be allowed some one to assist him before the committee,
as from his age and infirmity it would be a hard
task for him to perform the necessary labor.
Many expressed themselves in favor of granting this request,
but the meeting decided against it!
The committee having completed the investigation,
reported in favor of confirming the judgment of the Quarterly Meeting;
one of their number declining to sign the report, which was adopted, by the meeting.

John Wilbur,
desiring to be present to hear the report of the
committee and conclusion of the meeting in his case,
was called in, and they were read in his hearing.
After sitting a short time in silence, he rose, and remarked in substance,
that however unjust he believed the decision to be,
yet he should entertain no hardness against any concerned in the proceedings against him;
that it was his desire that none of our members should depart
from the ancient principles and testimonies of the Society,
nor suffer any innovation upon them; these had been dear to him from his youth up,
and were still dear to him; he then withdrew.

[.offset]
+++[+++It will be apparent to the reader of the foregoing narrative that South
Kingston Monthly Meeting was laid down in a very extraordinary manner,
in violation of the plain provisions of the discipline;
and that it was done for the purpose of bringing John Wilbur
again within reach of the Yearly Meeting`'s committee,
in another Monthly Meeting which was entirely under their control.
His disownment there was only effected through the
direct action and influence of that committee,
in a summary and most irregular manner, in utter disregard of his rights as a member.
These proceedings, under the same pervading and desolating influence,
were confirmed on appeal to the superior meetings, in 1843 and 1844.

[.offset]
It may be proper here to show the manner in which these
sad perversions of right order were afterwards overruled,
and how those who were so unjustly cast out for their
faithful stand against innovation upon our principles,
were restored to their just position and station in the Society.
Near the close of the year 1844,
in the progress of the measures adopted by those supporting the new views,
to enforce a conformity to their rule,
they effected a separation (through the action of the Yearly Meeting`'s committee,
assisted by a committee from the Quarter,) in Swanzey Monthly Meeting,
which was speedily followed by further separations
throughout Rhode Island Quarterly Meeting,
of which that Monthly Meeting was a component part.

[.offset]
After these had taken place, the Quarterly Meeting, though much reduced in numbers,
was relieved of that unhallowed influence and rule which had so long prevailed therein;
and many members^
footnote:[Upwards of eighty.]
of the late South Kingston Monthly Meeting gave written information to the Quarter,
that they felt themselves aggrieved,
and the principles and Discipline of the Society to have been sorrowfully violated,
in the dissolution of the Monthly Meeting, and that they desired the restoration thereof,
believing it would "`contribute to the right vindication
and establishment of the primitive Christian doctrines,
discipline and order of our religious Society;`" which request was,
by the Quarterly Meeting, forwarded to the Yearly Meeting,
with the expression of its "`deliberate, united sense and judgment,
that the cause of Truth does require that the Yearly Meeting
should reverse its former decision in the case,
and restore South Kingston Monthly Meeting,
with the rights and privileges and obligations belonging to it,
and resting upon it prior to its dissolution.`"

[.offset]
John Wilbur also gave notice to Greenwich Monthly Meeting,
of his intention to appeal to the Yearly Meeting for a reconsideration of his case,
and a reversal of its judgment therein.
The Monthly Meeting united in requesting the Quarterly Meeting
to "`forward a minute to the Yearly Meeting respecting this case,
as one of unjust dealing, requiring its reconsideration,
and a reversal of its former decision;`" which was done by the Quarterly Meeting,
with an expression of its judgment "`that this case,
equally with that of South Kingston Monthly Meeting,
calls for the like action on the part of the Yearly Meeting.`"

[.offset]
These appeals came before the Yearly Meeting in 1845, after the separation;
and upon a full and thorough investigation,
the former judgment of the Yearly Meeting was in both cases reversed,
the Monthly Meeting reestablished,
and John Wilbur restored to his right of membership
and station of minister in our religious Society.]
