[short="Chapter VII"]
== Chapter VII. Visits in Pennsylvania, New Jersey, and New York, in 1852 and 1853, and Further Correspondence.

My account of the proceedings of New England Yearly Meeting and its committees,
from 1840 to 1845, recorded in a book entitled [.book-title]#A Narrative and Exposition, etc.,#
gives a plain statement of the trials and sufferings which I endured for that time,
from the hands of false brethren,
because of my conscientiously bearing testimony against the unsound
doctrines that were written by members of the Society in England,
and allowed by Friends there to be spread largely throughout all our settlements,
both in Europe and in America;
by which means this people seem to be rapidly approximating
towards an apostasy from their first principles;
but it is hoped and believed that a few will be spared for the upholding of the same
blessed faith and doctrines of pure Christianity which were received and promulgated,
through the faithfulness of a very few, at first, two centuries ago.

Since the separation in New England Yearly Meeting, which occurred in 1845,
and of which ample accounts have been published,
I have been much of the time engaged in visiting all the Quarterly and Monthly Meetings,
as well as the particular meetings of those Friends, in their different allotments,
who were favored, through great mercy, to withstand the torrent of unsound doctrine;
some of them I have attended many times over, laboring, in the ability afforded,
for the furtherance and establishment of their minds
in the true profession of primitive Christianity,
and in standing fast in the faith, testimonies, and practices thereof,
as did our worthy predecessors.
I have, also, during these six years,
held many meetings among people of other denominations,
in different parts of New England,
in which service I was favored to witness the good Shepherd to go before,
and his helping hand to be extended,
for the upholding of his testimonies among the people.

During the year 1851,
I felt drawings in my mind towards Friends of Philadelphia Yearly Meeting,
and this concern in gospel love had so matured,
that it appeared best to lay it before Friends at our Monthly Meeting, in the first mo.,
1852, when I obtained their certificate of concurrence,
in order for religious service in some parts of Pennsylvania and New Jersey,
and this certificate was indorsed by Rhode Island Quarterly Meeting,
held in the second month following.
For the accomplishment of this service I left home on second day, the 23rd,
and went that night to New York, where, next morning,
I met with my dear friend William Hill, who has kindly given up to accompany me,
and assist in the performance of this service.

We took the cars at Jersey City,
and went to Trenton where some Friends from Pennsylvania met us,
and we went together to the house of our dear friend Sarah Healy,
and soon after dinner set out for Buckingham with her,
and our friend Benjamin Cadwallader.
We lodged that night at the late dwelling of Ruth Ely, with three of her grandchildren.
Next day attended the Select Quarterly Meeting,
and on fifth day the public Quarterly Meeting, which was, as I trust, a time of favor.
I was largely opened on the passage, "`Blow ye the trumpet in Zion,
proclaim a fast,`" etc.
My certificates were readily received in both the men`'s and women`'s meetings.

The work before us looks formidable, and our steppings along perilous,
so that an entire trust in the Divine guidance and strength is, above all things,
to be desired.
It seems likely that this service may be the hardest of this kind
that I have met with in the course of my pilgrimage in time;
but I recur to the consideration that he who putteth forth can control the wrath of man,
and make hard things easy; therefore I desire to trust in him.
On sixth and seventh days we made some social visits to the families of Friends.
On first day morning we went to the meeting at Falsington, which was large,
and I was considerably opened in gospel authority among them, greatly to the relief,
peace, and comfort of my own mind, and, as it appeared,
to the satisfaction of Friends present,
many of whom went with us to Middletown in the afternoon;
but this was rather a laborious meeting, made up of Friends, Gurneyites,
Hicksites and Methodists;
yet I labored with this mixed multitude for some length of time, after long silence,
but not to the obtaining of so much satisfaction as in the morning.

From hence we went home with our dear friend George W. Brown, and lodged.
On second day morning he went with us to Philadelphia.
A short time after our arrival, a prominent Friend residing in the city,
with whom I had some previous acquaintance called to see us, and,
after the usual salutation,
referred to the reading of my certificate at Bucks Quarterly Meeting,
and also to the appointing of a meeting for me at Middletown,
and spoke of it as a violation of the conclusion
of the Yearly Meeting of Ministers and Elders,
and as an act of insubordination in the Friends of that Quarterly Meeting.
I told him, "`that there were probably different opinions on that subject;
that Philadelphia Yearly Meeting undoubtedly had a right to manage their own concerns,
but that I hardly thought it best for us to go into a discussion of the subject at this
time,`"--thinking it too soon on coming into the city to take up such a subject as this.
He did not say that I must not appoint any meetings, or offer my certificate;
but I supposed he meant it.

On third day we were at the North Meeting, in which I had good service;
and I have no doubt it was to the satisfaction of the sound Friends,
and to the stopping of the mouths of the gainsayers.
David, at a certain time, desired the Lord to "`show him a token for good,
that his enemies might see it and be ashamed.`"
Though not asked by me, I trust I have, in some degree,
realized such favor here in this city,
where there are many enemies to primitive Quakerism.

On fourth day we went to Orange Street Meeting, through which I sat in profound silence,
no spring of the gospel arising.
Dined at William Evans`'s, and next day attended Arch Street Meeting,
in which I had open service in declaring the Truth.
On sixth day morning, the 5th of 3rd mo.,
I wrote a note to the Friend who first met me in the city,
testifying against my being recognized as a minister with a certificate,
desiring him to give me his objections, in writing, against my being so accredited,
in order that by having such objections at once before me,
I might seriously consider the import of them.

After this we set out for New Jersey, and went over the ferry to Moorestown,
to our dear friends Ebenezer and Rachel Roberts.
A number of Friends came there for the purpose of welcoming us to this land,
and it was indeed comforting and strengthening to us to meet with these dear fellow-sufferers,
and to commune with them in the precious fellowship of the gospel.
We went this afternoon to the house of our dear friend Josiah R. Reeve, at Medford,
and it was very comfortable to us to lodge several nights under his roof.
The next day after coming here we attended Upper Evesham Monthly Meeting,
in which my good Master gave me such an opening as he had never given me before.

It was concerning the destroying angel passing over the land of Egypt,
and the assurance that all who abode not in their
tents should perish of the devouring pestilence.
The Lord is thy tent, O Jacob, and thy tabernacle,
O Israel!--the only safe abidance whilst the destroying
angel is now passing over our Israel.
But, truly, there are, among the leaders of this large Monthly Meeting,
those who have eyes, but see not, and ears, but hear not, and are, apparently,
completely entangled by leading characters in the city,
and made to think that the Yearly Meeting has actually laid a prohibition upon all the
subordinate meetings not to read certificates from any one coming from New England,
as a minister, however well authorized by the great Head of the church he may be,
notwithstanding the notable decision of Philadelphia Yearly Meeting in 1849,
in regard to the separation in New England.

Nevertheless, many Friends did faithfully advocate the reading of my credentials;
but the clerk, who seemed to act uprightly, was obliged to pass over it.
I believe, however, that all who hesitated expressed full unity with me and my testimony.
One old Friend, who said the most against reading my certificates,
on the ground of the supposed prohibition of the Yearly Meeting,
came to me afterwards and expressed much unity with me,
saying they were in a bad condition about New England certificates!
On first day, the 7th, we went to Lower Evesham meeting, which was a highly favored time,
nor did I ever notice a more profound silence to prevail than after I took my seat,
or greater attention whilst I was speaking.
In the opening, these words forcibly impressed my mind,`" Thy will be done on earth,
as it is done in heaven;`" and in the course of my testimony,
it was shown to be the Lord`'s will that his church militant should be pure and holy,
like his church triumphant.

We spent the afternoon with our aged friend Hinchman Haines, at his own house,
and from thence went that night to Ebenezer Roberts`'s, to lodge.
On second day, the 8th, we went to Haddonfield Monthly Meeting--a dark time, indeed,
and the darkness was such as to be felt by us both, and very oppressive;
so much so that no public testimony could be borne there at that time.
But I told them in the Meeting for business that
I had a few lines from my friends at home,
setting forth their unity with me,
and their concurrence with my prospect of service in these parts, and, if desired,
it would be produced;
but two or three said the reception of it would be
contrary to the conclusion of the Yearly Meeting,
and so they passed immediately on with their business.

We attended their Monthly Meeting, at Moorestown,
on third day--an atmosphere very different to us from that
of the place we were at the day before (where,
however, there are undoubtedly some valuable Friends.) At Moorestown,
Truth rose into dominion in the public meeting,
and the presence of the Lord was felt to overshadow the assembly;
and although there were one or two, in the meeting for business,
who objected to the reading of my certificate,
so many voices called for it that the clerk felt his way entirely clear to read it,
and it was read in both the men`'s and women`'s meetings.
Next morning the Pennsylvania Friends, from whom it seemed hard parting,
left for home whilst we were about to leave for Haddonfield Quarterly Meeting.

In the Quarterly Meeting of Ministers and Elders I was silent,
but some preaching they had which was not very savory to me,
and the meeting was dull and painful rather than otherwise.
The public meeting next day, was, I believe,
the largest Quarterly Meeting that I ever attended in America,
and would have been a favored one, as I apprehend, but for a sad interruption.
When I was about to rise, with a clear opening, a minister arose,
and held forth a long time, and in a tiresome manner,
which so jostled the ark that I was ready to think, for a time,
that it would not be recovered; however, sitting quietly for some time,
my prospect again opened, and although the meeting had been long sitting,
I had some good service among them.
At the opening of the Meeting for business,
Hinchman Haines and Ebenezer Roberts both spoke so fully in our favor,
and of their confirmation that we from New England
belonged to a church of which Christ is the head,
that I felt easy not to offer my credentials,
having so recently offered them to their Monthly Meeting at this place.
After this meeting we returned to Philadelphia.

Sixth day, the 12th.--William Hill left me this morning to go home for a few days,
and during his absence I stayed awhile in the city,
and on this and the day following visited some friends and wrote to my friends at home.
On first day morning I attended Arch Street Meeting,
and was so mercifully favored in testimony as to bring great peace of mind,
and had the acknowledgment from dear W. H. Jr., of his unity therewith.
Afternoon, at the North Meeting, silent.
On second day morning, before leaving for Frankford,
I incidentally met with the Friend who met me on my arrival in the city,
and to whom I had since sent a note.
I now took occasion to say to him that I had been in expectation of a letter from him,
giving his reasons, in writing,
why a minister coining from us could not be recognized within Philadelphia Yearly Meeting.
He said that he had already given me the whole reason verbally, to wit:
that the Select Yearly Meeting came to the conclusion that no minister
coming from New England should be recognized until the question should
be decided which of the parties were the legitimate body of Friends;
he said he saw no way for any minister coming from
the "`smaller body "`to be recognized here,
or to be allowed to appoint meetings.
I told him it would be a great hardship to a minister coming here in the right authority,
to be obliged to be detained from one meeting day to another,
and not be allowed to appoint meetings.
He said he thought there was no help for it.
I asked him a few questions, and the interview ended, and I went to Frankford,
where I spent several days; attending their meeting,
writing to my valued friend Lydia A. Barclay, at Aberdeen,
and also to the Friend above alluded to;
the latter not to be forwarded until inspected by some solid Friends.

Meantime, I returned to the city, and went with several Friends out to Plymouth,
to see the widow of my dear deceased friend Ezra Comfort, whom I visited,
with a number of her children, and attended their little meeting on first day,
all to good satisfaction.
On the same evening I returned to the city, and, after due examination,
sent my letter to the Friend, as follows:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Frankford, 3rd mo., 17th, 1852.

[.salutation]
To My Dear Friend, +++_______+++ +++_______+++,

Not having contemplated going into the subject which thou introduced
to me on my arrival in Philadelphia on the 1st inst.,
I was not prepared for a discussion of it at that time; nor do I yet feel competent,
by any means, to speak of it in a manner commensurate with its importance; but,
inasmuch as it nearly relates to my present concern and religious service in these parts,
I did, on a little reflection, feel a desire to see thy view of the whole case,
stated at once on paper, including the ground of thine and others`' objections,
(if other there be,) to the recognition of sound ministers
from what is called the "`smaller body`" in New England.

Hence the occasion of my note to thee on the 5th, and of my saying to thee,
on our incidental meeting on second day last,
that I was in expectation of a letter from thee.
Now, should I have understood thee to say,
that thou had given me the whole ground of objection at the first interview, to wit,
the conclusion of your Yearly Meeting of Ministers and Elders,
and that it was therefore unnecessary to give it in writing?
And when I asked the question,
whether your Yearly Meeting of Ministers and Elders were authorized, by your discipline,
to dictate the proceedings of your subordinate meetings for discipline,
was I correct in understanding thee to say that it was not so authorized?
And further, when I asked thee if any prohibition was laid, or had been laid,
upon our ministers being countenanced in appointing meetings within your Yearly Meeting,
did I rightly understand thee to say there had been none?

And, did I correctly understand thee to say,
notwithstanding what thou had before stated (as the ground of objection),
that thou didst not see any way that we could be availed of our rights,
until we should be acknowledged by Philadelphia Yearly Meeting?
Again acknowledged?
And was this consequence considered in the decision of the Select Yearly Meeting?
And was there, or was there not, any future act of the Yearly Meeting,
alluded to at the time when such conclusion was come to?
And was there ever any record made of such conclusion,
or when its effects should terminate?
or any official account of it sent down to Quarterly or Monthly Meetings?
And should I not understand that such conclusion looked forward to such
time as when the Yearly Meeting should examine the New England case,
and decide the important question of right and wrong between the two bodies?

We, on the one part,
are well satisfied with the language of the "`Report`" adopted by your Yearly Meeting,
viz:
that "`Common justice and the cause of Truth demand that the claims of each should
be impartially examined,`" and "`that it becomes the duty of the Society,
under the guidance of Divine wisdom, to inquire into the circumstances of the case,
so that it may not withhold from those to whom they may belong the precious
rights and privileges which membership in our Society confers.`"
This I understand as a plain prelude and reference to their decision of the case,
an account of which decision immediately follows this extract from the
document containing the Report--see pages from 29 to 38--unnecessary,
and too long to be all quoted here; but which we understood to be,
and still understand to be, an able and clear, as well as candid,
decision of the case between those who had stood fast in
the support of the doctrines and discipline of the Society,
and those who had violated both;
setting forth which of the parties was entitled to
acknowledgement by Philadelphia Yearly Meeting,
and confirmed by a pertinent quotation from Robert Barclay.

But I feel as if it would be right to refer to a few items more,
in this remarkable summary of their decision.
Page 31 it says,
"`If consistent and exercised members are not to be allowed
to declare their dissent from unsound doctrines,
then farewell to the maintenance of any sound doctrine in the church of Christ.`"
"`This would be an inlet to the greatest innovations, and, in time,
might overturn the Society.`"
Again,
"`Although the manner in which this separation was effected was not such as we think
affords a precedent safe to be followed in the organization of a Yearly Meeting,
yet, inasmuch as those Friends which compose the smaller body,
appear to have acted from a sincere desire to maintain
the doctrines and discipline of the Society,
and the rights secured by it to all its members,
and had been subjected to proceedings oppressive in their character,
and in violation of the acknowledged principles of our church government,
we believe that they continue to be entitled to the rights of membership,
and to such acknowledgment by their brethren as may be necessary
for securing the enjoyment of those rights.`"

[.numbered-group]
====

[.numbered]
_First,_ then,
I might remark that the manner of this separation
was not contrived by any concert of our people,
but as way appeared to be made for it, by the hand of a gracious Providence,
for our deliverance; but, truly, as you say, "`it was the course pursued by them,
(the Gurneyites,) in these transactions, which led to a separation.`"
And, inasmuch as there never has been any rule laid down as a "`precedent`" to be followed
in a deliverance of those who serve the Lord from those who serve him not,
there have seldom any two cases, among all that have transpired, been alike,
but often very different; nor was the New England separation contemplated, on our part,
as an imitation of any other, or to be a precedent for any hereafter to adopt;
and we agree with you that it might, therefore, be unsafe to attempt to follow it,
in manner and form, in different cases.
Circumstances have been so different, from the earliest time,
in those cases where the Lord`'s people had lapsed into great error,
that we behold the variety of ways which he has devised for the deliverance
of those who feared him from those who were involved in error and darkness.

[.numbered]
_Second,_ "`that they continue to be entitled to the rights of membership,
and to such acknowledgment by their brethren as may be necessary
for securing the enjoyment of those rights.`"
This we understand not to have been said to those of the
"`larger body,`" whom both you and we have testified against,
but to those of the "`smaller body,`" that they continue
to be (as they had been) members of the Society,
and entitled to the rights of membership,
and to such acknowledgment by their brethren as may be necessary
for securing the enjoyment of those rights.

====

We understand that when this case was submitted to the Meeting for Sufferings,
it was for the purpose of so inquiring into the facts and
circumstances connected with the division in New England,
as that the Yearly Meeting might know how to decide understandingly
which body should be accredited as the legitimate body of Friends.
And was their report, so clearly awarding to each body its due,
received as satisfactory by the Yearly Meeting?
And, if their representation of the proceedings of the '``' smaller body`" is correct,
why not accredit the least and humblest of the Lord`'s messengers coming from thence,
if their example is good, and their ministry savory?

Now, in a view of what you have done of this sort, collectively and individually,
I should scarcely have thought,
(but for thy suggestions,) that there had been a man living, seeing it,
that would have charged anybody with insubordination to Philadelphia Yearly Meeting,
for recognizing the least member of the "`smaller body`" in New England,
in whatever capacity he may fairly stand.

Finally, my dear friend, should it fall to thy lot, as an arbiter,
to decide in a case between two parties, the one consisting of ten persons,
and the other of ten thousand, when thou had obtained a good understanding of it,
and found the lesser number to be right, and the larger to he wrong,
how long would thou be disposed to hesitate in the
awarding of justice to the smaller number,--and that,
without looking at consequences that might or might not follow?

[.signed-section-closing]
From thy friend,

[.signed-section-signature]
John Wilbur.

--

After writing the foregoing letter I felt easy to go forward,
and to propose the appointment of meetings when they did not come in course;
nor were we refused, at any place where we desired it;
and thereby were enabled to have a meeting every day,
until we returned from the country into the city again.

On second day, the 22nd of 3rd mo.,
I attended the funeral of my dear young friend Rebecca Brown, formerly Rebecca Kite,
a valuable young woman.
She was attacked with erysipelas in the face, and died in about one week`'s time.
I was silent at this funeral.
Next day I attended the Monthly Meeting for the northern district
and was mercifully helped to support the best of causes.
Elizabeth Pitfield followed me sweetly.
In the Meeting for business, I mentioned my having a few lines from my friends at home,
setting forth their unity with me, and approbation of my present engagements.
A lengthy discussion ensued; some objecting,
whilst others feelingly advocated the reading of my credentials,
but there was so much objection that it was passed over.
Some untrue statements were made by the Gurneyites,
as to what was in the "`Report,`" whereupon the document itself was offered by a Friend,
to prove those statements to be unfounded.

W+++.+++ Hill returned this afternoon; and on fourth day, the 24th, we left the city,
and the same day attended Whiteland Meeting, which was an open time, and after meeting,
dined with David Cope; he had been very sick, but was now recovering, and glad to see us,
and we, him.
He remarked that it was my lot, in the ordering of a good Providence,
to come amongst them, and said that all honest Friends would be truly glad of our coming,
and would be strengthened by it.
Samuel Cope met us here, and took us to his house at Bradford, where we stayed all night,
and next morning attended their mid-week meeting at West Chester.
Here I had pretty close, searching labor,
but some encouragement was offered to the faithful,
whilst those who are inclined to depart from our doctrine were feelingly warned;
and it seemed very trying to be embodied with such.

After this meeting we dined at Hannah Gibbons`'s, many other Friends being there with us.
From hence, Samuel Cope took us in his carriage to Westown School,
where I met with three of my grandchildren.
Next day we went to Goshen Meetings where "`mouth and wisdom`" were mercifully given.
Seventh day, 28th, had a meeting at Willistown, small and silent as to the ministry.
Samuel Cope met us, and took us to his own house that night, and next day,
1st of the week, we attended their meeting at Bradford,
where we found assembled a large number of people,
unto whom the testimony of Truth flowed forth freely, in the demonstration of the Spirit,
and not without the authority, as I trust; and peace and joy ensued.
But the glory belongeth unto Him who put forth and went before,
because without him no gospel can be preached.

After meeting we went home with our valued friend Moses Bailey,
who belongs to this meeting.
Visited a sick man, and his son and daughter, this afternoon--a pleasant season.
On second day we went twelve miles,
and had a meeting at West Caln at three o`'clock--this meeting was small,
and proved rather a laborious time; however, through honest labor, peace was our reward.
Next day we had another appointed meeting at East Caln, much larger,
in which I was much enlarged in testimony, to my relief and satisfaction.
Afternoon, we travelled ten miles to Aaron Sharpless`'s,
where I met with my dear friend and correspondent, Mary Kite,
and we were mutually glad to see each other.

This place is called Birmingham, where we attended their Monthly Meeting,
in which I had a living testimony to bear,
to the necessity of holding fast the profession of our faith, and to stand fast,
lest the enemy beguile us, and lure us from a firm standing on the Rock of Ages.
At this place we were met by our friend Isaac Hayes,
who took us to his house near Westown School, with whom we lodged.
Next day we attended their meeting at the school, consisting of more than two hundred,
pupils and others;
and truly I have seldom been so remarkably led and enlarged in such a meeting--an
interesting company--the whole family seemed very glad of our company and services.
On sixth day, 9th, we went to Concord Monthly Meeting and had pretty satisfactory labor;
dined at William Scattergood`'s, and returned at night, with Isaac Hayes.

On seventh day, 10th, our dear friends I. and R. H. went with us to Parkersville,
where we had an open good meeting; a large gathering,
towards whom the current of gospel love and life ran as a stream.
Dined at John Parker`'s, where our friend Morris Cope met us, and,
after visiting an aged Friend and family, guided us to his house at New Garden; where,
next day, being first day, 11th, we met with Friends and some others in the morning,
to pretty good satisfaction, and in the afternoon,
had an appointed meeting at Fallowfield, in which I was much enlarged,
and the gospel current ran freely.

After this, we arrived again in Philadelphia on the 12th, and on third day, the 13th,
attended the North Meeting, where I had a striking testimony to bear,
and John Wood being present, was exercised in supplication.
Next day, went to Orange Street Meeting, where we had an open time,
to my own great relief and peace of mind.
Here I met with my dear friend Robert Scotton.
Next day, at Arch Street I was silent.
My kind friend William Hilles took me to Germantown,
where I attended their mid-week meeting; a pretty open time,
although the meeting was smaller than usual, many being away.
From here we went to Byberry, where we attended their meeting, to good satisfaction,
and then returned to Philadelphia.

On seventh day, the 17th, I attended the Yearly Meeting of Ministers and Elders; and,
inasmuch as certificates which are not directed to Philadelphia
Yearly Meeting are not expected to be presented and read there,
I omitted to present mine, as advised by some judicious friends.
On first day morning at the North, and in the afternoon, at Arch Street Meeting,
I was raised up, in the authority of the everlasting gospel,
in bearing testimony to the Truth.
The forenoon, or first sitting of the Yearly Meeting was rendered very painful to me,
by the reading of epistles from all the Gurneyite Yearly Meetings in the world,
save that of New England, and all fraught with the most glowing language,
as it would seem,
that the ingenuity of man could well frame and bring together in the form of an epistle;
passing over, and keeping out of sight,
those false doctrines which are fostered by the leading
characters of those corresponding bodies.

My companion and I could not view this correspondence
which Philadelphia carries on with those people,
to be anything better than a dry, dead formality,
if not greatly tinctured with the leaven of the Pharisees, which is hypocrisy.
In the afternoon the Gurneyites rallied their forces,
and came forward with a determination, as it appeared, to expel me from the house;
with Israel W. Morris for their leader.
He said that John Wilbur,
a man who had been regularly disowned by New England Yearly Meeting,
before the separation, was present, contrary to the order of discipline, and, therefore,
ought not to be suffered to remain in the meeting.
He was followed, in pretty rapid succession, by many of his associates,
in the same strain; one said that I had presented no certificate, and had, therefore,
no right to be there.
But the third party, however good their will might be,
knew too well that such a step as ejecting me, would not bear; and,
fearing the risk of a separation if this motion was pressed on,
stood against the measure of expulsion.

William Evans said that such a discussion would be unprofitable;
that although the individual had been, in a manner, disowned,
he appealed to the "`smaller body,`" and they restored him to membership with them;
and this Yearly Meeting has acknowledged them to be members of Society,
and had never before disputed their right of sitting in Philadelphia Yearly Meeting.
But although it was pretty well known that the Gurneyites
could not carry this question against the conservatives,
(William Evans being clerk,) yet a number of our
sound Friends came boldly forward against the proposition,
divers speaking in the most decided manner, concerning the just course which I had taken,
and of how much I had suffered in support of our doctrines and testimonies,
referring to the "`Report`" of this meeting, and proposing that it should be read,
if Friends could not otherwise remember its contents.

The occurrence of this controversy, (for which the Gurneyites must have the credit) was,
as I believe, of some profit to the cause of Truth,
binding more strongly the minds of the honest-hearted, to our doctrines; and moreover,
it procured for me and my friends, an increase of sympathy,
and had a tendency to gather more nearly and confirm the feeble-minded.
This controversy continued for nearly an hour,
and the clerk made a number of attempts to resume
the business of the meeting before he could succeed;
for it was, as I suppose he feared, the longer it continued, the better for our cause.

Fourth day morning, I was raised up in the Select Meeting,
in a manner wonderful to myself, on the subject of the ministry,
which was corroborated by E. Pitfield; all to the satisfaction of sound Friends,
and even, as I was told, it drew a confession to the Truth, from some of the Gurneyites.
As a party they advocated the London circular,
and pressed for it to be sent to the women, in which William Evans coincided.
The circulation of this document among the American
Yearly Meetings is clearly an attempt to pacify them,
and to make them so satisfied with the defective doctrines of Gurney and Ash,
(coming through their hands in London,
and allowed by them,) as that there may be no disturbance here,
or separation on account of those unsound sentiments,
which have already produced great dissension in the Society at large,
and which sentiments Philadelphia Yearly Meeting had divers time entreated them to suppress;
but of which entreaty they had taken no notice.

This view of the case was pretty clearly developed in the meeting,
and the acceptance of that circular ably objected to.
A report from the Baltimore deputation was brought into this Yearly
Meeting and the reading of it strenuously advocated by the Gurneyites,
and also by members of that committee from North Carolina, Indiana and Baltimore,
but they did not succeed.
This discussion was carried on mostly between the Gurneyites and the conservatives,
and of the latter, Samuel Bettle and William Evans were the chief speakers.

Fifth day, the 22nd, we attended the North Meeting--silent.
On sixth day morning, the corresponding epistles to all the Gurneyite Yearly Meetings,
were brought in and read, save to that of New England;
and a painful loss of ground by this Yearly Meeting
was manifested in the reading of these replies,
because of the absence of any allusion whatever, to the unsound doctrines so rife,
and so perilously entertained within all the Yearly
Meetings to whom these epistles were addressed;
and consequently no caution, counsel,
or admonition was administered by this Yearly Meeting, as had heretofore been done.
To carry on a correspondence with other Yearly Meetings, omitting the greatest thing,
or only thing,
which requires most imperiously the counsel of their
brethren is not only useless and formal,
but tends to quiet their consciences,
and to pacify them in the entertaining of the evil--than which,
there had better be no correspondence at all.

On sixth day, the 23rd, about midday, the Yearly Meeting concluded,
and we spent the afternoon in calling on our dear friends,
and in company with many of them at our lodgings.
Sweet indeed was the fellowship, true sympathy and tender love,
which flowed freely among these who had been so often and so strongly bound together,
baptized by the one Spirit into the one body,
and permitted to drink together of this one Spirit.
Return to thy rest, oh my soul, at the feet of Him who has been with us,
and kept us in the way we should go,
and opened the hearts of so many dear and precious brethren and sisters towards us,
and ask of him to keep them in a place of safety, under his own holy pavilion,
where love and peace may reign forever and ever!

Next morning, the 24th, we took a hearty and affectionate leave of these dear friends,
and went on our way, rejoicing as we went, towards home;
though unworthy of such signal favor,
yet permitted in the greatness of the Lord`'s mercy, to bring our sheaves with us.
I parted with my children, William and Mary Hazard, and my dear companion William Hill,
in New York, that night, and I reached Westerly early next morning, where my wife was,
and found her tolerably comfortable, as to health; and we, with our children,
were mutually glad to meet once more,
and I trust our hearts were bowed in gratitude and thankfulness to him who mercifully
so ordered and permitted us to see each other`'s faces again.

After returning from this visit to Pennsylvania and New Jersey,
it was not long before my dear wife, who had been for some time in declining health,
grew more and more unwell, and from a pretty comfortable state,
by the time of our Yearly Meeting at Newport, where she went, she became very poorly,
and after returning home, went out no more, save once, a short distance;
but continued to fail until the 19th of 12th mo.
following, when she departed in great peace and quietness,
having a comfortable assurance of a happy immortality.
We had lived together, in great harmony and affection, for nearly sixty years;
she was my faithful helper and bosom friend to the last; and the loss of her help,
and sweet company, and good counsel, has been, and still is, a close trial,
and nearly felt by me at this time, the 28th of 7th mo., 1853.

+++[+++The following Testimony concerning this dear friend issued by South Kingston
Monthly Meeting is deemed worthy of a place in this Volume.]

[.embedded-content-document.testimony]
--

[.blurb]
=== Testimony of South Kingston Monthly Meeting concerning Lydia Wilbur, deceased.

Our beloved friend, Lydia Wilbur, wife of John Wilbur, was born in Stonington,
Connecticut, 22nd of fourth month, 1778.
Her parents were Amos and Thankful Collins, esteemed members of the Society of Friends.
She was religiously inclined from her youth up,
and was appointed to the station of an elder at an early age,
which station she continued to fill with usefulness
and propriety during the remainder of her life.
Entering early into the marriage state,
the cares and responsibilities of a numerous family devolved upon her.
She was entirely united with her husband,
and his faithful helper in endeavoring to bring up
their children in simplicity and plainness,
according to our profession, and to teach them the fear of the Lord.
And her concern was not only for her family,
but she greatly loved and desired the prosperity of Truth everywhere.
It may be truly said that she was a peacemaker,--prudent and discreet.
She had very humble views of her own attainments, always preferring others to herself.
She was a most affectionate wife and mother,
and entered deeply into feeling and sympathy with
her dear husband in his many religious engagements,
freely giving him up to travel in Truth`'s service.

The following brief extracts from some of her letters written to
him whilst he was engaged in a religious visit to Great Britain
and Ireland will serve to show the state of her mind at that time,
and the near unity and sympathy she felt with him
in his gospel labors and travels in that land.

[quote]
____
_Second mouth, 9th, 1832._
I can salute thee in the love that first united us together,
and I trust will always remain,
and I desire that the preserving Hand that has been with
thee may still continue to be with thee in all thy trials,
and in all thy lonely moments, which no doubt thou hast at times experienced.
I believe the Master hath called for this sacrifice at thy hands;
to give up all that was near and dear in this life, to cross the mighty ocean,
and there to proclaim the everlasting gospel to a people unknown to thee.
Although discouragements at times seem to be my lot,
yet as I endeavor to abide in patience they are removed and I am made
a little to rejoice that I have been permitted to take the care at home,
while my dear husband is so exposed for the peace
of his own mind and the good of the precious cause.`"

_Third month, 7th, 1832._
"`I believe we have all tried to do the best we could in thy absence,
although I sometimes feel closely tried with the
thought of being so long separated from thee,
my dear husband; but I have endeavored for patience,
and to wear the sackcloth underneath,
but it would be no marvel if the edge of the hem should sometimes appear.
I cannot express the sympathy and tender regard I feel for thee,
and I do greatly desire that the unslumbering Shepherd
of Israel may keep and direct thee in all thy movements,
and that the feet of thy mind may stand sure on that Rock where there is safety.
I greatly desire for myself that I may keep in this safe place;
but I feel my unworthiness and the need of thy help and prayers for my preservation.`"

_Eighth month, 25th, 1832._
"`I think my health is as good as I could expect amid my trials and afflictions,
which have been many.
My trust has been in the Lord alone, and blessed be his name,
he has been as a stay and a staff to bear up my mind
when it has been ready to faint by the way.
Oh! how I have craved that the Lord may be near to
support thee in this time of deep trial,
and in all others that may be permitted thee,
so that thou may not sink or faint under the sore affliction
which has been meted out to us no doubt for our good.^
footnote:[Referring to the death of a beloved daughter, an account of which,
by another hand, accompanied this letter.]
How pleasant it would be to have the sweet company of a beloved companion at this time;
but I dare not ask for it until thou feels released from that land.
____

The singular and varied trials of her beloved husband,
during the latter part of his life,
consequent upon a faithful adherence to our ancient doctrines and testimonies,
weighed heavily upon her spirit, and tended not a little at times to cast her down,
yet her sympathy and near feeling with him were manifested
to the holding up and strengthening of his hands,
while under suffering and persecution on this account.

In the spring of 1852,
her health which had been gradually failing for two or three years, became much impaired,
and symptoms of disease appeared which soon assumed a serious aspect.
In the early part of her sickness, she said,
she would like to live a little longer on account of her dear husband,
remarking that he would be left very lonely;
but after a time this was made very easy to her,
and she gave up all expectation and desire of recovery, saying, "`I would rather go.`"
She said several times,
that it was a great thing to be entirely prepared for such a change.
Once when making this remark, she said she thought she was not quite ready;
that there was much to look over.
She was endued with remarkable patience and sweet resignation to the Divine will;
her countenance bespeaking great quietude of mind.
On its being observed to her that she looked very happy, she said she was so.
A friend inquired of her how it looked to her now in regard to the stand
which we had taken in reference to the troubles in the Society.
She replied, "`It looks as clear to me now as ever it did.`"

She requested her dear love to be given to her children that were not present,
then added, give my love to everybody.
She gradually failed and after lying in a deathlike slumber for two or three hours,
when it was thought she would speak no more,
she opened her eyes and in an audible voice said,
"`I shall now go soon;--I am ready;`" after which she spoke no more,
but continued several hours, appearing to be in a sweet sleep; and so she departed,
drawing her breath so gently shorter and shorter
that the precise moment when the spirit left,
could scarcely be perceived.
She died on the 19th of twelfth month, 1852, in the seventy-fifth year of her age,
and was interred in Friends`' burying-ground at Hopkins on the 22nd,
after a solemn meeting on the occasion.
And now, in view of the quiet and lowly walk of this our beloved friend through life,
we feel this language of our Lord and Saviour to be peculiarly applicable in her case,
"`Blessed are the poor in spirit, for theirs is the kingdom of heaven.`"

Signed by direction and on behalf of South Kingston Monthly Meeting of Friends,
held at Hopkinton 23rd of third month, 1857.

[.signed-section-signature]
Ethan Foster, Clerk.

[.signed-section-signature]
Ann Perry, Clerk.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Lydia A. Barclay to John Wilbur.

[.signed-section-context-open]
Aberdeen, 24th of 8d mo., 1852.

[.salutation]
My Dear And Valued Friend,

Thy favor of the 9th of last month came to hand the first of this,
and was indeed very acceptable,
and in no part so much as where thou speaks of the heavy exercise now upon thee;
in which my mind has seemed almost daily since to travail, and go along with thee,
as I seem to fancy thee going to one part or another of that Yearly Meeting,
parts of which thy good Lord has called thee to visit in his love,
and in the fulness of the blessing of the gospel!

My dear ancient friend,
my heart rejoiced in that it was thus laid upon thee to go thereaway,
and was lifted up in fervent praises and prayer,
unto the mighty and good Strengthener of all his faithful servants,
that he would be pleased to strengthen thee both in body and mind for this journey,
and preserve thee from all snares and perils, and worst of all,
those among false brethren,
and such as make a fair profession of being for the
good old way of Truth and the testimony thereof,
yet there is reason to fear are not wholly true and staunch thereunto!
And from time to time since I had thine, and when thinking of thy getting on,
and how thou wouldst be received,
fresh breathings have continually arisen in my heart
for thy safe guidance from day to day,
thy all-sufficient strengthening and sustaining (amidst the trials
and deep exercises that must be thy portion) unto all faithfulness,
watchfulness, and deep humility,
and thy favoring with such a portion of heavenly comfort and peace,
as will make up for all sufferings, and be a rich reward for all sacrifices!

I have looked upon it as a peculiar mark of heavenly goodness towards
the remnant of rightly exercised and true feeling ones there,
that they may be strengthened and comforted; as well as towards the weak and wavering,
that they may be confirmed and have their eyes opened;
and oh! that those who have been from unwatchfulness led away into the enemy`'s snare,
may be aroused to see their situation, and cry mightily to be helped out of it,
and yet come to bear a true testimony for the blessed Truth!
Oh! the longings of my soul that through the Lord`'s
humbling goodness to his faithful servant,
this labor of love may be especially blessed, and his own pure and holy name be exalted,
praised and glorified over all!

I do trust thou wilt be enabled to put to silence the mouths of the gainsayers,
through the Lord of all-sufficiency giving thee a
mouth and wisdom which they cannot resist,
albeit at the same time preserving thee in that humility,
which honoreth his name and cause, as thou sayest!
Ah! my dear friend, I most entirely unite with thee,
that our Yearly Meeting is the most reprehensible of all in the Divine sight,
from neglecting their duty,
and suffering this dire disease to get to such a height as it has done,
and to spread through their members to other parts, thus infecting them,
and bringing trial upon them to a fearful extent.

And how well do I remember Edward Harris finding thee weeping over us,
in the yard at Devonshire House meeting,
and encouraging thee to go down with my dear brother John, to Croydon, for a week,
where thou wast helped a little over the bitterness of that grief!
But those tears are all bottled by the Divine hand,
and I believe those of many more in our poor land, who are thus filling up in measure,
that which is behind of the afflictions of Christ for his body`'s sake, the church;
for surely some of us are as it were, killed all the day long,
and eat our bread with bitterness, and mingle tears with our drink!

And some such poor weak ones as me, are ready to say,
blessed are they who are taken from the evil to come,
and gathered to their heavenly home!
I do most truly feel what thou sayest as to the cause
of this prevalency of the hour and power of darkness!
The very thing thou mentions has seemed to run through
me as I have sat in our Yearly Meetings,
at sundry times for years and years past; as also of the abominations working in secret,
as in old time when Ezekiel was bid to make a hole in the wall,
and look on what the elders of Israel were doing in the dark!
And now there seems no hope, for the whole head is sick and heart faint,
and there is no knowing of the disease and weakness which has spread over us,
but all is thought to be in a fair state, and a flourishing state too,
seeing they can compass sea and land, and do so many mighty works!

Therefore the few who are constrained to show the house of Israel their backslidings,
are designated as poor pitiful complainers and miserable comforters, narrow-minded,
uncharitable souls, that do more harm than good, etc., etc.
Yes, it is as thou sayest, a profanation in the mouth;
the good words and high profession of some who think
they are advocating the ancient Truth,
whereas Christ is crucified amongst, or in them.
But the day is coming when all shall be tried,
and none but the true Jews will he able to stand with acceptance.

I have been fearing +++_______+++ +++_______+++ has had some counsel from a certain quarter,
not to retail passages across the Atlantic;
and I have queried it of him in my present letter,
saying that there is a wisdom and prudence, that instead of helping, hurts the true love;
for genial feeling minds, to whom the Truth is as the apple of the eye,
must communicate to each other, and it nourishes the true love and unity.
I shall feel greatly interested in hearing about the dear
and tried Friends (sound ones I mean) of New York,
to whom my soul seems to reach forth in many secret and fervent breathings.

[.signed-section-closing]
Thy nearly united friend,

[.signed-section-signature]
Lydia A. Barclay.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From J. W. to William Evans.

[.signed-section-context-open]
Hopkinton, 5th mo., 22nd, 1852.

[.salutation]
My Dear Friend William Evans,

However incompetent I am to do justice to a subject which has impressed my mind
in relation to a few things which transpired in the late Yearly Meeting at Philadelphia,
as I understood them,
yet I feel that it would be a relief to me briefly to confer with thee in relation thereto.
There were divers things in which there was evidently a disparity of views and opinions,
but decided as I believe in a proper manner,
yet the acknowledgment of the epistles then received by a conciliatory minute
on the benefit of a correspondence produced a painful impression on my mind,
whatever the effect might have been on the minds of others.

It was well known, that every one of the bodies from whom those documents were received,
were prevailingly entertaining doctrines essentially
at variance with the doctrines of Friends;
and most,
or all of them are ostensibly endeavoring to enforce them upon
all who have not already embraced them either directly or indirectly,
for the purpose, as it would seem,
of harmonizing the Society at large in the adoption of them.
The want of unity and harmony in the Society of Friends at this time is, as I believe,
fully acknowledged to have been occasioned by the one part cherishing unsound views,
while the other part discards them, and appeals to the ancient doctrines.

That this is the ground of dissension,
is plainly obvious from the fact that the contrast as exhibited by the
"`Appeal for the ancient doctrines,`" issued by Philadelphia Yearly Meeting,
was strongly opposed by the former in both that and Ohio Yearly Meetings,
and the document was not received by any of the Yearly Meetings which sent these epistles,
although offered to them, as we are informed;
than which no better testimony can be reasonably called for to
prove that the cause of disunity rests upon the question of doctrines.
And, furthermore,
much other irrefragable testimony can be adduced to show
that such is the ground of disunity in the Society,
that discipline and good order have been abused in the support of those defective doctrines,
and that those Yearly Meetings are disposed to overlook,
and even to apologize for such perversion and violation of discipline
for the purpose of upholding those unsound doctrines,
and for the expelling of those who honestly withstood them.

There were, also, among the epistles alluded to,
several which exhorted Philadelphia Yearly Meeting to a correspondence
with those who thus identified themselves with such perversion of Quakerism.
Had the minute acknowledging the receipt of those epistles simply
expressed that epistles were received from such and such bodies,
and a committee appointed to essay suitable replies,
and if that committee had brought in replies adapted
to their condition and defection as heretofore,
I apprehend that I should have been spared a great
part of the exercise which has induced these remarks;
which exercise I did not feel commissioned to open in the meeting, as I now do to thee.

The minute speaking so highly of a correspondence
made on the receipt of those Gurneyite epistles,
was undoubtedly well pleasing and strengthening to those people in your Yearly Meeting,
and can hardly fail to be discouraging and painful to sound Friends,
if not weakening to the cause of Truth.
For in all cases, as I understand things,
whatever strengthens error in individuals or in the church
tends to weaken the right thing in that body and its members.
The London "`Circular,`" coming from those who are themselves
chargeable with the cause of the late and present tendency
to separation certainly comes from them with an ill grace;
and until they make amends for their great and culpable deficiency,
they must be considered by sensible and upright Friends as having
put their hands to a work that belongs not to them to do.
Or, otherwise, until they come out candidly and say,
as their acts plainly evince they mean,
we do indeed intend to uphold the doctrines of Gurney and Ash,
and to adopt them as the doctrines of the Society;
and our desire is that all Friends in America may
do the same and have no dissension about them.
In this there would be consistency.

Now until one of these courses is taken,
their epistle or circular must stand in a most inconsistent
and reproachful point of view!
But if the doctrines which have by consent gone forth from them,
are to continue to be adhered to by a number beyond control, then those, if any there be,
adhering to our first principles, would be vastly better off by themselves,
than in connection with such apostates;
and the disparity of numbers could not well affect this conclusion.
If the precepts of our Saviour,
and the order of our discipline be correct in premising
a separation of one unsound member from the church,
(if he could not be reclaimed,) lest his influence
or example should corrupt others in the same body,
then if a greater number,
or a majority of the whole body become apostate to the true doctrines,
how much more necessary and imperious, even in proportion to the ratio of numbers,
and for the safety of those who are yet preserved from heresy,
that they should become separate from those who have not been preserved lest
the influence of the greater number should leaven the whole body.

Indeed, the very design of a social religious compact,
is that the believers in the true doctrines and practices should be gathered out and
become separate from those who believe not in those doctrines and practices,
for the preservation of all the faithful members
from the contaminating influence of unbelievers,
as is well set forth by Robert Barclay.
Thou knowest, my dear friend, as I trust,
that those religious societies which have degenerated the
most from the true Christian doctrines and practices,
have declaimed the loudest against a separation from them, their faith and practice;
and have been the most violent in dealing with,
and even persecuting such as testified against them.
For instance, the primitive Christian church,
when it had become itself apostate from true Christianity,
declaimed against those who conscientiously protested against her degenerate doctrines,
and avowed those of a more primitive description.
How exceedingly that degenerate body strove against those better men,
because they testified against them and became separate from them.

Before I close, my dear friend,
I feel like reminding thee (though I doubt not but thou hast often
thought of it) of the important station in which the Head of the
church has placed thee or permitted thy friends to place thee--how
great the responsibility of such a station at such a time as this,
and under existing circumstances when the welfare of the church and the
course of many may be greatly affected by thy management and decisions;
insomuch, that if upright and just,
they will happily tend to confer upon all their just rights,
and go to the preserving of many, within the pale of right principles,
while the reverse of this would tend to promote that most fearful result--the scattering
of the flock of true believers from the enclosure of the true Shepherd.

In a conscientious course, in the fear of the Lord,
the upright man humbly confides and trusts in a Divine Providence.
He (the Lord) can control all consequences that come of doing justly.
He will, if our acts are righteous, make all of them work together for good.
Thou knowest that in the administration of the discipline as before stated,
an unsound member, if we cannot restore him, must be disowned,
according as Christian usage has been from the first until now;
without compromising with error for fear of the consequences.
Such compromising has brought weakness and prostration upon the Society of Friends
to the extinction of the testimonies in many places at different times;
and what can we expect now, if we suffer to dwell with us great numbers,
whom we know to be in unity with those who have grievously succeeded in turning
Israel away from the covenant and law of the spirit of life in Christ Jesus,
the testimony whereof was so precious to our faithful forefathers,
and which cost Him who called them a vast amount of suffering endured by his servants?

And if we, as a body,
suffer such numbers of these who have thus departed
from the faith to unite with us and we with them,
in our best convocations, our most solemn meetings of the heads of the tribes,
what a wide door we open for all to follow them and their views;
and by the authority of the Yearly Meeting how sacrilegiously we remove the landmarks,
and the restraints of the gospel doctrines, and tarnish the glory of them,
by holding out this language,--be your faith what it may,
we are willing to keep fellowship with you rather than break our ranks,
and lose the honor that attaches to great numbers.
Was it not the ancient and prominent characteristic of Quakerism to do
that which the Lord and his Truth required without regarding those consequences
which the wisdom and fear of man or his misgivings might suggest?

My faith is strong that no division for the Truth,
and in the wisdom of it will ever tend to scatter the true seed of God`'s Israel.
And now I am inclined to ask if there be an order in a Yearly Meeting
which clashes with or stands opposed to the divine ordering,
would it not seem indispensable that a remedy should be provided?
If the Head of the church should move on the mind of a minister
in New England to visit some part of your Yearly Meeting,
and his ministry should evince that he came thus authorized,
still your order is esteemed to be by some such that you cannot recognize such an one.
Again a professed minister without any divine commission
for it offers himself to your acceptance;
if he come from New York or Baltimore Yearly Meetings do you not think
yourselves bound by that order to receive and acknowledge him?
Hence if you do so, your order stands opposed to the divine ordering; as also your doings.
But the Truth can never supersede or contradict itself.

Now in regard to Philadelphia Yearly Meeting, can they not, if they desire consistency,
and humbly ask wisdom of God,
be enabled unreservedly to conform their order (if
they have not already done so) to the divine ordering,
and if they have, to practise upon it?
I trust thou art sensible, my dear friend,
how much good to the cause of our blessed Master the clerk of Philadelphia
Yearly Meeting can do in the present state of things,
and how his loyalty to the Truth will redound to his own present peace,
as well as to his future joy and consolation.

[.signed-section-closing]
From thy true friend,

[.signed-section-signature]
John Wilbur.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From Lydia A. Barclay to J. W.

[.signed-section-context-open]
Aberdeen, 26th of 6th mo., 1852.

I speak of the pleasure and comfort of thy letters, but my dear friend,
they (or these two) conveyed sorrowful tidings from Philadelphia,
that seemed to wound the best life in me, as it regards such as I have much love for,
though some of them are unknown in the outward!--what shall
we say to these things! they must excite mourning and pity
towards such as we believe have erred from the right path,
and also lead us to fear and tremble for ourselves,
knowing the insidious snares of the enemy, and our own great weakness!
Oh! may they stir us up to watch closely and take heed lest we
should fall in any degree from that measure of steadfastness which
has hitherto in mercy been vouchsafed us poor and panting ones,
and may ability be received through the spirit of supplication
to breathe for our preservation to the end,
with that of those dear unto us,
not forgetting those dear ones who have caused us this grief,
if peradventure the Lord would be pleased to give them to see their
danger and bring them back by deep humiliation!

I saw, last week, a letter of W. E. to R. R which tried me much,
as it evinced such a different spirit to what would (to my mind)
be consistent with the professions of Christian love,
forbearance and meekness, and the apparent firmness to Truth, which it contained!
There was the most careful avoiding of any expression towards thee, indicative of love,
or sympathy, or unity, or to the recognition of thee as a minister in any way,
and even alluded to that exercising time thou wast favored with
in the Select Meeting as only "`a few remarks on the ministry!`"
Alas! what a changed feeling there must be!
I could not help in returning it animadverting closely and sorrowfully upon it to dear R.

In looking around our Yearly Meeting, I can but see and feel there are but very,
very few whom I can entirely unite with! and the desire often arises
(in mournfulness!) to be prepared and fitted to be removed hence,
and to be at rest from the tribulations caused by the enemy! yet
desire to be resigned to suffer as long as need be! if I may but
be preserved upright and deeply humble to the end!
How glad I am and was to hear how thou was helped, and I trust preserved,
and my heart was filled with thanksgivings and praise to Him the mighty strengthener
and tender preserver of his dear faithful children the world over;
who still regards in compassion the low estate of his exercised servants and handmaids,
and sends them help from his holy sanctuary as they need it,
to the melting and contriting of their souls before him,
and to the renewing of their humble trust and filial confidence
in the never-failing arm of his salvation!

Alas! poor C. B. I thought it would be so with her,
and I never felt at liberty to express unity with her concern,
no more did several others!
I believe with thee,
that no others but such as are like her would be liberated
to visit your land! so we must visit the seed in spirit,
and Oh! there is a love and unity,
and consolation in Christ which extends and flows over sea and land,
and to distant corners, truly and wonderfully precious,
which he is to be praised and adored for in the depths of fleshly abasement!
What matters the preaching of close things, and ancient doctrine in words,
and extolling our early Friends,
and their writings and testimonies! my feeling is respecting any such,
if they have not a testimony to bear against the doctrines of J. J. Gurney,
believe them not, for they are inconsistent,
and are but garnishing of the sepulchres as it were of those they are extolling so,
and thus prove they are in the spirit of those who persecuted and opposed them.
May the Lord preserve us purely to his praise,
and grant us a little place of rest within the pearl gates at the end,
is the earnest breathing of thy affectionate and united friend,

[.signed-section-signature]
Lydia A. Barclay.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From The Same.

[.signed-section-context-open]
Aberdeen, 29th of 11th mo., 1852.

[.salutation]
My Dear Friend,

Thy remarks on the proceedings of our last Yearly Meeting are very just; there is indeed,
a continual attempt at great and good-looking doings
to hide from the unsuspecting our deformity,
and defection from ancient principles, and so by degrees to wheedle us round,
until the gilded chain which binds us under the prince of darkness, shall be completed!
I think I never was so distressed with the state of things in London Quarter,
as when I was in those parts this autumn, and attended the Quarterly Meeting,
and some other of the meetings there away;
there is such a complete despotism or hierarchy rather,
and yet under the most plausible appearance!

These unfaithful leaders got the Yearly Meeting to
send forth a minute all over the kingdom,
advising to appoint Quarterly Meeting`'s committees everywhere,
and they are also overruling in these committees where they can;
and I believe in consequence of the chief of them being in London Quarterly Meeting,
they are likely (if they have not already done so)
to overrule in the Monthly Meetings throughout,
so as to carry the gravestone question,
which they themselves mooted in the Yearly Meeting, over the heads of,
and to the grief of the few solid faithful Friends left in the different meetings!
It has indeed been an apple of discord,
for it has shown how discordant with ancient principles
many are whom we had esteemed as good sort of Friends!
But it is well there should be something to manifest the evil among us.

Ah! the little band of such as are devoted to the ancient
doctrines are being tried and refined in various ways;
we are separated one from another by distance,
so that we have not the help or comfort of each other`'s company,
and we are losing others by death;
but if it all tends to deepen us in inward experience that we may
more closely cling to the alone and all-sufficient Source of help,
it will be well; and then if ever our deliverance comes,
it will be more manifestly from above, and no flesh shall glory in his sight!
I was affected to hear of inconsistency in several
ministers and elders when in the South,
one of them subverting in principle and conversation
our testimony as to dress and address.

These are opening the door for further encroachments on our testimonies;
so that it sometimes seems to me,
that the time may not be distant (though I may not live to see it) when
those who desire to uphold the pure Quaker doctrine and example,
will be compelled to come out from amongst the unfaithful and compromising,
and even though a mere handful, to touch not, taste not that which is unclean,
that they may with holiness bear the vessels of the Lord!
But such as these are only as one in a Quarterly Meeting.
Still, I expect we know not, if Truth`'s standard were upheld rightly,
but that many more who are wavering might flock to it!
I cannot but feel the prophecy of Sarah Grubb in 1820, is fast fulfilling,
that we shall not be to be distinguished from the many other sects or horns of profession,
which are pushing in various ways against the Truth, and in some cases,
against each other also.

[.signed-section-closing]
Thy affectionate friend,

[.signed-section-signature]
L+++.+++ A. Barclay.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From The Same.

[.signed-section-context-open]
Aberdeen, 7th of 2nd mo., 1853.

[.salutation]
My Dear And Valued Friend,

I unite with thee in regard to a coming out from those who are not true ancient Friends;
but I believe such will be clearly shown when and how to step,
and will be strengthened to guard against creaturely activity and zeal,
and preserved in deep humility and watchfulness,
and they will find it necessary to be deeply exercised
in a godly care over all their members,
watching for each other`'s growth and preservation;
for if a little company make a stand for ancient principles,
their conduct and conversation must be consistent therewith,
otherwise there may be danger of its only being a
separation of one worldly spirit from another,
and great reproach will be entailed on the blessed cause!

It is but a small part here that are aware of what has transpired in New England,
and those who do know it keep it entirely out of sight,
love and harmony being so preached up now; and there is perhaps, in consequence,
a sort of reserve towards,
and standing aloof from those who are known to be of the ancient sort,
even on the part of those who at heart wish well to the ancient doctrines;
they dare not come out with their sentiments,
so thou may judge how little there is of the blessings
of true unity and love in this part of the heritage.
Thy remarks are very just in regard to the various degeneracies in the church,
and those parts in the books of Isaiah, Jeremiah and Ezekiel,
that allude to the chosen people of Israel,
I have often thought apply very closely to us in many respects.

I only hope their lot may not be ours; still,
I cannot but believe that the revelation or dispensation of Truth as made
known to our worthy forefathers is the last and lasting one,
and that though we may be cast off as a people,
yet others will be raised up in the same life and spirit that lived, and moved,
and acted in our forefathers,
whether in this or other nations who shall carry on the Lord`'s work;
for the blessed Truth must and shall prevail over all!
And now my endeared friend and elder brother, though last yet not least felt,
I earnestly crave thy support and strengthening guidance and preservation
from day to day through the deep exercises and unknown afflictions that
await thee in this thy arduous engagement and evening sacrifice;
yea,
I may say fervent supplications have been given me both vocally as well
as inwardly expressed on thy behalf yesterday in and out of meetings.

Oh that the Lord`'s humbling, strengthening arm may be with thee,
and his precious consoling presence around thee to keep thee in all the way thou goest,
and bless the work of thy hands,
and if he please bring thee back again in humble
peace and grateful praise to thy dear family,
where I trust the peace-giving smiles of his glorious countenance
will make up abundantly for the renewed sense of bereavement,
and be as a crown to thy sacrifice!

In dear love and sympathy, I remain thy hearty friend,

[.signed-section-signature]
Lydia A. Barclay.

--

Having had drawings in my mind for a considerable length of time,
to pay a religious visit to Friends and others in
some parts of the States of New York and Pennsylvania,
and having obtained the necessary certificates,
after attending our Quarterly Meeting at North Providence, I proceeded to Fall River,
and on the 7th of 2nd mo., 1853, went by steamer to New York,
and next day by railroad to Poughkeepsie, where I met with my son-in-law,
William R. Hazard, and went with him to his house, near Washington Hollow,
and next day went to the public meeting, after their Quarter,
but not as a concern of mine;
here was almost a constant succession of preaching and praying,
for near two hours and a half, but my mouth was not opened.

There was present one Daniel Haviland (grandson of
the old prophet of the same name) from Quaker Hill,
who stood long and spoke with much warmth,
and delivered much sound Quaker doctrine as to the letter,
but apparently in the will of the creature and with much self-complacency.
There are two of dear old Daniel`'s sons who are
acknowledged as ministers among the Gurneyites,
who as it appears,
may well be compared to those Jews who boasted of being the children of Abraham.
Next day I went to Stanford Select Quarterly Meeting, which was indeed a painful time,
and no marvel, considering the unsound condition of that meeting;
it was my lot to be silent.

But I had felt a great weight and burden upon my mind ever since coming into this county;
and was almost in doubt what the result would be;
which continued with me until some time after the commencement of the meeting for worship,
the next day, when a single sentence presented,
as being intended for me to express in the meeting,
touching the fitness of all which the Lord requires of us,
and the adaptation thereof to his purposes,
without seeing anything which might follow the expression of this sentence;
nor was there any passage of Scripture subject or doctrine presented until
expressing the words which came as they occurred one after another,
when by and by Scripture passages and doctrine began clearly to open,
and the great attention with which we ought to regard the words of Christ,
whether spoken in that prepared body or through the
revelation or manifestation of his spirit in man,
referring to the testimony that "`Never man spake like this man,`" and
also that the great purpose and result of Christianity was our deliverance
from sin through the sanctifying power and baptism of the Holy Ghost,
not only to be witnessed for once, but to be witnessed through our whole life,
not merely to make us once clean, but to preserve us from falling away.

We find that of our Saviour`'s immediate followers,
after the great favors which they had received in
hearing him who spake as never man spake,
and in seeing his mighty miracles,
and partaking of the loaves and fishes which his hands had broken,
great numbers of them fell away and went backward,
as it might be on account of the straitness of his words--the doctrines of the Cross,
or otherwise,
it might be that some of these took discouragement from the reproaches
which the leaders in Israel so freely cast upon him;
that this might have had great effect in reducing
the number of his disciples among the people;
and might have contributed to the misgivings of John the Baptist,
shut up as he was in prison,
and disappointed that the house of Israel did not believe in the Lord Jesus,
whose character, mission, and power himself had so largely testified of.

And I referred to the errand sent by two of his disciples;
that notwithstanding his lone condition,
he was directed and applied to the right source for information; he did not go to men,
the leaders of Israel, to obtain satisfaction as to his character,
but sent his messengers unto Jesus himself, with the inquiry,
"`Art thou he that should come, or look we for another?`"
Then I related what was done, and what Jesus said to the disciples of John,
dwelling emphatically upon the last expression,
"`And blessed is he whosoever is not offended in me.`"
Showing that the enemy always has been, and always would be,
seeking to work an offence in the minds of the followers of Christ,
and that he is in the present day seeking to turn them back as in that day.

When I had gone thus far,
one Samuel Marriot broke in upon me by expressing a desire "`that
our aged Friend would desist from going further,`" to whom I remarked
that for the reason that I was far advanced in age,
and in all probability should not have the like opportunity
to clear myself of those present,
and inasmuch as I was persuaded that my service among them was in the will of Christ,
I hoped they would not interrupt me,
as I believed I was nearly clear of what rested upon me at this time;
and so after a short time, in a loving address to the people, I closed.
After two other persons had spoken at some length, and the shutters were closed,
one Paul Upton came and whispered to me, desiring that I would go out,
but he did not speak out; so pretty soon I mentioned what the Friend had said to me,
and subjoined,
if that meeting had a choice that I should withdraw (notwithstanding
I had the usual credentials) I was free to do so,
feeling clear of the service whereunto I was called among them.

It was suggested by some one that I was not a member of the Society;
when a member of the meeting said, that Philadelphia Yearly Meeting,
the only body which had examined the New England case,
had decided that I was a member of the Society of Friends,
and had permitted me to sit in their Yearly Meeting.
Although many were in favor of my remaining,
yet the prevailing voice was that I should go out, and so I left the meeting,
with several others who were dissatisfied with such proceedings.
It is probable that the matter given me to deliver
among them was not well relished by some;
however, I enjoyed great peace in this day`'s labor,
and in the patient endurance of the reproaches that
were heaped upon me for the blessed Master`'s sake.
It was for standing firm to the same doctrine that George Fox preached in many meetings,
and for which he was hauled or driven out, and in a much rougher manner, too,
than I was stopped and driven out; but, my being driven out,
by those pretending to be Friends--by false brethren--made it, peradventure,
as trying to me, as the rough treatment which he met with, was to him.
It is believed that Stanford Quarterly Meeting has lost much credit by this day`'s proceedings,
among some of its own members, and in the public mind.

From this place, with W. R. Hazard for my companion,
I went over the Hudson River to Coeymans, where we attended their meeting on first day;
but it being very snowy, it was much smaller than usual; yet I had good service,
referring to Paul`'s declaration to one of the churches,
that it must be through much tribulation that they could enter the kingdom,
evincing the necessity of a patient endurance of judgment brought over the natural man,
in order to produce repentance and sanctification;
and subsequently recurred to the vision of the prophet when he saw a stream
issuing from under the thresh-hold of the house of the Lord;
and setting forth the gradation of the depth on descending this river,
coming first up to the ankles, then to the knees, and next to the waist,
and finally becoming a river that could not be passed, deep enough to swim in;
showing that we must descend and get so deep down into the river of judgment,
as to be renovated and sanctified from one degree to another,
and brought to a willingness to abide there, and to get deeper and deeper,
which experience would not be unprofitable to the very best of us.

I was also led to recur to the apostle`'s doctrine,
to show the gradation and advancement in grace, viz: "`Tribulation worketh patience,
and patience experience,`" etc.;
showing that tribulation patiently endured will greatly
instruct us in the school of experience,
and establish us in true and experimental Christianity;
referring also to the passage in Revelation,
"`These are they that came out of great tribulation,
and have washed their robes and made them white in the blood of the Lamb.`"
And although I did not feel that there was much resistance to my testimony,
but quite an openness to receive it on the part of some, yet, as I believed,
a part of those to whom my concern extended were not present,
I did not feel easy without requesting a more general
gathering of the people on the next day,
if Friends felt free for it; but,
even those professing to be sound Friends appeared to be afraid to accede to my request.

From here we went to Troy, on second day, and from there on third day, to Westmoreland,
where we met with kind Friends,
and the following evening had a large meeting at a small village called Hampton,
in which I had much enlargement amongst a mixed company of Baptists, Methodists, etc.,
and the following evening had a small open meeting with
the Baptists in their own house in another direction,
and so stayed and attended Friends`' meeting on first day, which was an open,
favored time.
Whilst here I felt some drawings in my mind to go northward,
and visit Friends in the Black River country, but we heard the snow was very deep there,
so that this and other circumstances discouraged us from going at present.
Third day our friends Isaac Peckham and wife took us in a sleigh to Brookfield,
where we were kindly entertained.
A meeting was notified for us here which was quite fully attended by Friends and others,
notwithstanding it was a snowy day, and we had a very open time,
although it was seen that there was a great want of living concern among them.

From here we went to Smyrna and met with kind entertainment.
Many Friends here seem not to know their own standing;
for while they think themselves sound Friends or call themselves so,
they have much charity for the Gurneyites, and a good deal of sympathy with them,
and have, by being mingled with them in religious society,
suffered a loss by the insidiousness of the enemy through the leaven of unrighteousness,
so dangerous to the body if suffered to be introduced and to remain in it.
This the Saviour of men cautioned his people to guard against.
Beware of the leaven of the Pharisees, said he, which is hypocrisy.
A caution never more wanted than at the present time, and in our Society;
for the leaven of Gurneyism is radical hypocrisy;
professing Quakerism whilst its aim is to destroy it,
and to raise up a different religion upon its ruins.

On first day we attended their meeting,
and found that many of their neighbors had the knowledge of our being there,
so that the meeting was very large;
and truly I was never more sensible of the great necessity of being
furnished with a little of that wisdom which is from above,
than now; and I long waited for it,
and was mercifully helped to preach the gospel in the demonstration of the Spirit,
and as I trust to divide the word of Truth to their several conditions,
insisting upon the necessity of the hearts of the
individual members being clean and pure,
in order that the church, the body of Christ, should be pure,
and as the apostle said without spot or wrinkle,
so that his will might be done by the church on earth
as it is done by the church in heaven;
alluding to the time which we read of in Holy Scripture,
when "`there was war in heaven,`" Michael with his angels fighting against the dragon;
when the dragon with his angels was cast out.

And that we might see from the divers interpositions of the divine power and Providence
that it has always been His will to separate the evil from the good amongst men,
that he might have a pure people amongst whom to place his
name,--a church with whom he would delight to dwell.
I referred to the separation of those who feared him in Noah`'s time,
and to the separation of his people Israel from the Egyptians
by a pillar of fire by night and a pillar of cloud by day;
and also to the separation of those who approached
his altar with offerings of strange fire,
from his true Israel;
and to the Lord`'s commandments to his people when they possessed the land of promise,
that they should not mingle with the nations who knew not God, but should drive them out,
lest they should be corrupted with their images and their doctrines;
for that his people must be pure and holy.

I also cited Christ`'s parable of the vineyard,
showing that the branches must be like the vine,
for truly all those branches which are withered,
are and must be broken off and can bear no fruit.
It was further shown that the old adversary had never failed,
whenever the Almighty had effected a reformation,
or had gathered to himself a church and people,
to attempt to allure them away from their allegiance to him,
or to draw them to the wilderness, bestirring himself with his every effort,
and with his artful delusions,
to frustrate the Lord`'s purposes in obtaining for himself
a holy people with whom he might be pleased to dwell.
Very extensive and arduous were my labors here,
and my blessed Master was near and went before,
and fulfilled his early and gracious promise,
that he would be to those who trusted in him a mouth and wisdom
which their adversaries should not be able to gainsay or condemn.

We had a public meeting the same afternoon in the Methodist house at Smyrna village
which was attended by nearly the whole body of Friends thereaway and by many others.
This was also a time of great openness;
strength and enlargement being mercifully given in
the promulgation of the everlasting gospel,
in which the way of life and salvation was clearly explained and set forth.
On second day we reached Westmoreland again, and,
not feeling easy to leave Friends of Leray Quarter, in the Black River country,
on third day, the first of 3rd mo.,
we set out for those parts and passed some meetings by, way not opening to attend them.

On fourth day we travelled through very deep snow to Lowville,
and next day attended their Preparative Meeting in which
I had good service through the abounding of best help;
and although there were strong Gurneyites in this meeting,
yet they were so softened and brought down as to let us sit in their Meeting for business,
without objection.
We lodged the following night at the house of Thomas Townsend, an aged Friend;
here we made some attempts for a meeting in the Methodists`' house,
but the afternoon and evening were so very snowy that the meeting was not held.

Next day went twenty-seven miles to Leray, and the day following,
with Samuel Child for our guide, we went to Indian River,
and put up with Robert Townsend, an elder in Society;
to him we applied for a meeting that afternoon or evening;
and after some consultation it was concluded to have it at 7 o`'clock that evening.
This meeting was said to be attended by every one of their members and divers others.
It was a highly favored meeting, and the Friends were very loving and affectionate.
We tarried all night at R. Townsend`'s, and he and wife were very kind to us.
Next day returned to Leray, and attended their first day meeting, which was large,
other people having heard of our being expected there.

Here I was greatly enlarged in delivering the gospel message,
commencing with the passage, "`No man knoweth the things of a man,
but the spirit of a man within him, so no man knoweth the things of God,
but the spirit of God,`" setting forth the utter insufficiency of the
wisdom of man to comprehend or demonstrate the things of God;
and it was a very solemn time--an opportunity worth travelling far to obtain.
We went from this meeting to Samuel Child`'s where
we were kindly cared for by him and his wife,
and had the company of two of his brothers.

Next morning we parted with our kind friends Isaac Peckham and wife;
and took cars at Watertown for Rome, and then to Auburn,
and so by carriage to Poplar Ridge.
On third day we went to see our valued, aged Friends, William King and wife,
and their two sons John and Alfred, with their wives.
This family had of latter time emigrated from England and settled here.
We put up this night with our friends Joseph and Winnefred Chace,
and the next day attended their Preparative Meeting;
in which I felt and expressed a living concern that those few who appear
to have been chosen to stand by the ancient testimonies of Friends,
in New York, might live so near to the blessed Master,
and so entirely put their trust in him,
as to be enabled to fulfill his purpose in calling them to their allotment,
so exceedingly important:
and that they might wait on him in great humility for strength and wisdom;
referring for their encouragement to the wonderful
deliverance of the Lord`'s people formerly,
by a very few men under the hand of Gideon--and that it was so ordained that man might
not claim the glory of such deliverance--referring also to the simplicity of the means,
the lamp in the pitcher, etc.
It was a solid instructive time.

After meeting, in company with John King, we dined at Abiel Gardner`'s,
and went to the house of our friend Job Otis to lodge.
On the following day we made several visits to our beloved friends,
and next day went over the lake to Ulysses,
and were met at the shore by friends who kindly cared for us;
and next day we called on the families of Friends in that vicinity,
and had a meeting at evening in the Methodist Meetinghouse at Jackson village;
and I did indeed feel thankful for the help afforded.
The minister, and most of his hearers had never before been at a meeting of Friends;
and they expressed much satisfaction.
The meeting was large and the service extensive.

On first day morning we attended Friends`' Meeting at Hector,
and public notice being given, the meeting was large, and, as I trust,
to the honor of Truth.
At 4 o`'clock the same afternoon we had a meeting at a Baptist Meetinghouse at Searsburg,
which was large, and we were favored with best help,
in showing that Christianity is the same now that
it was in the days of Christ`'s personal appearance,
and in the apostle`'s time--that in itself it had not in
the least degree changed or diminished in life and power;
and that the present lapsed condition of the professors of it was owing to their misgivings
and want of faith and faithfulness to its manifestations and operations in the soul.

I referred to Christ`'s charge to his disciples on the first occasion
of his sending them forth--to his promises unto them;
and furthermore,
to his referring to those promises in his charge to them at the time of his last personal
interview with them--comparing the latter also with John`'s testimony of him,
contrasting his own baptism with that of Christ, which is with the Holy Ghost;
the one unto repentance,
the other to the thorough purgation of the hearts and affections of men.
In this service, help and strength, mouth and wisdom were admirably given.
Most of the principal Friends of Hector Meeting were there;
and here I met with dear Lydia Hallock; Joseph Tripp and wife being also with us.
We went with Lydia to the house of her son-in-law, Aaron Mekeel, with many dear friends,
whose company and conversation were comforting.
Next day we had the same company together at William Mekeel`'s.

From this place we went to my brother-in-law, John Collins`'s, where we stayed two nights.
While here, in Hector, I felt a strong desire to visit Joseph Cole and brothers,
in Alleghany county, (of a family formerly residing in my own neighborhood,
and then in the practice of frequently attending our meetings,)
but many circumstances seeming to make it difficult,
I felt released, upon writing them an epistle of exhortation and counsel.
On fourth day we attended Hector mid-week meeting,
and had an excellent parting opportunity with Friends by themselves,
in which counsel flowed freely in the demonstration of the good spirit,
and in the fellowship and communion of the Holy Ghost.

On fifth day we left here, and went to Ithaca, and from thence by railroad to Owego,
where we tarried until sometime after 12 o`'clock p.m., and then took the express train,
and went forward with great speed towards the Hudson River,
until we came to the Delaware, about sunrise,
to a place where the railroad is cut into the side of a vast ledge of rocks,
judged by some of our company to be about four hundred feet high, nearly perpendicular,
and about thirty or forty feet above the river,
and but just the width of the roadbed from the ledge.

Here the two hindmost cars ran off the track towards the ledge, we being in the last;
and we found, by examination,
a curve in the way just as we came to this perilous situation, and, also,
that several of the rails were broken and driven
out of their places at different and distinct points.
But, whatever the cause, the two cars ran off, as before stated,
and the wheels of the one in which we were seated fell into a water-passage,
about eight feet broad, whereby we became disengaged from the next car; and, when so,
our course was inclined towards the ledge,
so as to bring the forepart into contact with it, which stove it very much to pieces,
and brought us to a stand at once, and our seats to the floor.
Our seat, as I remember, was the third or fourth from the front door--and,
what was wonderful, all on board escaped without injury.

After a half hour`'s detention, spent in arranging the passengers,
and placing some in the baggage cars, we were again under way.
If our car had run off the rails on the opposite side,
the way was so narrow that we must have been plunged into the river.
Praised be the Lord for our preservation!
Notwithstanding this detention, and thereby failing to meet the cars in course,
we got on, through Newburg and Poughkeepsie, to my children`'s dwelling, at Washington,
the same day.
The many afflictions, oppositions,
and dangers which we met with during this journey in New York,
brought afresh to my mind Paul`'s enumeration of the perils which had fallen to his lot.
The enemy strove to deter him from fulfilling the Lord`'s purposes,
if not to destroy his life.

On first day, 20th of 3rd mo., we had a meeting in the Congregational house,
at Washington Hollow, in which, I trust,
the word of Truth was rightly divided amongst the many Lo! heres, and Lo!
Theres.
Third day, 23rd, we took passage in a barge, and came to New York city in the morning,
and, after calling on our friends, went to Rahway,
reaching the house of our dear friend Martha Wood before night.
We lodged here, and next day attended their mid-week meeting,
which was open and satisfactory.
After meeting, going to the depot, we met with our dear friend William Hill,
and all went on together to our friend Sarah Healy`'s,
where we met with our dear friends Elizabeth Pitfield and Lydia Reeve,
with Sarah`'s children.
Mutually glad we were to see each other.

On the following day we had an appointed meeting there at 3 o`'clock, which was large,
and considerable labor fell to my lot;
yet much deliberation and care seemed needful in feeling for the right stepping-stones.
E+++.+++ Pitfield was exercised acceptably in supplication.
We lodged that night with George W. Brown, E. Pitfield also being there.
Next day George took us to Burlington, where W. R. Hazard parted with us,
and we went on to Ezra Haines`'s, at Rancocus, and dined; he and wife open-hearted,
plain-spoken, sound Friends.
Afternoon we went to Josiah R. Reeve`'s,
and our rejoicing to see each other was mutual and full of consolation.

Here we tarried the night, and on first day morning attended their meeting, at Medford,
where much arduous labor was called for at my hands,
and in bearing the ancient doctrines of Truth set
forth the minds of many seemed to be tendered.
Afternoon, Josiah and his wife went with us to Moorestown, where we had a meeting,
at 3 o`'clock the same day, long silent, but comfortable in the end,
in the delivery of a short, lively testimony.
After meeting we went to the house of our dear aged friends Ebenezer and Rachel Roberts,
where a number of other dear friends met us, and we were much refreshed together.

Second day afternoon we travelled twelve miles, and lodged at Hughes Bell`'s,
and the following morning attended Woodbury Monthly Meeting,
in which I was mercifully helped and much enlarged in bearing a
living testimony to the power of the gospel of Christ our Lord.
We went on that afternoon towards Salem, and lodged at the house of William Carpenter,
(a sound, understanding Friend,) and on fourth day attended Salem Monthly Meeting,
where I was enabled to bear testimony to the doctrines of Friends, but which,
as appeared in the sequel, gave great offence to the two persons who sat near us.

When the meeting for business was opened,
one of them said there was a person present who was not a member of the Society,
and therefore had no right to sit in that meeting,
which assumption was seconded by the other, but denied by four Friends in the meeting.
I then mentioned that if that meeting did not see cause to pay
any deference to the decision of their own Yearly Meeting,
but desired me to go out, I was very free to do so;
on which they poured out a volley of declamation, and made many charges,
saying that I had been disowned by my own Monthly, Quarterly, and Yearly Meetings, etc.,
etc., and further said that they had a right to protect their own meeting.
To this I thought best to make no reply; and,
having accomplished the service which lay upon me, withdrew,
as did also my friends William Hill and Allen Roberts;
for when they commanded me to go out, they included those who were with me.

The objectors to our sitting endeavored to bring more to speak against us, but could not.
The sound Friends were exceedingly grieved at this usage of us,
and one elderly man did plead very feelingly for our rights,
and was broken into many tears.
But I felt, on leaving the house, very peaceful,
and enjoyed great consolation by the incomes of the dear Saviour`'s love,
who made me willing to suffer reproach for his and the gospel`'s sake.
After this meeting was over,
we went with the elderly Friend alluded to--Josiah N. Reeve--six miles, to his house,
on our way to the next meeting.
I found this Josiah N. Reeve to be a grandson of Mark Reeve,
an eminent minister of the last century, who lived at Greenwich.

Josiah went with us to that place,
where we put up with our dear aged friend John Sheppard, who has five sons,
valuable Friends; and at this place we also met with George Bacon,
and his wife and children, very hearty Friends.
They claim here to be all sound Friends, save one,
and expressed satisfaction with my labors among them.
After our visit here, we went back with Josiah N. Reeve,
and were lodged and cared for in the kindest manner by himself, sister and brothers,
closely located together.
From thence we went to Salem, and took boat to Newcastle, in Delaware.
From this place we proceeded to London Grove, in the State of Pennsylvania,
to the house of our valued friend Morris Cope, who went next day with us to Sadsbury,
where we put up with our dear friend Priscilla Cooper.

I was pretty long silent at the meeting here,
but way finally opened for a powerful testimony among them, tending, as I trust,
to harmonize them together.
After this meeting we came to the house of our dear friends Isaac and Rebecca Hayes,
at East Bradford, his brother Benjamin and wife accompanying.
On the following day, which was the first of the week, we attended that meeting,
to good satisfaction, where, among other doctrines of Friends,
that of the primary order and authority of the Holy Spirit
before the Holy Scripture was largely set forth;
but for whose sake I know not, it being a Friends`' meeting,
and no public notice requested.

After meeting we went home with our dear friend Samuel Cope, where we lodged;
and next morning Samuel went with us to his brother David Cope`'s,
on our way to Philadelphia, where, on third day,
I attended their mid-week meeting in the Northern District.
After this we made divers social visits, until sixth day morning,
when I parted with many dear friends in Philadelphia, and coming on to New York,
went on board the steamboat that evening, and arrived at Westerly next morning,
feeling very peaceful and quiet.
I spent the day with my children and friends here, and the morning following,
which was the first day of the week, and the 10th of 4th mo., 1853, arrived at home,
in good health,
and very thankful for the preservation so mercifully extended in many ways.
