[short="Preface to the Letters"]
== Letters to a Friend, On Some of the Primitive Doctrines of Christianity.

[.centered]
By John Wilbur.

[quote.scripture, , Phil. 4:8.]
____
Finally, brethren, whatsoever things are true, whatsoever things are honest,
whatsoever things are just, whatsoever things are pure, whatsoever things are lovely,
whatsoever things are of good report; if there be any virtue, and if there be any praise,
think on these things.
____

+++[+++The following Letters,
written by John Wilbur to his friend George Crosfield of Liverpool,
during his first visit to Great Britain,
bear evidence to the clearness of his vision in perceiving thus early,
the encroachments of an innovating and modifying spirit in the Society,
as well as his faithfulness in raising a warning
voice against its delusive and pernicious effects.
These letters were published by the Friend to whom they were addressed,
and brought down upon their author the severe condemnation of those who
were insidiously at work to undermine the true principles of Friends,
both in England and America.

[.offset]
On returning to his own country,
he was soon called to account by some of the leading
characters in New England Yearly Meeting,
for writing these letters,
and for suffering them to be published without first submitting
them to the judgment of the Morning Meeting in London.
In point of fact, he did suggest the submission of the Letters to the Morning Meeting,
and inquiry was made of the Friend having charge of the records of that Meeting,
as to the practice in such cases; who replied that it was not the usage in that country,
to bring forward such pamphlets for revision.

[.offset]
The storm of indignation,
with which J. W. was nevertheless assailed on this occasion on the part of some,
clearly evinced the deep and settled purpose which existed in their minds,
to effect a change in the principles of the Society,
as well as their conviction that the Letters were
adapted to counteract their long-cherished design.
These feelings of hostility to him were so far indulged,
that attempts were made to bring him under dealing at that time,
on account of these Letters;
being charged with having turned aside from his proper business in writing them,
raising a false alarm, and creating an unnecessary agitation in the Society, etc.

[.offset]
But the publication of the "`Beacon,`" and the defection in England
termed the "`Beaconite Separation,`" soon after occurred;
the seceders holding to the very doctrines guarded against in these Letters,
and thereby clearly showing the necessity and timely
adaptation of the warning contained therein.
"`Beaconism`" was an offshoot from Quakerism,
in the same direction with the views of J. J. Gurney and his adherents;
but this development of them was premature,
and too radical and open for any considerable number
of the Society at that time publicly to adopt them.
Some of the leaders in this schism, however, did not hesitate to affirm,
that their views had been thus changed by the writings of J. J. Gurney.

[.offset]
These writings,
though in the main more insidious and plausible than the open defection of the
"`Beacon,`" no less surely led away from the Truth as always held by Friends;
and they have indeed produced a far more sweeping effect,
than any bold avowal of the same principles could have accomplished.
Their legitimate results are becoming more and more manifest to every intelligent observer.
One after another of the testimonies of the Society,
and the restraints of the Discipline, are being abandoned;
paving the way for an easy union with the fashionable and sin-loving world,
and at the same time affording the clearest proof that there was ample
cause for the deep concern and apprehension of our dear friend John Wilbur;
whose labors, to avert the entire overthrow of the Society,
were so abundant and faithful,
amid all the sore trials and sufferings which fell to his lot.
We commend these Letters to the serious consideration of the reader.]

[.centered]
=== Preface.

In publishing the following Letters,
it is necessary that I should briefly state some of the reasons
which have induced me thus to give a more extended circulation
to what was originally only a private communication of sentiment.

They contain the views of a Friend who, during his visit and gospel labors in this land,
was often led into deep exercise and solicitude on subjects
of great interest and importance to our religious society.
The views which he has taken, and the sentiments he has expressed, are, in my judgment,
well calculated to afford instruction and profit;
and to support the ancient doctrines and testimonies of our society;
nor can I doubt but they will be acceptable to,
and be well received by all who wish these doctrines and
testimonies to be maintained in their ancient purity.
Yet to others who may be shunning the cross, and the narrow way,
and seeking for themselves and their children more liberty;
endeavoring to combine what are altogether irreconcilable,
the grandeur and friendships of this world with the plain and simple way of truth,
I expect some of the sentiments contained in this work, will be very unpalatable.

A recurrence to our first principles is at all times profitable and advantageous;
the present day abounds with writings, both of a religious nature and others,
much mixed with opinions and sentiments very different from those held by us as a society;
and whilst these books are extensively read amongst us,
there is reason to fear that the perusal of them tends much
to the exclusion of the writings of our own society;
that thus loss is sustained by many of our members, who are more deficient,
than they ought to be, in the knowledge of our principles on various important points:
a more extended acquaintance with these principles,
and a more strict adherence to the testimonies of the society, are much to be desired,
and would be of great benefit.

The following Letters are calculated to impart such knowledge,
and to promote such an adherence,
and I publish them with the hope that these may be their
effects--that they may be read with a desire to be instructed,
and to profit by the sentiments they inculcate.
The responsibility of giving them this publicity attaches not to the writer,
but belongs exclusively to me.

[.signed-section-signature]
George Crosfield.

[.signed-section-context-close]
Liverpool, 10th Month, 1882.
