== Letter I. / Introductory.

[.salutation]
My Dear Friend,

I have often recurred, with a degree of satisfaction to my early impressions,
as well as to the instructions which were given me by my parents.
They early made me acquainted with the doctrines of Christianity,
so far as the reading of the Scriptures of Truth would give me that knowledge,
and I was carefully instructed to reverence these sacred writings.
The precepts of the New Testament in a particular manner,
did seem fully to correspond with those secret sensations,
which I was early led to believe were the openings and leadings of Truth upon my mind:
I was enabled also, without an expositor, to receive and satisfactorily to understand,
some of the more prominent and simple doctrines of the gospel,
as to the character and the several offices of Jesus Christ the Saviour of the world.

And now also in due time,
the history of the Society of Friends was introduced to my reading and observation;
and my youthful mind was thereby strengthened and confirmed,
to make a more perfect discrimination between the works of the law and those of faith;
and to perceive what faith in God, and in the Lord Jesus Christ would do,
even that faith which worketh by love to the purifying of the heart.
I saw that it was sufficient; that it enabled those sons of the morning of our day,
notwithstanding the mighty opposition which lay in their way, to work the works of God;
even those spiritual works which were wrought in them, and by them,
through the sanctifying power of the Holy Spirit,
in the covenant of God`'s promise unto them;
even in like manner as the primitive Christians did,
they joined and worked with the workings of grace in themselves
to the glory of God and to the praise of the Lord Jesus Christ.

And now I found myself to be one of this Society, not by birth and education only,
but I embraced, and received,
and fully believed in the doctrines of Christianity as professed by it,
and I have ever since loved the Society and its testimonies
wherever they have been planted;
not only in my native land of America, but also in this nation,
where this the Lord`'s right hand planting was, as regards our Society, first begun.

Seeing now that my lot has been cast amongst my friends here,
in the love and service of the gospel,
I have verily thought that the good of this people has come nearer
to my best desires and feelings than ever it did before,
and that for this reason;
that this dedication has cost me more than any other service in which I have been engaged;
and many, yea very many in this land, have become as bone of my bone,
and flesh of my flesh;
if indeed I may be allowed to use and to spiritualize the expression;
they have become as brothers and sisters in those tender feelings
which I trust spring from the one blessed source of Divine love;
so that though as an alien and a stranger here, as to the outward,
still I feel to be one of you, and in my measure,
to joy in your joys and grieve in your griefs--to travail in affliction with you,
and in desire that you may faint not:--to endeavor
to strengthen the hands which hang down with weakness,
or rather to put up a prayer that our best Helper may lift them up,
that he may confirm the feeble knees;
and that all who have taken upon them the profession,
may be encouraged to stand fast in the Lord,
and faithfully in the testimonies of our God; so that this people,
whom in his own good pleasure he chose to raise up and advance,
distinct from all others of this day, to be as a beacon, a light,
and a waymark outwardly in the world, may hold on their way,
and continue faithful through his power to support and maintain
the inestimable ground which God did lead them,
and gave them to stand upon;
and that they may never suffer any by-way apprehension of good to draw their attention
from the one great object of God`'s peculiar design in raising them up to be a people,
even to bear testimony to the spiritual nature and design of the gospel,
as well as to uphold the glorious plan of redemption in all its other parts.

In whatever degree the present condition of the Christian world
may now be improved by what has been done through this people,
yet if by means of their unfaithfulness, a reaction should take place and continue,
we may fear that when this people shall again have
mingled with those from whom they came out,
and the advanced ground of God`'s providence be thus vacated,
that the religious testimonies given them to bear, will also be lost with them.
Should such an event occur, then indeed will it be better for mankind coming after,
that this Society had never existed; for the enemy of all good,
will not then fail to suggest that the ground having
been once taken and found to be untenable,
it would be vain and fruitless for any to attempt the like again; for we know,
that the more efficient the means that may have been resorted to to attain an object,
if those means fail, the more we despair of ever attaining that object.
But O! that the spirit and power of the gospel may
never give place to profession and form,
however garnished and glowing that form or profession may appear.

And now my dear friend,
my mind having been much exercised under divers weighty and important
considerations of this nature since I have been in this land,
I am induced to believe, it will contribute to my peace of mind,
to open a little and spread forth before thee,
a few remarks upon those subjects which have been more prominently
and peculiarly exercising to my mind,
during my labors amongst you;
but I have no hope of being able to do justice to a review
of so important a nature as may seem to be premised,
but only in such a way as I can endeavor to discharge what I apprehend to be my duty;
I propose, therefore, in my succeeding letters,
to treat upon some points arising out of the foregoing considerations.
