[short="Letter III. The Effect of Action and Reaction"]
== Letter III. / The Effect of Action and Reaction Upon the Professors of Christianity, Especially in Relation to the Society of Friends.

[.salutation]
My Dear Friend,

We learn from history,
that whenever God in his providence has made way for an advance of his church and people,
their old enemy and watchful foe,
has then always been ready to exercise all his maneuvers
and powers to drive her back again into the wilderness;
and we have no need to go further back than the Protestant reformation for a proof of it;
for in a review of those times,
we easily recognize his palpable and bestirring efforts to frustrate the blessed work,
and to tarnish the beauty that seemed to be dawning upon the church, and, if possible,
to deter her from going forward in the way which God had opened before her,
even to the advanced ground which he had provided
for the pitching of her tents and tabernacles.

Thus, when the early reformers began to see the errors and inconsistencies of the Romish Church,
the evil effects of their outward forms and observances
could not but greatly strike their attention,
and particularly their doctrine of the real presence of the body and blood
of Christ in what was called the sacrament of the Lord`'s Supper;
the whole, and particularly the latter,
tending to a denial of the spirituality of religion,
and the benefit of the offering once made for all,
by the sufferings of Jesus Christ without the gates of Jerusalem.

The errors of Socinus were also propagated about this time,
and his followers were thus in reality associated
with the Romish Church in effecting the same object,
though by different means,
and seemed to threaten the overthrow and downfall
of the whole doctrine of Christian redemption.
The earnest efforts of the honest-hearted and sincere
reformers urgently opposed both these evils,
and the Romish Church, defending in a very undue manner the doctrine of works,
the abuse of which was the foundation of their system of priestcraft,
the enemy of all good, took advantage of the heat of this controversy,
and through a want of watchfulness and care on the part of the first reformers,
they were led on, step by step, to such a warm defence of the doctrine of the atonement,
as to lose sight of the more practical operation of the light, grace,
and spirit of our Lord Jesus Christ; and this gained such ground at a later period,
during the hot disputes between the Calvinistic Puritans and the Protestant Episcopacy,
which retained many of the Romish superstitions and errors,
and they were so exclusively and intently fixed on extolling the merits of the former,
that they very much lost sight of the necessity of the latter;
and so by inattention to it, their experience in,
and faith concerning the power of practical religion,
gradually diminished and vanished away;
insomuch that finally they became so void and faithless of the spirit and life of religion,
that he who made a profession of spirituality, became as it were,
a by-word and a hissing to these great and zealous
supporters of the ever blessed atonement.

Yea, and those who worshipped God in spirit, who walked in his light,
and believed in the perceptible guidance and influence of his holy spirit,
were deemed mystics and enthusiasts; and now having lost the life and the power;
the faith of these high professors generally was only literal,
and their devotions an imitation, consisting of forms and ceremonies,
and things that belonged to the outward law.
Thus they in their turn, as the others in another way had done,
made a breach in the same covenant or system of Christianity,
and rejected very much of the vital and spiritual part,
the regenerating power of the Holy Spirit.

This, we may well suppose,
was effected by the action and reaction of that zeal of
an unregenerate heart which tends to errors and extremes.
But God, even her God, forsook not his church.
He interposed to renew his whole covenant with her,
notwithstanding her wavering and vibrations from the true centre,
the power of the gospel!
He would lead her again out of the wilderness where her enemy had driven her,
and he would speak comfortably to her.
He would raise up unto her faithful witnesses, whose hearts he would enlarge,
that they should understand, and whose eyes he would anoint that they should see,
and he would restore again to the church the whole covenant entire as in primitive times,
and men should be able again to see equally every provision of his salvation.

And they, our predecessors, did see and did walk in the light of the Lord Jesus,
in which every one who walketh also believeth,
and they do ever believe the whole covenant of God,
and their faith will be found in all that faith can do,
and their works in all that works can do.
And they see that such faith as stands only in literal things,
and is not also in the light, and life, and power, is dead, being but partial and alone;
and in proportion as is the increase of faith, so is the increase of works;
and so vice versa, as regards a living faith, and those works which are with it,
which are the fruits of the Spirit of God.
For such a faith, according to the declaration of the apostle,
is also the fruit of the same spirit, so that he who hath not the Spirit of Christ,
nor walketh by it, cannot have the faith as it is in Jesus.

But the coming forth of George Fox, and his contemporaries,
for the restoration of God`'s covenant,
as well as the primitive testimonies and doctrines of the gospel,
drew upon them the malice and rage of the old watchful foe;
for the advancement of the church, by the redeeming power of God through Jesus Christ,
still excited the most dire hatred of her enemy, the devil, whose malice,
as it did in the early days of the Christian church,
now again instigated and poured forth a mighty volume
of rage and persecution against them,
hoping no doubt to get to himself some honor over the church of God.
For inasmuch as in the primitive times he was able to persecute the Christian church,
only by and through the people of the world,
so now he hoped to divide Christ`'s kingdom against itself,
and if not to the overthrow of all--yet to the dividing of the spoil,
and himself to share in it, by arraying Christian against Christian,
catholic against protestant, and finally, even protestant Christians against each other.

Now it was seen that even those who were making the highest
profession of the atoning blood of their Redeemer,
and who were placing the most implicit reliance and confidence therein,
could be brought forward in the very face of the gospel,
to spoil and devour the professors of the same faith; for this plain reason only,
that they, the latter,
were endeavoring to embrace and observe all the commands
and doctrines of their Lord and Master Jesus Christ.
They had made a firm stand and notable advancement against the kingdom of darkness,
therefore the prince of darkness now rose in his
fury and spread the work of cruelty around,
increasingly striving to waste and paralyze this people.
But this advanced guard--this little band of humble warriors,
fighting under the strong banner of Christ Jesus, their holy head and leader,
were invincible, because their Captain was with them, and went before them;
and for this reason, that their weapons were not carnal,
but mighty through God to the pulling down the strong holds of Satan and his armies.

I shall now proceed to make some remarks upon Socinianism and infidelity,
subsequent to the rise of the Society of Friends,
and on the introduction of these opinions among them,
and among other Christian professors.
If inquiry were to be made for the first cause of these
modern deviations from the soundness of Christian faith,
we might easily trace it to the same source whence evil first came into the world,
and whence we are to look for the primary origin of all iniquity;
and if we were to seek for the grounds on which that
first cause of evil acts on our fallen nature,
our inquiries must end in the conviction,
that it rests in a disposition for insubordination
to the needful restraints of the divine law,
and on pride, that great upholder of self, and of the will of the flesh.
These are the elements, in the absence of the humbling power of Truth,
with which the enemy pitches his strongholds and builds his embattlements,
even in the unrestrained will of man, and in the pride of his heart;
a pride which may not be seen on his person, but which either his words or his actions,
sooner or later, will show to have a dwelling in his heart.

Hence, he will in a greater or less degree, stand opposed to the pure, humbling,
and needful restraints of the gospel; in some way or other this will be found,
and to such a degree at least, as will keep him under the dominion of evil.
But the out goings by which the tempter leads man off from the ways of Truth,
are varied according to his natural disposition;
according too to the traditions received,
and the condition and faith of the society with which he is connected,
and of those deviations which lead from the Truth; the enemy,
although he regards the least, still glories most in the worst and widest;
and although high professing hypocrisy cannot be deemed the least of these,
yet open infidelity must be acknowledged the greatest; still it is believed,
that the ready foe has made the former a clue to the latter,
and however natural it is for things to produce their like,
yet we find that through the interposition of an evil agent,
the natural order may be broken and reversed,
and a thing may lead to another widely differing in its degree,
and in some respects in its nature, yet in denomination the same.

As one extreme often produces another,
so may the abhorrence of one evil lead the unwary mind into its opposite evil;
and although, in some dispositions, over action may subside into inaction,
yet it undoubtedly often produces reaction; and as it regards spiritual agency,
where the power of Truth is not the moving principle,
then there is another power which influences and controls men`'s actions,
and controls that which lends to action, viz: their faith,
or rather their notions or way of thinking;
for indeed if they are not in some degree under the influence of the Truth,
let their profession be what it may,
they can have nothing which deserves the name of faith.
For when men forsake the power of Truth, this choice gift is continued to them no longer;
they then have not its renewing assurances, they are trusting in a false hope,
which is nothing more than the spurious workings of the deceiver.

The vanity and pride of ascribing to man the honor
of saving himself by his own good works,
as is done by those who rely for salvation on works alone,
has been eagerly grasped by the devil;
and at the same time that he extols it to its devotees,
he exhibits it in the most ridiculous point of view to all such as,
seeing its inconsistencies, are led into the Calvinistic sentiment,
which excludes good works altogether,
causing them to confide exclusively in Christ`'s outward atonement for them,
and in this way the enemy takes advantage of man`'s frailty;
still charity leads us to the persuasion that sincerity
may exist in the one as well as in the other,
but practical observation obliges us also to admit,
that a complete character of hypocrisy may be found in both.

Again, where good works or obedience are struck altogether from the account,
and God believed to be equal in all his ways,
and implicit confidence being placed on Christ`'s redemption without us,
then comes in the doctrine of universal salvation without any condition.
In all these forms of belief we can plainly see the care taken to provide
an escape from the pain and conflict of the sanctifying and practical
work of the grace and spirit of God upon men`'s souls for their purification,
so that a place may be found and abode in, for the continued indulgence of the flesh;
and the will of man, vainly attempted to be kept alive in every form of religion,
save the one true form in which obedience and the power of the Spirit dwelleth.

It must be acknowledged then, that the mind let out to mere opinions, without the living,
fundamental, and true touchstone of the light and grace of God,
confirmed by the Scriptures, will probably run into great errors; and so it seems many,
very many, have run.
But the devil has not led every one in the same way,
though he may bring them to the same bitter end at last,--for
there are many paths which lead through devious windings,
but all come out at the same sad point.
He may induce both professors and non-professors,
(the freedom of the gospel is not apparent in one,
nor its fruits in the other,) to disbelieve the spirituality of Christianity,
because they see their neighbour, who is high in the profession of it,
either a mere enthusiast or a hypocrite.
Again, he may induce some men to disbelieve in the atonement of Jesus Christ,
because many who lay great stress upon it, are in their practice no better than infidels.
Furthermore, he may induce many to condemn Christianity under every name and form,
because they see those who profess to believe in,
and follow the Lord Jesus Christ as a Saviour, continue to pursue this world,
the lust of the eye, and the pride of life, with great avidity, like other men.

But after all, whatever the inducement may appear to be,
or whatever may be seen in others inclining thereto,
the strongest ground of unbelief is in a man`'s own heart, and in the utter want,
or loss of true religion there.
To such as are inclined to reasoning, Satan is fully able,
successfully to pervert and misrepresent the doctrines of the gospel,
because when their minds are darkened and know not the Truth,
he can and does lead them to mistake his false radiance for the light of Christ,
and thereby induces a great reversion of views and sentiments, making light darkness,
and darkness light, before them.
Hence they become an easy prey to infidelity.
In this way I apprehend it was that some were seduced in the early days of our Society,
even such as had more self love and spiritual pride, than vital Christianity, to wit:
John Perrott, John Wilkinson, and others.
(See Sewell`'s and Gough`'s Histories.)

But we see how soon their anti-christian doctrines were
discerned and detected by George Fox and his contemporaries,
because the light and spirit of Christianity abode in them;
even a measure of that Spirit which trieth every spirit,
and is able to decide whether it be of God or not.
The judgment of Truth was thus placed upon the heads of
these innovators and great pretenders to spirituality.
And again, in more modern times, it was in the self-same way,
that Satan deceived and led away some in Ireland, and many in North America;
and it is believed that the facility of his victory over them,
was greatly owing to their self love, self righteousness,
and their great want of meek Christian principle.
Insomuch that by his transforming power, he succeeded in bringing them to suppose,
or to profess that they supposed,
that our first Friends did not believe in the true divinity
and reconciling sacrifice of our Lord Jesus Christ;
than which a greater absurdity, and perversion of things, could hardly be imagined.

For however the views of others as to the spirituality of religion,
were such as necessarily to lead our early Friends
to dwell much upon that part of the Christian doctrine,
and to insist on the leading of God`'s grace in the heart;
yet there is nothing more obviously foreign to the
truth than the pretensions of those Socinian seceders,
viz:
that our first Friends did not believe in the true godhead and manhood of Jesus Christ,
and in the blessed purpose of his sacrifice.
So that we verily know that these outbreakings,
cannot in the least degree be grounded upon any defect in our predecessors,
in any point of Christian faith concerning the offices and character of Christ;
for abundant evidence is deducible from their writings
to prove that such a defect did not exist.

As has been before suggested, the professors of Christianity in the time of George Fox,
had generally forsaken the spirituality of religion,
but were not in the least wanting as to a belief in the outward coming, the divinity,
and sacrifice of Christ.
Hence there was not that necessity of insisting upon
faith in this last-mentioned part of the Covenant,
respecting which there was no defect of faith,
as upon that part in which there was a deficiency;
and this their practice was according to Truth and sound reasoning.
For what skilful physician, being called to administer to a diseased person,
would not resort to such medicine,
as would tend to counteract the complaint that was already upon him,
rather than to administer to a disease under which he did not suffer,
and in which respect he was entirely sound and healthy.

Now, as the literal and spiritual parts of Christianity cannot be considered
by any truly enlightened mind to be opposing or contending properties,
any more than the body and soul of a perfect man,
so therefore there can be no necessary fear,
that to promote the right apprehension of the one could endanger the safety of the other.
To say that except a man has the spirit of Christ he is none of his,
does not gainsay the testimony that "`God was manifest in the flesh, seen of angels,
believed on in the world,
received up into glory!`" and I believe that the
more true spiritual Christianity a man has,
the better he will be qualified rightly to see and to estimate
the doctrines of Truth as contained in the Holy Scriptures
relative to the outward coming and offices of Jesus Christ;
and for this very reason I believe, and am abundantly convinced,
that our predecessors had much more of the true faith,
and had much clearer views of the meaning and standing of the Scriptures,
as well as of the true divinity of,
and the purposes of the sufferings of our Lord and Saviour,
than other professors of that day,
who were making a high profession of their faith in them,
but many of whom were wanting in spiritual and vital religion.
