== Letter VI. / On Plainness and Self-Denial.

[.salutation]
My Dear Friend,

My mind has often been brought into much painful exercise on account of the many
departures from the wholesome Christians testimonies of simplicity and plainness;
testimonies faithfully upheld by the Society of Friends in its earlier days,
and times of its greater purity; leading to humility and meekness,
and to the avoiding of pride and high-mindedness.
There is no difficulty in ascertaining from whence
these testimonies were drawn by our early Friends,
even from Jesus Christ himself, that great example of meekness and self-denial;
and the source too from whence every wholesome admonition,
and good and perfect gift are received;
and if through all good conscience we will "`observe whatsoever he commandeth us,
even to follow him;`" and what the apostles preached and observed also,
we shall find it needful to make a stand against the insidious pursuits of vanity,
and a worldly spirit, and a nurturing of the will of the flesh.

The apostle declared that "`the grace of God which bringeth salvation,`" teacheth
(also) the "`denying of ungodliness and the world`'s lusts,`" and this truth,
with the declarations of Christ himself, to wit, "`if any man will be my disciple,
let him deny himself and take up his daily cross
and follow me,`" and "`take my yoke upon you,
and learn of me,
for I am meek and low of heart,`" and that of coming to be a disciple
of Christ and wearing his yoke brings us to the denying of what
another apostle calls "`the lust of the flesh,
the lust of the eye,
and the pride of life;`" and it is by this practical self-denial
that the followers of Christ are distinguished from other people;
it is not what men say, or profess, that makes the true distinctive character,
for a man may think much, and believe much,
and rely much upon the sufferings of Christ upon the cross,
and at the same time be an utter enemy to the cross of Christ,
as it regards his own practical endurance of it,
a thing indispensable to a disciple of Christ; and it is very evident,
that there can be no true follower,
without possessing so much of the spirit and power of the cross,
as will work in him to the mortifying of the deeds of the body;
to the sanctifying of the spirit, and to the subjugation of the will of the flesh.

And a good degree of this experience is undoubtedly
witnessed by individuals under different denominations;
but the Society of Friends from the first,
found it needful to adhere to greater purity of manners than other professors had done,
in order to be more perfect followers of his example,
as well as of his doctrine of the strait and narrow way which leads to life;
believing indeed the verity and truth of his sayings;
and that his doctrines of the cross are unequivocal; and finding by practice too,
that the bearing of his cross patiently and honestly, did in very deed,
work to the mortifying of the deeds of the flesh;
hence as a people we have seen more clearly than others
the necessity of "`always bearing about in the body,
the dying of the Lord Jesus,
that the life also of Jesus might be made manifest in our body.`"
"`For we which live, are always delivered unto death for Jesus`' sake,
that the life also of Jesus might be made manifest in our mortal flesh. 2 Cor. 4:10-11.
`"

Whatever then may be the practices or sayings of others,
we feel bound faithfully to adhere to the commands and doctrines
of Christ and his apostles as recorded in holy writ,
as well as to the word of God`'s grace in our hearts,
to the denying of all desires after the maxims and manners, fashions and customs,
of this vain world.
And as this was a subject not unworthy of the Son of God, and his apostles,
in his and their preaching and personal simplicity,
none will do well in charging his more scrupulous followers with narrow-mindedness,
because of their conformity to the doctrine and practice of Christ and his apostles;
seeing that every one of his disciples should conscientiously keep his commandments,
and follow his example of meekness and humility.

Nor let any one be deterred from the practice of a self-denying
life because he may sometimes see traditional or hypocritical
professors trusting in a form of godliness without the power;
for there is not one of the Christian virtues,
but attempts have been made to counterfeit it;
and they also who make such attempts are enemies to the cross of Christ and him crucified,
which is the power of God, and wisdom of God,
and which also the apostle told one of the churches,
he was resolved only to know amongst them.

There was I think more than one reason why the peculiar
and primitive testimonies of plainness were given to,
and upheld by the Society of Friends; and first,
because they are congenial to the very nature of Christianity in its purest form,
and agree better with its other testimonies.
And secondly, because if conscientiously maintained,
they would serve to exhibit this constant acknowledgment to the world,
"`I am the Lord`'s!`" And thirdly,
because it would be an enclosure round about the tender plants of a rising generation;
for by observing these peculiarities in language, manners, and appearance,
there would not be that inclination to mix familiarly with others;
and this has proved to our beloved youth a great preservation
from the corruptions and vanities of the world.
In this point of view, the benefit to our Society has been incalculable;
for though it is not these peculiarities of plainness that cause us to be fruitful,
yet by them as an enclosure, the fruit may be kept from being devoured.
It is the good soil of the garden, well cultivated, that bringeth forth the fruit,
but it is the fenced wall of God`'s providence round about,
that keepeth it from being devoured by the creatures without.

And so far is this testimony from being a burden or a hardship,
it is through the gift of Him who helpeth, a choice blessing from his hand,
and a blessing too, which if we as a people should begin to despise and lightly esteem,
God will in his displeasure perhaps remove from us.
Yea, and if the vine which he has planted, when he looked for grapes,
should be found bringing forth only wild grapes,
he will certainly remove this safe enclosure, and suffer the wild beast to tread it down;
and he will also command the clouds that they should rain no rain upon it.
And as a small leak, if suffered to continue, will sink a ship,
however good and richly laden, and as a small breach in the enclosure of the vineyard,
however fruitful, will let in the devourer, so I believe if this testimony,
(however small any may deem it,) should be abandoned,
it would greatly endanger our safety.

Yea, and if the boundaries of demarkation between this people and others,
as exhibited in our peculiar testimonies, were removed,
or suffered to go down through the fear of controversy or of singularity;
then should we be prepared to go back, and mingle again with others,
and that definite and honorable characteristic by which
we have been known and distinguished from all others,
would be seen and known no more.
Hence I consider it highly important to be ourselves faithful, and to train up,
and instruct our families in these Christian testimonies, and other doctrines of Christ,
by a constant exhibition of this good and comely order and example, as well as by clear,
plain argument, and open and full declaration of the hope within us.

And if the true ground of the gospel of our Lord and Saviour in its primitive purity,
as seen by us, cannot be supported without controversy,
then let it be done in the meekness and wisdom of Jesus by controversy;
for the cause of the blessed Truth is worthy both of controversy, and of a warfare too,
under the banners of the Prince of Peace.
And to strengthen the minds of any, who might be wavering,
we may well refer them to the steady and unabating
exercises and advice of the Yearly Meeting in London,
for upwards of one hundred and fifty years past;
a body which has extended its concern and care over the whole Society,
for its preservation in the meekness, simplicity, and purity of the gospel, and which,
in point of religious knowledge, Christian authority, and weight of character,
has never been exceeded in the Christian world, since its establishment.

And now my dear friend, in the conclusion of these letters, I may well say,
that they have been written in the feeling of that love which knoweth no bounds;
and which hath for its object the true happiness and salvation of all; desiring that,
as I have written them in simplicity and tenderness of spirit,
thou wouldst permit them to receive a portion of thy consideration.
I feel a fervent solicitude that all may stand fast in the Lord,
and hold the profession of their faith without wavering, cleaving to the blessed Truth,
and submitting to its humbling power;
and thankfully receiving every provision of God`'s providence,
which is dispensed to us in common with others,
and holding fast too those which have been in a more
peculiar manner mercifully committed to us,
as the testimonies and statutes of the Lord were to a people formerly.
Then might we not all well say, "`Woe is me, that I sojourn in Mesech,
that I dwell in the tents of Kedar`" even in the land of Midian,
for the crown of his pride must be reduced in Jacob; yea,
and it must be brought down in Israel: and again: though Esau be thy brother,
and the Lord hath planted him upon his high mountain, and given him a place in the earth,
yet Israel must not dwell with him, nor abide there, for he must dwell alone.

And behold Moab also, his kinsman, for neither shall he join himself unto Moab,
however multiplied his burnt-offerings, and exalted his sacrifices upon his high places;
for Israel must abide in his tent, yea, even in his lowly tabernacle a little longer,
until the indignation be overpast; for the Lord is his tent and his tabernacle,
and it was he that first led him forth and allotted to him his possessions in the valleys,
and as the trees of lign aloes hath he planted him in his garden enclosed,
and made him fruitful as by the river side;
and if he will be content to dwell in the land where the Lord his God has planted him,
and keep his statutes, then the Lord will bless him still, in the midst of the nations,
and he will cause that no enchantment nor divination shall prevail against him,
and so shall he abide as a tabernacle that shall not be taken down.
And though many may forsake him and despise him, because he is small,
and his dwelling is in a low place,
and because the glory of this world shineth not upon the ark of his testimonies,
yet let him not be dismayed, the Lord is his light and God his glory;
and he will encamp round about him;
and his righteousness shall "`go forth as brightness`"
and his "`salvation as a lamp that burneth!`"

[.the-end]
The End.
