[short="Chapter VIII"]
== Chapter VIII. Second Visit to Europe, in 1853-4, and Conclusion of the Journal.

In the seventh month, 1852, during my wife`'s sickness,
I was surprised at the introduction of a prospect
of again visiting Great Britain and Ireland,
in the discharge of religious duty;
but the circumstances and position of our Yearly Meeting,
as well as my own standing with relation to those who have
departed from the original principles of Friends,
of which description consists the greater part, by far,
of those under our name in Great Britain and Ireland,
made the accomplishment of such a visit look difficult.
The concern however continuing with me, in the 4th mo., 1853,
I obtained a certificate from my own Monthly Meeting of its unity therein,
and an endorsement thereon by our Quarterly Meeting of its concurrence therewith,
in the 5th month.
This weighty concern was also opened in our Yearly
Meeting of Ministers and Elders in the 6th month,
and its full approbation and sympathy being expressed, a certificate was granted,
fully liberating me to proceed in that important
and apparently difficult service in those countries.

Considering my advanced age, it seemed indispensable that someone should bear me company;
and as no other suitable Friend presented,
my children concluded that one of their number would go with me, and, in the result,
my second son Amos C. Wilbur, gave up his business for the time,
and kindly consented to be my companion and sharer
in the tribulations attendant on such an undertaking.

[.offset]
+++[+++The following letter was received from his friend Lydia A Barclay,
before he left home on this important visit:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Aberdeen, 6th of 7th mo., 1853.

[.salutation]
My Dear And Valued Friend John Wilbur,

Your last letter, this week, has greatly comforted me,
in that you have been strengthened to see clearly,
and act faithfully and humbly in this awful matter,
and that way has seemed to open to go forward, and that you are preserved peaceful,
and like a servant waiting for your Master`'s further revealings and commands,
willing to obey them! and I was much struck with
the way in which you seem called to go--that is,
to London (as it were the heart and capitol of the enemy`'s kingdom!) first.
I see the heavenly Wisdom in the leading;
although the affectionate part in me longs to see you first,
and I had been hoping you might have recruited after your voyage
under my cottage roof! but I see now it is best otherwise,
so I must have patience.
I have been trying to think how I might help you in any way.
But oh! my dear and honored friend, you know on whom help is laid,
and who can hold up your head amidst all the billows--so I crave
you may be preserved from looking at what may await you,
but simply and humbly lean on him who has hitherto helped!
Oh! I earnestly crave, if consistent with the divine will,
that your bodily health may be kept up amidst it all,
for I know how greatly it is affected by suffering of mind.

[.signed-section-closing]
Your nearly united and affectionate friend,

[.signed-section-signature]
Lydia A. Barclay.

--

We went on board the steamship Niagara at Boston, under the command of Captain Leitch,
which left that port on the 28th of 9th mo., 1853,
and reached Liverpool on the 9th of 10th mo., eleven days at sea, mostly good weather.
On landing in Liverpool we went directly to the house of our dear friend Margaret Crosfield,
with whom, and her valuable husband George Crosfield, I lodged when before in England.
She received us gladly and very cordially, and made us as comfortable as we could be,
under the deep exercise of mind that lay heavily upon us,
with the prospect of very trying and difficult service before us.

Went to see Thomas Thompson the oldest and principal Elder in this place,
whose carriage towards us, and treatment, was apparently cordial and affectionate,
expressing a great deal of sorrow and pity for me, in my condition; but before parting,
seemed greatly disposed to discourage my proceeding on this visit, and to turn me back,
by telling me that my going into any meetings of
Friends in this country would be very dissatisfactory,
and that any attempt to speak in them would be more so;
he also expressed a doubt of its being borne with,
and averred that I was not a member of the Society of Friends.
I observed to him, that a person who had transgressed no discipline,
but was dealt with and disowned in violation of discipline, was, nevertheless,
rightfully a member of the Society, according to the discipline,
both of New England and Old England;
and inquired of him whether he had unity with J. J. Gurney and his doctrines,
to which he replied, that he had good unity with him as a Gospel Minister,
and that his writings were very much unexceptionable!

Hereupon I cited to him several items which stand in contradiction to Robert Barclay;
to which he replied,
that there were several passages in the Apology from which he dissented.
He raised a general charge against the controversial writings of the early Friends,
which evinced, as he said, too much bitterness of spirit, adding,
that many of these writings were more fit for the fire than for the public eye,
including many of the writings of George Fox and those of Edward Burrough by name,
and not excepting any in this general animadversion.
I observed to him that the Almighty always had, from the beginning,
a controversy with all evil,
and consequently all his faithful servants had to
proclaim it and to bear testimony against the evil;
and cited him to the holy prophets and to Christ himself, and his apostles,
who testified with no less plainness of speech, against the iniquities of men,
than did the early Friends; hence,
I said I see no more reason for accusing the early Friends with bitterness in
controversy than we have to charge the holy men of old with the same thing.

On Fifth day morning the 13th, we went to Manchester, and sat their week-day meeting,
in which I had no opening in the ministry,
but was induced to believe that there were some present who were
endeavoring to worship the Father in spirit and in truth.
At the close of the meeting, many Friends of the foremost rank gathered around us,
and shook hands very cordially, some of them inviting us to their houses.
We went home with our dear friend Hannah Harrison,
the widow of the late honest and faithful John Harrison,
who supported the cause of Truth, regardless of consequences.
She is granddaughter of the Jane Crosfield,
at whose house John Woolman speaks of resting a few days.
She is an honest, agreeable woman, and a true Friend.

A number of the Friends alluded to came and spent the evening with us at H. H.`'s,
with whom we had much agreeable conversation;
and they desired to know what my general or particular prospects were.
I told them, as to particulars, I could not tell how I might be led,
but my general prospects were not to be stirring up strife,
but to attend Friends`' Meetings, and if way opened for it, to labor therein,
as I might be led; with which they seemed satisfied.
I also told them that no small object in view was to visit the seed,
and to strengthen the things that are ready to die.

Sixth day, the 14th, Elizabeth Midgely, a ministering Friend of Rochdale,
called to see us; she appears to be of the primitive stamp,
and expressed a desire that the peace of God might abide and remain with me.
I saw her father and grandfather, both living when I was in England before,
but now both deceased--her father quite recently.
Last evening a young man from Leeds, by the name of Daniel Pickard, called to see us,
who said that when he heard of my coming again to England,
it warmed his heart within him--and expressed a strong desire for us to come to Leeds.
Our dear friend Lydia A. Barclay came here on sixth day, greatly to our comfort.
I became acquainted with her twenty-one years ago, and upwards,
and have corresponded with her frequently since,
but had not expected ever to see her face again in mutability,
until since this prospect opened in my mind, which made the meeting more interesting,
she being faithful to the ancient doctrines of Friends.

We stayed here and attended their two meetings on first day,
in which I had nothing given me to communicate, but she had a short,
lively testimony in the afternoon.
I was abundantly satisfied in the will of my divine Master,
that silence should be my lot,
and am convinced that it did more for the promotion of the cause of Truth,
under the present circumstances in this place, than could have been effected by any,
communication by me, at this time.
Many Friends were very affectionate and loving,
and we were invited to a Friend`'s house to tea,
where were assembled about twenty Friends,
by whom much unity with me was freely expressed, and felt to prevail,
as well as much sympathy on account of the great sufferings
and afflictions which had fallen to my lot.
J+++.+++ B, a minister, and the only one here, was one of the company.
We were in company, while here,
with a considerable number of Friends who seem resolved to hold fast to sound doctrines;
and to have a hope that the current of unsound doctrine
is rather on the ebb in this land.

On second day morning we parted with dear L. A. Barclay and H. Harrison,
and took the cars for Birmingham, ninety miles;
and a more peaceful and joyful day I think I never had than this--the
fruit of obedience to the Divine mind and will at Manchester.
My heart was indeed full of praise and thanksgiving to the name
of Him who had thus marvellously kept and directed me,
and turned my great afflictions and anguish of spirit, into joy unspeakable;
and the glory was ascribed to everlasting Goodness.
At Birmingham, we were kindly and affectionately entertained by Samuel King and family,
where also came in his brother William, Eliza Brady, and Henry Kenway; the latter,
on parting,
expressed a hope that I might be favored to fulfill
the purpose of coming over on this visit.

On third day, 18th, we went to London, by railway, one hundred and thirteen miles,
and put up at a boarding-house, kept for Friends, by William Hughes.
Fourth day, Robert Forster and Samuel Cash,
members of a committee of their Meeting for Sufferings,
appointed in anticipation of our coming, called to see me,
ostensibly for the purpose of dissuading me from the pursuit of my concern;
they referred to my standing as a disowned member,
and separated from the body with which they correspond in New England, and are in unity,
adding, that if I attempted to speak in any meeting, the audience would be informed,
at the close, that I was not a member of the Society.
I told them that according to both their discipline and ours,
if a person was dealt with and disowned, contrary to discipline,
his right of membership was not annulled or prejudiced thereby;
and that Philadelphia Yearly Meeting had clearly shown that
my disownment was palpably at variance with our discipline.
R+++.+++ F. said that all Yearly Meetings were independent bodies, and consequently,
they had nothing to do with New England Yearly Meeting, whether right or wrong.

I replied,
that we would suppose some one of the Yearly Meetings
had departed entirely from our doctrines,
and wholly disregarded our discipline,
whether London Yearly Meeting would hold itself bound to sustain the unity,
and continue the correspondence?
On attempting to reply to this question,
he found so much difficulty that he speedily turned from it.
But I asked him how they knew which was the genuine Yearly Meeting of New England,
seeing they did not go into an official examination of the case?
He said they knew by the names of the correspondents.

He was then asked, that seeing there was great dissension in New England at the time,
how he knew those correspondents were on the side of Truth?
To this, there was no less difficulty in answering than before.
But he said that no Yearly Meeting had any right
to inquire into the proceedings of another;
in reply to which,
he was reminded that both bodies in New England appealed
to London for the decision of the controversy,
and both offered their arguments to prove the legitimacy
of their claim to be New England Yearly Meeting of Friends,
it being agreed that there could be but one.
And inasmuch as both parties submitted the decision of the case to London Yearly Meeting,
that Meeting had a plain, full, and just right,
and it became their duty to investigate the case, and then judge,
whereas they had refused to make such investigation,
and had come to a decision without it.

Here, again the difficulty of answering occurred.
But, to refer to the forepart of the conference again,
they asked what my prospect of service was.
I told them, to visit the Meetings of Friends, and to appoint some among other people;
not with any view to stir up strife, but, if required by my divine Master,
to preach the doctrines of true Christianity;
which I had no hesitation in saying were fully believed and practised by our first Friends,
and demonstrated by their writings to be the doctrines of true Christianity,
as set forth in the New Testament.
And reference was made to the modern doctrines sent abroad by one of their number,
which had been the principal cause of dissension and disunity in America.

They attempted to excuse the Society from responsibility on this ground,
by saying that it was the business of the Monthly
Meeting where the writer resided to see to that:
well, suppose the Monthly Meeting do not see to it?
why then it falls upon the Quarterly Meeting; well,
suppose the Quarterly Meeting do not notice the case, what then becomes of it?
which again brought hesitation.
Well, then, I said, I should think that the Yearly Meeting,
or the Meeting for Sufferings, or the Morning Meeting,
must necessarily be responsible for the publication of such doctrines,
as the constituted guardians of the testimonies and doctrines of the Society;
to which no direct reply was made.

And the reasonable and undeniable ground was taken by us
that the Yearly Meeting of London does stand accountable
for the great trouble and dissension in the Society in America,
because it has allowed its members to publish and send there,
doctrines which are contradictory to the doctrines of Friends,
which unsound doctrines it was in their power to have suppressed,
and which it was their imperative duty to suppress.
This stands as a great delinquency of duty against
London Yearly Meeting and its Meeting for Sufferings.

The subject of judging a case without a hearing was brought before them,
or even without an inquiry into the circumstances and claims of the parties,
showing that even the heathens were more just than to do so;
than to do as many of the Yearly Meetings had done, in judging the New England case.
They had a special law and usage among the Romans, before the Christian era,
that no man should be condemned without a fair trial, or without a hearing;
of which R. F. and S. C. were reminded;
and they were also reminded how altogether better qualified a tribunal must be,
to give a righteous judgment, after examining and hearing a case,
than without taking such steps--that Philadelphia Yearly Meeting had investigated
the matter of our right to attend Meetings for discipline abroad,
and determined that we have that right.

Fifth day, the 20th, we were invited and went to Tottenham,
dined at R. Forster`'s and took tea at G. Stacy`'s,
tarried there all night and on sixth day morning called on Edward May,
then returned to the city,
and went at eleven o`'clock to meet the whole committee
of the Meeting for Sufferings at their request.
This committee consisted of eight members, Robert Forster, Samuel Cash, George Stacy,
Samuel Gurney, Peter Bedford, Thomas Norton, Samuel Fox, and Thomas Chalk,
seven of whom were present.
R+++.+++ Forster opened the case by saying that on fourth day he and
Samuel Cash had informed John Wilbur that the committee were unwilling
that he should attend the meetings of Friends in this country,
and that if he attempted to speak in them,
the meeting at the close would be informed that he was not a member of the Society,
which conclusion was approved by several of the committee.

I informed them that myself and companion came there by
the request of two of their number for the purpose of conferring
with them on the subject introduced to us on fourth day,
and supposed that, as they did not admit that we were members of the Society,
they would not claim to have any jurisdiction over us; and subjoined,
that in this conference we would answer all reasonable
questions that they should see fit to propound;
and hoped that in the same freedom they would give
us such reasonable information as we might desire,
to which, I think they made no reply.
They said a good deal of the sympathy they felt for us,
nevertheless that they could not do otherwise than reject me as a minister,
inasmuch as I had been separated from the body in New England,
which London Yearly Meeting had decided was the true body of Friends there;
but it was suggested by us that the decision of that
meeting (London) was liable to be incorrect,
seeing it was done at once without an investigation
of both accounts sent from the two bodies;
to which they replied, that they had nothing to do with that matter.

We told them that Philadelphia Yearly Meeting having
instituted a careful and impartial inquiry,
decided that the larger body had in many instances, in their proceedings,
violated the discipline, and their acts had been oppressive,
and subversive of the rights of individuals etc.--to which little or no reply was made.
Subsequently,
I told them that if they carried out the conclusion
come to of publicly saying in the meetings,
that I was not a member of the Society, we should be under the necessity of explaining,
in some way or other to Friends in this country,
the whole affair of my pretended disownment;
and that I felt it right at the present time, if Friends would be patient to hear me,
to go into a brief defence of my case; and although some expression of dissent was heard,
yet after a short pause, I stood up,
and observed that their discipline and ours (in that respect alike) decided that
if an individual was dealt with and disowned in a manner contrary to discipline,
his right of membership was not impaired thereby, even if he had done things improper,
(because the error of the church tends to greater evil than
the errors of an individual;) but that in this case,
abundant evidence could be adduced to prove that the error
was exclusively on the part of those who dealt with,
and disowned me.

This has been demonstrated by those whose rights were wrongfully taken from them;
and clearly and ably shown to be so by Philadelphia Yearly Meeting, who,
although they may not be considered here, so competent as London,
yet the deliberate examination of all the particulars and circumstances of the case,
entered into by them, preponderates largely in favor of awarding to Philadelphia,
a just and legitimate decision of this case, as set forth in their Report of it,
and summed up in that part contained between pages 29 and 38.

And besides, that I attended that Yearly Meeting in 1852,
even after the case was so plainly stated and decided in the document here alluded to,
and an objection was made on the first day, to my sitting in that meeting,
and the subject pretty fully discussed,
and when all appeared satisfied with speaking on both sides,
the clerk at the table decided that I had a right to a seat in their meetings for business;
and I further stated,
that at that time I found no obstruction to attending
their subordinate meetings for business,
and appointing meetings in Friends meetinghouses, when occasion offered,
which was frequent.
I also told them that in New York Yearly Meeting,
very similarly situated to this in England in most respects,
I was allowed to relieve my mind at all times freely,
and that I always left them feeling better towards me than when I first met with them.

And further, that those of other societies in our land,
had always (with a single exception) freely opened their houses,
and heard me patiently and gladly, although they do not see with us eye to eye;
but the savor attending the communications of real Friends on such occasions,
makes them generally satisfactory.
I then recurred to the entire coincidence of the
doctrines of Friends with primitive Christianity,
and stated that I had no hesitation in believing them to
have been satisfactorily proved to be pure Christianity,
by the early writers in the Society,
and practical in their working and operation on the mind of man;
and that when lived up to, they will lead, and did lead our forefathers,
as their memorials abundantly show,
to a triumphant conclusion and translation to a glorious immortality;
and I expressed a fervent desire that Friends everywhere,
might adhere to these dignified Christian doctrines.

But inasmuch as the larger body in New England hold that the modern views,
added to the ancient, are an improvement, and make out a more perfect system,
and as these new views came from this side the water, I would desire Friends here,
if they have indeed found an improvement upon the doctrines and testimonies of Friends,
(being so competent to set it forth,) that they would furnish us therewith,
that we might carry it over to our people in America;
and said to them that it was a satisfaction to me to have
the opportunity thus to explain my own standing in America,
and the concern which I felt for the safety and prosperity of all those under our name,
and could have desired that a greater number of Friends might have been present.

[.offset]
+++[+++The foregoing is a summary of the conversation, which occurred,
as near as could be remembered, and is substantially correct.]

On seventh day we went to Lewes, and from there to our friend John Rickman`'s,
at Wellingham.
He and his wife and family were truly kind to us.
His daughters Rachel, Priscilla, and Matilda are valuable Friends,
the two former acceptable ministers.
We attended both their meetings the next day, the first a pretty open time;
and we lodged with this dear family until fourth day,
when we attended their week-day meeting,
in which I was raised up in testimony in a comfortable and relieving manner.
At this place was the first of my opening my mouth
in the ministry since landing in England,
that is, in a meeting for worship.

On fourth day, the 26th, went to Brighton, where we lodged at Daniel P. Hack`'s,
and next day attended their meeting, where Grover Kemp placed us on a low side seat,
but where I had a short lively testimony, citing the people to Christ,
our Saviour--to be adhered to in preference to man.
At the close, a man named Charles Tyler said to the meeting,
that "`this man who has spoken so much to us, is not certificated,
nor a member of the Society,`" to which I replied
that I supposed Friends did not understand the case,
and if desired, it would be explained after meeting.
But they were very shy of us, scarcely one offering a hand,
and none inviting us to their houses.

After meeting we had much conversation with D. P. and E. Hack, and found them,
contrary to our expectation, decidedly for the new doctrines.
He said that I ought to have submitted to my disownment,
and continued to meet with those who had disowned me;
and now thought it wrong for me to proceed any further in this way,
but that I ought to return directly to America.
I heard him patiently,
supposing it was something he had in charge from those whom we had seen in London.
When he had done, I stated the case to him,
substantially as I had stated it to those in London;
upon which they seemed to grow pensive, or otherwise were confounded,
and knew not what to say; but, to do them justice, they treated us very kindly.
At parting he expressed a great desire that they with me might be favored to
meet in Paradise--that we might do nothing that might deprive us of such happiness;
to which I replied that I could freely subscribe to this.

Not having fully relieved my mind while with these friends,
I wrote them from Dorking as follows:--

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Dorking, 10th mo., 30th, 1853.

[.salutation]
My Dear Friends Daniel P. And Eliza Hack,

We hardly feel satisfied to get entirely away from your quarter without acknowledging
on paper your almost unexampled kindness and attention in sustaining us and making
us comfortable so long in the good things which this world affords;
and also to reciprocate the kind concern which D.
manifested on our parting for my well being.
Nothing more could he have desired or asked for the dearest friend he has in this world;
and I thought it most probable that it might be on account of his
apprehension of the danger that I am in of missing the great end
of our existence--the attainment of life eternal.

And if so it made his remarks the more kind and interesting.
But, under whatever apprehension they were made,
I can again respond thereto and thank him for his
good will and good desires for my everlasting happiness.
And truly my dear friends I do also feel concerned for you,
and for all like you who are "`to give account`"
for the faithful performance of their stewardship,
as watchmen at their posts upon the walls of our Zion--to blow the trumpet,
giving it a certain sound, not giving the token for peace when an enemy is approaching,
or even within the camp.

Oh! if the sentinels should through an apprehension of great safety fall into a slumber,
then will our old watchful foe perceive it, and will not fail to take advantage of it,
as he is at this day working most insidiously in the dark,
yet crying peace! peace! even in the day of imminent danger to the Lord`'s people.
I perceive that you have not much if any concern
about the modern doctrines abroad in the Society,
although adverse and contradictory to the dignified and fundamental doctrines of Friends,
which latter have been proved most fully and most clearly,
not only by many early writers but by those of later time to be in perfect
accordance with the doctrines of our blessed Lord and his apostles,
in which a true and living faith is essential,
in order for a correct walking in that holy way which leads to eternal life.

That eminent apostle Paul saw the necessity of guarding against every appearance of evil,
well knowing the tendency of the unrighteous leaven (though
never so little) to increase and leaven the whole lump.
This understanding of the apostle undoubtedly led him to protest most
decidedly against the introduction of unsound doctrines into the church.
"`If any man or an angel from heaven bring in any
other doctrine than that you have heard of us,
let him be accursed;`" and the apostle John writes to the same purpose.

And I was surprised to find you with those testimonies before you so indifferent
as to the dangers which are consequent upon such introduction of error--such
contradiction of fundamental doctrines as have been brought in.
Or can it be that your apparent indifference is owing to your having adopted
the new doctrines believing them to accord with the doctrines of Friends?
Inasmuch then as either indifference or deception and false views must endanger
the well-being of those who have known the Truth as it is in Jesus,
I do feel concerned for you who I am persuaded have had clearer views; indeed,
too clear a vision to be misled by the devices of men, principalities or powers.
And I do desire, my dear friends,
that you would go directly to the blessed Master who has the light of life,
which if you do unreservedly,
I hope and trust he will give you to see the snare which the enemy lays for our feet.

It was for my loyalty to the true doctrines of the
gospel as professed and demonstrated by Friends,
and to the discipline and testimonies of our religious Society,
that I was reprehended by false brethren in New England,
who inflicted the most cruel punishment in their power upon me,
and even separated me from their community because I testified against those fake doctrines;
thus furnishing clear and undeniable evidence that
they themselves had received and believed in them.
And as it is unreasonable to suppose that any body of professing Christians would
excommunicate a member for denying a doctrine which themselves do not believe,
(it being a contradiction in terms,
and a thing which the best or worst never do,) we then have it
clearly demonstrated that the "`larger body`" in New England hold
to the doctrines which they persecuted me for refusing,
and of course are not Friends.

And would it be marvellous if the Head of the church should yet raise up and
anoint some who belong to no society to go into your meetings in England,
and preach Christ just as George Fox preached?
agreeably to scripture testimony "`Aliens shall be your ploughmen,
and strangers shall stand and feed the flocks.`"
Greatly desiring your present and everlasting good I subscribe
myself your real and much interested friend.

[.signed-section-signature]
John Wilbur.

--

On seventh day, the 29th of 10th month, we came to John Cheal`'s, near Ifield,
and lodged, and next day he and wife took us to Capel Meeting,
where we met with a little number of dear sound Friends;
and although I went there in the greatest degree of poverty and weakness,
yet on sitting down at the Master`'s bidding the water became wine,
and out of weakness there came forth strength, and a memorable time we had together.
Much encouragement was offered to this little number,
on condition of their faithful devotion to their divine Master and to his cause;
and in the course of this service, a prophetic view of things to come was opened,
and a belief was expressed that the Lord was on his way to get him honor,
and that he would overturn, overturn, overturn, until his own work shall be accomplished.

After this meeting we dined at John Dale`'s, and he took us to Dorking,
where we attended their afternoon meeting,
in which my mouth was opened on the remarkable analogy
between the light of the sun in the firmament,
the outward light, and the light of Christ; of Him who said,
"`I am the light of the world, he that follows me shall not walk in darkness,
but shall have the light of life`"--a spiritual and inward light.
As the material sun is the light and life of the outward man, and the outward world,
so the Sun of Righteousness is the light and life of the inner man.
And as a future life is of eternal duration, and this but short,
that which would fit us for the former,
must be of infinitely more importance than anything
which contributes to the support of the latter.

The forlorn condition of man if he were totally deprived of the material sun,
which enlightens and warms the whole earth, was set forth,
and compared to that of an exclusion, through unbelief,
from the shining of the Sun of Righteousness, so essential to the life of the inner man,
and to his growth and fruitfulness in the Lord`'s heritage.
And considerable was also said of the great necessity of a change of heart,
and of the breath of divine life being breathed into the soul,
to the effecting of our salvation.
We were not interrupted in this meeting,
though by far the greater part appeared to embrace the new doctrines.

We stayed here at George Hayman`'s until third day, the 2nd of 11th mo.,
when we left Dorking, and went to Croydon, and put up at a public house.
In the evening, called on Peter Bedford, who professed much kind feeling,
but was very rife in his accusations, and discovered underneath,
much bitterness of spirit, savoring too much of his,
who was called the accuser of the brethren.
He affirmed that I told him, when I was at his house in 1832,
that there would be a division in the Society in England,
and that Charles Osborne would bring it about.
On my firmly and confidently denying the charge, he gave it up.
But one thing we gained by going to see him, we brought him to confess the truth,
as to his faith.
He and Thomas Norton both acknowledged their full belief in the doctrines of J. J. Gurney,
neither of them having any ears to hear anything to the contrary.

Next day we attended meeting at Croydon,
and therein referred to Christ`'s exhortation to one of the churches, namely,
"`Hold fast that which you have,`" referring to the circumstance that
there had been a direct communion between the heavens and the earth,
through the days of the Patriarchs and the Prophets;
that God had continued to reveal himself through Jesus Christ,
immediately to his creature man,
but that the professing Christian church had become enveloped in darkness;
and since that time, by reason of the unfitness of its professors,
the testimony of Jesus, which is revelation,
had been much withheld therefrom until our early Friends were prepared to receive it,
and to walk faithfully by its guidance, as the rule of life,
and thus this unspeakable blessing to the church was again restored;
and how exceedingly essential is it for her that "`she hold fast that which she has.`"

And the Saviour`'s invitation on a certain occasion, was brought to view,
"`If any man thirst, let him come unto me and drink.
He that believes in me, out of his heart shall flow rivers of living water;
but this he spoke concerning the Spirit,
which they that believe in him shall receive,`" for no man can impart it,
unless he receive it.
And the glory of this dignified principle was further illustrated
by our Saviour`'s doctrine concerning himself;
"`I am the true shepherd; the true shepherd puts forth his own sheep,
and goes before them, and they hear his voice,
but the voice of a stranger they will not follow.`"

We became acquainted, while here, with a number of honest-hearted Friends.
The measures resorted to, to destroy our influence,
and to prevent our service for the Truth, produced no small sensation among the people,
and tended to bind the honest ones more closely together,
and cause them the more fully to sympathize with us.
P+++_______+++ B+++_______+++ did what he could at the close of the meeting, to reproach me,
and thereby to destroy the effect of my testimony,
without any reference to what I had delivered in the meeting.
We had several precious opportunities with the faithful Friends here,
to their great comfort and strengthening, and to our satisfaction.
At these times we also had the company of several dear Friends from Dorking and Capel,
where we had been.

On fifth day, the 3rd, went to London again and put up at William Hughes`'s as before.
On sixth day, the Meeting for Sufferings again met,
and took up the subject of our continuing to attend their meetings,
and enlisting the sympathy and kind feelings of so many Friends.
At this time,
it seems they undertook to lay a greater restraint upon Friends receiving us,
and formed a minute of their advice to all their members through the nation;
and Robert Forster and Samuel Cash were appointed to see us again,
and read to us their proceedings.
On their doing so, I requested a copy, which they promised to furnish.
We had much free talk with them,
and drew them out to a full confession of their unity with J. J. Gurney and his doctrines;
and they hesitated not to defend some of the most absurd of them, which I quoted,
but pretty soon, Robert desired that I would quote no more!

[.offset]
+++[+++The following is a copy of the Minute referred to:]

[.embedded-content-document.minute]
--

[.blurb]
=== At a Meeting for Sufferings, held 4th of 11th mo., 1853.

This meeting thinks it proper to remind Friends in the different parts of the nation,
that in the year 1829, a minute was adopted by our Yearly Meeting,
to the effect that no individual coming from America was to be
at liberty to travel among us in the work of the ministry,
until his certificates had been authenticated by this meeting.

Information is received by this meeting that John Wilbur,
formerly a member and a minister in New England Yearly Meeting,
is arrived in this country and has been visiting some meetings
of Friends in the professed character of a minister.
No certificates on his behalf have been presented to this meeting,
and through a communication received from the Meeting for Sufferings in New England,
this meeting is officially informed,
that John Wilbur is not a member of our religious Society.

Under these circumstances, and in accordance with the minute of the Yearly Meeting,
by which this meeting is entrusted with a general care of whatever
may arise during the intervals of that meeting affecting our religious
Society and requiring immediate attention,
this meeting feels it to be its duty to put Friends on their guard,
against doing or allowing any act not in accordance
with the true Christian order of our religious Society,
or with the decision of our own Yearly Meeting in the year 1846,
when it recorded its conclusion not to receive a communication
from the body which had seceded from New England Yearly Meeting,
and with which body John Wilbur is now connected.

This meeting trusts that Friends everywhere, acting in the meekness of wisdom,
yet in the firmness and consistency of Christian
principle and in accordance with gospel order,
will carefully refrain from admitting John Wilbur into our Meetings for Discipline,
or accepting him either in our meetings for worship,
or in our families in the character of a minister.

[.signed-section-closing]
Signed on behalf of the meeting,

[.signed-section-signature]
Robert Forster, Clerk.

--

On first day, 6th, we went to Devonshire House Meeting,
where an openness to receive us was seen and felt,
and much openness to declare the Truth among them, was witnessed.
The subjects of prayer,
of sincerity--a prominent characteristic of Christianity--and
of doing the divine will on earth,
as it is done in heaven, were opened and enlarged upon,
and it was shown that the primary Christian intention, as also that of our early Friends,
was to establish a church below, pure and holy, resembling the church in heaven.
After meeting, a great number of Friends of both sexes, gathered round us,
with smiling countenances,
giving us their hands in a manner which gave testimony of their unity of feeling.
In the afternoon, attended Westminster Meeting, throughout which great darkness,
as a thick covering, was over us.
A formal, lifeless prayer was made;
but it did seem to me that there was no help for them, as a body;
therefore I was not allowed to speak to them.

Second and third days I was much unwell, but went as far as Tottenham on the latter day,
where we took lodgings at a tavern.
On fifth day, the 10th, went to their meeting here,
and was led to recur to the efforts which the enemy
had always made to frustrate the Lord`'s good purpose,
in causing an advancement unto righteousness among men,
and in gathering to himself a people who should serve him, and do honor to his holy name;
referring to the Israelitish church, formed in Moses`' time, and to the Christian church,
established by our Lord and his apostles, and how Satan did bestir himself,
and how lamentably successful he was,
in causing the Lord`'s people to depart from his law,
and from his covenant and in bringing them under the power of darkness.
And that, since primitive Christianity was revived by our first Friends,
his efforts had not been lacking,
to seek for the destroying of the doctrines and testimonies of the Truth,
as held by them.
I exhorted Friends to be aware of his designs herein, and was much enlarged in testimony.

At the approach of the Meeting for business,
(for it was their Monthly Meeting,) one Paul Bevan said,
"`the person present who had intruded himself upon the meeting,
was not a member of our Society.`"
Dr. Edward May, a minister, said,
"`he did not think that which had been offered in that meeting
was any intrusion,`" and a Friend who sat back said,
"`he agreed with E. M. that there had been no intrusion;
for that he had good unity with what had been said.`"
As I rose up to leave the house,
I said that if the Friends of that meeting did not agree with me in principle,
all I could say was, that I was sorry for it.
Two Friends followed us out, and said to us, that there were many in that meeting,
who were united with us in sentiment, and both invited us to their houses,
with one of whom, William Edmonds, we dined, and took tea with Dr. May,
at the request of himself and wife--found them apparently sound,
but afraid of a separation.

This fear has been so industriously and universally
instilled into the minds of Friends in this country,
that if ever the honest ones are delivered,
it must most likely be in some other way;--a way perhaps not altogether
hidden from those whose eyes have been anointed to see clearly.
The younger class of the Society seem rapidly leaving it,
so that very few of the families, even of the leading men, are now left in the Society;
and no marvel, for they have opened a wide door for it;
and themselves are going off the stage of action, so that, by and by,
there may be none left to oppress the honest-hearted.

[.offset]
+++[+++The following letter from Lydia A. Barclay, to his daughter at home,
gives some further account of his trials and services at this time:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Aberdeen, 10th of 11th mo., 1853.

[.salutation]
My Dear Friend,

Your dear father is in the Lord`'s holy keeping I cannot doubt,
and shall not be forsaken or made desolate,
but shall be as the apple of the eye kept from hurt;
and I have often in regard to him remembered that expression, "`Touch not my anointed,
and do my prophets no harm.`"
I had been very anxious about him,
and it was an unspeakable relief to me to hear he was favored to land in safety;
and on the 14th of last month I went to meet him in Manchester,
and was sorry to find I had by mistake of post missed him a whole day,
not knowing he was there.

We met at the house of the widow of my nearly united friend, John Harrison,
a true valiant in the Lamb`'s army, not a mere fireside warrior!
Ah! I cannot tell you how rejoiced I was to see him,
we embraced each other in that pure love and holy fellowship,
which neither the mighty waters of the ocean, nor yet the floods of affliction,
can ever quench, nor had they quenched,
during the twenty-one years that had elapsed since we last parted in London,
after a sweet time of heavenly feeding and strengthening together.
There are but few left now of that interesting party; and what is worse far,
that which your dear father had been made to foretell, has come to pass exactly.

He attended Manchester Meeting three times in silence,
sitting under the gallery (to my great trial to sit above him).
Two dear Friends made way for him above, but a third, an elder of the modern school,
pushed them on, and permitted it not.
We dined at our quarters, and several came in to see him, and on the same evening,
we took tea at the house of one of the above elders;
where we met twenty of such as uphold our ancient principles,
and a sweet evening we had sharing his converse,
which partook much of a ministerial character,
(a thing much out of date with us nowadays,
the glory having sadly departed from our Israel!) but more than all,
there was a feeling of the dear Master`'s presence and power over and among us,
that cemented and strengthened us together:
and we parted with comfort and praise in our hearts.
Next morning we reluctantly parted; we went homeward, and they went on by Birmingham.

I may here say that your dear father is greatly bowed and
shrunk by age in these twenty years of deep affliction,
but his vigor of mind, and lively zeal,
and courage to go forth to battle for the precious cause`'s sake, appears to me unabated.
I thought there seemed at Manchester much curiosity to see and hear him;
and Friends must have been quite unprepared (by the many evil reports spread
latterly against him) to see such a sweet placid-looking old patriarch,
so humble and unobtrusive.
I do trust his visit may do away with much prejudice, and open the eyes of many,
as well as be the means of comforting and strengthening
the rightly exercised and tribulated remnant among us.

My dear friend, how awful does it seem to me that any should reject his ministry;
surely the dust off the feet of the truly anointed servant;
shall rise up at the day of judgment against these rejecters!
And is it not said it shall be more tolerable for Sodom and Gomorrah,
than for those where this is the case?
I tremble for these Friends; surely it will be brought home to them at a future day!

The Meeting for Sufferings finding that the means they had hitherto adopted had failed
to deter Friends from receiving him in their house and associating with him,
have adopted a more vigorous expedient, namely,
to print and largely circulate a Minute of theirs,
charging Friends to refrain from receiving him into their meetings and houses as a minister,
and saying they had official information from America,
that he had been disowned by that Yearly Meeting,
with which our Yearly Meeting is in unity, and corresponds!
And they sent two of their number to hand the same to him;
and Amos says that in the course of the conversation that ensued,
they avowed their approval of and unity with J. J. Gurney`'s writings,
especially with that sentence where he condemns Barclay, Penn, and Penington!

So you may see in what a state our poor Meeting for Sufferings
is,--not worthy the honorable name of Quakers!
There is no seeking for the wisdom or judgment of Truth,
though there may be at times a slight mock show of it!
You know better than I can describe (having tasted thereof)
the great affliction of belonging to such a mixed church!
But I trust in the Lord`'s time we shall be delivered and purified; and oh! says my soul,
may it be in his will, time, and way, and not ours,
nor by any wisdom or activity of the creature, that no flesh may glory in his sight,
but that the praise, thanksgiving,
and glory may all flow unto his holy and ever blessed name!
Oh! to be preserved humble, watchful, and faithful; and the good end that crowns all,
and is peace, shall be obtained through unbounded grace!
Your dear father was likely to visit a few of the meetings in and about London,
and then to go towards Suffolk and Essex, I believe.
My cry is daily for his help and preservation,
and I have a humble trust it will not go unanswered, to the ears of the Lord of Sabaoth,
who is pitiful, tender, and all powerful.

[.signed-section-closing]
Your sincere and affectionate friend,

[.signed-section-signature]
Lydia A. Barclay.

--

On sixth day went to Sudbury, and lodged at John King`'s,
and on first day attended their meetings.
In the morning, had a very open time,
in referring to the perils which had ever awaited the church, in all ages,
but particularly citing the account in Holy Writ, of Israel on the borders of Moab,
and of the purpose of the King of Moab to destroy them, calling on Balaam, saying,
"`Come curse me Jacob, come defy me Israel;`" following the account,
that when Balaam lifted up his eyes, and saw Israel abiding in his tents, he exclaimed,
"`there shall be no enchantment against Jacob,
nor divination against Israel;`" mentioning, also,
that a place of safety was always desirable for the Lord`'s people, and quoted the words,
"`The Lord is your tent, O Jacob, and your tabernacle,
O Israel,`"--that here is our only place of safety in times of trouble, etc.,
and was much enlarged on several Christian doctrines.
Here, notwithstanding the edict from the Meeting for Sufferings,
prohibitory of their receiving me, as a minister, had come to hand,
they assigned to me the "`top of the meeting,`" (as
they call it here,) and made no objection to us,
in any way.

On third day we went to Bury, and there attempted a public meeting, which,
on account of a noted lecture, failed for that evening; and next day,
being their market-day, we could not have it, and so we left for Bakewell, in Derbyshire;
where we arrived on sixth day night,
and were received gladly and affectionately by Friends there;
we lodged at William Gauntley`'s. On first day morning, the 20th, attended their meeting,
to good satisfaction, and notwithstanding the effort of the Meeting for Sufferings,
I was received with marked approbation in the fellowship of the gospel,
by these honest-hearted Friends at Bakewell, who cheerfully assisted in obtaining for me,
a meeting for the inhabitants of the town, which was a very large gathering,
and proved to be a truly satisfactory meeting, in which Christ was preached,
in the demonstration of the Spirit.

On fifth day, the 24th, went to Monyash, and attended their mid-week meeting,
having good, open service among them, they receiving us cordially and affectionately.
Returned to Bakewell, and on seventh day, the 26th, went to Sheffield, and on First day,
attended their fore and afternoon meetings--silent in the morning,
but in the afternoon had a fine and open time, in testifying of the great purpose,
intention, and power of the gospel,
in the deliverance of men from their fallen condition,
greatly to the relief and peace of my own mind;--found a few honest Friends there,
though much uninformed of the state of things in the Society.
Lodged the first night at an inn, and the second, at John Haywood Jones`'s,
where we were kindly and affectionately entertained.

On second day we returned to Bakewell,
and on third day I was engaged in preparing a Circular letter, containing strictures,
which I had previously penned, on the Circular of the Meeting for Sufferings, which had,
in some places,
succeeded in making Friends believe that I am a willful
and unauthorized intruder upon Friends here in England,
and which has made my service hard and trying,
meeting with so many that have been set against me by the said document,
sent beforehand into all parts of the nation.
Hence it seemed highly needful, in some way or other, to place the thing on right ground,
as was the practice of the ancient Friends, when they were attacked;
and no better way being seen than by a letter addressed to a few Friends,
in different parts of the country, to be printed and sent by mail,
this mode was adopted--all which we hope to accomplish in a few days.

First day, the 4th, attended their meeting at Bakewell, in the morning,
and at two o`'clock had a meeting at Longston, with Congregationalists and others;
and a door of utterance was largely opened, and matter suited to their condition,
was freely and mercifully furnished, and we returned to Bakewell in great peace.
The same evening, attended their afternoon meeting at Bakewell,
in which I had something to offer, suited, as I trust, to the condition of those present,
some of whom are not members of the Society.
On second day, had large meeting at Monyash, in the Methodist house,
wherein I was greatly helped to declare the doctrines of the gospel,
and it was a very solemn time.
My Circular letter before alluded to having been printed at Manchester,
it was now forwarded to persons in most parts of the nation.

[.offset]
+++[+++The following is a copy of the same:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Manchester, 12th Month, 1853.

[.salutation]
Dear Friend,

It is evident from a document recently put in circulation
in all parts of the Society under our name in this nation,
that the body which denominates itself a Meeting for Sufferings, is prepared, in full,
to indorse the acts and proceedings of a body of people in New England,
who have seceded from the doctrines of Friends, and have, in a palpable manner,
violated their discipline, in defence of unsound doctrines,
and in defence of the writers of those unsound doctrines; and who have, by these acts,
brought about a separation in the Society of Friends in New England aforesaid.

And if those composing the Meeting for Sufferings are the
deputed representatives of London Yearly Meeting,
and are invested with the authority of said Yearly Meeting,
then that Yearly Meeting would seem to be involved,
and to stand accountable in this endorsement of such acts of the said body in New England,
and have therefore become a party with them in those acts,
and have made one common cause with them;
and all this without making any official inquiry or examination into the charges
of apostasy that were preferred against that body so seceding.

This lapse from Friends`' doctrines was seen and testified against,
by those who stood fast in keeping to and upholding the doctrines of the
New Testament as most faithfully held by our worthy predecessors;
and efforts were not lacking on their part to reclaim those who had thus departed.
By the same Friends were also brought to view, the unhallowed attempts,
by certain publications, to modify and change these pure doctrines;
and they raised their testimony against these proceeding,
the doing of which was agreeable to the commands of the Lord to the holy prophets,
and to the example and command of our Lord and his apostles;
because exposing of the evil is as essential as the promulgation of the good,
in the wisdom of Divine Providence,
and therefore indispensable for a discrimination between the good and the evil;
and there is scarcely to be found in the Bible, a view more fully inculcated,
since the discrimination was made to our first parents.

But how comes it about that London Yearly Meeting, and a coordinate body in America,
with whom it is in full correspondence, (which,
in point of intelligence and stability of religious character,
was believed to be inferior to none in that country or elsewhere,)
should decide the New England question in so different a manner?
To this question we can hardly conceive of more than two ways of responding.
One would seem to be this:--because one of these Yearly Meetings made an official
and thorough investigation into the facts and circumstances adduced on both sides,
while the other attended only to the representations on one side;
which leads to the inquiry whether such partial decision is considered
by the issuers of the document (if we might be allowed to use their
own language) to be "`acting in the meekness of wisdom,
yet in the firmness and consistency of Christian principle,
and in accordance with gospel order?`"
Each body in New England appealed to London Yearly
Meeting on behalf of the justness of its cause,
yet but one of these bodies could obtain a hearing,
and that was the body which supported the unsound doctrines.
With what confidence, then,
can the Meeting for Sufferings exhort individuals
or meetings to act upon Christian principles,
when themselves have so palpably violated the rules of a just judicature?

The second mode of answering the interrogatory may probably be,
by adverting to the unison in doctrine between the issuers of this document
of the Meeting for Sufferings and the seceders in New England,
which is now so well known;
this may very likely be the reason why they desired not to look into the case,
lest the disparity between their views and those upheld by Barclay, Penn, and Penington,
should too plainly appear;
and why they chose to own the seceders and to refuse those of the ancient order;
they as well as their coordinates in New England,
being so partial to their author and his sentiments, as not only to extol him,
but also to vindicate his doctrines;
hence there is no marvel that they consider me to be out of unity with them.

But in thus writing of your Meeting for Sufferings as a body,
I have no wish to include every individual member of it, or to hurt any tender mind;
far be it from me, believing,
as I do that there are those among them who remain steadfast to
those principles for which our early predecessors suffered so much,
though they may not often declare their allegiance openly.
But since I have now come to this country,
and have had conversation with some members of that meeting, I have found them,
with few exceptions, to be decidedly in unison with the sentiments of their author,
even where he condemns Barclay, Penn, and Penington;
hence I do admit that they are not in unity with me,
or with the Yearly Meeting to which I belong.

In principle they deny me, and consequently I am unable to own them;
and therefore did not feel the liberty to offer them my credentials,
they having now adopted sentiments contradictory to those
understood to be held by the Society in 1829.
Notwithstanding, if they will now come forward, and disclaim the New Doctrines,
acquitting themselves of them, it would afford much satisfaction to the undersigned,
as well as to many Friends on both sides of the Atlantic,
who have no desire to entertain a feeling of disunity,
but rather that all might be joined together by those
bonds which ought never to be broken.

Under present circumstances it is more easy to my
mind not to attend any Meetings for Discipline,
under the control of those holding unsound views; my concern here rather is,
to inculcate the doctrines of Friends,
and to impress them upon the minds of those I meet with;
because there has never been any other root,
producing so good fruit as that of Christ in man,
a doctrine proved by more than twenty testimonies, from Christ and his apostles,
it being the work of Christ within us, as well as the work of Christ without us,
that brings salvation;
and I find a seed in this nation that is not ashamed of the cross of Christ,
nor of his doctrines, which shone forth so conspicuously in George Fox.

And, notwithstanding the document that has been issued against me,
I still do not feel as though I should be clear in the sight of my divine Master,
without endeavoring to visit that suffering seed in this land,
such as may be willing to receive me;
having been impressively reminded with reference to the before-mentioned paper,
of the reply of Peter and John, when commanded not to speak at all,
nor teach in the name of Jesus:--"`Whether it be right in the sight of God,
to hearken unto you more than unto God, you judge.`"

If a man be prepared honestly to adopt the sublime language of Job, "`Behold,
my witness is in heaven,
and my record is on high,`" he will be enabled to stand fast in the Lord;
but if he vindicate the wrong, and refuse to condemn it,
all his professions of the right will avail him nothing.
Seeing the Meeting for Sufferings has condescended
to speak so freely of a low and humble messenger,
who, if he had not been so noticed, might have passed quietly along,
thinking himself to be but as a solitary individual; they will therefore, he trusts,
allow him to vindicate not his own name, but the cause of Truth;
though unworthy to be compared at all with one who said,
"`After whom is the king of Israel come out?
after a flea?`"
He who could command the legions of Israel went forth with
a strong band in pursuit of one who wished him no harm,
nor yet any evil, but much good for the Lord`'s cause and people.

But the Lord, in whose hands were the destinies of Israel, took care of his own cause,
and did not permit Saul to destroy David,
but caused David`'s drooping spirits to be sustained by the gathering unto him
of a few congenial souls who were prepared to share a common lot with him.
David could not refrain from honoring the horn in Samuel`'s hand,
which had once shed the oil upon the head of Saul; and therefore desired not his life;
but only took his skirt as a proof of his own fidelity.
Saul`'s mind, filled with jealousy,
resorted not to the dictates of best wisdom in deciding the most important questions,
but was actuated by the strongest prejudice and fear for his own supposed safety,
and therefore could not even listen to the just pleadings of Ahimilech.
But the third incumbent on the throne of Israel sought for wisdom,
and by wisdom was led to hear the statements of both the claimants for the living child,
thereby being enabled in a remarkable manner to make a righteous decision,
and to give the living child to its own mother.
Therefore, let not my dear fellow-probationers chide me,
for I have come here in the fear of the Lord,
and in my small measure for the upholding of his testimonies.

Now, if further testimony be needed,--besides my well-authenticated
and accrediting certificates from our Monthly and Quarterly Meetings,
and from our Select Yearly Meeting of Friends for New England,
which have been presented to a deputation from the Meeting
for Sufferings,--in relation to my right of membership,
I will adduce the testimony of that disinterested coordinate body, above alluded to,
(the Yearly Meeting of Philadelphia;) they say: "`When, therefore,
as in the present case, two bodies come before a Yearly Meeting,
both under the same title,
and each claiming to be the coordinate branch of the Society bearing that name,
it becomes its duty, under the guidance of divine Wisdom,
to inquire into the circumstances of the case;
and that it may not withhold from those to whom they belong,
the precious rights and privileges,
which membership in our Society confers.`"--"`From
the statements put forth by both bodies,
it appears clear to as that important principles and usages of the Society,
as well as private rights,
have been disregarded in the progress of the transactions therein recorded.
Some of the most prominent points in which this has been done,
appear to us to be the following.`"--(See pages 29 to 38,
_Philadelphia Report._) After which they say:
"`Although the manner in which this separation was effected,
was not such as we think affords a precedent in the organization of a Yearly Meeting,
yet inasmuch as those Friends,
who compose the smaller body appear to have acted from a sincere
desire to maintain the doctrines and discipline of the Society,
and the rights secured by it to all its members;
and had been subjected to proceedings oppressive in their character,
and in violation of the acknowledged principles of church government--we
believe that they continue to be entitled to the rights of membership,
and to such acknowledgement from their brethren as may be necessary
for securing the enjoyment of these rights.`"

Then speaking further of the larger body, they say:
"`Their acts have gone to condemn many who have been
standing for the ancient faith of Friends,
and against the introduction of error; that in so doing,
wrong opinions have received support,
and the discipline and rights of members have been violated;
and that it was the course pursued by them in these transactions which led to the separation.
Until, therefore, these proceedings shall be rectified or annulled,
we see not how unity is to be restored.`"

In conclusion, let me add,
that believing controversy for the sake of controversy to be wrong,
and ever to be avoided, this paper is not intended to lead to unavailing disputation;
but I would remind such as are fearful of anything which they think may tend to "`divide
in Jacob and scatter in Israel,`" that from the fall of man to this very day,
the Lord has had a controversy against evil, and his chosen ones must have the same;
and this controversy, far from tending to scatter the faithful,
unites them in the great work of maintaining that
holy "`faith once delivered unto the saints.`"

[.signed-section-closing]
I remain, with love, your friend,

[.signed-section-signature]
John Wilbur.

--

On fifth day, after a solid,
melting opportunity with a considerable number of dear and precious Friends at Bakewell,
at which season, testimony flowed freely,
and my prayers were lifted up for their preservation,
and for the preservation of all the honest-hearted ones in this nation, we took leave,
in great love and near affection, and went to Manchester, where we arrived after dark.
Went to dear Hannah Harrison`'s, and lodged with her family,
(she not at home.) On sixth day, wrote letters to America,
and also several letters to Friends in England,
and at evening took the cars and went to Rochdale,
and lodged with my dear and valuable friends Martha Midgely and her daughter Elizabeth;
the latter, a minister, in whose company and sweet conversation we were much refreshed;
indeed, on the way from Manchester to their habitation,
my mind was wonderfully filled with the Divine presence,
perhaps to as great a discovery of his love, his wisdom, and his power,
as I had ever before witnessed;
affording a blessed confirmation of his owning me and my service in this land;
to the pouring out of my soul in praise and thanksgiving
to his great and ever blessed name.

Although I have been many times under great affliction on account of false brethren,
and the envious spirit in which they treated me, yet the Lord, in the midst of all,
has not forgotten to be gracious, but has often, yes,
very often favored me with the strengthening incomes of his holy presence, love,
and goodness; whereby hope and faith have often been renewed to us.
In the afternoon of seventh day, we went to Marsden, dear E. Midgely in great kindness,
accompanying us most of the way, and then returning home.
On first day, the 11th, attended their meeting at Marsden, where I had a lively,
searching testimony for such as had missed their way,
comparing them to a man who had been overtaken with darkness,
and found himself in the midst of a vast howling wilderness,
surrounded with beasts of prey, and liable, in case of any attempt to advance,
to fall from a precipice, or to be plunged into an abyss,
from which there might be no recovery; setting forth,
that if such a one had a belief that he could be heard,
how great would be his cries for someone to come
with a light whereby he might find his way out,
and be delivered from his awful position; from this, very pertinent doctrine was drawn,
and applied to some conditions present.

We lodged here with Caleb Haworth, a son of the late James Haworth, of the same place,
who might be denominated a patriarch of our day, a minister and elder,
worthy of double honor; and this, his son, with whom we sojourn,
is a man of a sound mind;
and we think there is good ground to hope that he will not
depart from the faith once delivered to the saints;
and so fully witnessed by our faithful predecessors.
We left Marsden on third day, the 13th, and went to Bradford, and put up at an inn,
and next day attended their mid-week meeting, in which I had an opening,
on the passage "`Blessed is he whosoever is not offended
in me;`" and in the course of my service,
alluded to those who took offence at the straitness of the Saviour`'s words,
and went back and walked no more with him;
suggesting that the influence of the leaden of the people, who would not confess him,
might conduce to that offence, etc., and I was much enlarged,
and strength given to testify of the liability of our going backwards,
and not knowing the offence of the Cross to cease,
by means of a perfect submission thereto.

After meeting, we dined with several sound Friends,
who were very solicitous that we should stay over first day, and attend their meetings;
but having relieved my mind so fully, I felt easy,
and so went to Leeds the same afternoon, where we called on Daniel Pickard,
and he went with us to see an aged minister by the name of Mary Wright,
of about 98 years.
She is valiant in support of the doctrines of early Friends,
and in full possession of her mental powers; and holds out to be a living minister.^
footnote:[Deceased within the present year (1859) in the 104th year of her age.]
We first lodged two nights with Sarah Tatham, and on sixth day went to Gildersome,
and attended the funeral of a Friend,
whose many relations were not members of our Society.
In this meeting, I had good open service, well adapted to the occasion,
help being mercifully afforded; and, as at Bradford, so here,
great peace and consolation followed my labors.
After this, we lodged at Joseph Kitching`'s, as long as we stayed in Leeds.

On sixth day evening, two leading persons came to us,
for the purpose of advising and persuading me from
persisting in proceeding any further on this service,
and to return to America.
These men professed to believe both in J. J. Gurney`'s doctrines, fully,
and those of the early Friends; a thing altogether impracticable,
because many of the former flatly contradict the latter.
They found much fault with my Circular letter, on account of some strong expressions,
as they said, therein contained;
but I referred them to the plain manner in which George Fox, and other early Friends,
spoke, using much stronger language than I had done, in that letter.
We attended their fore and afternoon meetings on First day, in both which,
I was largely engaged in advocating Scripture doctrines, as held by our early Friends,
and applied them to Christian practice and Christian experience; and,
in so clear a manner, that the Gurneyites did not attempt,
(as far as we could learn,) to gainsay any part; nor yet to invalidate my standing,
as had, heretofore, been sometimes the case.
Such a step has not been taken, since the issuing of my Circular,
which seems to have disarmed them for the present.

On first day evening, there came more than twenty Friends voluntarily together,
at our lodgings,
which afforded me a good opportunity to commend them for their faithfulness,
in making a stand against the new doctrines,
and to encourage and exhort them to stand fast in the Lord,
expressing an assurance which I had, that if they would hold fast their integrity,
faithfully, great good awaited them; and that their reward would be sure.
Dear old Mary Wright, and four overseers were present.
This company of dear Friends agreed on, and read to us, a paper,
+++[+++afterwards signed by them and delivered to him,]
expressive of their full satisfaction with my visit to this country, and particularly so,
with my service at Leeds; expressing a full belief that my visit to England at this time,
is in the ordering of Divine Providence.

On second day our dear friend Daniel Pickard bearing as company, we went to Preston,
and lodged, and on third day, to Calder Bridge, and on fourth day had a meeting there,
attended by all their members, and a number of other people,
they having previous knowledge of our expecting to be there on that day.
In this meeting I was concerned to impress upon those present,
the necessity of obtaining the right thing,
and being satisfied with nothing short of it;--namely,
a measure of the divine Life to be witnessed in their hearts.
After this meeting, we went to Lancaster,
where next day we attended their mid-week meeting,
where the Lord`'s call by the mouth of one of his prophets,
to "`blow the trumpet in Zion, and to assemble the elders,`" etc., was brought to view,
and the latter part impressed, calling on the priests, the Lord`'s ministers,
to weep as between the porch and the altar, and let them say, "`Spare your people,
O Lord, and give not your heritage to reproach! for why should the heathen rule over us,
and why should it be said, where is their God?`"

A desire was expressed that, as pertaining to us, the former days might return to us,
as a people,
and that true Christian zeal might be restored to us in
such measure as was witnessed by our worthy predecessors,
and that the testimonies of the Truth, as upheld by them, may be upheld by us; when,
if happily so, it will not be said, "`Where is their God?`"
for behold the shout of a king will be heard in the camp,
because of the victory that will have been obtained,
by the devotion of our whole hearts unto God.
After meeting, went to Carlisle, and put up at an inn,
and next day attended their meeting, silent; and after meeting, went to Wigton,
and called and took tea with Alexander and Sarah Dirkin, sound in principle,
but somewhat like Joseph of Arimathea--disciples, but not openly for fear of the Jews.
They are afraid to condemn the spurious doctrines brought into the Society of later time,
lest they should incur the displeasure of the leaders of the people;
for the minds of the ministers and elders, and through them, many others,
if not most others have become corrupted, and leavened, more or less,
into what our Saviour called the doctrine of the Pharisees;
they had perverted justice and judgment,
and yet were making great professions of fidelity to the law of the Lord,
but construing and administering it in their own way,
keeping the outside clean and beautiful, while within, he declared,
they were as ravening wolves.

On first day, attended their meeting at Bolton,
and the neighbors obtaining knowledge of our being expected there,
as many people came as their house would hold;
and I was pretty largely opened in the ministry, and in a manner that brought peace.
Afternoon--attended Wigton Meeting, but had nothing, vocally, to communicate.
We lodged here at our kind friend Robert Dodgson`'s, where I was unwell,
and lay by a day or two.
On fourth day, went by the Railway to Glasgow,
and lodged at Robert Smeal`'s. Here we met with our dear and truly beloved friend,
Lydia A. Barclay, she having come all the way from Aberdeen to meet us,
and in whose company we were refreshed;
she lodging at our friend William Smeal`'s. We attended their mid-week meeting here,
and those on first day, the 1st of 1st mo., 1854, in which I had satisfactory service,
although, in the first and last, I was not extensively engaged.

In that on first day morning,
it came before me to refer to the efforts which the old adversary had always made,
when the Lord had effected an improvement, or reformation among men,
bestirring himself to corrupt and turn them back again;
and I referred also to several noted epochs in which
he had sorrowfully succeeded;--as in Noah`'s time,
when that little church of himself and family were brought out from a wicked world,
how soon the enemy, in his craftiness, seduced them into great folly,
and a distrustfulness of the Lord`'s Providence for them,
so that they attempted to contrive a way themselves for their own salvation,
by building a Babel which should reach the heavens.
Not much more foolish were they in this, than are many of the devices of wise men,
in these our days.

The Mosaic reformation, for the seed of Abraham, was also spoken of,
and how soon the enemy turned the people away back from it.
And then again,
that greatest of all events for the deliverance of men from
their evil way--the coming of our Lord and Saviour,
introducing the gospel power more fully, for the blotting out of sin, for sanctifying,
the inner man, and the keeping of him from a lapse again thereinto.
But alas! after all the most effectual means were thus provided,
so long as the first nature remains,
the old enemy takes the advantage by working upon it,
and seducing man to work in his own way, will, and wisdom,
to find an easier and shorter way, like the Babel builders,
to effect the great object of salvation by his own devices.
Thus he becomes wise above that which is written,
and seeks to evade the pain and irksomeness of the cross of Christ,
and self-renunciation,
so indispensable for purging out all the leaven of unrighteousness from his nature;
and so the Christian church, the best of bodies, through those seductions of the enemy,
working upon the will and wisdom of the creature,
fell into a grievous lapse and apostasy,
from the only true and living way of the sanctification, redemption,
and salvation of the soul of man.

From this lapse, a deliverance, even in part, was only obtained through great sufferings,
and the loss of many lives,
and there were but few who maintained their fidelity to their Lord and Master,
through these fiery trials.
But further effort was made, by George Fox and his fellow-laborers,
through more and grievous sufferings and persecutions,
from the hands of high Christian professors, under a gross mistake, like Saul,
of doing God service.
And now again, in this our day,
the same old deceiver has succeeded in exalting the
minds of worldly wise and learned men,
and seduced them to turn back themselves and to turn others back, in many respects,
to the literal and carnal views of those from whom our predecessors came out,
and testified against.
The authority and influence of these worldly wise ones, are bringing the church, if,
indeed they have not already brought her, back again,
into a great declension from the life and power of true Christianity.

On second day evening, we left Glasgow, and passed over the channel to Belfast,
in Ireland, that night, and went to Lisburn, and put up at an inn.
Being somewhat unwell, and a deep snow that fell, while here, obstructing the Railway,
we did not leave Lisburn until first day afternoon, the 8th,
so that I was at their meeting twice, but had nothing to communicate;
yet they had preaching on both occasions--they seem to be in a
kind of passive subjection to the "`Quaker hierarchy`" in Ireland.
After this we went to see Jacob Green,
a minister who had been twice in America on religious service.
He and family received us kindly and affectionately;
but he also is now borne down by those who bear rule in this land,
in the upholding of the spurious doctrines of J. J. Gurney,
and so tries to make a virtue of what he thinks a
necessity to obey the rulers of his people;
and has come to the conclusion to try to live in peace with all men,
and so avoid saying or doing anything that would offend the Gurneyites;--a course which,
I fear, if long continued, will have a paralyzing tendency on his own mind.

I tried to impress him with a true sense of the danger of keeping peace,
at the expense of principle, or by a sacrifice thereof.
After this, on our way to Dublin, we called on Charles and Ann Wakefield, both ministers,
and among the chief Friends in the north of Ireland.
These Friends had been, but four or five years ago,
making a faithful stand against the doctrinal innovations of later time,
made upon our principles, and still speak decidedly against the writings of J. J. Gurney,
but express full unity with those leading members who have imbibed those doctrines,
and consequently are in favor of a decree put forth by those
leading members requiring all Friends in Ireland,
to refuse me as a minister.
Thus we see what the influence of leading men will do,
when they are actuated by the love of power, and beguiled with false doctrine.

We arrived in Dublin on fourth day night, the 12th, and not knowing any Friends there,
of the ancient order, we took lodgings at an inn,
and were not known to be there by any members of the Society, until meeting time,
on sixth day morning, when we went in and sat down among them.
Here I had a pretty full opening upon the passage of, Christ the true Shepherd,
and upon the necessity of all his sheep hearing his voice,
and of distinguishing it from the voice of the stranger,
and upon some other important Christian doctrines.
After meeting, several Friends came and spoke very kindly to us,
desiring our company at their houses, but as we were bound to Moat the same afternoon,
we could not now comply with their invitation.

[.offset]
+++[+++Before leaving for Ireland, he received the following letter from John Pease,
to whom his Circular had been sent; and the succeeding reply was written from Dublin.]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
East Mount Darlington, 12th mo., 16th, 1853.

[.salutation]
Respected Friend, John Wilbur,

I have received your printed letter, dated at Manchester, 12th month of this year.
I consider it candid in you to own so freely your continued
dissatisfaction with the writings of a certain author,
I suppose our late dear Friend, J. J. Gurney; also,
your disunity with the members of the Meeting for Sufferings of London,
and the body of those whom they represent.
I also approve the conclusion you have come to,
not to attempt to attend any meeting for discipline in this
land;--but how could you have arrived at any other?
At the same time I cannot reconcile with such admissions,
your continuing to offer your ministry to those who loved and honored J. J. Gurney,
and accept his writings generally;
and whose inmost feelings and sense of what is due to the good order of the church
alike bind them to respect and adhere to the conclusions of the body.

How an individual can claim to preach among a body of Christians
with whom he is neither in membership nor unity,
I cannot understand.
That there may be those who receive you as a minister of Christ,
and that you are at liberty to visit such,
I admit;--but any interruption to divine worship is a solemn thing,
and however lowly any man who allows himself in it may be in his own estimation,
those who are placed as watchmen are bound to guard against,
and in a Christian spirit to resist it.

For myself, were I to call any minister a Father in Christ, and I think I may do so,
that Friend and Father in very solemn language told me,
that while devoutly meditating upon J. J. Gurney
and his position in a Meeting of Ministers and Elders,
he was favored with a remarkable evidence of the Holy Spirit,
(and with such intimations I know he was well acquainted,)
bringing to his remembrance the language,
"`Touch not my anointed, and do my prophet no harm.`"
I have no doubt but that he lived and labored and died in the settled persuasion
that J. J. Gurney was an honored instrument in his right lot among us;
and I never heard so many testimonies or so strong,
to the service of any man as I heard from place to place, of his labors in your land.
A similar and growing conviction in unison with all these testimonies attend me.
I do not indorse his writings or the writings of any man
or set of men beyond those of the penmen of Holy Scripture.

I believe the early Friends were, many of them, men fearing God.
I honor their memory; and the views of gospel Truth, which they held and promulgated,
I love and adopt far beyond those held by any other body,
notwithstanding the fallibility of both conception and declaration
which attached to them in common with all (good) men,
but the longer I live,
the more prayerfully I desire the exaltation of Christ and his cause,
whatever man has said or may say, "`Let God be true, and every man a liar.`"

Holding (I hope in a good conscience) the foregoing sentiments,
I can do no other than believe with sorrow that you
have been long warring under very mistaken feelings;
and much desire that you may at once lay down your arms and finally
obtain peace through our Lord and Saviour Jesus Christ.

[.signed-section-closing]
Your sincere friend,

[.signed-section-signature]
John Pease.

[.postscript]
====

This letter is not written to provoke either controversy or extended correspondence,
which I should decline;
but as an honest reply to what I accept as an honest letter from you.

I am authorized by my beloved father to say that he entirely unites in this letter.

====

--

[.offset]
+++[+++Reply To The Foregoing Letter:]

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Dublin, 1st month, 12th, 1854.

[.salutation]
Friend John Pease,

Your letter of 12th mo., 16th, was duly received,
and no disposition to charge you with unkindness is entertained,
nor with a lack of candor in vouching for J. J. Gurney and his sentiments,
inasmuch as every person has a moral right to entertain
such religious sentiments as he sincerely believes;
but whether a man of your capacity, holding to the doctrines of J. J. G.,
would be candid if he professed to be a Quaker, is entirely another question;
those doctrines being so obviously contradictory and repugnant to those of Friends,
faithfully held and clearly proved for nearly two centuries
to be the pure and vital doctrines of Christianity,
according with the Holy Scriptures.

Nor have I been able to see the consistency of your course or that of any others,
acknowledging full unity and fellowship with a man whose published sentiments
on many essential and fundamental points of doctrine are thus at variance with,
and repugnant to Friends`' doctrines;
inasmuch as we have the best authority for saying that,
"`the tree is known by his fruit,`" "`that a good
tree cannot bring forth evil fruit,`" and so forth.
And who are there in England that will attempt a public reconciliation
of the doctrines of J. J. G. with the doctrines of early Friends?

If anyone should make such an attempt, I presume it would be at the expense of candor,
as well as the perversion of good sense and sound judgment.
Barclay and the other early writers, whose doctrines rested on the ground of Truth,
had no occasion for cavilling,
or for perverting the plain and true meaning of the Holy Scriptures,
because in the Truth there are no evasions, turnings, or windings,
in the demonstration of its principles.
But J. J. G. strives in his [.book-title]#Brief Remarks# to make his readers believe that all the apostle
meant by the expression "`Christ in you,`" was the incarnation of Christ,
or God manifested in the flesh.
To quote his own words: "`The plain fact, however, appears to be,
that the mystery of which the apostle is speaking,
is that of the incarnation of the Son of God.`"
Whereas,
there are more than twenty passages in Holy Writ which prove the correctness
of the doctrinal view held by Friends on this point.

But to prove J. J. G. and his views to be right you adduce the affirmative
testimonies of many in America who I have no doubt were his strong votaries;
and so, according to the numbers, from what I have seen and heard,
there are as many of Elias Hicks`'s disciples that would eulogize him as much;
a thing of common occurrence in cases of innovation upon the principles of any Society;
but let the fruits--their doctrines be rather adduced as testimony.
I am not at all a stranger to the fact that he has made
great strides both in Old England and in New England,
which he has effected by drawing many to his person and to his doctrine;
but that no more proves its rectitude than did the
success of E. H. the truth of his doctrine.

They were both undoubtedly sagacious and skillful in gathering
many to themselves! not much less so perhaps than was Absalom,
who found means to bring more men to the field than could David the Lord`'s anointed.
But however many and able the adherents of Elias Hicks or J. J. Gurney,
either party has not adventured to attempt a reconciliation
of their respective doctrines with those of Friends,
in a public manner; though often desired to do so,
that all might know and understand the improvement which they profess
has been made upon the first principles of Friends.
Thus having utterly declined, and continuing to do so,
is ample testimony against their sincerity in Friends`' doctrines;
and especially when we see so much evasion and reserve in their confessions of our faith,
leaving so many loopholes through which to escape.

You approve the conclusion to which I had come not
to attend Meetings for Discipline here;
a conclusion arrived at before leaving America,
provided things here were no better than I expected.
We had the opportunity of offering ourselves for
such attendance before our first coming to London,
but made no such attempt.
Again you say,
"`At the same time I cannot reconcile with such admission your continuing
to offer your ministry to those who loved and honored J. J. Gurney,
and accept his writings.`"
But is it a mystery to you, friend John,
that the Lord`'s messengers should ever have been sent to
preach to those in former times differing from them in opinion?
and especially if that difference of opinion involved
false doctrines or led to erroneous practices?
Was it not always the purpose in preaching the gospel, and does it not remain so,
to reclaim men from wrong things, as well as to inculcate the right?
with which if you are unable to reconcile my practice,
so I am no better able to reconcile your views with Scripture testimony and practice
until you make it out that the Gurney people are whole and need no physician.

You intimate that I am not a member of the Society; but by what authority?
and by what authority do the Meeting for Sufferings make the same assertion?
Only by an ex parte authority,
never having officially ascertained by an examination of the New England case themselves;
and therefore how is it that you or they should be
so uncivil towards Philadelphia Yearly Meeting,
as to contradict them flatly and plainly in the decision of the
case which they have availed themselves of the means of understanding,
while you have not--they have declared me to be a member
and entitled to all the rights and privileges thereto pertaining,
and have practically carried out that decision by receiving me both in their yearly,
and other meetings for worship and discipline as a minister of the gospel of Christ,
and therefore such allegations as are brought against me here, in this respect,
are of no consequence to me, however they may affect others.

But will you blame me for not being satisfied with the proceedings of
your Meeting for Sufferings in attempting to prevent the accomplishment
of a concern which my blessed Master has laid upon me;
that is, to visit his people in this land,
for the purpose of upholding the doctrines and testimonies which
in his good Providence he revived and gave to our worthy predecessors,
and required of them to support?
But I have no personal controversy with any man or body of men;
yet do not admit of the papal opinion, namely, that the church as it is, cannot err;
nor does it appear that you have adopted that opinion for all times,
inasmuch as the body was always made up of individuals; taking the ground,
as I understand you, that every man, even in the church, is or was a liar;
but however you may be willing to include our early Friends in such a sweeping denunciation,
you might probably be inclined to spare the present Yearly Meeting and the Meeting
for Sufferings from the imputation of variableness or shadow of turning.

You imply that I am in the practice of interrupting
meetings for divine worship by preaching in them,
but I suppose you would agree that if commissioned
by the Head of the church so to speak in them,
that it would not be deemed an interruption to such solemnity;
but as you have not been present on any such occasion,
I would ask would it not be well for you to refrain from judging?
To prove J. J. Gurney to have been anointed you cite me to a passage
of Scripture recommended by someone in relation to his standing,
and which was told to you, namely: "`Touch not my anointed, and do my prophet no harm.`"
The very same words were once quoted in my hearing
by a Friend then of eminent standing in America,
for the purpose of screening Elias Hicks from the judgment of Truth.

And now a word upon your concluding paragraph:
you say "`holding the foregoing sentiments,`" and no doubt anxious to sustain them,
that "`you believe with sorrow that I have been long warring under very mistaken feelings,
and are led to desire much that I may at once lay down my weapons,`" etc.
There is no marvel, that this should be your belief,
not knowing or perceiving by reason of the apparent darkness
into which the new views have necessarily plunged you,
whether the weapons of a Christian`'s warfare are carnal or spiritual,
by any internal evidence.
But I desire that the blessed Messenger of the new covenant may
break into your soul with a powerful beam of his heavenly presence,
in such manner as that you may clearly see the mystery of iniquity,
whereby the enemy is striving to turn this people back again
to the house from which they came out.

[.signed-section-closing]
Your friend and well-wisher,

[.signed-section-signature]
John Wilbur.

[.numbered-group]
====

Note.--Instead of proving J. J. G. to be sound by quoting his doctrines,
you have brought to view the vague sentiments of his votaries;
but I would advert briefly to the sentiments of that
devoted and faithful servant of Christ,
Thomas Shillitoe,
who had known his course of life from his youth and had read his writings.
He said in his last sickness, "`I declare that J. J. G. is an Episcopalian,
not a Quaker.`"
And the editor of a periodical in Boston, who had been furnished with his books,
declared his doctrines to be as different from those of
the Society of Friends as Calvinism is different from Arminianism;
and this he said without expressing his assent to,
or dissent from either of those extremes.

====

--

We went by rail, after sunset, sixty-eight miles, to Moate,
where our dear friend John G. Sargent met us, and took us five miles further,
to his residence at Hall, and staying there over seventh day,
we went with them to their meeting at Moate,
where I largely bore witness to the apostasies, through the devices of the enemy,
that had always followed a reformation, or recovery of any portion of the people,
from a lapsed condition;
and closed the list by referring to a lapse from
principle now prevailing in the Society of Friends,
drawing them away from the most advanced and dignified ground, whereunto the Lord,
in his Providence, had called any people in modern times;
and however the enemy is lacking in power, he resorts to lies and deceitful devices,
in order to lure away this people from that holy and honorable
ground on which their doctrines and testimonies are founded.
And seeing, how by such devices, he has corrupted the Lord`'s people,
subsequent to every effort which he has made for
the recovery of men from their evil ways,
it is of great importance to us that we make a firm
stand against these devices of the enemy,
in his attempts to introduce an apostasy into the Society of Friends,
as he had done into the church of God in former ages.

We attended their meeting at Moate again on fourth day,
in which I had good open service for the Truth, suitable to their condition,
as I believe.
On fifth day we left Hall, and went back to Dublin,
and tarried all night at Joseph Glaiser`'s, who, with his wife,
treated us with great kindness, John G. Sargent being with us,
having kindly undertaken to accompany us as far as Waterford.
On sixth day we went by rail to Clonmel, one hundred and thirty-four miles,
and took lodgings at an inn, and on first day morning, the 21st, I had, in their meeting,
an open and enlarged testimony on the doctrine of
Christ being the messenger of the new covenant,
and on other Christian doctrines, but, in the afternoon, was silent.
On second day, left Clonmel and went to Waterford, and lodged at an inn,
and on third day took boat for Bristol, where we landed on fourth day,
between 1 and 2 p.m., having had a comfortable passage.
We put up at an inn,
and felt very thankful in being preserved in crossing the water in these perilous times,
many vessels and ships at sea having of late been lost,
through the violence of the wind and storms.
This passage from Waterford to Bristol is called about two hundred and twenty miles.

Fifth day morning, the 25th,
Henry Hunt sent a carriage and took us to his house (his wife being an old acquaintance).
We had much conversation on the state of things in the Society.
She professes to hold fast the original doctrines of Friends,
yet is so inconsistent as to say that she thinks there is very little
in Gurney`'s doctrines that varies from the ancient principles of Friends,
and also professes to believe that J. J. G. was a good Christian--an idea that has been,
with so much pains circulated everywhere,
that even some pretty sound Friends have been made to believe it, and this,
notwithstanding the manifest inconsistency and hypocrisy by which he was marked,
in professing to hold to the ancient principles of Friends,
as he was sometimes compelled to do to maintain his standing, while, at the same time,
he labored so hard to undermine and overthrow many
of their most valued and distinguishing doctrines.

On sixth day attended their mid-week meeting--small, and, on my part, silent;
but several were starting up and speaking, as I thought, to no profit.
After meeting, went home with William Tanner, who married Sarah,
the only one remaining of Daniel Wheeler`'s children.
We stayed, and attended their morning meeting on first day, which was large,
and strength and understanding were afforded to preach
the gospel in the authority of Truth,
and much to the softening of those who were our opposers,
some of whom had previously requested us to desist from pursuing our prospect any further.
On second day morning E. Hunt sent for us again to her house,
and appeared desirous of an alliance, and of signing conditions of peace,
and labored to make me believe that their best ministers
preached just such doctrines as I did there the day before.
She was apparently very affectionate, and I spoke kindly to her,
hoping she had received some benefit by our visit.

Second day afternoon, the 30th, went to Bath,
and next day was at their mid-week meeting--on fourth day at Melksham,
and on fifth day at Reading, all open, favored meetings,
and wisdom was given to preach the gospel with clearness and in Divine authority, and,
truly, there is an evident increase of openness to receive us.
At Reading they were very desirous that we would
stop and attend another meeting with them,
but our arrangements having been made, and word sent forward,
and the minds of Friends here left under very good feelings,
we thought best to go forward.
We came to Croydon on seventh day, the 4th of second month,
and attended both their meetings on first day.
In the morning I was largely engaged in delivering the Truth among them,
much to the comfort of the honest-hearted--the savor of life unto life to them,
but of death unto death to those who are lost.
In the afternoon I had nothing to offer among them.

On second day, the 6th, came to London, and put up again at William Hughes`'s,
in Scott`'s Yard, and on third day was at their mid-week meeting, at Southwark, London,
which was very small, compared to its numbers twenty-one years ago;
and however low things were felt to be, and out of order,
yet I had a lively opening in the gospel,
and was enabled to set things home to the witness for God
in themselves and the Truth was raised into dominion,
to the comfort of Friends and shame of my enemies; and one Thomas Norton, an elder,
was constrained to acknowledge the overshadowing of the presence of the Saviour,
and said that, although he was one of those who issued the Circular,
and which he would still recommend to my consideration,
yet he could but say that he hoped I should be favored to get safely home,
and experience the reward of peace.

On fourth day, the 8th, went to the Peel meeting, in the city,
where a Friend expressed a thankfulness that I had not passed them by.
We had an open, searching time, and the gospel current flowed freely.
Jacob Post, an elder, who sits at the head of this meeting, invited us home with him,
and entertained us very kindly, and his sister was also truly kind.
He is in his eightieth year, and very intelligent.
We had much interesting conversation on the state of things in the Society; and,
although he is not fully aware of the imminent danger in which the Society is involved,
yet appears to be sound himself in our doctrines,
and says that J. J. Gurney was idolized by Friends in this country.
He has published several small volumes upon the doctrines of Friends.
On parting, he freely expressed a desire that the blessing of Heaven might rest upon me,
and that I might reach my home in safety.

On fifth day, the 9th, went to Stoke-Newington meeting,
and never was greater favor vouchsafed to me than on this occasion, as I believe;
for truly, as David said, "`the Lord showed me a token for good,
that my enemies might see it and be ashamed;
"`and the gospel doctrines ran forth through me, (who feel myself to be, for meanness,
but as a trumpet of a ram`'s horn,) with great clearness, and with life and power;
and while the creature is humbled, the Lord`'s great and holy name is to be magnified,
for to him alone all glory and honor is due, world without end, amen!

And now I feel easy to leave the metropolis,
truly thankful to the God and Father of all our sure mercies
that he has been pleased to regard my low state,
and to give me strength and courage to speak boldly in his holy name to
his backslidden people in this great city and its neighborhood.
Friends here are greatly reduced in numbers since my visit to them twenty-one years ago,
and the vitality and spirit of true religion greatly lost
and departed from since the coming in of the present century;
and I have a fearful apprehension that unless a greater concern should be awakened,
to the raising up of a remnant of more honest and faithful standard-bearers,
that the Lord`'s holy testimonies will be lost in this city, if not in this kingdom.

On seventh day, the 11th, went to Birmingham, and lodged at William Southall`'s,
and on the day following attended their fore and afternoon meetings.
The promise of mouth and wisdom was mercifully fulfilled,
and strength was given to preach the ancient doctrines
of pure Christianity in both meetings,
to my great relief of a burden concerning this place,
and to much solid peace and satisfaction; nevertheless,
there is little hope of a succession of faithful Friends here.
On second day, went to Bakewell,
and stayed there and rested until the 25th of second month,
when we took coach and came to Manchester,
and on first day attended their fore and afternoon meetings,
and I was largely opened in declaring the truths of the gospel of life and salvation,
in both of those meetings; and the few honest-hearted,
faithful believers in vital Christianity were refreshed and strengthened.
Stopped here again at dear H. Harrison`'s.

On third day, the 28th, we came to Liverpool,
and took lodgings with our dear friend Elizabeth Waterhouse, a widow,
and the daughter of my former dear friend George Crosfield.
Sat through their painful meeting on fifth day, in silence,
which is held by and under the control of those who do not
believe in many of the fundamental doctrines of Friends.
In this large meeting, there are perhaps not more than three or four sound Friends,
of whom Margaret Crosfield is the chief.
We have agreed for a passage to America on board the steamship Arabia,
to sail on seventh day, the 4th. On the morning of this day, we went to the dock,
Elizabeth Waterhouse bearing us company, and were conveyed by a tender to the steamer,
which lay some distance off in the harbor, where she remained till twelve o`'clock,
when we parted with dear E. W. and two men Friends, who, with many other people,
went on shore, and we were immediately under way, and soon at sea,
but did not lose sight of Ireland until the next afternoon.

We had a pretty rough, boisterous passage of twelve days and thirteen hours,
experiencing one very heavy gale; I was seasick most of the time.
We landed in Boston on the 17th of 3rd month, at one o`'clock in the morning.
Went, the same afternoon, by railway, to Fall River,
where my children and friends were rejoiced to see us.
Stayed here and attended their meetings on first day,
in both which I had good open service.
On second day, went by boat to Providence, and visited my children thereaway,
and on third day, the 21st, came to Westerly, visiting my children and friends there,
and next day reached my home at Hopkinton.

And now, on a retrospective view of this visit and service in Great Britain and Ireland,
it appears to have been the most interesting and important of any mission, service,
or work that has ever been called for at my hands.
And, through the obedience of faith, it has been attended to and accomplished,
now in my advanced age, by and through the help of Him who thereunto called,
and put forth and went before; giving mouth and wisdom,
agreeably to his own gracious promise, which my enemies were not able to gainsay, or,
in effect, to withstand.

And this was witnessed by keeping to his injunction, of wholly trusting in him,
and not meditating beforehand what I should say, when about to attend a meeting,
but therein waiting on him for direction, whether to vocal service, or to keep silence;
being, as I trust, fully resigned to either, and waiting for an opening thereto,
if indeed his will was that I should speak in a meeting.
Hence, the will of the flesh being out of the question, and my trust in him alone,
he has been pleased to work, even through a weak instrument,
in and through his own strength, and in the demonstration of his own power,
and under the guidance of his own spirit and heavenly wisdom,
to the confounding of my enemies,
and to the strengthening and sweet refreshment of my friends.

I was persuaded, before leaving my own home,
that the greater purpose of my going to Europe at this time was
the public promulgation of the primitive Christian doctrines,
as seen and held, and most surely believed, by Friends,
from the first down to our own time; and that in the life, and power,
and sufficiency which, I had faith to believe,
the great Minister of the sanctuary would give,
it was that the object of such a mission could be accomplished,
and his honor and righteous testimonies sustained;--knowing, that,
after all the labor bestowed,
it is God alone that can prosper the work and give the increase,
keep and enable those to hold on their way whose minds have been
quickened and renewed in and through the life that is in Christ,
and which is the light of Christ in men, and the power of the everlasting gospel.

But whether this or that shall prosper, the Lord knows;
and although great my concern for the holding fast of the honest-hearted, it suffices me,
that my divine Master has, in his own gracious goodness, accepted, so far as I can see,
the devotion and services thus rendered, as being acceptable to him;
in which hope my joy is full, and sweet peace my unmerited portion;
and the language of the Psalmist is my inward song, "`Give thanks unto the Lord,
O my soul, for his mercy endures forever!`"

[.offset]
+++[+++The following letter written soon after his return from this visit,
will serve further to show the feeling of satisfaction
and peace with which he looked on it in the retrospect.]

[.embedded-content-document.letter]
--

[.letter-heading]
From J. W. to William Hodgson, Jr.

[.signed-section-context-open]
Hopkinton, 5th mo., 13th, 1854.

Although, my dear friend, I do sometimes nearly come to want, and necessarily so,
for the frequently reminding me of the source from which all good comes,
as also of my own poverty and wretchedness,
without the immediate supplies from the Fountain of all good;
yet when permitted to look back upon my late journey,
and a little to realize the marvellous and gracious preservations of infinite goodness,
amid the dangers which awaited us, by sea and by land,
and through the enmity of false brethren,
and subtleties of an enemy`'s assaults upon untried ground,
I seem to be lost in admiration of the goodness of God, extended to an unworthy creature,
and leading to language like some on record: "`Give thanks unto the Lord, oh! my soul,
for his mercies endure forever.`"

A sense had often before been given me, when in the field,
that preservation could not be witnessed without the guardian care of the blessed Shepherd;
and now,
when greater perils were to be met with than I had ever before experienced I was driven,
the more entirely and devotedly, unto the only Helper of his poor trembling messengers,
whom he sends forth as lambs among wolves,
(never before so fully realized,) to trust in him,
and to depend entirely upon him for mouth, and wisdom, and strength.
And blessed be the name of Him who promised those whom he sent forth,
when personally with them, "`And I will be a mouth and wisdom unto you,
which your adversaries shall not be able to gainsay or condemn.`"

Truly, it was only through the fulfillment of this gracious promise,
that we were favored to obtain the victory in so many instances;
nor did he ever fail to help me in keeping to his commandment,
not to premeditate beforehand; and to the praise of his great name, I can say,
that I had never before so little cause to regret anything that transpired,
as on the late occasion, the consideration of which brings consolation and peace of mind.
And although feeling very peaceful, in having, so far as I can see,
done what was called for at my hands, the usefulness of the work,
and the keeping of those minds which have been renewedly
stirred up to revert to first principles,
and the importance of cleaving to them,
must be left to Him whose blessing only can prosper the labors of his messengers.

Under the circumstances attending my service in those large meetings in England,
that of seeking for or desiring to address them with enticing words,
was entirely out of the question; but that which was desired and asked for, was,
understanding and strength; which, through the Lord`'s mercy,
were not withheld on any occasion when labor was required.

In much near and affectionate love to yourself, and family,
and to all dear inquiring friends, as if named, I conclude, and am your friend,

[.signed-section-signature]
John Wilbur.

--

[.offset]
+++[+++After the accomplishment of this last visit to Great Britain,
calmness and peace were eminently the clothing of his spirit;
yet his solicitude for the preservation of Friends upon the ancient Foundation
continued unabated--being manifested by visiting some and writing to others,
under the constraining influence of the love of Christ

[.offset]
He kept no further record or journal of his life,
but feeling that his labors and trials were nearly concluded,
he calmly awaited the summons from works to rewards with an unfaltering
trust that a mansion of eternal rest was prepared for him.
After a short illness, h e died in great peace on the 1st of 5th month, 1856,
at the house of his son-in-law, Thomas Foster,
with whom he resided after the death of his beloved companion in 1852.]

[.offset]
+++[+++The following memorial concerning him was issued by South Kingston Monthly Meeting:]
