[short="Testimony of South kingston Monthly Meeting"]
== Testimony of South Kingston Monthly Meeting of Friends, Concerning John Wilbur, Late of Hopkinton, R. I., Deceased.

"`The memory of the just is blessed;`" and it has ever been
the concern of those to whom the cause of Truth is dear,
to perpetuate the remembrance,
and to preserve memorials of the lives of such as have devoted themselves to its service;
whose chief concern was to be found "`walking in the footsteps
of the flock of Christ`'s companions,`" and by example,
as well as precept, to persuade others to persevere in the pathway of holiness,
the end of which is everlasting life.
While acknowledging our obligation submissively to
acquiesce in every dispensation of divine Providence,
in the assurance that he does all things well,
yet the removal of such dedicated laborers from the church
militant has ever been felt as a loss to survivors;
and more especially has this been realized at periods of great degeneracy, and when,
because of the abounding of iniquity, the love of many has waxed cold,
and the way of Truth is evil spoken of.

Regarding the present as peculiarly such a time,
our minds are deeply impressed under a sense of the loss we have sustained,
in the removal from works to rewards of our late beloved friend, John Wilbur;
and we believe it right for us to hand down to posterity
our testimony to the excellency of his character,
and to his eminent services in the cause of Truth and righteousness in the earth.

He was born at Hopkinton, R. I., 17th of seventh month, 1774.
He was the son of Thomas and Mary Wilbur;
who were exemplary members and elders of our religious Society,
and were concerned to bring up their children conformably to its principles and discipline.
Few particulars of his childhood having been preserved,
we pass over this season with a few remarks thereon,
written by himself at a later period.
"`Regarding what is past, I may say,
that the guarded care of my parents--a constant attendance of religious meetings,
and an attention to the reading of the Scriptures were a
great help to my mind in preparing the way for,
and directing my attention to the saving principle of divine grace within;
the restraining power of which, I became acquainted with in very early life.
And I feel constrained to bear testimony to its efficacy and sufficiency
in effecting the work of the regeneration and salvation of all
who yield to its reforming power.`"

From this,
as well as from the corroborating statements of others who knew him at this period,
we learn that he was a youth of exemplary deportment
and religiously inclined from early life.
When about nineteen years of age, he was united in marriage to Lydia,
daughter of Amos and Thankful Collins,
with whom he lived in great harmony and conjugal affection nearly sixty years,
until her death, which occurred about three years before his own.
He first appeared in the ministry in the thirty-sixth year of his age,
and continuing to grow in his gift,
and his offerings therein being satisfactory to his friends,
he was acknowledged a minister not long after;
and being careful to attend to the monitions of the heavenly Teacher,
he became an eminent instrument in the Divine hand for promulgating the glorious
truths of the gospel of life and salvation to his fellow men.

He was ardently attached to the principles of the
religious Society of which he was a member,
not only on account of their accordancy with the Holy Scriptures,
and with the precepts and example of his parents, for both which he had great veneration;
but from a living experimental knowledge of their truth and efficacy
in preserving those who embrace and live up to them from the snares
of the enemy and the contamination of the world;
enabling them to meet with calmness and resignation
all the vicissitudes and exigencies of life,
and leading in the end to the haven of everlasting rest and peace.
He believed that they embrace the whole great and glorious plan of redemption,
as unfolded in the New Testament.

Hence, he was a firm believer,
not only in the divinity of our Lord and Saviour Jesus Christ,
and in all that he did for us without us,
in that prepared body in which he came to do his Father`'s will,
wherein he tasted death for every man, and suffered the just for the unjust,
that he might bring us to God,
blotting out the handwriting of ordinances which were against us,
and becoming a propitiation for sins that are past, repented of, and forsaken;
but also in his inward and spiritual appearance in the heart,
wherein is experienced by those who truly look for him,
his second coming without sin unto salvation;
and his interposition as a sure helper and deliverer in
preserving us from falling into the like thraldom again.
This, with our worthy forefathers, he regarded as the Christian covenant,
consisting of two parts; both alike essential, and neither availing without the other;
but both together constituting the whole great plan of Christian redemption.

But while he was sound in the Scripture doctrines
always held by true Friends from the beginning,
and was one of whom it might truly be said,
"`he kept the faith`" yet he failed not to enforce the necessity of good works,
which he regarded as the genuine fruits of a living faith;
and he was deeply concerned to be found living up to his profession,
maintaining both by precept and example the importance of holiness of life,
and that a mere profession, however good, will avail nothing.
He was eminently gifted and qualified for usefulness in the administration of the discipline,
and management of the affairs of the Society; his views being clear,
and his expression of them generally pertinent and to the point.

And while he was careful that offenders be dealt with in tenderness and meekness, yet,
when such labors of love failed,
he was firm and decided in placing the judgment of Truth over such,
and often expressed a concern, lest, through weakness or the fear of man,
this important part should be neglected.
He was an example of humility, plainness, and consistency in his daily walk,
and concerned to bring up his children therein--combining, with gentleness and meekness,
firmness and decision;
bringing in wholesome restraint to the aid of persuasion and exhortation, by which,
through divine help,
he was remarkably successful in bringing up a large
family of children in plainness and sobriety,
and at the same time securing their filial love and tender regard.

He was a diligent attender of meetings both for worship and discipline,
seldom failing to attend them in due course,
unless prevented by severe illness of himself or some other of his family;
and it was his uniform practice on such occasions to take his family with him,
or as many of them as he could with convenience,
and when met with his friends for the solemn purpose of divine worship,
the weightiness of his spirit while reverently waiting on the Lord, was often felt,
by those who were present, to have a solemnizing effect on the meeting.
When he arose to speak, it was with the arising of Divine power;
and he was careful not to run before his guide,
often proceeding slowly and with great deliberation,
minding the stepping-stones as he proceeded; but when it pleased his divine Master,
as was often the case, to vouchsafe an open door of utterance,
he appeared as an eminent and powerful minister of Christ;
and it might be truly said of him,
that his speech and his preaching were not with enticing words of man`'s wisdom,
but in demonstration of the Spirit, and of power;
often falling upon the tried and penitent soul as the gentle rain,
or distilling as the silent dew; while, to the rebellious and disobedient,
it was as the fire and the hammer,
causing them to tremble under a sense of their undone condition, as opened to their view,
and raising the query, "`What shall we do to be saved?`"

He travelled extensively as a minister,
both in this country and in Great Britain and Ireland, which he visited twice,
only surviving his return from the last visit about two years.
In addition to his usual occupation,
(the cultivation of a small farm,) he was much employed
by the community as a surveyor of land;
and being considered very capable and accurate in this vocation,
he was often sought after, as well on this account as for his uprightness in dealing,
intelligence, and kindly bearing towards all with whom he had interaction.
To these characteristics, may be added a cheerful and social disposition,
which rendered him an interesting companion; and he was, so far as is known,
without exception, beloved and respected by all with whom he thus became associated.

In all his interactions with his fellow-men, he was truly a peacemaker;
being often resorted to as a counsellor in cases of difficulty,
and as an arbitrator in settling disputes among his neighbors.
He was enabled, by the soundness of his judgment and discrimination,
through divine assistance, to be eminently serviceable in such cases;
and the confidence of his employers in his integrity and impartiality was such,
that he was enabled, almost without exception,
not only to escape the censure of those to whom he decided adversely,
but to retain their friendship and respect.

Often, with the approbation of his friends,
he appointed meetings and attended funerals among
those of other denominations within his own county,
to their comfort and satisfaction; which was frequently acknowledged on their behalf;
and tended not a little to strengthen their love and regard for him.
But he was far from being of the number of those who court popular favor and applause,
who baulk the testimonies of Truth, or warp them to suit the public taste.
He evinced the same unbending adherence to principle
in all companies and under all circumstances.
His faithfulness in this respect,
as with many others in different ages who had gone before,
brought him into many conflicts, which, however severe,
he endured with unwavering firmness and fidelity.
Of these,
by far the most trying and enduring were those which arose from
a radical departure from the doctrines and testimonies of Friends,
on the part of large and sweeping numbers in the Society,
at two different periods during his life.

The promulgation of unsound and antichristian doctrines by Elias Hicks
and his adherents was the occasion of much sore trial to him,
long before the open rupture in the Society occasioned thereby;
and he was constrained faithfully to bear his testimony against this spirit of unbelief,
in all its delusive appearances;
firmly adhering to the ancient testimonies of the Society in regard to
the divinity and offices of our blessed Lord and Saviour Jesus Christ,
and laboring in the ability afforded him to counteract the
desolating effect of views so derogatory to his divine character
and atoning sacrifice for the redemption of fallen man.
But in maintaining this controversy, he was mercifully preserved, as we may well believe,
through continued reliance upon Him on whom help is laid,
from running into error on the other hand,
of which there is ever great danger with those who allow their natural feelings to predominate,
and are remiss in keeping up the watch,
as we have had lamentable evidence in the falling away of many in this way,
who escaped the wreck of the first storm.

In the years 1831-2, he made his first visit to Great Britain and Ireland;
where he soon saw the working of a spirit, the tendency of which appeared to him to be,
to carry the Society back towards the outward and
literal views of the formal professors of the day,
and, if unchecked,
to land its members on the same ground from which
our faithful predecessors had first taken their departure.
In his own language, he "`saw, or thought he saw, the great subtlety of the enemy,
in taking advantage of the Hicksite heresy,
which led off on the one side from the true doctrine,
working on the minds of those who were the most prepared
to forsake the original ground of vitality;
so that while they were guarding against a fatal lapse on the one hand,
he might the more easily plunge them into another as destructive on the
other,--both insidious and defective in relation to the true faith in
the offices and attributes of the Saviour of men.`"

As, against the errors of Elias Hicks and his followers, so against these unsound views,
he felt called upon, both then and after his return to his native land,
to bear his testimony.
And when, a few years after, Joseph John Gurney,
who was strongly identified with these new views,
(having introduced and advocated them more or less
openly in most of his voluminous writings,
and thus more than anyone else being publicly responsible
for them,) came to this country on a religious visit,
our beloved friend took an early opportunity, on his arrival in New England,
to express to him the uneasiness which he had long felt
with many of the views thus promulgated in his printed works,
now spread abroad, not only in England but widely in this country also.
He entreated him to disavow such portions of them as were not in
accordance with the ancient and well-known principles of the Society,
as the first step towards opening his way for service among us.

But instead of complying with this request, or in any way making satisfaction,
he entered into a defence of all his writings,
claiming that there was nothing unsound in them;
and attempted to shield himself behind the certificate which he brought with him.
This being the case, and failing to prevail on the Meeting for Sufferings here,
to investigate those writings and decide on their soundness, he felt constrained,
as an individual, from a sense of religious duty,
and in accordance with the requirement of our discipline,
to warn his fellow-members against imbibing,
or giving countenance to these unsound sentiments.
We do not regard this as the proper place to detail the consequences
of the faithfulness of our dear departed friend herein,
nor is it necessary,
as a correct account thereof has already been published and extensively circulated.

Suffice it to say, that amid the sufferings and conflicts consequent thereon,
he never faltered in his adherence to the original
principles and testimonies of the Society of Friends,
as held and maintained by George Fox, Robert Barclay,
and their co-laborers in the beginning, and died, as he had lived,
in the firm belief that, in adhering to them through evil report and good report,
he had not followed cunningly devised fables, but pure, living, and eternal Truth.
And it may truly be said of him as of Joseph, anciently,
"`The archers have sorely grieved him, and shot at him, and hated him;
but his bow abode in strength,
and the arms of his hands were made strong by the hands of the mighty God of Jacob.`"

He was much and justly valued as a correspondent,
and his labors in this line were extensive during the greater part of his life.
His letters, whether descriptive, didactic, or religious, were always interesting;
but the latter class were by far the most numerous;
and it was eminently as a religious writer that he excelled.
In penning his views on subjects of this important nature, he avoided speculation,
and went directly to the point of vital Christianity.
The continued support and perpetuation of the principles and testimonies of Truth,
in their original purity, as always maintained by faithful Friends,
was to him a subject of paramount importance; and for this he labored abundantly,
both orally and in writing; being often, during the latter part of his life,
bowed down under deep concern, lest they should, through the love of ease, lukewarmness,
and the speculative propensities of this degenerate age,
be cast aside and lost to the world;
than which he believed a greater loss could scarcely befall the family of man.

Owing to the introduction of the unsound views into the Society already noticed,
much that he wrote during the latter part of his life was of a controversial nature;
yet few men were more averse to controversy for its own sake,
or more inclined to avoid it in common conversation, unless principle was involved,
than he; but when this was so, whether in public or in private,
he failed not to defend the Truth and the right; often saying,
that if the pure and unchangeable principles of Truth cannot be maintained without controversy,
then now, as at the first, they must be maintained by controversy;
that faithful and upright men have in all ages kept
up a controversy against error and corruption,
and that while a succession of such continues to be raised up,
and error and wrong continue in the earth,
so long this controversy must and will be maintained.

After the separation in New England Yearly Meeting was effected,
through the efforts of those who gave their support to the unsound sentiments,
which unhappily included many of the influential characters therein,
thus causing the devastation to be more widely spread;
he labored assiduously for the preservation of the small body which
continued to adhere to the ancient doctrines of the Society,
and for that of the honest-hearted in other parts of the heritage,
under a concern for whom, he visited with certificate,
many of the meetings within the limits of New York Yearly Meeting.
He also attended the Yearly Meeting of Philadelphia,
and many of the subordinate meetings thereto belonging,
greatly to the comfort of the sincere-hearted,
to whom the ancient testimonies of Truth were still dear,
many of whom were under suffering for the cause sake,
and laboring under much discouragement.

In the spring of 1853,
he laid before his Monthly Meeting the prospect of
a second visit to Great Britain and Ireland.
This was no small trial to him, as well as to his children and friends;
his advanced age making the prospect of his return look very doubtful.
But after weightily deliberating upon it,
and believing the opening to be in the true light,
his concern received the approbation of the Monthly,
and subsequently of the Quarterly and Yearly Meetings,
and being furnished with certificates of unity and sympathy therefrom,
he embarked from Boston on the 28th of ninth month, 1853,
accompanied by his son Amos C. Wilbur.

Soon after his arrival in England,
he had an interview with a large committee of the Meeting for Sufferings,
at their request;
before whom he spread his concern for the preservation of
the Society on its ancient ground of principle and discipline,
and showed that this was what himself and Friends in New England had been standing for;
and that where the matter had been fully investigated,
as was done by Philadelphia Yearly Meeting,
this was found and acknowledged to have been the case.
Although they allowed him to relieve his mind,
and were unable to gainsay or resist what he said,
yet it was painful to him to find them fully committed to the views of J. J. Gurney,
and unwilling to acknowledge that any portion of them were unsound.

Besides this,
he had interviews with many others of the leading characters in different places,
who generally acknowledged unity with the same sentiments.
Thus he found his previous apprehensions in regard to this class confirmed;
but in the course of this visit,
he found a considerable number of true mourners on account of the desolations of Zion,
whose eyes had been anointed to see things in their true light.
These were sitting in solitary places, and their secret cry was, "`Spare your people,
O Lord, and give not your heritage to reproach.`"
To these, he was in a peculiar manner drawn, and was with them,
greatly to their comfort and satisfaction,
as was afterwards evinced by written testimonials from some.
He was permitted to return to his home in safety, after an absence of about six months.

After his return, he seemed to regard his labors as nearly finished;
often speaking of this visit as an evening sacrifice,
in the offering of which he felt great peace.
It proved to be the last journey of a religious nature,
which he made beyond the limits of his own Yearly Meeting; within which, however,
he continued to labor to the comfort and edification of his friends.

Though firm and uncompromising, he was mild and forbearing, and remarkably unassuming,
evincing no ill will towards those who differed from and
were disposed to resort to extreme measures against him.
He often spoke of having endeavored to weigh his motives, and his acts in this matter,
with those whom he once regarded as his friends, in the balance of the sanctuary,
with a desire to be rightly directed in all his movements;
saying that whenever he had looked towards concession and compromise,
the way had seemed covered with darkness,
and he had clearly seen that those precious testimonies of Truth for which
our worthy predecessors suffered and laid down their lives,
cannot, without incurring a fearful responsibility, be compromised.

Having faithfully served his Lord and Master in his day and generation,
the evening of his life was eminently serene and tranquil;
evincing a state of quiet waiting for the final change, which he looked upon as near;
often remarking, both in public and in private,
that he believed his day`'s work was nearly done.
Especially was this the case during the last year of his life.
Being much indisposed, while on a visit to one of his daughters,
he said he often thought of the probability of his being suddenly removed,
and remarked that there was no terror to him in the prospect,
but that it looked pleasant to him.
And in a public testimony in his own Monthly Meeting,
after expressing his continued impression that he
was near the termination of his earthly labors,
he said that in looking towards a separation from the world and the things of it,
he felt that there were no strong ties to be broken;
that the world had lost its charms for him,
that there was nothing pertaining to it which it was hard for him to leave,
save his beloved friends,
and he trusted that even the separation from them would be made easy;
that the change to him seemed desirable,
not only on account of a release from labor and exercise,
but of a reunion with loved ones who had gone before.

On taking leave of a friend`'s family,
after attending the last Monthly Meeting before his decease, though then in usual health,
he remarked that he believed he was there for the last time.
Thus forewarned and prepared, with his lamp trimmed and his light burning,
he awaited the last remaining conflict, which, in Divine mercy and condescension,
was made short.
On the morning of the 28th of fourth month, 1856, he was seized with severe pain,
which threatened immediate dissolution.
Being aware of this, he said to his daughter, "`If I go now, all will be well.`"
She soon after reminded him, that he was taken ill much as his mother had been,
who survived but about half an hour, but added, "`I do not wish to alarm you.`"
He replied, "`You cannot alarm me.`"

On the day following, finding that he continued to fail, she said to him, "`Father,
you are very feeble, do you expect to recover?`"
He replied, "`No, I know I shall not, and I do not desire it; I am ready to go.`"
She said, "`Then you have seen enough of this world?`"
He replied, "`Yes, plenty, plenty.`"
She told him she had been looking towards him for company,
when her dear husband (then low with consumption) should be gone.
He replied, "`You must not.`"
During the severe paroxysm of bodily distress, which lasted for several hours,
not a murmur escaped him, nor any token of impatience.
Although active remedies succeeded in relieving his pain,
yet his constitution had so far given way, that he continued to sink, and subsequently,
from weakness and what appeared like partial paralysis of the organs of speech,
articulation became difficult,
so that he said comparatively little that could be understood;
but what could be understood was indicative of peacefulness and resignation.

In reply to the question whether he felt peaceful, he replied "`very.`"
His interest in the welfare of the Society continued unabated to the last,
as was evinced, on the evening before his decease,
by his desiring to hear read a letter received,
giving some account of Philadelphia Yearly Meeting; and, during its reading,
he turned his face to the reader and listened attentively.
On being inquired of, if he understood it, he replied that he did.
Late in the evening, his eldest son, who lived at a distance,
and whom he had been expecting, arrived, and, on approaching him,
asked him if he knew him; he called him by name, and smiled very pleasantly.
His son inquired of him in regard to the state of his mind; he answered,
that "`his way was clear before him;`"--to another,
he said he was "`very happy,`" which was nearly his last expression.

In the latter part of the night, he fell into a quiet slumber,
in which he continued until about eight o`'clock on fifth day morning,
the 1st of fifth month, when he departed from here, aged nearly eighty-two years,
and was interred in Friends`' burying-ground, in Hopkinton, on the 4th of the same,
after a solemn meeting on the occasion,
wherein a true and living testimony was borne to the uprightness of his character,
and the faithful dedication of his life to the blessed cause of Truth and righteousness.

In thus reviewing the life and gospel labors of this our departed friend,
we are led to adopt, as peculiarly applicable to him,
the language of the beloved and faithful disciple,
conveyed to him in the visions of light: "`And I heard a voice from heaven,
saying unto me, write, blessed are the dead which die in the Lord from henceforth; yes,
says the Spirit, that they may rest from their labors, and their works do follow them.`"
And so we have been brought renewedly to believe,
that the results of the faithful labors of this dedicated servant of the
Lord have not terminated with his valuable and eventful life;
but that they will continue to be felt,
to the strengthening and animating of survivors and those that follow after,
even in ages and generations yet to come.

Signed by direction and on behalf of South Kingston Monthly Meeting of Friends,
held at Hopkinton, 23rd of 3rd month, 1857.

[.signed-section-signature]
Ethan Foster, Clerk.

[.signed-section-signature]
Ann Perry, Clerk.
