[short="Letter II. On the Fall of Man and Christian Redemption"]
== Letter II. On the Fall of Man, and on Christian Redemption.

My Dear Friend,

If it be, as has been affirmed, that enmity took root in some of the heavenly company,
and that they through pride were led into rebellion,
and an attempt to set up and establish a kingdom for themselves in opposition to,
and above the throne and kingdom of God;
still we have no reason to believe that the needful and mighty act of God in
expelling from the regions of light their arch leader with all his band,
had, or could have, any effect as a reconciliation, or any tendency to remove the enmity,
however humbling their defeat and condition.
No, nor that it were possible for those who had been created free partakers
with their blessed and eternal King in the riches of his glory,
after such daring rebellion and attempted usurpation,
could ever be restored to that glorious state which they had lost by their fall;^
footnote:["`For it is impossible for those who were once enlightened,
and have tasted of the heavenly gift, and were made partakers of the Holy Spirit,
and have tasted the good word of God, and the powers of the world to come,
if they shall fall away, to renew them again unto repentance.`"
Heb. 6:4-5 and 6--also Heb. 10:26.]
for, as we may well believe,
no mediation could be found between these rebels
and Him whom they had attempted to dethrone;
they had sinned willfully and without temptation,
and there remained therefore to them no more sacrifice for sins,
but they were consigned to the blackness of darkness forever.^
footnote:["`Depart from me, you cursed ones, into everlasting fire,
prepared for the devil and his angels.`"
Matt. 25.41.
"`For if God spared not the angels that sinned,
but cast them down to hell, and delivered them into chains of darkness,
to be reserved unto judgment.`" 2 Peter 2:4.
"`And the angels which kept not their proper domain,
but left their own abode, he has reserved in everlasting chains, under darkness.`" Jude 6.
"`And there was war in heaven:
Michael and his angels fought against the dragon; and the dragon fought and his angels,
and prevailed not; neither was their place found any more in heaven.
And the great dragon was cast out, that old serpent, called the devil, and Satan,
which deceives the whole world; he was cast out into the earth,
and his angels were cast out with him.`"
Revelation 12:7-8, and 9.]

Hence, this arch-pretender,
finding himself forever defeated by the power and interminable decree of God,
was excited to the highest pitch of hatred and malice,
and seeing he was now forever expelled from the glories above,
would seek to obtain for himself some other place and kingdom where to rule.
He therefore, as it would appear, then sought out, and by his subtle temptation,
assailed the lower creation of God,
that he might hereby establish his dominion over a noble race which God had here placed,
newly-created by his divine hand,
in his own image "`a little lower than the angels`" and
furnished too with power from his almighty Creator,
if he had been obedient,
to resist and overcome this proud usurper of the prerogative of heaven; but he,
the wicked one (for such he had now become) by deceit and lies,
and by a proud contradiction of the law and commandments of God,
attempted to turn away man from his allegiance to his beneficent Maker and Father,
and to corrupt and obliterate the character and image of
uprightness and holiness which God had impressed upon him;
and instead thereof to stamp him with the mark and inscription of the beast,
which is sin, and serves to show to whose kingdom he belongs.

In this the serpent succeeded but too well; and man, through pride,
and listening to the tempter,
and seeking to obtain knowledge beyond what his Creator had assigned to him,
fell into a mighty lapse of transgression, and was estranged from his Maker;
the threatened penalty of his disobedience was inflicted upon him,
and his condition was properly denominated death, than which, if it remain,
there can be no greater punishment; and this death was truly realized,
inasmuch as he died spiritually by losing the divine life through his transgression.
He was dead also as it regards a sense of goodness;
for his feelings were now so perverted, that they led him to consider God,
who was truly his all beneficent Father, to be his enemy;
he himself having now become the subject of another kingdom.

As things now were, it remained entirely with God,
whether he would provide a way for man to return again to his rightful allegiance,
so that the first purpose of his own benevolence and glory might still be realized;
or whether he would abandon this ruined work altogether.
But rejoice, O heavens! and sing, O earth! and break forth into singing,
O you mountains of the forest! love, boundless love, and mercy led the way,
and if a plan could be found compatible with both
the blessed attributes of justice and mercy,
so that his statutes should not be rescinded nor dishonored,
then God would open a way for them to return to himself again.

And joyful to think and to know, in the richness of his grace a way was found,
and a Mediator was also found and ordained who would for this,
even for this fallen creature, give life for life.
For however man had conceived pride, through the instilling of the author of it,
and had a desire to be wise in himself, and to be as God,
yet he had not rebelled as the fallen angels had done;
hence a provision could be made and adapted to remove
out of the way that which had befallen him;
and this provision should apply to him,
on condition that he would then by obedience reverse his disobedience,
for when the sacrifice for sin repented of, was in that day ordained,
the Lord said then unto man, "`If you do well, shall you not be accepted?`"

But as it regarded the character and office of the Mediator,
it was seen that he must also be a man: as it was man that sinned,
so like must be given for like, and life for life, yes, and death for death.
That is, the death of a man temporally,
(God`'s leniency being such,) should be accepted
as an equivalent pledge for the death of a man spiritually,
he being yet within the reach of such a pledge, not having sinned as those had sinned,
who had fallen before him; and so, by a pledge,
should man be redeemed from the judgment of death that rested upon him.

But as sin could not be atoned by sin,
any more than disobedience could be atoned by disobedience, or by an impure offering;
and as the subsequent race of man, if a race should be permitted,
must descend through these sin-stained progenitors;
therefore the offering of a mere man yet unredeemed,
could not be equivalent to the effecting of redemption; and as no mere man, therefore,
could be an equivalent pledge without first having a pledge; nor even then,
so long as the nature and propensity to sin remained in him; so, therefore,
no one could be found among men merely as such, that could possibly redeem his brother,
or give to God a ransom for him.

There were also other, and still higher and greater reasons,
why a mere man could not be a sufficient mediator,
because in the covenant of such a redemption as this must be to succeed to salvation,
there must be a bringing to repentance,
before the sins which had been committed could be forgiven or atoned for.
And then again, and which is indispensable and cannot be commuted,
man`'s heart must be enlightened, drawn and guided to the truth and to righteousness;
for although he repent and his sins be remitted for once,
yet without something to keep him from a recurrence to them, he will still sin,
and never forsake the commission of it.

For however he may know his former sins expiated by the atonement, still,
if he witness not the interposition of a power to preserve him in future from sin,
he will go on again, adding sin to sin, until the accumulation become such,
and the duration of his transgressions so outlive the day of God`'s grace,
that the application of the mediation, whether without or within,
will be rendered entirely unavailing.
And here we see the supreme excellency of the light and grace of this provision;
that if observed, is able to keep us from a state,
out of which the atonement itself is not designed to redeem
us--even that of sinning against the Holy Spirit.
(See Heb. 6:4-6, and chap. x. 26.)

If the offering of a mere man could have been given and accepted for sins already passed,
still this could have no effect in keeping man from sinning in future.
But still the interposition and mediation must be effected,
as wisdom teaches us to believe, by the seed of the woman, even by the man Christ Jesus,
who should know no sin, and in whom the fulness of God should dwell bodily,
and this body and life of man in which he designed himself to dwell,
should be a pure offering and sacrifice of the first fruits,
even of the first and only man who never sinned.

This was therefore a sacrifice of a sweet smelling savour unto God, in which,
and by which,
he would blot out from his presence the transgression of every penitent sinner,
and obtain a place and ground for him, whereon he would deign to meet him;
and such too as would enable him to receive the divine grace,
and prepare him for the guidance of the divine Spirit: for without this,
man could not so much as be brought to repentance, and much less,
to that which is the hardest of all attainments; the forsaking and ceasing from sin;
for the mediation as well as the mediator was to be the Immanuel, God with us;
not only God in Christ Jesus, reconciling the world unto himself,
but also God in them through a measure of his spirit, as was declared,
"`you in me and I in them!`"

And we have not only abundant Scripture testimony,
to show the fitness and necessity of a mediator, to act in us, and with us,
as well as without us, and for us:
but our own inability alone to do anything that is good,
clearly teaches us the high order and urgent necessity of a spiritual
and continual mediation to guide and preserve us.
Herein is much of the excellency of the mediation seen,
that after the expiation of repented sins,
He the Mediator of the whole glorious covenant of life and salvation,
is to us a mediator still, keeping with us,
and constantly teaching us the denying of all ungodliness: for such is our weakness,
even after remission, that but for his help continually,
we should soon fall into our old sins again,
and our last state would be worse than the first.

So that in the end Christ may have died for us a thousand times,
(if by his judgments we should be so many times brought to repentance,)
and still we be continually growing worse and worse;
indeed, and though we might all the time be acknowledging the atonement,
and having the most implicit confidence in it, still if we do not believe in him,
and receive him, the promise of the Father, the Immanuel to be with us, to keep us,
all will be in vain.
Yes, and if we do not by the power of the agency which God gives us, work with him,
and endeavor to keep his commandments, then the covenant to us is broken; yes,
and by us is also broken; and moreover,
if this indispensable part of the covenant so clearly identified
and enforced by the undeniable authority of the Scriptures,
is disregarded or rejected,
however clear and full our faith may be in another indispensable part,
still we are covenant breakers,
and but partial believers in the gospel of our Lord and Saviour Jesus Christ.
And again, on the other side: if any man with the Bible in his hand,
shall deny the divinity of Christ,
and the efficacy and necessity of his outward sacrifice,
then all his professions of light or grace, or spirit,
(if indeed he have the presumption to make such a
profession,) will be but a mere ignis fatuus,
or a counterfeit of the right thing, and will only contribute to his condemnation.

Now if by the suggestion of an evil spirit the fall of man was effected through disobedience,
then are we not to conclude, that through the interposition of a good spirit,
the restoration is to be effected in the reverse of that by which man fell;
even in obedience?
And obedience is not a whit less necessary on account of
what has gone before it in order to make way for it;
for what Christ has done for us without us,
has not rescinded a single obligation for us,--has
not in the least exonerated us from obedience,
or from fulfilling as much of the conditions as devolves upon us.
In every covenant there is either a promise, an obligation, or a condition,
between two at least; thus in that between God and us,
after the first step which he himself has taken, to make way for all his promises,
as well as even the application of the atonement,
it is upon the condition of our obedience,
and the fulfillment of our part of that covenant,
which ensures to us an eternal inheritance.

Christianity having been ordained as the blessed means of
restoring man from his fallen condition and from sin,
to a state of holiness and acceptance with God,
is of all things the most hateful to the devil; indeed,
he hates the faith and the power as well as the author of it.
He strove mightily to destroy the child Jesus, through the instrumentality of Herod,
so that if possible he might frustrate and prevent his glorious mission among men;
so likewise it is to be presumed that he unwittingly strove,
through the chief priests and elders,
to apprehend and bring him before Pilate and Herod that they might destroy him,
not knowing at the time, that therein he was fighting against his own kingdom;
for however cunning, yet he is not infinite in understanding,
nor can he know beforehand the divine purposes.

For although the coming of Christ, and his character as the Messiah,
were so clearly spoken of, that doubtless, he as well as the children of men,
were in expectation of it; yet the benefit of his death and sufferings,
were described in so mysterious and hidden a manner,
that even the most enlightened of men could not comprehend it until after his resurrection,
when he himself clearly explained it to two of his
disciples as they walked from Jerusalem to Emmaus,
as well as at other times.
Thus the enmity and malice of the devil led him ignorantly
on to instigate the Jews to destroy the man Jesus,
not knowing, as we may well believe,
the satisfactory and saving purpose of the death of Christ.

The plan of our salvation and redemption then, on the part of Divine Providence,
consists of three things:--1st. Repentance, or rather his power that leads to it.
2nd. The atoning blood of Christ: and 3rd, his Holy Spirit which sanctifies;
and this agrees with the apostle John`'s testimony
that there are three that bear witness in the earth,
namely: "`the Spirit, the water and the blood, and these three agree in one.`"
For we are instructed that the water of Jordan, administered upon the body of Jesus,
and upon the bodies of men, represented repentance, and showed,
and was thus acknowledged by Jesus himself,
that judgment which brings to repentance comes first;
after this the blood of Christ shed at Calvary as an atonement and reconciliation for us,
comes in the second place;
and the gift of the Holy Spirit for our guidance
and sanctification comes in the third place;
and this order of time, and their succession to each other,
was arranged by Wisdom itself; for as the baptism of John, signifying repentance,
took place first; so the offering of Christ, for the expiation of sins thus repented of,
came next in succession; and lastly,
the more full diffusion of the Holy Spirit followed for
the accomplishment and completion of the work of sanctification;
and as to the two former,
their order is sufficiently proved by the times of those events; and as to the latter,
its place is clearly demonstrated by the direction
of truth and the nature of things;--see John 7:39,
"`For the Holy Spirit was not yet given, because that Jesus was not yet glorified.`"
But after his death and resurrection, "`he breathed on them,
and bade them receive the Holy Spirit,
which is the eternal spirit that sanctifies men`'s hearts.`" John 20:22-23.

There are several operations and effects of the Spirit
distinctly spoken of in the Scriptures of Truth,
as being effectual to salvation,
and they are severally alluded to by Christ and his apostles,
as well as by the holy men of old, in such manner as if each was saving of itself;
and for the reason, as I apprehend, that not one of these requisite,
all of which are indispensable to our future well-being,
should be overlooked or excluded from the summary
of our faith in the covenant of life and peace.
And these provisions and conditions may be thus enumerated:--

1st. That men are to be saved by the outward coming, sufferings,
and death of Jesus Christ, through whom their souls are reconciled unto God.

2nd. That men are to be saved by faith in God, and in his Son Jesus Christ.

3rd. That men are to be saved by regeneration and baptism of the Spirit.

4th. That men are to be saved by Divine Grace.

5th. That men are to be saved by the Spirit of Christ or of God.

6th. That men are to be saved by the knowledge of God.

7th. That men are to be saved by obeying and keeping the commandments of God,
and the Lord Jesus Christ.

To exemplify and demonstrate the foregoing positions,
I would refer to the subjoined passages of Scripture,
as being distinctly applicable to them, and which, collectively,
would seem to constitute and include the whole covenant of life and salvation.^
footnote:["`Even so must the Son of Man be lifted up, etc.
John 3 14--We have redemption through his blood.
Eph. 1.7.--Who gave himself for us, etc. Titus 2:14.
--And washed us from our sins in his own blood. Rev. 1:5.
"`And whosoever lives and believes in me, etc. John 11:26.
--For you are all the children of God, by faith in Christ Jesus. Gal. 3:26.
"`He shall baptize you with the Holy Spirit, etc.
Matt. 3:11,13--Except a man be born again, etc. John 3:3.
--Baptism doth also now save us, etc.
1 Pet. 3:21
"`But by the grace of God, I am what I am, etc. 1 Cor. 15:10.
--My grace is sufficient for you, etc. 2 Cor. 12:9.
--For by grace you are saved through faith. Eph. 2:8.
--For the grace of God that brings salvation has appeared to all men. Tit. 2.11.
"`And his Spirit has gathered them. Isa. 34:16.
--It is the Spirit that quickens, etc. John 7:63.
--For the law of the Spirit of life in Christ Jesus, etc.
Rom. 8:2--But he that sows to the Spirit, etc. Gal. 6.8.
"`And this is life eternal,
that they might know you, etc. John 17:3.
"`If you do well, shall you not be accepted? Gen. 4.7.
"`Obey my voice, and I will be your God,
and you shall be my people: and walk in all the ways that I have commanded you,
that it may be well unto you. Jer. 7:23.
"`And being made perfect,
he became the author of eternal salvation unto all them that obey him. Heb. 5:9.
"`Verily, verily, I say unto you,
if a man keep my saying, he shall never see death. John 8:51.
"`Bringing into captivity
every thought to the obedience of Christ. 2 Cor. 10:5.
"`Fear God, and keep his commandments, etc. Ecc. 12:13.
--And whatsoever we ask,
we receive of him because we keep his commandments, etc. 1 John 3:22.
--He that says, I know him, and keeps not his commandments,
is a liar and the truth is not in him. 1 John 2:4.
--He that keeps his commandments dwells in him, and he in him. 1 John 3:24.
--And this is love, that we walk after his commandments, etc.
2 John 6.`"]
And I would desire to ask everyone who is looking
for the blessed hope of this high calling,
even the glory of salvation, whether he can venture,
even secretly in his own soul to disregard,
or openly to disavow anyone of the above conditions of his eternal salvation?
And whether on serious reflection,
he would not be fearful of doing so at the great risk of his soul`'s happiness?

Then how needful it is to have a full belief in the doctrines of Scripture,
and in every part of them, not merely assenting to some and passing slightly over others,
for fear that a practical and living belief in them
should lead us to much pain and conflict of spirit,
and to the mortifying of the will of the flesh.--Then
let everyone come down and prove himself,
and examine, by the light of Christ, all the hidden and dark avenues of his heart,
remembering that every secret thing must be opened
and brought to judgment in the day of Jesus Christ.
And oh, how desirable, that when that day shall come upon every one of us,
we may submit to it, while there is yet tenderness in our hearts,
so that a spirit of unbelief in any one of these great doctrines
of life and salvation may never be entertained;
that none of the great truths of the gospel may be looked upon with indifference,
but that every one of us may be so quickened and made alive unto God,
by the resurrection and power of Jesus Christ,
as to be furnished and blessed with the perceptive and all
instructive guidance and influence of his Holy Spirit.
