== Letter IV. / On the Secession in America.

[.salutation]
My Dear Friend,

It has been supposed by some, that within the last century,
there had been either a defect in the faith of the Society of Friends,
as to the outward coming and atonement of Jesus Christ;
or otherwise not enough of care taken by its ministers to lay sufficient stress upon,
or to allude sufficiently to the efficacy of the sacrifice of Christ without us,
so as by that means to keep up a safe barrier against the inroads of infidelity.
I think the latter was the case with too many in America,
and I make no doubt that if Friends had been timely aware of what might come,
and what did afterwards come, they would have been better guarded against it.

But I know not that there was any unsoundness in our Society there,
until the seeds were sown in the mind of him who stood at the head of the late secession,
excepting only in a very few solitary individuals.
Nor do I think that the open infidel writings of Paine, nearly half a century ago,
had any effect in shaking the faith of Friends; for, as far as my knowledge extends,
these writings were justly deprecated by them,
and treated everywhere with the abhorrence they justly merited;
but whether the publications of Paine,
or the more artful and refined writings of Priestley, contained the seed,
which first fell on the fitly prepared ground: namely,
the heart of the first founder of the American secession, I am not prepared to determine;
but through whatever medium, or whether only through the agency of Satan,
it seems that either by a lapse into spiritual pride, or by some other means,
his heart was exceeding congenial to its growth,
and his natural talent and manner were wonderfully calculated to supplant truth unobserved;
as well as for the first spreading the seeds of infidelity.
It seems however that there were a few prominent characters about the same time,
or soon after,
who were prepared to receive from this their leader those seeds of infidelity.

Hence through him and them (men of great influence) awful
devastation was made in the Society of Friends in America;
and however the Socinian doctrine may have lamentably
spread far and wide both in Europe and America,
still I apprehend that so great a schism or devastation in proportion to numbers,
has not been known elsewhere, as in the instance just mentioned.
Here then a question may arise, whether the Society of Friends, from its peculiar tenets,
or discipline, is more exposed to the influence of such doctrines,
than other branches of the Christian church.
To this it may be replied with much confidence, that the plain, full,
and true doctrines of Friends are not more nearly
allied to Socinianism than are those of others.
No! and if indeed the doctrines of this Society are
the genuine doctrines of primitive Christianity,
which we do most surely believe, then are they farther from infidelity than any others.

Nevertheless,
there is no doubt at all that the devil envies those most who are the most purely Christian,
and consequently presses them the most sorely with his temptations,
and strives the hardest to ensnare and drive them back from their advanced ground;
and upon this principle we are led to believe that the temptations
with which he tempted the author of Christianity,
were greater than those whereby he has ever tempted men.
By the same rule he exerts his power more against good men than against others,
and besides, the more good he can despoil and overcome,
the greater his victory and exultation.
But however great the trials of those who stand high in the scale of profession may be,
still, if it be a profession to which God has called them,
their dwelling being "`in the secret place of the Most High,`" they "`shall
abide under the shadow of the Almighty,`"--and their strength and their
protection will certainly be equal to the trials of their day;
hence as their feet abide upon the watch tower, their habitation will be kept in safety.

But a mere profession of Christianity is altogether
unavailing in a Quaker as in any other.
Yet as it regards the extent of that dereliction of principle
which befell so many professing with Friends in America,
however they may still profess to be Christians,
yet everyone acquainted with their skepticism,
cannot but fear that they or their leaders have so far abandoned
Christianity as to forfeit their right of benefit in the
outward coming and propitiatory sacrifice of Jesus Christ,
and consequently their right in the whole covenant;
as all depends upon that blessed sacrifice.
But it would seem as if the devil did make a kind of compromise with them,
and such too as he had made with none other than professed Quakers,
for as their principles lead them to believe in the light, grace,
and spirit of Christianity, as a distinguishing article,
it would seem that he despaired of so managing with them,
as to strike this off at once with the other important part of the great plan,
he therefore permitted them still to profess the spiritual guidance,
(which nevertheless if real,
there is nothing that he hates worse,) well knowing that if he could induce a
flat denial of the proper divinity and atonement of Jesus Christ without them,
that they would not then, in the very nature of things,
be sharers in the true light of Christ within them, and walk in it:
so that he could now deceive them with his false radiance,
which they should mistake for the real light.
For having denied "`the Lord that bought them,`" they could not be enlightened by him.

Now, according to their manner of thinking and reading too,
as they would of course be looking for light and spirit to guide them,
full opportunity presented for this false light of the fallen angels,
and the true light being thus superseded by darkness,
through unbelief and hardness of heart,
there was no power in them to distinguish between the true and the false;
between Christ and antichrist; hence antichrist took the lead,
and his light and his spirit became their guide! he, well pleased enough with it,
and with their cry,
which was a continual reiteration of "`the light! the light! the
spirit! the spirit!`"--and Christ within but not without! yes,
and proud and vaunting enough is he,
to have wrested from Christ his name! and to obtain from the children
of men the honor and homage attached to their leader! glorying
too in his own power of transformation and delusion,
in making himself as God and sitting as God!

Now in this we see his cloven foot again,
and his twofold and cunning intention in pushing forward these infidel
and deluded professors to the cry of "`the spirit of the Lord! the spirit
of the Lord!`" and filling their mouths continually with it,
and for this very purpose; that the truly spiritual Christian,
whom he cannot in the same way decoy, may if possible,
be made to loathe the very name of Christ in spirit,
or "`Christ within the hope of glory,`" this manifestation of the covenant being so
continually brought forward and taken in vain by those well known to be antichristians.
Hence we see the art and power of the arch-destroyer
to contrive and form a deadly weapon with two edges,
calculated to cut, to wound,
and to kill each way! he fills the mouths of his deluded followers,
both with a cry against Christian redemption, and at the same time for it; that is,
partly for and partly against, in order to divide Christ;
thus also to divide and part asunder his people,
and to destroy the one half on his right hand, and the other half on his left!

Then seeing the destroyer has gone forth, let all stand fast:
for he has now but dressed up his old trick in a new garb,
in order to play it off again upon the unwary, and those who cry peace.
He has instigated the Socinian doctrine on the one
hand to take captive all that is possible thereby,
intending that those who may escape it,
shall in their flight for refuge take shelter in the doctrines and opinions of men,
in unconditional assurance,
or in the flesh without the spirit,--because therefore the Socinian
or Hicksite has sinfully denied the divinity and atonement of Christ,
shall we unnecessarily and sinfully too,
abandon everything else relative to God`'s salvation,
that so we may establish what they deny?
as if it were possible for us to obtain salvation by the one without the other.

And will any be driven through cowardice from a practical faith in divine grace,
and the light and spirit of the gospel,
because these seceders have illusively pretended thereto.
Will any man be deterred from reverently naming and believing in the holy name,
because the atheist chants it off with scorn?
Not the true Christian, no;
for if the very worst of men deceptively profess the best of things,
that will never occasion the true believer to abandon them,
nor if the unfaithful abandon one part of the covenant, professing to support the other,
it will never induce the former to reverse it,
for in so doing he would be a covenant breaker as much as the other.

Now, in conclusion,
I would ask if it is not alike dangerous to man and dishonorable towards God,
to deny that Jesus Christ has done anything for our salvation without us,
and to deny that he is doing anything for us, within us, for the same purpose;
seeing that if we reject either of these provisions, we cannot be saved,
for we cannot so much as begin a good life,
without the application of that great sacrifice of his body, once made for all men.
Nor in the second place can we advance a single day of our
lives in the Christian way and warfare against sin,
without his presence and help continually extended to us.

The former was a mighty offering of his own body, a living sacrifice,
once made for the reconciliation of man;
the latter is a continual extension and operation of his power and spirit,
light and grace, perceptibly working in the hearts of men,
for their preservation and safe guidance through the whole course of their lives;
for however much and long a man may have gone forward
by cooperating with the spirit of God in himself,
yet he can never witness preservation and a continuance in well-doing but through
the power of this grace and spirit of God working in him and with him;
and if the declarations of our Lord Jesus Christ, and the apostle Paul, be correct,
man might for lack of a continuance herein, sin against the Holy Spirit,
and fall from a good state into one from which it would
be impossible even for the atonement itself to restore him.
