== Letter V. / On the Holy Scriptures.

[.salutation]
My Dear Friend,

It will be seen by every rational well-informed mind,
that the comparison of two or more things together
does not virtually diminish the real value of either;
but affords a ready way of exhibiting, and ascertaining, the equal, or superior,
or inferior properties of things differing both in nature and kind, namely,
the good and the evil; and these severally have their degrees;
but my present purpose will be answered by a brief recurrence to the good.
On this great scale is beheld, even by us, short-sighted as we are,
a mighty range of vast extent from the lowest to the highest,
in the blessed order of God`'s assignment; for no man has ever been able to comprehend,
or to reach to the higher degrees of the radii of this mighty circle:
so that we see there is room for a place and a station for every
good thing in the spiritual as well as in the temporal economy,
and that without any interference or infringement upon each other.

And God stands above all, and over all, and through all, and is in all, and orders all;
and in comparison of whom there is no created thing
which can be named in the heaven above,
or the earth beneath, or under the earth, or even all things put together;
they can indeed be no more accounted of, than the drop of the bucket,
or than the particles of dust which cleave to the balance;
and this is the more evinced to us by reflection
on his glorious attributes of wisdom and power,
justice and mercy, goodness and love, each in itself unbounded in extent;
yet in him all are comprehended, each of itself filling all things,
yet each clearly distinct; all in harmony, and what is wonderful, all are one,
and that one is God, and each of these bears witness to the whole,
and God in each records his mighty power, and testifies, and manifests himself in all.
He, Jehovah, is seen of angels, but he has also manifested himself unto man; and,
which all believers acknowledge, he has not only manifested himself,
but also the knowledge of his will, and that too at sundry times and in various manners.

But as it regards the ways and means by which God, through Jesus Christ,
has revealed his will in former times,
or at least as respects the adaptation of those ways
and means to the minds of men in the present day,
there appears to be a great difference of opinion between us as a people,
and other professing Christians--which difference Robert
Barclay in his apology for the true Christian divinity,
has set forth in a clear, cogent, and scriptural manner.
He has in that work answered the great question,
whether that principle which contains the light, grace, spirit, and faith of the gospel,
or the Bible,
is the first and best leader and controller of the Christian`'s life and practice;
and he has fairly made the Bible to decide this question itself.

None need do more than simply quote all the passages from
the Scriptures which speak in favor of both these positions,
and there will certainly be found a great preponderance
in favor of the ground taken by our early Friends,
and taken also by the apostles, in following the directions of our Lord,
as to the guidance of his spirit, and its operation upon men`'s hearts.
And I would indeed that all who may have any doubts on this point--might
first read the New Testament carefully through with candor,
and an eye to the subject,
and then examine Robert Barclay`'s proposition on the same subject,
when the coincidence will be readily seen.
But though Robert Barclay has clearly and unanswerably demonstrated this,
I would suggest the following queries for the consideration of all inquirers:--

[.numbered-group]
====

[.numbered]
_1st._ Can the Scriptures, or did they ever, save anyone without the spirit?

[.numbered]
_2nd._ Is a person called to the work of the ministry by the Scriptures,
or by the spirit of Jesus Christ?

[.numbered]
_3rd._ Is a man brought under a concern to go from
one place to another to preach the gospel,
by the Scriptures, or by the constraining power of the spirit and love of Jesus Christ?

[.numbered]
_4th._ And when he is arrived at the place assigned, and is assembled with the people,
is it not the spirit of Christ that truly unfolds the Scriptures,
and brings to view the state of men, either in the words of Scripture,
or in some other suitable language?

[.numbered]
_5th._ And when a professed minister preaches in any of our meetings,
his doctrines not being repugnant to the letter of the Scriptures,
are the elders or others to judge by the Scriptures, or by the Spirit of Truth,
whether his ministry is from the right spring or not?

[.numbered]
_6th._ Did not the Jews think they had eternal life in the Scriptures
and yet would not come unto Christ that they might have life?

====

Finally, Christ the Lord, is the minister and leader of his people,
(others as well as ministers,) for they do believe the truth of his gracious words,
that he is with them, and dwells in them, and girds them,
and brings all things to their remembrance;
and they know him and his words which he spoke in the days of his flesh,
to be unequivocal and true, and not feigned words, or vain pretensions.
They know too, by blessed experience, that their faith in Him, their leader,
is a practical and living principle--that it is not a mere theory; and they find,
the living experience confirmed to them by literal testimonies from the Scriptures.
Hence they are enabled livingly to believe the Scriptures,
and to assign them their proper place;
or rather to allow them to take their own station
and allotment in the blessed schedule of God`'s providence,
declaring themselves to be "`profitable for doctrine, for reproof, for correction,
for instruction in righteousness,`" and that through
faith they are able to make us wise unto salvation;
where too he has also placed them,
and where they acknowledge themselves to have been placed.

Hereby those who attempt to put them in the place of the
immediate and life-giving instruction of the spirit of Christ,
are not true and genuine believers, of the full, fair,
and irrefragable testimony of the Holy Scriptures,
as it relates to the question before us.
In making a comparison of the blessed spirit of the gospel with the Scriptures of truth,
there is nothing lost to them;
for placing it above them is no diminution of their excellency, nor of their character;
nor can there be any dishonor brought to the sacred writings,
by placing the all manifesting spirit, and light, and grace of God,
through our Lord Jesus Christ,
over and above them in the rightful order of God`'s manifestations
and provisions for the children of men.

No, truly, it cannot be derogatory to the Scriptures,
nor to any other creature here below, to place the second Adam, the Lord from heaven,
the quickening spirit, above them; and it may be presumed that no person who believes in,
and is disposed willingly and self-denyingly to wait from time to time,
for the coming of the Lord from heaven, the quickening spirit,
will be disposed to give the preference to aught which is beneath the power,
and the life, the covering; and the instruction; proceeding from it:
for these know it to be their Alpha and Omega,
truly the beginning and the end of all their Christian movements;
but this would never authorize anyone in the least
to believe or act contrary to the Scriptures,
which are a blessed revelation of the will of God.

If we compare the Scriptures with the writings of our early Friends,
there will be nothing lost to the latter by placing the former above them,
and in the higher sphere of that exalted rank, where they do deservedly,
and ever ought to stand, far above all modern writings,
for several considerations which are well defined by Robert Barclay.
For as the Scriptures, being authentic and true,
place themselves below Christ and his blessed Spirit,
so the writings of our worthy predecessors being also true,
place themselves meekly and modestly,
entirely below the holy Scriptures--a correct position.

Now, therefore, as the Scriptures are true and authentic in word and doctrine,
and stand above all other writings, we may fully admit them to be the only outward,
fit rule and standard by which all the professors
of Christianity may prove and try their doctrines;
and more especially, where that Spirit which tries the spirits,
is not so well known and understood.
This outward test being then generally agreed to by all,
is a treasure of inestimable value, and the more so,
because it instructs them of the purchase of their redemption,
and emphatically directs all to the light and grace of God, through the gospel;
which are the very things that our forefathers and we as a people have insisted on.

But we see, nevertheless, that for lack of a perfectly single eye to the light of Christ,
some of the doctrines of this perfect standard are misconstrued and differently understood,
so that Christendom has become divided into various denominations,
and each of these denominations has a creed or confession of faith peculiar to itself,
and founded, as it is supposed, upon a right understanding of the Scriptures;
every individual member, therefore,
of these different sects feels himself bound to believe and support
the doctrines of the gospel as understood by his own society;
and such is surely his duty, if he believes with all his heart that they are correct.
But whenever any member of a religious body sincerely thinks that he has
found important errors in the fundamental doctrines of his own people,
it then becomes his duty openly and candidly to say to them, "`That such and such,
being your faith, and such and such mine, I must therefore separate myself from you,
my views having become established, and my duty prompting me to open them to you,
and before all men, and not knowing but as you are many and I am but one,
that you are still more correct than I, I am resolved, therefore,
to take no secret measures, nor to use any hidden influence,
to draw you unawares into my opinion; knowing as I do,
that the purity and integrity of the gospel is such, that no end, however seemingly good,
can sanctify any deceptive means to draw votaries to its support.`"

Candid and Christian was the way taken by our early Friends to
gather and establish a society coinciding with their own views;
they maintained honest, manly ground;
for their object was not a perversion of right principles,
but a fair and lucid exhibition of them in the very face of day.
Far different were the subtle movements of the seceders from Friends in America;
they endeavored, with all the art and cunning in their power,
secretly to gain and to proselyte the unwary, to their new-fangled system of infidelity.
How much more honorable to have come out into broad daylight, and proclaimed their views,
inviting others to their standard.
There might have been honor in such measures, though practised by infidels.

The subject before us, my dear friend, is one of deep importance,
(even the right assignment of the place of the holy Scriptures,) when we contemplate
the great consequences which await the retaining or abandonment of apostolic ground;
the ground taken by our predecessors in profession,
and which they supported with regard to the comparative
rank of the spirit of Jesus Christ,
and the Scriptures; for it would not require much foresight and sagacity to see,
that if we as a people, were to change the place of the Scriptures, and exalt them above,
and put them in the place of the teaching of the spirit of Christ,
that it must inevitably, and that before long,
completely overturn and change our ancient faith and practice,
concerning both silent worship,
and the need there is of a continually renewed qualification in a gospel minister:
two very prominent and important doctrines of the Christian religion.

They are indeed the true doctrines of the gospel of our Lord and Saviour Jesus Christ;
and they had been virtually witnessed by the real worshippers and
faithful messengers in all the previous ages of the world,
who waited, spoke, and wrote as they were moved by the Holy Spirit.
The knowledge and true experience of these doctrines had been very much lost,
even since the more refulgent dawning of gospel light upon the sons of men,
until they were proclaimed, and the true,
standard was again raised and supported through much
pain and suffering by George Fox and his contemporaries;
and the same doctrines continue to be acknowledged by their
successors in faith down to the present day.
Yet it is lamentable that these doctrines remain to be peculiar to the society of Friends,
and that they only (it is believed) as a body,
are found experimentally and livingly to teach and to practise them.

Inasmuch then as men, by silently waiting upon God,
may happily attain strength and instruction,
so they can thereby do more towards pulling down the strongholds of sin and Satan;
therefore his enmity is the more excited,
and his cunning the more exercised to allure them from this blessed ground;
for finding his attempts to drive them by violence from the truth, to be in vain,
he now very insidiously resorts to art and intrigue; he is very plausible with them,
seeking if he can, to relax their direct hold upon God,
and their dependence singly on him.
He asks but small concessions at once,
and admits something that shall very nearly resemble the right thing,
and yet not be the thing itself; he gives it a good name, alleging its necessity,
and extolling its advantages.

And however the adversary, hates the Holy Scriptures,
and would induce men to disbelieve them altogether, still,
when he cannot effect this purpose, it is like himself, to exalt them in name,
even above their right order and true standing, that so he may dishonor Christ;
hence he would place the Scriptures instead of,
or before the instructions of Christ`'s spirit,
casting a shade of darkness over men`'s minds, and over the true faith of the gospel,
subtilely suggesting the impracticability of a direct leading of the Holy Spirit,
and thus inducing ministers to abandon that flesh-paining
exercise of waiting for the promise of the Father,
and setting them to work,
to preach the letter only instead of Christ Jesus in the demonstration of the spirit,
and with power; hence by degrees he would in time,
so thoroughly change and remove this holy ground of our standing,
that it might finally be abandoned altogether;
which must indeed unavoidably be the case if we misplace the Scriptures,
(as some other professors do,) by putting them as our instructor before the Spirit;
then would our worship, our ministry, and our forms, become like theirs!
